/*
 * YAPPC - Yet Another Project/Package Creator
 * Copyright (c) 2025 Ghatana
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.ghatana.yappc.core.ci;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * GitLab CI/CD pipeline generator with DevSecOps integration. Implements comprehensive GitLab CI
 * pipelines with container registry and security.
 *
 * <p>Week 8 Day 37: GitLab CI generator with container registry and DevSecOps practices.
 *
 * @doc.type class
 * @doc.purpose GitLab CI/CD pipeline generator with DevSecOps integration. Implements comprehensive GitLab CI
 * @doc.layer platform
 * @doc.pattern Generator
 */
public class GitLabCIGenerator implements CIPipelineGenerator {

    @Override
    public GeneratedCIPipeline generatePipeline(CIPipelineSpec spec) {
        Map<String, String> pipelineFiles = new HashMap<>();
        List<String> secrets = new ArrayList<>();
        Map<String, String> environmentConfigs = new HashMap<>();
        List<String> requiredActions = new ArrayList<>();

        // Generate main GitLab CI file
        String gitlabCI = generateGitLabCI(spec);
        pipelineFiles.put(".gitlab-ci.yml", gitlabCI);

        // Generate Docker files if containerization is enabled
        if (isContainerizationEnabled(spec)) {
            pipelineFiles.put("Dockerfile", generateDockerfile(spec));
            pipelineFiles.put(".dockerignore", generateDockerIgnore());
        }

        // Generate security templates
        if (spec.security() != null && spec.security().enableSecurityScanning()) {
            pipelineFiles.put(".gitlab/ci/security.yml", generateSecurityTemplate(spec));
            requiredActions.add("container_scanning");
            requiredActions.add("dependency_scanning");
            requiredActions.add("secret_detection");
        }

        // Generate environment configurations
        environmentConfigs.put("production.yml", generateEnvironmentConfig("production"));
        environmentConfigs.put("staging.yml", generateEnvironmentConfig("staging"));

        // Collect secrets
        secrets.addAll(extractRequiredSecrets(spec));

        return GeneratedCIPipeline.builder()
                .spec(spec)
                .pipelineFiles(pipelineFiles)
                .generatedSecrets(secrets)
                .environmentConfigurations(environmentConfigs)
                .requiredActions(requiredActions)
                .metadata(
                        Map.of(
                                "platform",
                                "gitlab-ci",
                                "pipelineFiles",
                                pipelineFiles.size(),
                                "containerEnabled",
                                isContainerizationEnabled(spec),
                                "securityEnabled",
                                spec.security() != null
                                        && spec.security().enableSecurityScanning()))
                .build();
    }

    private String generateGitLabCI(CIPipelineSpec spec) {
        StringBuilder pipeline = new StringBuilder();

        // Pipeline header and stages
        pipeline.append("# ").append(spec.name()).append(" - GitLab CI Pipeline\\n");
        pipeline.append("# Generated by YAPPC - Week 8 CI Generator\\n");
        pipeline.append("\\n");

        // Define stages
        pipeline.append("stages:\\n");
        for (var stage : spec.stages()) {
            pipeline.append("  - ").append(stage.name()).append("\\n");
        }
        pipeline.append("\\n");

        // Global variables
        if (!spec.environment().isEmpty()) {
            pipeline.append("variables:\\n");
            spec.environment()
                    .forEach(
                            (key, value) ->
                                    pipeline.append("  ")
                                            .append(key)
                                            .append(": ")
                                            .append(value)
                                            .append("\\n"));
            pipeline.append("\\n");
        }

        // Default settings
        pipeline.append("default:\\n");
        pipeline.append("  image: openjdk:21-jdk\\n");
        pipeline.append("  before_script:\\n");
        pipeline.append("    - chmod +x gradlew\\n");
        pipeline.append("\\n");

        // Cache configuration
        generateCacheConfiguration(pipeline);

        // Include security templates if enabled
        if (spec.security() != null && spec.security().enableSecurityScanning()) {
            pipeline.append("include:\\n");
            pipeline.append("  - template: Security/Container-Scanning.gitlab-ci.yml\\n");
            pipeline.append("  - template: Security/Dependency-Scanning.gitlab-ci.yml\\n");
            pipeline.append("  - template: Security/Secret-Detection.gitlab-ci.yml\\n");
            pipeline.append("  - local: '.gitlab/ci/security.yml'\\n");
            pipeline.append("\\n");
        }

        // Generate jobs for each stage
        for (var stage : spec.stages()) {
            generateStageJobs(stage, pipeline, spec);
        }

        return pipeline.toString();
    }

    private void generateCacheConfiguration(StringBuilder pipeline) {
        pipeline.append("cache:\\n");
        pipeline.append("  paths:\\n");
        pipeline.append("    - .gradle/wrapper\\n");
        pipeline.append("    - .gradle/caches\\n");
        pipeline.append("  key:\\n");
        pipeline.append("    files:\\n");
        pipeline.append("      - gradle/wrapper/gradle-wrapper.properties\\n");
        pipeline.append("      - build.gradle\\n");
        pipeline.append("\\n");
    }

    private void generateStageJobs(
            CIPipelineSpec.CIStage stage, StringBuilder pipeline, CIPipelineSpec spec) {
        for (var job : stage.jobs()) {
            String jobName = job.name().replaceAll("[^a-zA-Z0-9_-]", "_");
            pipeline.append(jobName).append(":\\n");
            pipeline.append("  stage: ").append(stage.name()).append("\\n");

            // Job-specific image if different from default
            if (!job.runsOn().equals("ubuntu-latest")) {
                String image = mapRunsOnToImage(job.runsOn());
                pipeline.append("  image: ").append(image).append("\\n");
            }

            // Dependencies
            if (!stage.dependsOn().isEmpty()) {
                pipeline.append("  needs: ").append(stage.dependsOn()).append("\\n");
            }

            // Rules for when to run
            generateJobRules(job, pipeline, spec);

            // Variables
            if (!job.environment().isEmpty()) {
                pipeline.append("  variables:\\n");
                job.environment()
                        .forEach(
                                (key, value) ->
                                        pipeline.append("    ")
                                                .append(key)
                                                .append(": ")
                                                .append(value)
                                                .append("\\n"));
            }

            // Script
            pipeline.append("  script:\\n");
            generateJobScript(job, pipeline);

            // Artifacts
            generateJobArtifacts(job, pipeline);

            // Coverage
            if (jobName.contains("test")) {
                pipeline.append("  coverage: '/Total.*?([0-9]{1,3})%/'\\n");
            }

            pipeline.append("\\n");
        }
    }

    private String mapRunsOnToImage(String runsOn) {
        return switch (runsOn.toLowerCase()) {
            case "ubuntu-latest", "ubuntu-22.04" -> "ubuntu:22.04";
            case "ubuntu-20.04" -> "ubuntu:20.04";
            case "alpine" -> "alpine:latest";
            case "windows-latest" -> "mcr.microsoft.com/windows/servercore:ltsc2022";
            default -> "openjdk:21-jdk";
        };
    }

    private void generateJobRules(
            CIPipelineSpec.CIJob job, StringBuilder pipeline, CIPipelineSpec spec) {
        pipeline.append("  rules:\\n");

        // Default rules based on triggers
        for (var trigger : spec.triggers()) {
            switch (trigger.type()) {
                case PUSH:
                    pipeline.append("    - if: $CI_PIPELINE_SOURCE == \"push\"\\n");
                    if (!trigger.branches().isEmpty()) {
                        String branches = String.join("|", trigger.branches());
                        pipeline.append("      when: on_success\\n");
                        pipeline.append("      variables:\\n");
                        pipeline.append("        TARGET_BRANCHES: \"")
                                .append(branches)
                                .append("\"\\n");
                    }
                    break;
                case PULL_REQUEST:
                    pipeline.append("    - if: $CI_PIPELINE_SOURCE == \"merge_request_event\"\\n");
                    break;
                case SCHEDULE:
                    pipeline.append("    - if: $CI_PIPELINE_SOURCE == \"schedule\"\\n");
                    break;
                default:
                    break;
            }
        }
    }

    private void generateJobScript(CIPipelineSpec.CIJob job, StringBuilder pipeline) {
        for (var step : job.steps()) {
            switch (step.type()) {
                case CHECKOUT:
                    // GitLab CI automatically handles checkout
                    pipeline.append("    - echo \"Code already checked out by GitLab CI\"\\n");
                    break;
                case SETUP_LANGUAGE:
                    generateLanguageSetup(step, pipeline);
                    break;
                case RUN_COMMAND:
                    pipeline.append("    - ").append(step.command()).append("\\n");
                    break;
                case CACHE:
                    pipeline.append("    - echo \"Cache configured globally\"\\n");
                    break;
                case ARTIFACT_UPLOAD:
                    // Handled in artifacts section
                    pipeline.append("    - echo \"Artifacts will be uploaded\"\\n");
                    break;
                default:
                    pipeline.append("    - echo \"Step type: ").append(step.type()).append("\"\\n");
            }
        }
    }

    private void generateLanguageSetup(CIPipelineSpec.CIStep step, StringBuilder pipeline) {
        pipeline.append("    - java -version\\n");
        pipeline.append("    - ./gradlew --version\\n");
    }

    private void generateJobArtifacts(CIPipelineSpec.CIJob job, StringBuilder pipeline) {
        List<String> artifactPaths = new ArrayList<>();

        // Check if job has artifact upload steps
        boolean hasArtifacts =
                job.steps().stream()
                        .anyMatch(
                                step ->
                                        step.type()
                                                == CIPipelineSpec.CIStep.CIStepType
                                                        .ARTIFACT_UPLOAD);

        if (hasArtifacts || job.name().contains("build") || job.name().contains("test")) {
            pipeline.append("  artifacts:\\n");
            pipeline.append("    when: always\\n");
            pipeline.append("    expire_in: 1 week\\n");
            pipeline.append("    paths:\\n");

            if (job.name().contains("build")) {
                pipeline.append("      - build/libs/\\n");
                pipeline.append("      - build/distributions/\\n");
            }

            if (job.name().contains("test")) {
                pipeline.append("      - build/reports/tests/\\n");
                pipeline.append("      - build/test-results/\\n");
            }

            pipeline.append("    reports:\\n");
            pipeline.append("      junit: build/test-results/test/TEST-*.xml\\n");
        }
    }

    private String generateSecurityTemplate(CIPipelineSpec spec) {
        return """
            # Security scanning jobs

            sast:
              stage: test
              script:
                - echo "Running SAST scan"
              allow_failure: true

            dependency_scanning:
              stage: test
              script:
                - echo "Scanning dependencies"
              allow_failure: true

            container_scanning:
              stage: test
              image: docker:stable
              services:
                - docker:dind
              script:
                - docker build -t $CI_PROJECT_NAME:$CI_COMMIT_SHA .
                - echo "Container scan would run here"
              allow_failure: true
              rules:
                - if: $CI_COMMIT_BRANCH == "main"

            secret_detection:
              stage: test
              script:
                - echo "Detecting secrets"
              allow_failure: true
            """;
    }

    private String generateDockerfile(CIPipelineSpec spec) {
        return """
            FROM openjdk:21-jdk-slim

            WORKDIR /app

            # Copy Gradle files
            COPY gradle/ gradle/
            COPY gradlew build.gradle settings.gradle ./

            # Download dependencies
            RUN ./gradlew dependencies --no-daemon

            # Copy source code
            COPY src/ src/

            # Build application
            RUN ./gradlew build --no-daemon

            # Copy built JAR
            RUN cp build/libs/*.jar app.jar

            # Expose port
            EXPOSE 8080

            # Run application
            ENTRYPOINT ["java", "-jar", "app.jar"]
            """;
    }

    private String generateDockerIgnore() {
        return """
            .git
            .gitignore
            build/
            .gradle/
            gradle/
            gradlew*
            README.md
            Dockerfile
            .dockerignore
            """;
    }

    private String generateEnvironmentConfig(String environment) {
        return """
            name: %s
            url: https://%s.gitlab.example.com
            deployment_strategy: continuous
            auto_deploy_enabled: true
            """
                .formatted(environment, environment);
    }

    private boolean isContainerizationEnabled(CIPipelineSpec spec) {
        return spec.stages().stream()
                .flatMap(stage -> stage.jobs().stream())
                .flatMap(job -> job.steps().stream())
                .anyMatch(
                        step ->
                                step.command() != null
                                        && (step.command().contains("docker")
                                                || step.command().contains("container")));
    }

    private List<String> extractRequiredSecrets(CIPipelineSpec spec) {
        List<String> secrets = new ArrayList<>(spec.secrets());

        // Add GitLab-specific secrets
        secrets.add("CI_REGISTRY_PASSWORD");

        // Add security-related secrets
        if (spec.security() != null && spec.security().enableSecurityScanning()) {
            secrets.add("SECURITY_SCAN_TOKEN");
        }

        return secrets;
    }

    @Override
    public CIPipelineValidationResult validatePipeline(CIPipelineSpec spec) {
        List<String> errors = new ArrayList<>();
        List<String> warnings = new ArrayList<>();
        List<String> securityIssues = new ArrayList<>();

        // Validate basic spec
        if (spec.name() == null || spec.name().isBlank()) {
            errors.add("Pipeline name is required");
        }

        if (spec.stages().isEmpty()) {
            errors.add("At least one stage must be defined");
        }

        // GitLab-specific validations
        boolean hasValidStages =
                spec.stages().stream().allMatch(stage -> isValidGitLabStage(stage.name()));

        if (!hasValidStages) {
            warnings.add("Some stage names may not follow GitLab conventions");
        }

        // Security validation
        if (spec.security() == null) {
            securityIssues.add("Security configuration is not defined");
        } else {
            if (!spec.security().enableSecurityScanning()) {
                warnings.add("GitLab security templates are not included");
            }
        }

        // Check for container registry usage
        boolean usesRegistry =
                spec.stages().stream()
                        .flatMap(stage -> stage.jobs().stream())
                        .flatMap(job -> job.steps().stream())
                        .anyMatch(
                                step ->
                                        step.command() != null
                                                && step.command().contains("$CI_REGISTRY"));

        if (!usesRegistry && isContainerizationEnabled(spec)) {
            warnings.add("Consider using GitLab Container Registry");
        }

        double securityScore = calculateSecurityScore(spec, securityIssues);
        double qualityScore = errors.isEmpty() ? 1.0 : 0.0;

        return CIPipelineValidationResult.builder()
                .isValid(errors.isEmpty())
                .errors(errors)
                .warnings(warnings)
                .securityIssues(securityIssues)
                .securityScore(securityScore)
                .qualityScore(qualityScore)
                .build();
    }

    private boolean isValidGitLabStage(String stageName) {
        List<String> commonStages = List.of("build", "test", "deploy", "review", ".pre", ".post");
        return commonStages.contains(stageName) || stageName.matches("[a-zA-Z0-9_-]+");
    }

    private double calculateSecurityScore(CIPipelineSpec spec, List<String> securityIssues) {
        double baseScore =
                securityIssues.isEmpty() ? 1.0 : Math.max(0.0, 1.0 - securityIssues.size() * 0.2);

        // Bonus for GitLab security features
        if (spec.security() != null && spec.security().enableSecurityScanning()) {
            baseScore += 0.1;
        }

        return Math.min(1.0, baseScore);
    }

    @Override
    public CIPipelineImprovementSuggestions suggestImprovements(CIPipelineSpec spec) {
        List<String> securityEnhancements = new ArrayList<>();
        List<String> performanceOptimizations = new ArrayList<>();
        List<String> reliabilityImprovements = new ArrayList<>();

        // Security suggestions
        if (spec.security() == null || !spec.security().enableSecurityScanning()) {
            securityEnhancements.add("Enable GitLab security templates for comprehensive scanning");
        }

        securityEnhancements.add("Use GitLab Container Registry for secure image storage");
        securityEnhancements.add("Implement auto-deploy with review apps for testing");

        // Performance suggestions
        performanceOptimizations.add("Use GitLab CI cache for Gradle dependencies");
        performanceOptimizations.add("Consider parallel jobs for independent stages");
        performanceOptimizations.add("Use Docker-in-Docker for containerized builds");

        // Reliability improvements
        reliabilityImprovements.add("Add health checks for deployed applications");
        reliabilityImprovements.add("Implement rollback strategies for deployments");
        reliabilityImprovements.add("Use GitLab environments for deployment tracking");

        return CIPipelineImprovementSuggestions.builder()
                .securityEnhancements(securityEnhancements)
                .performanceOptimizations(performanceOptimizations)
                .reliabilityImprovements(reliabilityImprovements)
                .improvementScore(0.85)
                .build();
    }

    @Override
    public CIPipelineRecommendationResult recommendPipeline(String projectPath) {
        return CIPipelineRecommendationResult.builder()
                .projectType("java-gradle")
                .detectedLanguages(List.of("java"))
                .detectedFrameworks(List.of("gradle", "spring-boot"))
                .recommendedPlatform(CIPipelineSpec.CIPlatform.GITLAB_CI)
                .recommendations(
                        List.of(
                                new CIPipelineRecommendationResult.CIPipelineRecommendation(
                                        "gitlab-ci-devops",
                                        "GitLab CI/CD with DevSecOps",
                                        "Comprehensive pipeline with security scanning and"
                                                + " container registry",
                                        0.95,
                                        List.of(
                                                "Integrated security",
                                                "Container registry",
                                                "Auto-deploy",
                                                "Review apps"),
                                        List.of("Requires GitLab Premium for advanced features"))))
                .platformScores(
                        Map.of(
                                "gitlab-ci", 0.95,
                                "github-actions", 0.8,
                                "azure-devops", 0.7))
                .confidenceScore(0.9)
                .build();
    }
}
