package com.ghatana.refactorer.codemods.ts;

import com.ghatana.refactorer.shared.PolyfixProjectContext;
import com.ghatana.refactorer.shared.codemods.CodeModificationPlan;
import com.ghatana.refactorer.shared.process.ProcessRunner;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Objects;
import io.activej.promise.Promise;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 * Bridge to the ts-morph library for TypeScript/JavaScript code modifications. This class handles
 * applying code modification plans generated by the analyzer.
 
 * @doc.type class
 * @doc.purpose Handles ts morph bridge operations
 * @doc.layer core
 * @doc.pattern ValueObject
*/
public class TsMorphBridge {
    private static final Logger logger = LogManager.getLogger(TsMorphBridge.class);
    private static final String BRIDGE_SCRIPT = "bridges/tsmorph/apply-plan.mjs";

    private final PolyfixProjectContext context;

    // Will be used in a future implementation
    @SuppressWarnings("unused")
    private final ProcessRunner processRunner;

    public TsMorphBridge(PolyfixProjectContext context) {
        this.context = Objects.requireNonNull(context, "context cannot be null");
        this.processRunner = new ProcessRunner(context);
    }

    /**
     * Applies the given code modification plan to the source files.
     *
     * @param plan The plan to apply
     * @return A future that completes when the modifications are applied
     */
    public Promise<Void> apply(CodeModificationPlan plan) {
        Objects.requireNonNull(plan, "plan cannot be null");

        if (plan.isEmpty()) {
            logger.debug("Skipping empty code modification plan for {}", plan.getFilePath());
            return Promise.of(null);
        }

        if (!(plan instanceof TsMorphPlan)) {
            return Promise.ofException(
                    new IllegalArgumentException(
                            "Expected TsMorphPlan but got " + plan.getClass().getSimpleName()));
        }

        TsMorphPlan tsPlan = (TsMorphPlan) plan;
        Path filePath = tsPlan.getFilePath();

        if (!Files.exists(filePath)) {
            return Promise.ofException(
                    new IllegalStateException("File does not exist: " + filePath));
        }

        logger.info("Applying {} code modifications to {}", tsPlan.getActions().size(), filePath);

        // In a real implementation, we would use ts-morph to apply the changes
        // For now, we'll just log what we would do
        for (com.ghatana.refactorer.shared.codemods.CodeAction action : tsPlan.getActions()) {
            logger.debug("Would apply action: {}", action.getDescription());
        }

        return Promise.of(null);
    }

    /** Checks if the ts-morph bridge is available. */
    public boolean isAvailable() {
        try {
            // Try to find the bridge script
            Path bridgePath = getBridgeScriptPath();
            if (bridgePath == null || !Files.exists(bridgePath)) {
                logger.debug("ts-morph bridge script not found");
                return false;
            }

            // Check if Node.js is available
            ProcessBuilder pb = new ProcessBuilder("node", "--version");
            pb.redirectErrorStream(true);
            Process process = pb.start();
            int exitCode = process.waitFor();

            if (exitCode != 0) {
                logger.debug("Node.js is not available (exit code: {})", exitCode);
                return false;
            }

            // Check if ts-morph is installed
            pb = new ProcessBuilder("npm", "list", "ts-morph", "--json");
            pb.directory(context.getProjectRoot().toFile());
            pb.redirectErrorStream(true);
            process = pb.start();
            exitCode = process.waitFor();

            if (exitCode != 0) {
                logger.debug("ts-morph is not installed in the project");
                return false;
            }

            return true;

        } catch (Exception e) {
            logger.debug("Error checking ts-morph availability: {}", e.getMessage());
            return false;
        }
    }

    private Path getBridgeScriptPath() {
        // First try to get the resource as a URL (works in JAR)
        java.net.URL resourceUrl = getClass().getClassLoader().getResource(BRIDGE_SCRIPT);
        if (resourceUrl != null) {
            try {
                return Path.of(resourceUrl.toURI());
            } catch (Exception e) {
                logger.warn("Failed to convert resource URL to URI: {}", e.getMessage());
            }
        }

        // Fallback: look in the file system
        Path path =
                context.getProjectRoot()
                        .resolve("polyfix/modules/codemods/src/main/resources/" + BRIDGE_SCRIPT);

        if (Files.exists(path)) {
            return path;
        }

        // Check in the classpath
        path = Path.of("src/main/resources/" + BRIDGE_SCRIPT);
        if (Files.exists(path)) {
            return path;
        }

        return null;
    }
}
