package com.ghatana.finance.integration;

import org.h2.jdbcx.JdbcDataSource;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.Statement;

public final class PerformanceBaselineTestSupport {

    private PerformanceBaselineTestSupport() {
    }

    public static DataSource createDataSource(String name) throws Exception {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:" + name + ";MODE=PostgreSQL;DATABASE_TO_UPPER=false;DB_CLOSE_DELAY=-1");
        dataSource.setUser("sa");
        dataSource.setPassword("sa");
        initializeSchema(dataSource);
        return dataSource;
    }

    public static void initializeSchema(DataSource dataSource) throws Exception {
        try (Connection connection = dataSource.getConnection(); Statement statement = connection.createStatement()) {
            statement.execute("""
                CREATE TABLE IF NOT EXISTS e2e_test_runs (
                    run_id VARCHAR(128) PRIMARY KEY,
                    suite_name VARCHAR(128) NOT NULL,
                    scenario VARCHAR(128) NOT NULL,
                    status VARCHAR(32),
                    recorded_at TIMESTAMP NOT NULL
                )
                """);
            statement.execute("""
                CREATE TABLE IF NOT EXISTS e2e_step_assertions (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    run_id VARCHAR(128) NOT NULL,
                    step_name VARCHAR(128) NOT NULL,
                    assertion VARCHAR(512) NOT NULL,
                    expected VARCHAR(256) NOT NULL,
                    actual VARCHAR(256) NOT NULL,
                    passed BOOLEAN NOT NULL
                )
                """);
            statement.execute("""
                CREATE TABLE IF NOT EXISTS perf_baselines (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    run_id VARCHAR(128) NOT NULL,
                    suite VARCHAR(128) NOT NULL,
                    scenario VARCHAR(128) NOT NULL,
                    order_count INT NOT NULL,
                    p99_ms BIGINT NOT NULL,
                    error_count INT NOT NULL,
                    measured_at TIMESTAMP NOT NULL
                )
                """);
        }
    }
}
