/*
 * YAPPC - Yet Another Project/Package Creator
 * Copyright (c) 2025 Ghatana
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.ghatana.yappc.core.docs.adr.template;

import com.ghatana.yappc.core.docs.adr.model.ADREnums.ADRTemplateType;
import com.ghatana.yappc.core.docs.adr.model.ADRModels.ADRRequest;

import java.util.Map;

/**
 * Brief ADR template for quick decision documentation.
 * Includes only essential sections: decision, rationale, and impact.
 *
 * @doc.type class
 * @doc.purpose Brief ADR template for quick decision documentation.
 * @doc.layer platform
 * @doc.pattern Component
 */
public class BriefADRTemplate implements ADRTemplate {
    
    @Override
    public ADRTemplateType templateType() {
        return ADRTemplateType.BRIEF;
    }

    @Override
    public String generate(Map<String, Object> data) {
        ADRRequest request = (ADRRequest) data.get("request");
        String date = (String) data.get("date");

        return String.format(
                """
            # %s

            **Status:** %s | **Date:** %s

            ## Decision

            %s

            ## Rationale

            %s

            ## Impact

            %s

            ---
            *Brief ADR generated by YAPPC AI*
            """,
                request.title(),
                request.status(),
                date,
                request.decision().isEmpty() ? "*Decision to be added*" : request.decision(),
                request.rationale().isEmpty() ? "*Rationale to be added*" : request.rationale(),
                request.consequences().isEmpty()
                        ? "*Impact to be assessed*"
                        : String.join("; ", request.consequences()));
    }
}
