/*
 * YAPPC - Yet Another Project/Package Creator
 * Copyright (c) 2025 Ghatana
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.ghatana.yappc.core.docs.adr.template;

import com.ghatana.yappc.core.docs.adr.model.ADREnums.ADRTemplateType;
import com.ghatana.yappc.core.docs.adr.model.ADRModels.ADRRequest;

import java.util.Map;

/**
 * Y-Statement ADR template using the structured Y-statement format.
 * Format: "In the context of X, facing Y, we decided for Z to achieve A, accepting B."
 *
 * @doc.type class
 * @doc.purpose Y-Statement ADR template using the structured Y-statement format.
 * @doc.layer platform
 * @doc.pattern Component
 */
public class YStatementADRTemplate implements ADRTemplate {
    
    @Override
    public ADRTemplateType templateType() {
        return ADRTemplateType.Y_STATEMENT;
    }

    @Override
    public String generate(Map<String, Object> data) {
        ADRRequest request = (ADRRequest) data.get("request");
        String date = (String) data.get("date");

        return String.format(
                """
            # %s

            **Date:** %s
            **Status:** %s

            ## Decision Statement

            In the context of %s,
            facing %s,
            we decided for %s
            to achieve %s,
            accepting %s.

            ## Rationale

            %s

            ## Implications

            %s

            ---
            *Y-Statement ADR generated by YAPPC AI on %s*
            """,
                request.title(),
                date,
                request.status(),
                request.context().isEmpty() ? "*[context to be added]*" : request.context(),
                "*[concern/problem to be added]*",
                request.decision().isEmpty() ? "*[solution to be added]*" : request.decision(),
                "*[benefit/outcome to be added]*",
                "*[downside/trade-off to be added]*",
                request.rationale().isEmpty() ? "*Rationale to be added*" : request.rationale(),
                request.consequences().isEmpty()
                        ? "*Implications to be added*"
                        : String.join("\n- ", request.consequences()),
                data.get("timestamp"));
    }
}
