export {
  Typography,
  type TypographyProps,
  type TypographyVariant,
  Text,
  type TextProps,
  Heading,
  type HeadingProps,
  Link,
  type LinkProps,
  List as TypographyList,
  type ListProps as TypographyListProps,
  Code,
  type CodeProps,
} from './Typography.tailwind';
