-- Flyway V007: Checkpoint — display_name backfill phase complete
-- ============================================================================
-- This is a documentation-only checkpoint migration confirming that Flyway
-- has applied V006 (ADD COLUMN display_name) and DataMigrationService has
-- run BackfillEntitiesDisplayName.
--
-- The concurrent index on entities.display_name is created at application
-- startup by DataMigrationService via ConcurrentIndexMigration, which
-- executes CREATE INDEX CONCURRENTLY outside a transaction (a PostgreSQL
-- requirement that Flyway SQL migrations cannot satisfy).
--
-- DDL completed: V008 added a GIN index on entities.data for JSONB queries.
-- V009 documents IF NOT EXISTS semantics for all legacy indexes (see V009).
-- ============================================================================
