/*
 * Copyright (c) 2026 Ghatana Inc.
 * All rights reserved.
 */
package com.ghatana.yappc.api;

import org.jetbrains.annotations.NotNull;

/**
 * Security policy for preview sessions, defining CSP, sandbox restrictions, and trust levels.
 *
 * <p>Preview sessions are a security boundary for generated/imported UI, source imports,
 * component execution, clipboard/download permissions, and semi-trusted/untrusted artifacts.
 * This policy enforces runtime security constraints on preview operations.
 *
 * @doc.type class
 * @doc.purpose Security policy for preview sessions with CSP, sandbox, and trust classification
 * @doc.layer api
 * @doc.pattern Policy
 */
public final class PreviewSecurityPolicy {

    private final ContentSecurityPolicy cspPolicy;
    private final SandboxPolicy sandboxPolicy;
    private final TrustLevel defaultTrustLevel;

    public PreviewSecurityPolicy(
            @NotNull ContentSecurityPolicy cspPolicy,
            @NotNull SandboxPolicy sandboxPolicy,
            @NotNull TrustLevel defaultTrustLevel
    ) {
        this.cspPolicy = cspPolicy;
        this.sandboxPolicy = sandboxPolicy;
        this.defaultTrustLevel = defaultTrustLevel;
    }

    public ContentSecurityPolicy cspPolicy() {
        return cspPolicy;
    }

    public SandboxPolicy sandboxPolicy() {
        return sandboxPolicy;
    }

    public TrustLevel defaultTrustLevel() {
        return defaultTrustLevel;
    }

    /**
     * Creates a production-safe preview security policy with strict defaults.
     */
    public static PreviewSecurityPolicy productionDefaults() {
        ContentSecurityPolicy csp = new ContentSecurityPolicy(
            true,  // enable CSP
            "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https:; font-src 'self' data:; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none';"
        );

        SandboxPolicy sandbox = new SandboxPolicy(
            true,  // enable sandbox
            true,  // allow-scripts
            false, // allow-modals
            false, // allow-popups
            false, // allow-forms
            false, // allow-same-origin
            true   // allow-downloads
        );

        return new PreviewSecurityPolicy(csp, sandbox, TrustLevel.SEMI_TRUSTED);
    }

    /**
     * Creates a development preview security policy with relaxed defaults.
     */
    public static PreviewSecurityPolicy developmentDefaults() {
        ContentSecurityPolicy csp = new ContentSecurityPolicy(
            false, // disable CSP in dev
            ""
        );

        SandboxPolicy sandbox = new SandboxPolicy(
            false, // disable sandbox in dev
            true,
            true,
            true,
            true,
            true,
            true
        );

        return new PreviewSecurityPolicy(csp, sandbox, TrustLevel.TRUSTED);
    }

    /**
     * Content Security Policy configuration for preview runtime.
     */
    public record ContentSecurityPolicy(
            boolean enabled,
            String policyString
    ) {
        public ContentSecurityPolicy {
            if (enabled && (policyString == null || policyString.isBlank())) {
                throw new IllegalArgumentException("CSP policy string is required when CSP is enabled");
            }
        }
    }

    /**
     * Sandbox policy configuration for preview runtime.
     */
    public record SandboxPolicy(
            boolean enabled,
            boolean allowScripts,
            boolean allowModals,
            boolean allowPopups,
            boolean allowForms,
            boolean allowSameOrigin,
            boolean allowDownloads
    ) {}

    /**
     * Trust classification for preview artifacts.
     */
    public enum TrustLevel {
        /**
         * Fully trusted artifacts from verified sources within the tenant.
         */
        TRUSTED,

        /**
         * Semi-trusted artifacts generated by AI or imported from tenant-approved sources.
         * Requires sandbox and CSP enforcement.
         */
        SEMI_TRUSTED,

        /**
         * Untrusted artifacts from external or unknown sources.
         * Requires strict sandbox, CSP, and limited permissions.
         */
        UNTRUSTED
    }

    /**
     * Data classification for preview content.
     */
    public enum DataClassification {
        /**
         * No sensitive data, can be displayed without restrictions.
         */
        PUBLIC,

        /**
         * Internal company data, not for external distribution.
         */
        INTERNAL,

        /**
         * Confidential business data, requires access control.
         */
        CONFIDENTIAL,

        /**
         * Highly sensitive data (PII, secrets), requires strict controls.
         */
        RESTRICTED
    }
}
