//! Manual vs Automated classifier (heuristic)
//!
//! Combines presence and foreground window signals into a simple decision of
//! whether the current activity is likely manual (user-driven) or automated.

use crate::activity::fg_window::FGWindow;
use crate::activity::presence::Presence;

/// Classification outcome describing whether an activity is likely manual or automated.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ActivityKind {
    /// User is actively driving the session.
    Manual,
    /// Activity appears to be generated by automation or background tooling.
    Automated,
}

/// Classify activity:
/// - If presence is inactive: Automated
/// - Else if FG window app/title matches any known automation keywords: Automated
/// - Else: Manual
pub fn classify(presence: Presence, fg: &FGWindow) -> ActivityKind {
    if !presence.active {
        return ActivityKind::Automated;
    }
    let t = fg.title.to_lowercase();
    let a = fg.app.to_lowercase();
    let auto = ["selenium", "webdriver", "headless", "runner", "ci", "bot"];
    if auto.iter().any(|k| t.contains(k) || a.contains(k)) {
        ActivityKind::Automated
    } else {
        ActivityKind::Manual
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::activity::presence::Presence;

    #[test]
    fn inactive_means_automated() {
        let k = classify(
            Presence {
                active: false,
                idle_secs: 120,
            },
            &FGWindow {
                app: "app".into(),
                title: "Title".into(),
            },
        );
        assert_eq!(k, ActivityKind::Automated);
    }

    #[test]
    fn automation_keywords_flag_automated() {
        let k = classify(
            Presence {
                active: true,
                idle_secs: 5,
            },
            &FGWindow {
                app: "Selenium Grid".into(),
                title: "Test".into(),
            },
        );
        assert_eq!(k, ActivityKind::Automated);
    }

    #[test]
    fn default_is_manual() {
        let k = classify(
            Presence {
                active: true,
                idle_secs: 5,
            },
            &FGWindow {
                app: "Chrome".into(),
                title: "Inbox".into(),
            },
        );
        assert_eq!(k, ActivityKind::Manual);
    }
}
