/**
 * CostRecommendation Entity - Represents cost optimization recommendations
 *
 * <p><b>Purpose</b><br>
 * Persistent entity for storing cost-saving recommendations.
 * Tracks recommendations, their implementation status, and realized savings.
 *
 * <p><b>Usage</b><br>
 * <pre>{@code
 * const recommendation = new CostRecommendation();
 * recommendation.title = 'Reserve EC2 instances';
 * recommendation.savings = 5000;
 * recommendation.effort = 'LOW';
 * recommendation.implementation = 'Purchase reserved instances for 1-year term';
 * recommendation.estimatedMonthsSavings = 12;
 * await recommendationRepository.save(recommendation);
 * }</pre>
 *
 * <p><b>Lifecycle</b><br>
 * - SUGGESTED: Initial recommendation
 * - APPROVED: User approved the recommendation
 * - IMPLEMENTED: Recommendation has been applied
 * - VERIFIED: Savings verified and confirmed
 * - REJECTED: User rejected the recommendation
 * - SUPERSEDED: Replaced by newer recommendation
 *
 * @doc.type class
 * @doc.purpose Cost optimization recommendation entity
 * @doc.layer product
 * @doc.pattern Value Object
 */
export class CostRecommendation {
  /**
   * Unique identifier
   * UUID generated by database
   */
  id!: string;

  /**
   * Recommendation title
   * Human-readable summary of the recommendation
   */
  title!: string;

  /**
   * Detailed description of the recommendation
   */
  description!: string;

  /**
   * Estimated monthly savings amount (in USD)
   * Sum of projected monthly savings
   */
  savings!: number;

  /**
   * Estimated annual savings (in USD)
   * Calculated from monthly savings
   */
  annualSavings!: number;

  /**
   * Implementation effort level
   * LOW: < 1 hour, MEDIUM: 1-8 hours, HIGH: > 8 hours
   */
  effort!: 'LOW' | 'MEDIUM' | 'HIGH';

  /**
   * Implementation instructions
   * Step-by-step guide for applying the recommendation
   */
  implementation!: string;

  /**
   * Number of months over which savings occur
   * E.g., 12 for annual savings, 36 for 3-year reservation
   */
  estimatedMonthsSavings!: number;

  /**
   * Current status of the recommendation
   */
  status!:
    | 'SUGGESTED'
    | 'APPROVED'
    | 'IMPLEMENTED'
    | 'VERIFIED'
    | 'REJECTED'
    | 'SUPERSEDED';

  /**
   * Actual realized savings (after implementation)
   * Null until status is VERIFIED
   */
  realizedSavings?: number;

  /**
   * Date the recommendation was suggested
   */
  suggestedAt!: Date;

  /**
   * Date the recommendation was approved by user
   * Null if not approved
   */
  approvedAt?: Date;

  /**
   * Date the recommendation was implemented
   * Null if not implemented
   */
  implementedAt?: Date;

  /**
   * Date the savings were verified
   * Null if not verified
   */
  verifiedAt?: Date;

  /**
   * Associated resource IDs
   * For tracking which resources this recommendation applies to
   */
  resourceIds!: string[];

  /**
   * Tags for categorization
   * E.g., { 'category': 'Reserved Instances', 'service': 'EC2' }
   */
  tags!: Record<string, string>;

  /**
   * Record creation timestamp
   */
  createdAt!: Date;

  /**
   * Record last update timestamp
   */
  updatedAt!: Date;

  /**
   * Validates recommendation entity
   * @returns true if valid
   * @throws Error if validation fails
   */
  validate(): boolean {
    if (!this.title || this.title.trim().length === 0) {
      throw new Error('CostRecommendation: title is required');
    }
    if (this.savings === undefined || this.savings < 0) {
      throw new Error('CostRecommendation: savings must be non-negative');
    }
    if (!this.effort) {
      throw new Error('CostRecommendation: effort is required');
    }
    if (!this.status) {
      throw new Error('CostRecommendation: status is required');
    }
    if (!this.implementation || this.implementation.trim().length === 0) {
      throw new Error('CostRecommendation: implementation is required');
    }
    return true;
  }
}
