/**
 * @fileoverview Fidelity and residual island contracts.
 *
 * Defines FidelityReport and ResidualIslandReport — the canonical models for
 * measuring how much of the source intent was preserved through the
 * compile/decompile round-trip and surfacing unsupported constructs.
 *
 * @doc.type module
 * @doc.purpose Round-trip fidelity measurement and residual island reporting
 * @doc.layer platform
 * @doc.pattern Contracts
 */

import { z } from "zod";
import { SourceRefSchema } from "./source.js";

// ============================================================================
// LOSS POINT
// ============================================================================

/**
 * Severity of a single fidelity loss point.
 */
export type LossPointSeverity = "info" | "warning" | "critical";

export const LossPointSeveritySchema = z.enum(["info", "warning", "critical"]);

/**
 * Describes a specific aspect of the original source that could not be
 * faithfully represented or regenerated by the pipeline.
 */
export const LossPointSchema = z.object({
  /** Stable, machine-readable code for this loss type. */
  code: z.string().min(1),
  /** Human-readable description. */
  description: z.string().min(1),
  /** Severity of this loss. */
  severity: LossPointSeveritySchema,
  /** Source location where the loss occurred. */
  sourceRef: SourceRefSchema.optional(),
  /**
   * Confidence impact of this loss (0–1).
   * Critical losses have a higher impact on the overall confidence score.
   */
  confidenceImpact: z.number().min(0).max(1).default(0.1),
});

export type LossPoint = z.infer<typeof LossPointSchema>;

// ============================================================================
// FIDELITY REPORT
// ============================================================================

/**
 * Overall fidelity assessment for a single artifact node or entire pipeline run.
 *
 * A fidelity score of 1.0 means perfect round-trip; 0 means the source intent
 * cannot be represented at all by the current model/generator.
 */
export const FidelityReportSchema = z.object({
  /**
   * Overall fidelity score (0–1).
   * Computed as: 1 - sum(lossPoint.confidenceImpact) clamped to [0, 1].
   */
  score: z.number().min(0).max(1),
  /**
   * Whether a lossless round-trip is possible.
   * True only when score === 1.0 and there are zero loss points.
   */
  canRoundTrip: z.boolean(),
  /** Individual loss points that reduce confidence. */
  lossPoints: z.array(LossPointSchema),
  /** Optional node or pipeline scope identifier. */
  scopeId: z.string().optional(),
  /** Whether this report covers a full pipeline run or a single node. */
  scope: z.enum(["node", "file", "pipeline"]).default("node"),
});

export type FidelityReport = z.infer<typeof FidelityReportSchema>;

// ============================================================================
// RESIDUAL ISLAND
// ============================================================================

/**
 * A "residual island" is a source code construct that the pipeline cannot
 * represent in the logical model, and therefore cannot regenerate.
 * These must be surfaced to the user for manual handling.
 */
export const ResidualIslandSchema = z.object({
  /** Stable ID for this island within the report. */
  id: z.string().min(1),
  /**
   * Classification of why this island cannot be modelled.
   */
  kind: z.enum([
    "unsupported-syntax", // Syntax the parser cannot handle
    "imperative-logic", // Imperative/procedural logic not mappable to declarative model
    "runtime-dynamic", // Runtime-dynamic construct (dynamic component, eval, etc.)
    "external-lib-usage", // Undeclared external library usage
    "complex-state-machine", // Complex state machine beyond model capacity
    "css-in-js-pattern", // CSS-in-JS pattern not supported by DS tokens
    "test-harness-code", // Test/fixture code embedded in source
    "unknown", // Unclassified residual
  ]),
  /** Human-readable description of the residual. */
  description: z.string().min(1),
  /** Source location of the residual. */
  sourceRef: SourceRefSchema.optional(),
  /**
   * Suggested remediation for the user.
   */
  remediation: z.string().optional(),
  /**
   * Severity: does this block compilation or is it advisory only?
   */
  severity: z.enum(["blocking", "advisory"]).default("advisory"),
});

export type ResidualIsland = z.infer<typeof ResidualIslandSchema>;

/**
 * Report of all residual islands found during a pipeline run.
 */
export const ResidualIslandReportSchema = z.object({
  /** Total number of residual islands. */
  totalCount: z.number().int().nonnegative(),
  /** Number of blocking residuals (must be resolved before compile). */
  blockingCount: z.number().int().nonnegative(),
  /** The individual islands. */
  islands: z.array(ResidualIslandSchema),
  /** Whether compilation is possible despite residuals. */
  canCompileWithResiduals: z.boolean(),
});

export type ResidualIslandReport = z.infer<typeof ResidualIslandReportSchema>;

// ============================================================================
// FACTORY HELPERS
// ============================================================================

/**
 * Computes a FidelityReport from a list of loss points.
 */
export function computeFidelityReport(
  lossPoints: readonly LossPoint[],
  scopeId?: string,
  scope: FidelityReport["scope"] = "node",
): FidelityReport {
  const totalImpact = lossPoints.reduce(
    (sum, lp) => sum + lp.confidenceImpact,
    0,
  );
  const score = Math.max(0, Math.min(1, 1 - totalImpact));
  return {
    score,
    canRoundTrip: lossPoints.length === 0,
    lossPoints: [...lossPoints],
    scopeId,
    scope,
  };
}

/**
 * Creates an empty, perfect-fidelity report (no loss points, score = 1).
 */
export function createPerfectFidelityReport(
  scopeId?: string,
): FidelityReport {
  return {
    score: 1,
    canRoundTrip: true,
    lossPoints: [],
    scopeId,
    scope: "node",
  };
}

/**
 * Creates a ResidualIslandReport from an array of islands.
 */
export function createResidualIslandReport(
  islands: readonly ResidualIsland[],
): ResidualIslandReport {
  const blockingCount = islands.filter((i) => i.severity === "blocking").length;
  return {
    totalCount: islands.length,
    blockingCount,
    islands: [...islands],
    canCompileWithResiduals: blockingCount === 0,
  };
}
