package com.ghatana.datacloud.launcher.http;

import java.util.Map;

/**
 * Contract-backed route/action access registry.
 *
 * <p>Provides explicit access-level requirements for high-impact routes,
 * reducing reliance on path-prefix inference in security decisions.
 *
 * <p>DC-P1-04: Route entries are generated from OpenAPI contracts via
 * {@code scripts/generate-route-security-metadata.mjs}. Do not edit manually.
 * Regenerate with: {@code node scripts/generate-route-security-metadata.mjs}
 *
 * @doc.type class
 * @doc.purpose Route/action access-level registry for Data Cloud HTTP security
 * @doc.layer product
 * @doc.pattern Registry
 */
final class RouteActionAccessRegistry {

    // DC-P1-04: Auto-generated from OpenAPI contracts
    // Regenerate with: node scripts/generate-route-security-metadata.mjs
    private static final Map<String, DataCloudSecurityFilter.AccessLevel> ACCESS_BY_ACTION = Map.ofEntries(
        Map.entry("DELETE /api/v1/action/memory/:agentId/:memoryId", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("DELETE /api/v1/action/pipelines/:pipelineId", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("DELETE /api/v1/alerts/rules/:ruleId", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("DELETE /api/v1/analytics/queries/:queryId", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("DELETE /api/v1/bindings/:bindingId", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("DELETE /api/v1/checkpoints/:checkpointId", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("DELETE /api/v1/connectors/:connectionId", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("DELETE /api/v1/context/keys/:key", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("DELETE /api/v1/deployments/:deploymentId", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("DELETE /api/v1/entities/:collection/:id", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("DELETE /api/v1/entities/:collection/batch", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("DELETE /api/v1/event-types/:eventTypeId/schemas/:schemaId", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("DELETE /api/v1/governance/policies/:id", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("DELETE /api/v1/patterns/:patternId", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("DELETE /api/v1/release-readiness/:id", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("DELETE /api/v1/sessions/current", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("DELETE /api/v1/settings/keys/:id/revoke", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("DELETE /data-fabric/connectors/:connectionId", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("GET /admin/capabilities/connectors", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /admin/capabilities/encodings", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /admin/capabilities/schemas", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /admin/capabilities/transforms", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/action/agents/catalog", DataCloudSecurityFilter.AccessLevel.VIEWER),
        Map.entry("GET /api/v1/action/agents/catalog/:id", DataCloudSecurityFilter.AccessLevel.VIEWER),
        Map.entry("GET /api/v1/action/autonomy/domains", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("GET /api/v1/action/autonomy/domains/:domain", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("GET /api/v1/action/autonomy/level", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("GET /api/v1/action/autonomy/logs", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("GET /api/v1/action/autonomy/plan/:actionType", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("GET /api/v1/action/executions/:executionId", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/action/executions/:executionId/checkpoints", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/action/executions/:executionId/logs", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/action/learning/review", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/action/learning/status", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/action/memory", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/action/memory/:agentId", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/action/memory/:agentId/:tier", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/action/pipelines", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/action/pipelines/:pipelineId", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("GET /api/v1/action/pipelines/:pipelineId/executions", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("GET /api/v1/action/pipelines/:pipelineId/executions/:executionId", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("GET /api/v1/action/pipelines/:pipelineId/executions/:executionId/logs", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("GET /api/v1/action/plugins", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/action/plugins/:id", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("GET /api/v1/action/plugins/:id/sandbox", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("GET /api/v1/action/plugins/marketplace", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("GET /api/v1/agents", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/agents/:agentId", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/agents/:agentId/memory", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/ai/actions", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/ai/advisories/fabric/:collectionId", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/ai/advisories/quality/:collectionId", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/ai/advisories/workflows/:workflowId", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/ai/correlations", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/ai/feedback", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/ai/quality-summary", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/ai/suggestions", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/ai/suggestions/metrics", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/alerts", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/alerts/:id/remediations", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/alerts/groups", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/alerts/rules", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/alerts/stream", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/alerts/suggestions", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/analytics/kpis", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/analytics/query/:queryId", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/analytics/query/:queryId/plan", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/anomalies", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/auth/platform-session", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/auth/roles", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/bindings", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/bindings/:bindingId", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/brain/attention/thresholds", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/brain/config", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/brain/health", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/brain/patterns", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/brain/salience/:itemId", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/brain/stats", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/brain/workspace", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/brain/workspace/stream", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/catalog/marketplace/agents", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/catalog/marketplace/agents/:agentId", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/catalog/marketplace/agents/:agentId/reviews", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/checkpoints", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/checkpoints/:checkpointId", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/collections", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/collections/:id/cost-report", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/compliance/legal-holds", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/compliance/posture", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/compliance/soc2/report", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/conformance", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/conformance/entity-store", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/conformance/event-log-store", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/connectors", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/connectors/:connectionId", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("GET /api/v1/connectors/:connectionId/health", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("GET /api/v1/connectors/:connectionId/schema", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("GET /api/v1/connectors/:connectionId/sync/status", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("GET /api/v1/context", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/context/:collection", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/context/:collection/lineage/trust", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/context/snapshot", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/costs/summary", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/data-products", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/data-quality/trust-scores", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/entities/:collection", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/entities/:collection/:id", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("GET /api/v1/entities/:collection/:id/history", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("GET /api/v1/entities/:collection/export", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("GET /api/v1/entities/:collection/query/stream", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("GET /api/v1/entities/:collection/search", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("GET /api/v1/entities/:collection/similar", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("GET /api/v1/entities/:collection/stream", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("GET /api/v1/events", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/events/:offset", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/events/notifications", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/features/:entityId", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/governance/audit/summary", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/governance/compliance/summary", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/governance/degradation", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/governance/inventory", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/governance/kill-switch", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/governance/ops/summary", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/governance/policies", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("GET /api/v1/governance/policies/:id", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("GET /api/v1/governance/privacy/pii-fields", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/governance/privacy/verify", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/governance/retention/policy", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/governance/security/egress", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/hitl/pending", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/learning/episodes", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/learning/policies", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/learning/review", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/learning/status", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/learning/stream", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/lineage/:collection", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/lineage/:collection/impact", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/mastery/preview/decision", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/mastery/preview/retrieval", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/models", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/models/:modelName", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/operations/jobs", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/operations/jobs/:operationId", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/patterns", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/patterns/:patternId", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/queries/estimate", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/reports", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/reports/:reportId", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/runs", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/runs/:runId", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/sessions", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/sessions/current", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/settings", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/settings/approvals", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("GET /api/v1/settings/keys", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("GET /api/v1/settings/keys/:id", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("GET /api/v1/settings/notifications", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("GET /api/v1/settings/preferences", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("GET /api/v1/settings/profile", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("GET /api/v1/release-readiness", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("GET /api/v1/release-readiness/stats", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("GET /api/v1/release-readiness/:productId/:productVersion/:releaseTarget", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("GET /api/v1/settings/security", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("GET /api/v1/sovereign/audit", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/sovereign/backup", DataCloudSecurityFilter.AccessLevel.AUDITOR),
        Map.entry("GET /api/v1/sovereign/conformance", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/sovereign/data-residency", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/sovereign/data-subject-controls", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/sovereign/models", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/sovereign/profile", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/sovereign/region-policy", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/surfaces", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/surfaces/schema", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/user-activity/recent", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /api/v1/voice/intents", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /data-fabric/connectors", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /data-fabric/connectors/:connectionId", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("GET /data-fabric/connectors/:connectionId/statistics", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("GET /data-fabric/metrics", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /events/notifications", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /events/stream", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /governance/audit/summary", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /governance/compliance/summary", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /governance/degradation", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /governance/kill-switch", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /governance/ops/summary", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /governance/security/egress", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /health", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /health/deep", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /health/detail", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /info", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /lifecycle/changes/:changeId", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /lifecycle/recertification/:recertificationId", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /live", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /mcp/v1/tools", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /metrics", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /metrics/slo", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("GET /ready", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("PATCH /api/v1/settings/notifications", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("PATCH /api/v1/settings/preferences", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("PATCH /api/v1/settings/profile", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("POST /api/v1/action/autonomy/feedback-policy", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("POST /api/v1/action/executions/:executionId/cancel", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/action/executions/:executionId/checkpoint", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/action/executions/:executionId/restore", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/action/executions/:executionId/retry", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/action/executions/:executionId/rollback", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/action/learning/review/:reviewId/approve", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("POST /api/v1/action/learning/review/:reviewId/reject", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("POST /api/v1/action/learning/trigger", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/action/memory/:agentId", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/action/memory/:agentId/search", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/action/pipelines", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/action/pipelines/:pipelineId/execute", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("POST /api/v1/action/pipelines/:pipelineId/executions/:executionId/cancel", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("POST /api/v1/action/plugins/:id/conformance", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("POST /api/v1/action/plugins/:id/disable", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("POST /api/v1/action/plugins/:id/enable", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("POST /api/v1/action/plugins/:id/upgrade", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("POST /api/v1/action/plugins/:id/validate", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("POST /api/v1/agents", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/agents/:agentId/execute", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/ai/context/rank", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/ai/memory/retention", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/ai/next-action", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/ai/quality/drift-detect", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/ai/rag-feedback", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/ai/suggestions", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/ai/suggestions/:id/apply", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/ai/suggestions/:id/feedback", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/ai/suggestions/stages", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/alerts/:alertId/acknowledge", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/alerts/:alertId/resolve", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/alerts/:id/auto-remediate", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/alerts/:id/escalate", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/alerts/:id/remediate", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/alerts/:id/remediate/rollback", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/alerts/groups/:groupId/resolve", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/alerts/rules", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/alerts/suggestions/:suggestionId/apply", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/analytics/aggregation", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/analytics/anomalies", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/analytics/anomalies/:anomalyId/false-positive", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/analytics/automate", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/analytics/explain", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/analytics/forecast", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/analytics/kpis", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/analytics/query", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/analytics/suggest", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/bindings/:bindingId/simulate", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/brain/attention/elevate", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/brain/explain", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/brain/patterns/match", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/catalog/marketplace/agents", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/catalog/marketplace/agents/:agentId/install", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/catalog/marketplace/agents/:agentId/reviews", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/catalog/marketplace/agents/:agentId/simulate-install", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/checkpoints", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/release-readiness", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("POST /api/v1/collections/:collection/metadata", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/collections/:id/migrate", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/compliance/ccpa/opt-out", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/compliance/evidence-package", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/compliance/gdpr/access", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/compliance/gdpr/erasure", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/compliance/gdpr/portability", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/compliance/legal-holds", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/compliance/legal-holds/:id/extend", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/compliance/legal-holds/:id/release", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/connectors", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/connectors/:connectionId/disable", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("POST /api/v1/connectors/:connectionId/enable", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/connectors/:connectionId/rotate-credentials", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("POST /api/v1/connectors/:connectionId/sync", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/connectors/:connectionId/test", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("POST /api/v1/connectors/:connectorId/sync-health", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("POST /api/v1/connectors/suggest-mapping", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("POST /api/v1/context/:collection/rag", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/context/:collection/rag-policy-check", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/data-products", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/data-products/:productId/contract-check", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/data-products/:productId/sla-monitor", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/data-products/:productId/subscribe", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/deployments", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/entities/:collection", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/entities/:collection/anomalies", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("POST /api/v1/entities/:collection/batch", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("POST /api/v1/entities/:collection/export", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("POST /api/v1/entities/:collection/infer-schema", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("POST /api/v1/entities/:collection/suggest", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("POST /api/v1/entities/:collection/validate", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("POST /api/v1/entities/:collection/validate/batch", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("POST /api/v1/event-types/:eventTypeId/schemas", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/event-types/:eventTypeId/schemas/:schemaId/bindings", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/events", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/events/batch", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/features", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/governance/degradation", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/governance/kill-switch/activate", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/governance/kill-switch/deactivate", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/governance/policies", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("POST /api/v1/governance/policies/:id/toggle", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("POST /api/v1/governance/policies/simulate", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("POST /api/v1/governance/policy/evaluate", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/governance/privacy/redact", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("POST /api/v1/governance/recommend", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/governance/retention/classify", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/governance/retention/purge", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("POST /api/v1/governance/security/scan", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/hitl/:reviewId/approve", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/hitl/:reviewId/escalate", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/hitl/:reviewId/reject", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/learning/policies/:policyId/approve", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/learning/policies/:policyId/reject", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/learning/reflect", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/learning/review/:reviewId/approve", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("POST /api/v1/learning/review/:reviewId/reject", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("POST /api/v1/learning/trigger", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/mastery/learning-deltas/:deltaId/dry-run-promotion", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/mastery/obsolescence-events/process", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/models", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/models/:modelName/promote", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("POST /api/v1/nlp/parse", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/operations/anomaly-group", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/operations/forecast", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/operations/jobs/:operationId/cancel", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/patterns", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/patterns/:patternId/activate", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/patterns/:patternId/deactivate", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/queries/explain", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/queries/federated", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/query/nlq", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/reports", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/runs/:runId/cancel", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/session", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/sessions/cleanup", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/settings", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/settings/approval-request", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("POST /api/v1/settings/approvals/:id/approve", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("POST /api/v1/settings/approvals/:id/reject", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("POST /api/v1/settings/keys", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("POST /api/v1/settings/keys/:id/rotate", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("POST /api/v1/settings/security", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("POST /api/v1/sovereign/backup", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/sovereign/restore", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/sovereign/validate-transfer", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/user-activity/log", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/voice/intent", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/voice/intent/classify", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/workflows/analyze-risk", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /api/v1/workflows/validate", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /data-fabric/connectors", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /data-fabric/connectors/:connectionId/disable", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("POST /data-fabric/connectors/:connectionId/enable", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /data-fabric/connectors/:connectionId/sync", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /data-fabric/connectors/:connectionId/test", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("POST /governance/degradation", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /governance/kill-switch/activate", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /governance/kill-switch/deactivate", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /governance/policy/evaluate", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /governance/security/scan", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /lifecycle/changes", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /lifecycle/changes/:changeId/approve", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /lifecycle/changes/:changeId/reject", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /lifecycle/recertification", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("POST /mcp/v1/tools", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("PUT /api/v1/action/autonomy/level", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("PUT /api/v1/action/memory/:agentId/:memoryId/retain", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("PUT /api/v1/action/pipelines/:pipelineId", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("PUT /api/v1/alerts/rules/:ruleId", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("PUT /api/v1/bindings/:bindingId", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("PUT /api/v1/brain/attention/thresholds", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("PUT /api/v1/connectors/:connectionId", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("PUT /api/v1/context", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("PUT /api/v1/deployments/:deploymentId", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("PUT /api/v1/event-types/:eventTypeId/schemas/:schemaId", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("PUT /api/v1/governance/policies/:id", DataCloudSecurityFilter.AccessLevel.ADMIN),
        Map.entry("PUT /api/v1/patterns/:patternId", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("PUT /api/v1/sovereign/data-subject-controls", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("PUT /api/v1/sovereign/profile", DataCloudSecurityFilter.AccessLevel.OPERATOR),
        Map.entry("PUT /data-fabric/connectors/:connectionId", DataCloudSecurityFilter.AccessLevel.ADMIN)

    );

    private RouteActionAccessRegistry() {
    }

    static DataCloudSecurityFilter.AccessLevel requiredAccess(String method, String path) {
        DataCloudSecurityFilter.AccessLevel metadataAccessLevel = RouteSecurityRegistry.lookupRuntimePath(method, path)
                .map(RouteSecurityMetadata::requiredAccess)
                .orElse(null);
        if (metadataAccessLevel != null) {
            return metadataAccessLevel;
        }

        String normalized = normalizePath(path);
        String key = method.toUpperCase() + " " + normalized;
        DataCloudSecurityFilter.AccessLevel accessLevel = ACCESS_BY_ACTION.get(key);
        if (accessLevel != null) {
            return accessLevel;
        }
        return null;
    }

    private static String normalizePath(String path) {
        String normalized = path.replaceAll("/[0-9a-fA-F-]{8,}", "/:id");
        // P1-03: DO NOT normalize /api/v1/action/* to /api/v1/* - preserve canonical namespace
        // This ensures action routes are looked up with their canonical paths
        normalized = normalized.replaceAll("/learning/review/[^/]+/(approve|reject)$", "/learning/review/:reviewId/$1");
        normalized = normalized.replaceAll("/action/learning/review/[^/]+/(approve|reject)$", "/action/learning/review/:reviewId/$1");
        normalized = normalized.replaceAll("/connectors/[^/]+", "/connectors/:connectionId");
        normalized = normalized.replaceAll("/settings/keys/[^/]+/rotate$", "/settings/keys/:id/rotate");
        normalized = normalized.replaceAll("/settings/keys/[^/]+/revoke$", "/settings/keys/:id/revoke");
        normalized = normalized.replaceAll("/settings/keys/[^/]+$", "/settings/keys/:id");
        normalized = normalized.replaceAll("/settings/approvals/[^/]+/(approve|reject)$", "/settings/approvals/:id/$1");
        normalized = normalized.replaceAll("/plugins/[^/]+", "/plugins/:id");
        normalized = normalized.replaceAll("/action/plugins/[^/]+", "/action/plugins/:id");
        normalized = normalized.replaceAll("/governance/policies/[^/]+/toggle$", "/governance/policies/:id/toggle");
        normalized = normalized.replaceAll("/governance/policies/[^/]+$", "/governance/policies/:id");
        normalized = normalized.replaceAll("/autonomy/plan/[^/]+$", "/autonomy/plan/:actionType");
        normalized = normalized.replaceAll("/action/autonomy/plan/[^/]+$", "/action/autonomy/plan/:actionType");
        normalized = normalized.replaceAll("/context/keys/[^/]+$", "/context/keys/:key");
        normalized = normalized.replaceAll("/context/[^/]+/rag-policy-check$", "/context/:collection/rag-policy-check");
        normalized = normalized.replaceAll("/pipelines/[^/]+/execute$", "/pipelines/:pipelineId/execute");
        normalized = normalized.replaceAll("/action/pipelines/[^/]+/execute$", "/action/pipelines/:pipelineId/execute");
        normalized = normalized.replaceAll("/pipelines/[^/]+/executions/[^/]+/cancel$", "/pipelines/:pipelineId/executions/:executionId/cancel");
        normalized = normalized.replaceAll("/pipelines/[^/]+$", "/pipelines/:pipelineId");
        normalized = normalized.replaceAll("/action/pipelines/[^/]+$", "/action/pipelines/:pipelineId");
        normalized = normalized.replaceAll("/executions/[^/]+/(cancel|retry|rollback|restore)$", "/executions/:executionId/$1");
        normalized = normalized.replaceAll("/action/executions/[^/]+/(cancel|retry|rollback|restore)$", "/action/executions/:executionId/$1");
        normalized = normalized.replaceAll("/alerts/groups/[^/]+/resolve$", "/alerts/groups/:groupId/resolve");
        normalized = normalized.replaceAll("/alerts/suggestions/[^/]+/apply$", "/alerts/suggestions/:suggestionId/apply");
        normalized = normalized.replaceAll("/alerts/rules/[^/]+$", "/alerts/rules/:ruleId");
        normalized = normalized.replaceAll("/alerts/[^/]+/(remediate|auto-remediate|escalate|acknowledge|resolve)$", "/alerts/:id/$1");
        normalized = normalized.replaceAll("/models/[^/]+$", "/models/:modelId");
        normalized = normalized.replaceAll("/operations/jobs/[^/]+/cancel$", "/operations/jobs/:operationId/cancel");
        normalized = normalized.replaceAll("/operations/jobs/[^/]+$", "/operations/jobs/:operationId");
        normalized = normalized.replaceAll("/action/memory/[^/]+/[^/]+", "/action/memory/:agentId/:memoryId");
        normalized = normalized.replaceAll("/release-readiness/[^/]+/[^/]+/[^/]+$", "/release-readiness/:productId/:productVersion/:releaseTarget");
        normalized = normalized.replaceAll("/release-readiness/(?!stats$)[^/]+$", "/release-readiness/:id");
        normalized = normalized.replaceAll("/entities/[^/]+/[^/]+$", "/entities/:collection/:id");
        normalized = normalized.replaceAll("/entities/[^/]+$", "/entities/:collection");
        return normalized;
    }
}
