// Auto-generated from data-cloud.yaml + action-plane.yaml by generate-route-security-metadata.mjs
// DC-P1-07: Do not edit manually - regenerate with the script

// Add these entries to RouteActionAccessRegistry.ACCESS_BY_ACTION

Map.entry("GET metrics", DataCloudSecurityFilter.AccessLevel.VIEWER),
Map.entry("DELETE api/v1/entities/:collection/:id", DataCloudSecurityFilter.AccessLevel.VIEWER),
Map.entry("GET api/v1/events", DataCloudSecurityFilter.AccessLevel.VIEWER),
Map.entry("POST api/v1/pipelines/:pipelineId/executions/:executionId/cancel", DataCloudSecurityFilter.AccessLevel.VIEWER),
Map.entry("GET api/v1/alerts/stream", DataCloudSecurityFilter.AccessLevel.VIEWER),
Map.entry("GET api/v1/compliance/posture", DataCloudSecurityFilter.AccessLevel.VIEWER),
Map.entry("GET api/v1/sovereign/conformance", DataCloudSecurityFilter.AccessLevel.VIEWER),
Map.entry("GET api/v1/sovereign/region-policy", DataCloudSecurityFilter.AccessLevel.VIEWER),
Map.entry("PUT api/v1/memory/:agentId/:memoryId/retain", DataCloudSecurityFilter.AccessLevel.VIEWER),
Map.entry("GET api/v1/brain/salience/:itemId", DataCloudSecurityFilter.AccessLevel.VIEWER),
Map.entry("POST api/v1/mastery/obsolescence-events/process", DataCloudSecurityFilter.AccessLevel.VIEWER),
Map.entry("POST api/v1/analytics/explain", DataCloudSecurityFilter.AccessLevel.VIEWER),
Map.entry("GET api/v1/events/notifications", DataCloudSecurityFilter.AccessLevel.VIEWER),
Map.entry("POST api/v1/entities/:collection/infer-schema", DataCloudSecurityFilter.AccessLevel.VIEWER),
Map.entry("POST api/v1/executions/:executionId/restore", DataCloudSecurityFilter.AccessLevel.VIEWER),
Map.entry("POST api/v1/governance/recommend", DataCloudSecurityFilter.AccessLevel.VIEWER),
Map.entry("GET api/v1/ai/quality-summary", DataCloudSecurityFilter.AccessLevel.VIEWER),
Map.entry("GET api/v1/ai/advisories/fabric/:collectionId", DataCloudSecurityFilter.AccessLevel.VIEWER),
Map.entry("POST api/v1/models/:modelName/promote", DataCloudSecurityFilter.AccessLevel.VIEWER),
Map.entry("GET api/v1/features/:entityId", DataCloudSecurityFilter.AccessLevel.VIEWER),
Map.entry("POST api/v1/voice/intent/classify", DataCloudSecurityFilter.AccessLevel.VIEWER),
Map.entry("POST api/v1/governance/policies/:id/toggle", DataCloudSecurityFilter.AccessLevel.VIEWER),
Map.entry("GET api/v1/surfaces/schema", DataCloudSecurityFilter.AccessLevel.VIEWER),
Map.entry("POST api/v1/autonomy/feedback-policy", DataCloudSecurityFilter.AccessLevel.VIEWER),
Map.entry("GET api/v1/connectors/:connectionId/sync/status", DataCloudSecurityFilter.AccessLevel.VIEWER),
Map.entry("GET data-fabric/metrics", DataCloudSecurityFilter.AccessLevel.VIEWER),
Map.entry("POST api/v1/user-activity/log", DataCloudSecurityFilter.AccessLevel.VIEWER),
Map.entry("GET api/v1/agents/catalog/:id", DataCloudSecurityFilter.AccessLevel.VIEWER),
Map.entry("POST api/v1/plugins/:id/upgrade", DataCloudSecurityFilter.AccessLevel.VIEWER),
Map.entry("GET api/v1/events/:offset", DataCloudSecurityFilter.AccessLevel.VIEWER),
Map.entry("POST api/v1/collections/:id/migrate", DataCloudSecurityFilter.AccessLevel.VIEWER),
Map.entry("GET metrics/slo", DataCloudSecurityFilter.AccessLevel.VIEWER),
Map.entry("POST api/v1/events/batch", DataCloudSecurityFilter.AccessLevel.VIEWER),
Map.entry("POST api/v1/patterns/:patternId/deactivate", DataCloudSecurityFilter.AccessLevel.VIEWER),
Map.entry("GET api/v1/compliance/soc2/report", DataCloudSecurityFilter.AccessLevel.VIEWER),
Map.entry("GET admin/capabilities/transforms", DataCloudSecurityFilter.AccessLevel.VIEWER),
Map.entry("DELETE api/v1/event-types/:eventTypeId/schemas/:schemaId", DataCloudSecurityFilter.AccessLevel.VIEWER),
Map.entry("POST api/v1/bindings/:bindingId/simulate", DataCloudSecurityFilter.AccessLevel.VIEWER),
Map.entry("POST api/v1/runs/:runId/cancel", DataCloudSecurityFilter.AccessLevel.VIEWER),
Map.entry("POST api/v1/session", DataCloudSecurityFilter.AccessLevel.VIEWER),
Map.entry("POST api/v1/sessions/cleanup", DataCloudSecurityFilter.AccessLevel.VIEWER),
Map.entry("GET lifecycle/recertification/:recertificationId", DataCloudSecurityFilter.AccessLevel.VIEWER),
Map.entry("POST api/v1/catalog/marketplace/agents/:agentId/reviews", DataCloudSecurityFilter.AccessLevel.VIEWER),
Map.entry("GET api/v1/costs/summary", DataCloudSecurityFilter.AccessLevel.VIEWER),
Map.entry("GET api/v1/ai/suggestions", DataCloudSecurityFilter.AccessLevel.VIEWER),
Map.entry("POST api/v1/nlp/parse", DataCloudSecurityFilter.AccessLevel.VIEWER),
Map.entry("GET api/v1/auth/roles", DataCloudSecurityFilter.AccessLevel.VIEWER),
Map.entry("POST api/v1/ai/suggestions/stages", DataCloudSecurityFilter.AccessLevel.VIEWER),