package com.ghatana.yappc.ai;

/**
 * Discriminator indicating whether an AI-generated enrichment or suggestion was produced
 * by a deterministic rule-based system or a probabilistic ML/LLM model.
 *
 * <p>Every enrichment or generation surface in the YAPPC AI module must attach this label
 * so that product UIs and audit logs can surface the provenance of AI-produced content to
 * users. This is required for transparency, explainability, and regulatory compliance.</p>
 *
 * <h2>Usage</h2>
 * <pre>{@code
 * // A suggestion generated by the LLM router
 * Suggestion s = new Suggestion(id, project, phase, type, text, AiSource.MODEL, Instant.now());
 *
 * // A suggestion produced by a deterministic rule engine
 * Suggestion r = new Suggestion(id, project, phase, type, text, AiSource.RULE, Instant.now());
 * }</pre>
 *
 * <h2>Rendering guidance</h2>
 * <ul>
 *   <li>{@link #MODEL} — display "AI-generated" badge or attribution label.</li>
 *   <li>{@link #RULE}  — display "Rule-based" or "Automated" badge.</li>
 * </ul>
 *
 * @doc.type enum
 * @doc.purpose Canonical AI-source discriminator (rule vs model) for enrichment and generation surfaces
 * @doc.layer product
 * @doc.pattern ValueObject
 */
public enum AiSource {

    /**
     * The enrichment was produced by a deterministic rule-based system (pattern matching,
     * threshold checks, hard-coded heuristics, finite-state machines, etc.).
     * The output is reproducible given the same input.
     */
    RULE,

    /**
     * The enrichment was produced by a probabilistic ML or large-language model.
     * The output may vary across calls for the same input (temperature &gt; 0) and
     * is not fully explainable from first principles.
     */
    MODEL
}
