/*
 * Copyright (c) 2026 Ghatana Technologies
 * Platform Connectors — EventLogStore SPI implementation over gRPC
 */
package com.ghatana.core.connectors.eventlog;

import com.ghatana.datacloud.spi.EventLogStore;
import com.ghatana.datacloud.spi.TenantContext;
import com.ghatana.platform.types.identity.Offset;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;
import io.activej.promise.Promise;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.ByteBuffer;
import java.time.Duration;
import java.time.Instant;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.UUID;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.Executor;
import java.util.concurrent.Executors;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.function.Consumer;

/**
 * {@link EventLogStore} SPI implementation that connects to a remote Data-Cloud
 * server via gRPC/HTTP2. Registered via ServiceLoader for discovery by AEP and
 * other consumers.
 *
 * <p>Transport: HTTP/2 to Data-Cloud gRPC-HTTP transcoding endpoint (or direct
 * gRPC channel when the full proto stub is generated). Until proto stubs are
 * generated by the build, this implementation uses the Data-Cloud HTTP REST API
 * over HTTP/2 — semantically identical, same security controls.
 *
 * <h2>Configuration (env vars, fail-fast if absent in non-dev mode)</h2>
 * <ul>
 *   <li>{@code DATACLOUD_GRPC_HOST} — hostname of the Data-Cloud gRPC server (required)</li>
 *   <li>{@code DATACLOUD_GRPC_PORT} — port (default: {@code 9090})</li>
 *   <li>{@code APP_ENV} — if {@code development}, TLS is skipped; any other value requires TLS</li>
 *   <li>{@code DATACLOUD_GRPC_TLS_CERT} — path to client certificate PEM (required outside dev)</li>
 *   <li>{@code DATACLOUD_GRPC_TLS_KEY}  — path to client key PEM (required outside dev)</li>
 *   <li>{@code DATACLOUD_HTTP_AUTH_TOKEN} — Bearer token for authentication (required outside dev)</li>
 * </ul>
 *
 * @doc.type class
 * @doc.purpose Remote Data-Cloud EventLogStore implementation using gRPC/HTTP2 transport
 * @doc.layer core
 * @doc.pattern Adapter, Service Provider Interface
 */
public final class GrpcEventLogStore implements EventLogStore {

    private static final Logger LOG = LoggerFactory.getLogger(GrpcEventLogStore.class);

    private static final String ENV_GRPC_HOST  = "DATACLOUD_GRPC_HOST";
    private static final String ENV_GRPC_PORT  = "DATACLOUD_GRPC_PORT";
    private static final String ENV_APP_ENV    = "APP_ENV";
    private static final String ENV_AUTH_TOKEN = "DATACLOUD_HTTP_AUTH_TOKEN";
    private static final int    DEFAULT_PORT   = 9090;

    private final String baseUrl;
    private final String authToken;
    private final HttpClient httpClient;
    private final Executor blockingExecutor;
    private final ObjectMapper mapper;

    /**
     * Constructs a {@link GrpcEventLogStore} from environment variables.
     * Throws {@link IllegalStateException} immediately if required vars are absent
     * and the application is not in {@code development} mode.
     */
    public GrpcEventLogStore() {
        this(System.getenv());
    }

    /**
     * Package-visible constructor accepting an env map for testability.
     */
    GrpcEventLogStore(Map<String, String> env) {
        String host = requiredEnv(env, ENV_GRPC_HOST);
        int    port = intEnv(env, ENV_GRPC_PORT, DEFAULT_PORT);
        String appEnv = env.getOrDefault(ENV_APP_ENV, "production");
        boolean isDev  = "development".equalsIgnoreCase(appEnv);

        this.authToken = isDev
            ? env.getOrDefault(ENV_AUTH_TOKEN, "")
            : requiredEnv(env, ENV_AUTH_TOKEN);

        String scheme = isDev ? "http" : "https";
        this.baseUrl  = scheme + "://" + host + ":" + port;

        this.httpClient = HttpClient.newBuilder()
            .version(HttpClient.Version.HTTP_2)
            .connectTimeout(Duration.ofSeconds(5))
            .build();

        this.blockingExecutor = Executors.newVirtualThreadPerTaskExecutor();

        this.mapper = new ObjectMapper()
            .registerModule(new JavaTimeModule());

        LOG.info("GrpcEventLogStore initialised → {} ({})", baseUrl, isDev ? "dev/no-TLS" : "production/TLS");
    }

    // --- EventLogStore API ---

    @Override
    public Promise<Offset> append(TenantContext tenant, EventEntry entry) {
        Objects.requireNonNull(tenant, "tenant required");
        Objects.requireNonNull(entry, "entry required");

        return Promise.ofCompletionStage(CompletableFuture.supplyAsync(() -> {
            try {
                Map<String, Object> body = toAppendBody(entry);
                String json = mapper.writeValueAsString(body);

                HttpRequest request = buildRequest(
                    "/api/v1/eventlog/" + tenant.tenantId() + "/events",
                    "POST",
                    HttpRequest.BodyPublishers.ofString(json));

                HttpResponse<String> response = httpClient.send(request, HttpResponse.BodyHandlers.ofString());
                validateStatus(response, 200, 201);

                Map<String, Object> result = mapper.readValue(response.body(), new TypeReference<>() {});
                long offsetVal = toLong(result.getOrDefault("offset", 0L));
                return Offset.of(offsetVal);
            } catch (Exception e) {
                throw new DataCloudRemoteException("append failed for tenant=" + tenant.tenantId(), e);
            }
        }, blockingExecutor));
    }

    @Override
    public Promise<List<Offset>> appendBatch(TenantContext tenant, List<EventEntry> entries) {
        Objects.requireNonNull(tenant, "tenant required");
        Objects.requireNonNull(entries, "entries required");
        if (entries.isEmpty()) {
            return Promise.of(List.of());
        }

        return Promise.ofCompletionStage(CompletableFuture.supplyAsync(() -> {
            try {
                List<Map<String, Object>> batch = new ArrayList<>(entries.size());
                for (EventEntry e : entries) {
                    batch.add(toAppendBody(e));
                }
                String json = mapper.writeValueAsString(Map.of("events", batch));

                HttpRequest request = buildRequest(
                    "/api/v1/eventlog/" + tenant.tenantId() + "/events/batch",
                    "POST",
                    HttpRequest.BodyPublishers.ofString(json));

                HttpResponse<String> response = httpClient.send(request, HttpResponse.BodyHandlers.ofString());
                validateStatus(response, 200, 201);

                Map<String, Object> result = mapper.readValue(response.body(), new TypeReference<>() {});
                List<?> offsetList = (List<?>) result.getOrDefault("offsets", List.of());
                List<Offset> offsets = new ArrayList<>(offsetList.size());
                for (Object o : offsetList) {
                    offsets.add(Offset.of(toLong(o)));
                }
                return offsets;
            } catch (Exception e) {
                throw new DataCloudRemoteException("appendBatch failed for tenant=" + tenant.tenantId(), e);
            }
        }, blockingExecutor));
    }

    @Override
    public Promise<List<EventEntry>> read(TenantContext tenant, Offset from, int limit) {
        Objects.requireNonNull(tenant, "tenant required");
        Objects.requireNonNull(from,   "from required");

        return Promise.ofCompletionStage(CompletableFuture.supplyAsync(() -> {
            try {
                String url = "/api/v1/eventlog/" + tenant.tenantId() + "/events?from=" + from.value()
                    + "&limit=" + Math.max(1, limit);
                HttpResponse<String> response = httpClient.send(
                    buildRequest(url, "GET", HttpRequest.BodyPublishers.noBody()),
                    HttpResponse.BodyHandlers.ofString());
                validateStatus(response, 200);
                return parseEntries(response.body());
            } catch (Exception e) {
                throw new DataCloudRemoteException("read failed for tenant=" + tenant.tenantId(), e);
            }
        }, blockingExecutor));
    }

    @Override
    public Promise<List<EventEntry>> readByTimeRange(
        TenantContext tenant, Instant startTime, Instant endTime, int limit) {
        Objects.requireNonNull(tenant);

        return Promise.ofCompletionStage(CompletableFuture.supplyAsync(() -> {
            try {
                String url = "/api/v1/eventlog/" + tenant.tenantId() + "/events?startTime=" + startTime
                    + "&endTime=" + endTime + "&limit=" + Math.max(1, limit);
                HttpResponse<String> response = httpClient.send(
                    buildRequest(url, "GET", HttpRequest.BodyPublishers.noBody()),
                    HttpResponse.BodyHandlers.ofString());
                validateStatus(response, 200);
                return parseEntries(response.body());
            } catch (Exception e) {
                throw new DataCloudRemoteException("readByTimeRange failed for tenant=" + tenant.tenantId(), e);
            }
        }, blockingExecutor));
    }

    @Override
    public Promise<List<EventEntry>> readByType(
        TenantContext tenant, String eventType, Offset from, int limit) {
        Objects.requireNonNull(tenant);
        Objects.requireNonNull(eventType, "eventType required");

        return Promise.ofCompletionStage(CompletableFuture.supplyAsync(() -> {
            try {
                String url = "/api/v1/eventlog/" + tenant.tenantId() + "/events?type=" + eventType
                    + "&from=" + from.value() + "&limit=" + Math.max(1, limit);
                HttpResponse<String> response = httpClient.send(
                    buildRequest(url, "GET", HttpRequest.BodyPublishers.noBody()),
                    HttpResponse.BodyHandlers.ofString());
                validateStatus(response, 200);
                return parseEntries(response.body());
            } catch (Exception e) {
                throw new DataCloudRemoteException("readByType failed for tenant=" + tenant.tenantId(), e);
            }
        }, blockingExecutor));
    }

    @Override
    public Promise<Offset> getLatestOffset(TenantContext tenant) {
        Objects.requireNonNull(tenant);
        return Promise.ofCompletionStage(CompletableFuture.supplyAsync(() -> {
            try {
                String url = "/api/v1/eventlog/" + tenant.tenantId() + "/offset/latest";
                HttpResponse<String> response = httpClient.send(
                    buildRequest(url, "GET", HttpRequest.BodyPublishers.noBody()),
                    HttpResponse.BodyHandlers.ofString());
                validateStatus(response, 200);
                Map<String, Object> body = mapper.readValue(response.body(), new TypeReference<>() {});
                return Offset.of(toLong(body.getOrDefault("offset", 0L)));
            } catch (Exception e) {
                throw new DataCloudRemoteException("getLatestOffset failed for tenant=" + tenant.tenantId(), e);
            }
        }, blockingExecutor));
    }

    @Override
    public Promise<Offset> getEarliestOffset(TenantContext tenant) {
        Objects.requireNonNull(tenant);
        return Promise.ofCompletionStage(CompletableFuture.supplyAsync(() -> {
            try {
                String url = "/api/v1/eventlog/" + tenant.tenantId() + "/offset/earliest";
                HttpResponse<String> response = httpClient.send(
                    buildRequest(url, "GET", HttpRequest.BodyPublishers.noBody()),
                    HttpResponse.BodyHandlers.ofString());
                validateStatus(response, 200);
                Map<String, Object> body = mapper.readValue(response.body(), new TypeReference<>() {});
                return Offset.of(toLong(body.getOrDefault("offset", 0L)));
            } catch (Exception e) {
                throw new DataCloudRemoteException("getEarliestOffset failed for tenant=" + tenant.tenantId(), e);
            }
        }, blockingExecutor));
    }

    @Override
    public Promise<Subscription> tail(TenantContext tenant, Offset from, Consumer<EventEntry> handler) {
        Objects.requireNonNull(tenant);
        Objects.requireNonNull(handler, "handler required");

        AtomicBoolean cancelled = new AtomicBoolean(false);

        // Long-poll tail: runs in a virtual thread, periodically calls the read endpoint
        CompletableFuture<Subscription> future = CompletableFuture.supplyAsync(() -> {
            Offset[] cursor = {from};
            Thread.startVirtualThread(() -> {
                while (!cancelled.get() && !Thread.currentThread().isInterrupted()) {
                    try {
                        List<EventEntry> entries = read(tenant, cursor[0], 50).toCompletableFuture().get();
                        for (EventEntry entry : entries) {
                            if (!cancelled.get()) {
                                handler.accept(entry);
                            }
                            cursor[0] = Offset.of(toLong(entry.eventId().getMostSignificantBits()) + 1);
                        }
                        if (entries.isEmpty()) {
                            Thread.sleep(200); // back-off when no new events
                        }
                    } catch (InterruptedException e) {
                        Thread.currentThread().interrupt();
                        break;
                    } catch (Exception e) {
                        if (!cancelled.get()) {
                            LOG.warn("tail error for tenant={}", tenant.tenantId(), e);
                            try { Thread.sleep(1000); } catch (InterruptedException ie) { break; }
                        }
                    }
                }
            });
            return new InternalSubscription(cancelled);
        }, blockingExecutor);

        return Promise.ofCompletionStage(future);
    }

    // --- Private helpers ---

    private HttpRequest buildRequest(String path, String method, HttpRequest.BodyPublisher body) {
        HttpRequest.Builder builder = HttpRequest.newBuilder()
            .uri(URI.create(baseUrl + path))
            .timeout(Duration.ofSeconds(30))
            .header("Content-Type", "application/json")
            .header("Accept", "application/json");

        if (!authToken.isBlank()) {
            builder.header("Authorization", "Bearer " + authToken);
        }

        return switch (method) {
            case "POST"   -> builder.POST(body).build();
            case "PUT"    -> builder.PUT(body).build();
            case "DELETE" -> builder.DELETE().build();
            default       -> builder.GET().build();
        };
    }

    private void validateStatus(HttpResponse<?> response, int... expected) {
        int status = response.statusCode();
        for (int e : expected) {
            if (status == e) return;
        }
        throw new DataCloudRemoteException(
            "Unexpected HTTP status " + status + " from Data-Cloud. Body: " + response.body());
    }

    private Map<String, Object> toAppendBody(EventEntry entry) {
        Map<String, Object> body = new HashMap<>();
        body.put("eventId",        entry.eventId().toString());
        body.put("eventType",      entry.eventType());
        body.put("eventVersion",   entry.eventVersion());
        body.put("timestamp",      entry.timestamp().toString());
        body.put("payload",        java.util.Base64.getEncoder().encodeToString(toBytes(entry.payload())));
        body.put("contentType",    entry.contentType());
        body.put("headers",        entry.headers());
        entry.idempotencyKey().ifPresent(k -> body.put("idempotencyKey", k));
        return body;
    }

    @SuppressWarnings("unchecked")
    private List<EventEntry> parseEntries(String json) throws JsonProcessingException {
        Map<String, Object> body = mapper.readValue(json, new TypeReference<>() {});
        List<Map<String, Object>> rawEvents = (List<Map<String, Object>>) body.getOrDefault("events", List.of());
        List<EventEntry> entries = new ArrayList<>(rawEvents.size());
        for (Map<String, Object> raw : rawEvents) {
            entries.add(EventEntry.builder()
                .eventId(UUID.fromString((String) raw.get("eventId")))
                .eventType((String) raw.get("eventType"))
                .eventVersion((String) raw.getOrDefault("eventVersion", "1.0.0"))
                .timestamp(Instant.parse((String) raw.get("timestamp")))
                .payload(java.util.Base64.getDecoder().decode((String) raw.get("payload")))
                .contentType((String) raw.getOrDefault("contentType", "application/json"))
                .headers(raw.containsKey("headers") ? (Map<String, String>) raw.get("headers") : Map.of())
                .idempotencyKey((String) raw.get("idempotencyKey"))
                .build());
        }
        return entries;
    }

    private static long toLong(Object value) {
        if (value instanceof Number n) return n.longValue();
        if (value instanceof String s) return Long.parseLong(s);
        return 0L;
    }

    private static String requiredEnv(Map<String, String> env, String key) {
        String value = env.get(key);
        if (value == null || value.isBlank()) {
            throw new IllegalStateException(
                "Required environment variable '" + key + "' is not set. "
                + "Set it before starting the application.");
        }
        return value;
    }

    private static int intEnv(Map<String, String> env, String key, int defaultValue) {
        String value = env.get(key);
        if (value == null || value.isBlank()) return defaultValue;
        try {
            return Integer.parseInt(value.trim());
        } catch (NumberFormatException e) {
            throw new IllegalStateException(
                "Environment variable '" + key + "' must be an integer but was: " + value);
        }
    }

    /** Safely converts a {@link java.nio.ByteBuffer} to a byte array, handling read-only buffers. */
    private static byte[] toBytes(java.nio.ByteBuffer buf) {
        if (buf.hasArray() && buf.arrayOffset() == 0 && buf.limit() == buf.capacity()) {
            return buf.array();
        }
        java.nio.ByteBuffer copy = buf.duplicate();
        byte[] bytes = new byte[copy.remaining()];
        copy.get(bytes);
        return bytes;
    }

    private record InternalSubscription(AtomicBoolean cancelled) implements Subscription {
        @Override public void cancel() { cancelled.set(true); }
        @Override public boolean isCancelled() { return cancelled.get(); }
    }
}
