/*
 * Copyright (c) 2025 Ghatana.ai. All rights reserved.
 */
package com.ghatana.audit.persistent;

import com.ghatana.platform.audit.AuditEvent;
import com.ghatana.platform.audit.AuditQueryService;
import com.ghatana.platform.audit.AuditQueryService.AuditSearchCriteria;
import com.ghatana.platform.audit.AuditService;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.MethodOrderer.OrderAnnotation;

import javax.sql.DataSource;
import java.io.PrintWriter;
import java.sql.*;
import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.*;
import java.util.concurrent.*;
import java.util.logging.Logger;
import java.util.stream.IntStream;

import static org.assertj.core.api.Assertions.*;
import com.ghatana.platform.testing.activej.EventloopTestBase;

/**
 * Integration tests for {@link JdbcPersistentAuditService} — the persistent
 * replacement for ConcurrentHashMap-backed {@code InMemoryAuditQueryService}.
 *
 * <p>Uses an in-memory H2 database to validate JDBC operations without
 * requiring PostgreSQL. The H2 schema mirrors the V006 migration with
 * H2-compatible syntax.
 *
 * <p><b>Test Categories:</b>
 * <ul>
 *   <li>Write Operations — record(), append-only semantics</li>
 *   <li>Query by Tenant — findByTenantId (all + paginated)</li>
 *   <li>Query by Resource — findByResource</li>
 *   <li>Query by Principal — findByPrincipal</li>
 *   <li>Query by EventType — findByEventType</li>
 *   <li>Time Range Queries — findByTimeRange</li>
 *   <li>Find by ID — findById</li>
 *   <li>Count — countByTenantId</li>
 *   <li>Search — multi-criteria search with AuditSearchCriteria</li>
 *   <li>Tenant Isolation — cross-tenant data safety</li>
 *   <li>Concurrent Writes — thread safety</li>
 *   <li>Edge Cases — nulls, empty results, large payloads</li>
 * </ul>
 */
@TestMethodOrder(OrderAnnotation.class)
class JdbcPersistentAuditServiceTest extends EventloopTestBase {

    private static SimpleDataSource dataSource;
    private JdbcPersistentAuditService service;

    @BeforeAll
    static void initDatabase() throws SQLException {
        dataSource = new SimpleDataSource("jdbc:h2:mem:audit_test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL");

        try (Connection conn = dataSource.getConnection();
             Statement stmt = conn.createStatement()) {
            // H2-compatible schema mirroring V006__create_audit_trail.sql
            stmt.execute("""
                    CREATE TABLE IF NOT EXISTS audit_trail (
                        id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        tenant_id       VARCHAR(255) NOT NULL,
                        event_type      VARCHAR(255) NOT NULL,
                        entity_type     VARCHAR(100),
                        entity_id       VARCHAR(255),
                        action          VARCHAR(50) NOT NULL,
                        actor           VARCHAR(255),
                        actor_type      VARCHAR(50) DEFAULT 'USER',
                        "timestamp"     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        details         CLOB,
                        previous_state  CLOB,
                        new_state       CLOB,
                        correlation_id  VARCHAR(255),
                        source          VARCHAR(255),
                        ip_address      VARCHAR(45),
                        success         BOOLEAN NOT NULL DEFAULT TRUE,
                        error_message   CLOB
                    )
                    """);

            stmt.execute("CREATE INDEX IF NOT EXISTS idx_audit_tenant_time ON audit_trail (tenant_id, \"timestamp\")");
            stmt.execute("CREATE INDEX IF NOT EXISTS idx_audit_entity ON audit_trail (entity_type, entity_id)");
            stmt.execute("CREATE INDEX IF NOT EXISTS idx_audit_actor ON audit_trail (actor)");
        }
    }

    @BeforeEach
    void setUp() throws SQLException {
        service = new JdbcPersistentAuditService(dataSource);
        try (Connection conn = dataSource.getConnection();
             Statement stmt = conn.createStatement()) {
            stmt.execute("DELETE FROM audit_trail");
        }
    }

    @AfterAll
    static void tearDown() throws SQLException {
        try (Connection conn = dataSource.getConnection();
             Statement stmt = conn.createStatement()) {
            stmt.execute("DROP TABLE IF EXISTS audit_trail");
        }
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // 1. Write Operations
    // ═══════════════════════════════════════════════════════════════════════════

    @Nested
    @DisplayName("Write Operations")
    class WriteTests {

        @Test
        @DisplayName("record() persists audit event with all fields")
        void recordPersistsFullEvent() {
            AuditEvent event = auditEvent("t1", "AGENT_CREATED", "admin@co.com",
                    "AGENT", "agent-1", true,
                    Map.of("action", "CREATE", "source", "api", "ipAddress", "10.0.0.1"));

            runPromise(() -> service.record(event));

            List<AuditEvent> events = runPromise(() -> service.findByTenantId("t1"));
            assertThat(events).hasSize(1);
            AuditEvent stored = events.getFirst();
            assertThat(stored.getEventType()).isEqualTo("AGENT_CREATED");
            assertThat(stored.getPrincipal()).isEqualTo("admin@co.com");
            assertThat(stored.getResourceType()).isEqualTo("AGENT");
            assertThat(stored.getResourceId()).isEqualTo("agent-1");
            assertThat(stored.getSuccess()).isTrue();
            assertThat(stored.getId()).isNotNull();
        }

        @Test
        @DisplayName("record() auto-derives action from eventType")
        void recordDerivesAction() throws SQLException {
            runPromise(() -> service.record(auditEvent("t1", "PIPELINE_EXECUTED", "user@co", "PIPELINE", "p-1", true, Map.of())));

            try (Connection conn = dataSource.getConnection();
                 Statement stmt = conn.createStatement();
                 ResultSet rs = stmt.executeQuery("SELECT action FROM audit_trail WHERE tenant_id = 't1'")) {
                rs.next();
                assertThat(rs.getString("action")).isEqualTo("EXECUTE");
            }
        }

        @Test
        @DisplayName("record() handles null details gracefully")
        void recordNullDetails() {
            AuditEvent event = AuditEvent.builder()
                    .tenantId("t1").eventType("TEST_EVENT")
                    .timestamp(Instant.now()).success(true).build();

            assertThatCode(() -> runPromise(() -> service.record(event))).doesNotThrowAnyException();
            assertThat(runPromise(() -> service.countByTenantId("t1"))).isEqualTo(1L);
        }

        @Test
        @DisplayName("record() stores and retrieves JSONB details")
        void recordStoresJsonDetails() {
            Map<String, Object> details = Map.of(
                    "action", "CREATE", "reason", "auto-provisioned",
                    "count", 42, "tags", List.of("prod", "critical"));

            runPromise(() -> service.record(auditEvent("t1", "CONFIG_CHANGE", "sys", "CONFIG", "c-1", true, details)));

            AuditEvent stored = runPromise(() -> service.findByTenantId("t1")).getFirst();
            assertThat(stored.getDetails()).containsEntry("reason", "auto-provisioned");
        }

        @Test
        @DisplayName("multiple records are append-only")
        void multipleRecordsAppendOnly() {
            for (int i = 0; i < 5; i++) {
                final int idx = i;
                runPromise(() -> service.record(auditEvent("t1", "EVENT_" + idx, "user", "RES", "r-" + idx, true, Map.of("action", "CREATE"))));
            }
            assertThat(runPromise(() -> service.countByTenantId("t1"))).isEqualTo(5L);
        }
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // 2. Query by Tenant
    // ═══════════════════════════════════════════════════════════════════════════

    @Nested
    @DisplayName("Query by Tenant")
    class TenantQueryTests {

        @Test
        @DisplayName("findByTenantId returns all events for tenant")
        void findAllForTenant() {
            seedEvents("t1", 10);
            seedEvents("t2", 5);

            assertThat(runPromise(() -> service.findByTenantId("t1"))).hasSize(10);
            assertThat(runPromise(() -> service.findByTenantId("t2"))).hasSize(5);
        }

        @Test
        @DisplayName("findByTenantId returns empty for unknown tenant")
        void findEmptyForUnknownTenant() {
            assertThat(runPromise(() -> service.findByTenantId("nonexistent"))).isEmpty();
        }

        @Test
        @DisplayName("findByTenantId with pagination")
        void findPaginated() {
            seedEvents("t1", 20);

            List<AuditEvent> page1 = runPromise(() -> service.findByTenantId("t1", 0, 5));
            List<AuditEvent> page2 = runPromise(() -> service.findByTenantId("t1", 5, 5));
            List<AuditEvent> page5 = runPromise(() -> service.findByTenantId("t1", 20, 5));

            assertThat(page1).hasSize(5);
            assertThat(page2).hasSize(5);
            assertThat(page5).isEmpty();
        }
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // 3. Query by Resource
    // ═══════════════════════════════════════════════════════════════════════════

    @Nested
    @DisplayName("Query by Resource")
    class ResourceQueryTests {

        @Test
        @DisplayName("findByResource returns matching events")
        void findByResource() {
            runPromise(() -> service.record(auditEvent("t1", "CREATED", "u", "AGENT", "a-1", true, Map.of("action", "CREATE"))));
            runPromise(() -> service.record(auditEvent("t1", "UPDATED", "u", "AGENT", "a-1", true, Map.of("action", "UPDATE"))));
            runPromise(() -> service.record(auditEvent("t1", "CREATED", "u", "PIPELINE", "p-1", true, Map.of("action", "CREATE"))));

            List<AuditEvent> agentEvents = runPromise(() -> service.findByResource("t1", "AGENT", "a-1"));
            assertThat(agentEvents).hasSize(2);
            assertThat(agentEvents).allMatch(e -> "AGENT".equals(e.getResourceType()));
        }

        @Test
        @DisplayName("findByResource returns empty for no match")
        void findByResourceEmpty() {
            assertThat(runPromise(() -> service.findByResource("t1", "AGENT", "nonexistent"))).isEmpty();
        }
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // 4. Query by Principal
    // ═══════════════════════════════════════════════════════════════════════════

    @Nested
    @DisplayName("Query by Principal")
    class PrincipalQueryTests {

        @Test
        @DisplayName("findByPrincipal returns events for specific actor")
        void findByPrincipal() {
            runPromise(() -> service.record(auditEvent("t1", "LOGIN", "alice@co", null, null, true, Map.of("action", "LOGIN"))));
            runPromise(() -> service.record(auditEvent("t1", "LOGIN", "bob@co", null, null, true, Map.of("action", "LOGIN"))));
            runPromise(() -> service.record(auditEvent("t1", "LOGOUT", "alice@co", null, null, true, Map.of("action", "LOGOUT"))));

            List<AuditEvent> aliceEvents = runPromise(() -> service.findByPrincipal("t1", "alice@co"));
            assertThat(aliceEvents).hasSize(2);
            assertThat(aliceEvents).allMatch(e -> "alice@co".equals(e.getPrincipal()));
        }
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // 5. Query by Event Type
    // ═══════════════════════════════════════════════════════════════════════════

    @Nested
    @DisplayName("Query by Event Type")
    class EventTypeQueryTests {

        @Test
        @DisplayName("findByEventType filters correctly")
        void findByEventType() {
            runPromise(() -> service.record(auditEvent("t1", "USER_LOGIN", "u", null, null, true, Map.of("action", "LOGIN"))));
            runPromise(() -> service.record(auditEvent("t1", "DATA_ACCESS", "u", "TABLE", "t-1", true, Map.of("action", "READ"))));
            runPromise(() -> service.record(auditEvent("t1", "USER_LOGIN", "u2", null, null, true, Map.of("action", "LOGIN"))));

            assertThat(runPromise(() -> service.findByEventType("t1", "USER_LOGIN"))).hasSize(2);
            assertThat(runPromise(() -> service.findByEventType("t1", "DATA_ACCESS"))).hasSize(1);
        }
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // 6. Time Range Queries
    // ═══════════════════════════════════════════════════════════════════════════

    @Nested
    @DisplayName("Time Range Queries")
    class TimeRangeTests {

        @Test
        @DisplayName("findByTimeRange returns events within window")
        void findByTimeRange() {
            Instant now = Instant.now();
            Instant yesterday = now.minus(1, ChronoUnit.DAYS);
            Instant twoDaysAgo = now.minus(2, ChronoUnit.DAYS);
            Instant threeDaysAgo = now.minus(3, ChronoUnit.DAYS);

            runPromise(() -> service.record(auditEventAt("t1", "OLD", threeDaysAgo, Map.of("action", "CREATE"))));
            runPromise(() -> service.record(auditEventAt("t1", "RECENT", yesterday, Map.of("action", "CREATE"))));
            runPromise(() -> service.record(auditEventAt("t1", "NOW", now, Map.of("action", "CREATE"))));

            List<AuditEvent> recent = runPromise(() -> service.findByTimeRange("t1", twoDaysAgo, now));
            assertThat(recent).hasSize(2);
            assertThat(recent).extracting(AuditEvent::getEventType).containsExactlyInAnyOrder("RECENT", "NOW");
        }
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // 7. Find by ID
    // ═══════════════════════════════════════════════════════════════════════════

    @Nested
    @DisplayName("Find by ID")
    class FindByIdTests {

        @Test
        @DisplayName("findById returns matching event")
        void findById() {
            runPromise(() -> service.record(auditEvent("t1", "TEST", "u", "X", "x-1", true, Map.of("action", "CREATE"))));

            List<AuditEvent> all = runPromise(() -> service.findByTenantId("t1"));
            String id = all.getFirst().getId();

            Optional<AuditEvent> found = runPromise(() -> service.findById("t1", id));
            assertThat(found).isPresent();
            assertThat(found.get().getEventType()).isEqualTo("TEST");
        }

        @Test
        @DisplayName("findById returns empty for wrong tenant")
        void findByIdWrongTenant() {
            runPromise(() -> service.record(auditEvent("t1", "TEST", "u", "X", "x-1", true, Map.of("action", "CREATE"))));
            String id = runPromise(() -> service.findByTenantId("t1")).getFirst().getId();

            // Query with different tenant
            Optional<AuditEvent> found = runPromise(() -> service.findById("t2", id));
            assertThat(found).isEmpty();
        }
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // 8. Count
    // ═══════════════════════════════════════════════════════════════════════════

    @Nested
    @DisplayName("Count")
    class CountTests {

        @Test
        @DisplayName("countByTenantId returns correct count")
        void countByTenantId() {
            seedEvents("t1", 15);
            seedEvents("t2", 3);

            assertThat(runPromise(() -> service.countByTenantId("t1"))).isEqualTo(15L);
            assertThat(runPromise(() -> service.countByTenantId("t2"))).isEqualTo(3L);
            assertThat(runPromise(() -> service.countByTenantId("empty"))).isEqualTo(0L);
        }
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // 9. Multi-Criteria Search
    // ═══════════════════════════════════════════════════════════════════════════

    @Nested
    @DisplayName("Multi-Criteria Search")
    class SearchTests {

        @Test
        @DisplayName("search with all criteria")
        void searchAllCriteria() {
            Instant now = Instant.now();
            runPromise(() -> service.record(auditEvent("t1", "AGENT_CREATED", "alice@co", "AGENT", "a-1", true, Map.of("action", "CREATE"))));
            runPromise(() -> service.record(auditEvent("t1", "AGENT_UPDATED", "bob@co", "AGENT", "a-1", true, Map.of("action", "UPDATE"))));
            runPromise(() -> service.record(auditEvent("t1", "PIPELINE_CREATED", "alice@co", "PIPELINE", "p-1", true, Map.of("action", "CREATE"))));
            runPromise(() -> service.record(auditEvent("t1", "AGENT_DELETED", "alice@co", "AGENT", "a-2", false, Map.of("action", "DELETE", "errorMessage", "forbidden"))));

            // Search for alice's successful AGENT events
            AuditSearchCriteria criteria = AuditSearchCriteria.builder()
                    .resourceType("AGENT")
                    .principal("alice@co")
                    .success(true)
                    .build();

            List<AuditEvent> results = runPromise(() -> service.search("t1", criteria));
            assertThat(results).hasSize(1);
            assertThat(results.getFirst().getEventType()).isEqualTo("AGENT_CREATED");
        }

        @Test
        @DisplayName("search with eventType filter")
        void searchByEventType() {
            seedEvents("t1", 10); // All have "TEST_EVENT" type

            AuditSearchCriteria criteria = AuditSearchCriteria.builder()
                    .eventType("TEST_EVENT")
                    .limit(5)
                    .build();

            assertThat(runPromise(() -> service.search("t1", criteria))).hasSize(5);
        }

        @Test
        @DisplayName("search with time range")
        void searchByTimeRange() {
            Instant now = Instant.now();
            Instant hourAgo = now.minus(1, ChronoUnit.HOURS);

            runPromise(() -> service.record(auditEventAt("t1", "OLD", now.minus(2, ChronoUnit.HOURS), Map.of("action", "CREATE"))));
            runPromise(() -> service.record(auditEventAt("t1", "RECENT", now.minus(30, ChronoUnit.MINUTES), Map.of("action", "CREATE"))));

            AuditSearchCriteria criteria = AuditSearchCriteria.builder()
                    .fromDate(hourAgo)
                    .toDate(now)
                    .build();

            List<AuditEvent> results = runPromise(() -> service.search("t1", criteria));
            assertThat(results).hasSize(1);
            assertThat(results.getFirst().getEventType()).isEqualTo("RECENT");
        }

        @Test
        @DisplayName("search with pagination")
        void searchWithPagination() {
            seedEvents("t1", 20);

            AuditSearchCriteria page1 = AuditSearchCriteria.builder().offset(0).limit(7).build();
            AuditSearchCriteria page2 = AuditSearchCriteria.builder().offset(7).limit(7).build();
            AuditSearchCriteria page3 = AuditSearchCriteria.builder().offset(14).limit(7).build();

            assertThat(runPromise(() -> service.search("t1", page1))).hasSize(7);
            assertThat(runPromise(() -> service.search("t1", page2))).hasSize(7);
            assertThat(runPromise(() -> service.search("t1", page3))).hasSize(6);
        }

        @Test
        @DisplayName("search failures only")
        void searchFailuresOnly() {
            runPromise(() -> service.record(auditEvent("t1", "OK", "u", "X", "1", true, Map.of("action", "CREATE"))));
            runPromise(() -> service.record(auditEvent("t1", "FAIL", "u", "X", "2", false, Map.of("action", "CREATE", "errorMessage", "boom"))));

            AuditSearchCriteria criteria = AuditSearchCriteria.builder().success(false).build();
            List<AuditEvent> failures = runPromise(() -> service.search("t1", criteria));
            assertThat(failures).hasSize(1);
            assertThat(failures.getFirst().getSuccess()).isFalse();
        }
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // 10. Tenant Isolation
    // ═══════════════════════════════════════════════════════════════════════════

    @Nested
    @DisplayName("Tenant Isolation")
    class TenantIsolationTests {

        @Test
        @DisplayName("events are completely isolated between tenants")
        void tenantIsolation() {
            runPromise(() -> service.record(auditEvent("t1", "SECRET", "admin", "CONFIG", "c-1", true, Map.of("action", "CREATE"))));
            runPromise(() -> service.record(auditEvent("t2", "PUBLIC", "user", "DOC", "d-1", true, Map.of("action", "CREATE"))));

            List<AuditEvent> t1Events = runPromise(() -> service.findByTenantId("t1"));
            List<AuditEvent> t2Events = runPromise(() -> service.findByTenantId("t2"));

            assertThat(t1Events).hasSize(1).allMatch(e -> "SECRET".equals(e.getEventType()));
            assertThat(t2Events).hasSize(1).allMatch(e -> "PUBLIC".equals(e.getEventType()));
        }

        @Test
        @DisplayName("findByResource is tenant-scoped")
        void resourceQueryTenantScoped() {
            runPromise(() -> service.record(auditEvent("t1", "A", "u", "AGENT", "shared-id", true, Map.of("action", "CREATE"))));
            runPromise(() -> service.record(auditEvent("t2", "B", "u", "AGENT", "shared-id", true, Map.of("action", "CREATE"))));

            assertThat(runPromise(() -> service.findByResource("t1", "AGENT", "shared-id"))).hasSize(1);
            assertThat(runPromise(() -> service.findByResource("t2", "AGENT", "shared-id"))).hasSize(1);
        }

        @Test
        @DisplayName("count is tenant-scoped")
        void countTenantScoped() {
            seedEvents("t1", 10);
            seedEvents("t2", 3);

            assertThat(runPromise(() -> service.countByTenantId("t1"))).isEqualTo(10L);
            assertThat(runPromise(() -> service.countByTenantId("t2"))).isEqualTo(3L);
        }
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // 11. Concurrent Writes
    // ═══════════════════════════════════════════════════════════════════════════

    @Nested
    @DisplayName("Concurrent Writes")
    class ConcurrencyTests {

        @Test
        @DisplayName("50 concurrent writes all succeed")
        void concurrentWrites() throws Exception {
            int threadCount = 50;
            ExecutorService executor = Executors.newFixedThreadPool(8);
            CountDownLatch latch = new CountDownLatch(threadCount);

            List<Future<?>> futures = new ArrayList<>();
            for (int i = 0; i < threadCount; i++) {
                final int idx = i;
                futures.add(executor.submit(() -> {
                    try {
                        service.record(auditEvent("t1", "CONCURRENT_" + idx, "thread-" + idx,
                                "RES", "r-" + idx, true, Map.of("action", "CREATE")));
                    } finally {
                        latch.countDown();
                    }
                }));
            }

            latch.await(10, TimeUnit.SECONDS);
            executor.shutdown();

            // Verify all 50 written
            assertThat(runPromise(() -> service.countByTenantId("t1"))).isEqualTo(50L);

            // Verify no exceptions
            for (Future<?> f : futures) {
                assertThatCode(f::get).doesNotThrowAnyException();
            }
        }
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // 12. Edge Cases
    // ═══════════════════════════════════════════════════════════════════════════

    @Nested
    @DisplayName("Edge Cases")
    class EdgeCaseTests {

        @Test
        @DisplayName("record with minimal fields")
        void minimalEvent() {
            AuditEvent event = AuditEvent.builder()
                    .tenantId("t1").eventType("MINIMAL")
                    .timestamp(Instant.now()).success(true).build();

            assertThatCode(() -> runPromise(() -> service.record(event))).doesNotThrowAnyException();
            assertThat(runPromise(() -> service.findByTenantId("t1"))).hasSize(1);
        }

        @Test
        @DisplayName("record with large details payload")
        void largeDetailsPayload() {
            Map<String, Object> largeDetails = new HashMap<>();
            largeDetails.put("action", "CREATE");
            for (int i = 0; i < 100; i++) {
                largeDetails.put("field_" + i, "value_" + "x".repeat(100));
            }

            runPromise(() -> service.record(auditEvent("t1", "LARGE", "u", "X", "x-1", true, largeDetails)));
            AuditEvent stored = runPromise(() -> service.findByTenantId("t1")).getFirst();
            assertThat(stored.getDetails()).containsKey("field_99");
        }

        @Test
        @DisplayName("record preserves state change information")
        void stateChangeDetails() {
            Map<String, Object> details = new HashMap<>();
            details.put("action", "UPDATE");
            details.put("previousState", Map.of("status", "DRAFT"));
            details.put("newState", Map.of("status", "ACTIVE"));

            runPromise(() -> service.record(auditEvent("t1", "STATUS_CHANGE", "admin", "PIPELINE", "p-1", true, details)));

            AuditEvent stored = runPromise(() -> service.findByTenantId("t1")).getFirst();
            assertThat(stored.getDetails()).containsKey("previousState");
            assertThat(stored.getDetails()).containsKey("newState");
        }

        @Test
        @DisplayName("service implements both interfaces")
        void implementsBothInterfaces() {
            assertThat(service).isInstanceOf(AuditService.class);
            assertThat(service).isInstanceOf(AuditQueryService.class);
        }

        @Test
        @DisplayName("findById with non-numeric ID returns empty")
        void findByIdNonNumeric() {
            // Non-numeric IDs can never match a BIGINT primary key — service returns empty.
            Optional<AuditEvent> result = runPromise(() -> service.findById("t1", "not-a-number"));
            assertThat(result).isEmpty();
        }
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // Helpers
    // ═══════════════════════════════════════════════════════════════════════════

    private AuditEvent auditEvent(String tenantId, String eventType, String principal,
                                   String resourceType, String resourceId, boolean success,
                                   Map<String, Object> details) {
        return AuditEvent.builder()
                .tenantId(tenantId)
                .eventType(eventType)
                .timestamp(Instant.now())
                .principal(principal)
                .resourceType(resourceType)
                .resourceId(resourceId)
                .success(success)
                .details(details)
                .build();
    }

    private AuditEvent auditEventAt(String tenantId, String eventType, Instant timestamp,
                                     Map<String, Object> details) {
        return AuditEvent.builder()
                .tenantId(tenantId)
                .eventType(eventType)
                .timestamp(timestamp)
                .principal("system")
                .success(true)
                .details(details)
                .build();
    }

    private void seedEvents(String tenantId, int count) {
        for (int i = 0; i < count; i++) {
            service.record(auditEvent(tenantId, "TEST_EVENT", "user-" + i,
                    "RESOURCE", "r-" + i, true, Map.of("action", "CREATE", "index", i)));
        }
    }

    // ═══════════════════════════════════════════════════════════════════════════
    // Minimal DataSource for H2 in-memory testing (no HikariCP dependency needed)
    // ═══════════════════════════════════════════════════════════════════════════

    static class SimpleDataSource implements DataSource {
        private final String url;

        SimpleDataSource(String url) {
            this.url = url;
        }

        @Override
        public Connection getConnection() throws SQLException {
            return DriverManager.getConnection(url, "sa", "");
        }

        @Override
        public Connection getConnection(String username, String password) throws SQLException {
            return DriverManager.getConnection(url, username, password);
        }

        @Override public PrintWriter getLogWriter() { return null; }
        @Override public void setLogWriter(PrintWriter out) {}
        @Override public int getLoginTimeout() { return 0; }
        @Override public void setLoginTimeout(int seconds) {}
        @Override public Logger getParentLogger() { return Logger.getLogger("SimpleDataSource"); }
        @Override public <T> T unwrap(Class<T> iface) { throw new UnsupportedOperationException(); }
        @Override public boolean isWrapperFor(Class<?> iface) { return false; }
    }
}
