package com.ghatana.platform.domain.domain.event;

import com.ghatana.platform.types.time.GTimeInterval;
import com.ghatana.platform.types.time.GTimeUnit;
import com.ghatana.platform.types.time.GTimeValue;
import com.ghatana.platform.types.time.GTimestamp;
import lombok.Builder;
import lombok.Value;

/**
 * Immutable temporal information for events with multiple time dimensions.
 * 
 * <p>
 * Encapsulates comprehensive temporal metadata for events. Events have multiple
 * time dimensions: when they occurred (occurrence time), when they were detected
 * (detection time), how long they're valid (valid duration), and time bounds.
 * This multi-dimensional temporal model enables precise event correlation and
 * gap detection in time-series analysis.
 * </p>
 *
 * <h2>Time Dimensions</h2>
 * <dl>
 *   <dt><b>occurrenceTime</b>: GTimeInterval</dt>
 *   <dd>When the event actually occurred (may be a time interval for interval-based events)</dd>
 *
 *   <dt><b>detectionTimePoint</b>: GTimestamp</dt>
 *   <dd>When the event was detected/ingested into the system (point in time)</dd>
 *
 *   <dt><b>validDuration</b>: GTimeValue</dt>
 *   <dd>How long the event data is considered valid (staleness window)</dd>
 *
 *   <dt><b>boundingInterval</b>: GTimeInterval</dt>
 *   <dd>Time bounds for event analysis windows (upper/lower bounds)</dd>
 *
 *   <dt><b>granularity</b>: long</dt>
 *   <dd>Time granularity unit (milliseconds, seconds, etc.) for calculations</dd>
 * </dl>
 *
 * <h2>Architecture Role</h2>
 * <p>
 * Temporal data is critical for event processing:
 * <ul>
 *   <li><b>Temporal Ordering</b>: Maintains event order in time-series processing</li>
 *   <li><b>Gap Detection</b>: Identifies missing events or time gaps in streams</li>
 *   <li><b>Window Functions</b>: Enables time-windowed aggregation (tumbling, sliding)</li>
 *   <li><b>Pattern Timing</b>: Constraints pattern detection to time windows</li>
 *   <li><b>Clock Skew Handling</b>: Manages difference between occurrence and detection time</li>
 *   <li><b>Interval Events</b>: Supports interval-based events (duration rather than point)</li>
 * </ul>
 * </p>
 *
 * <h2>Creation & Usage</h2>
 * <pre>{@code
 * // Using factory method for current time
 * EventTime now = EventTime.now();
 *
 * // Using builder for custom temporal properties
 * EventTime eventTime = EventTime.builder()
 *     .occurrenceTime(GTimeInterval.between(start, end))
 *     .detectionTimePoint(GTimestamp.now())
 *     .validDuration(new GTimeValue(60, GTimeUnit.SECONDS))
 *     .boundingInterval(GTimeInterval.between(windowStart, windowEnd))
 *     .granularity(1)
 *     .build();
 *
 * // Access temporal properties
 * GTimeInterval occurrence = eventTime.getOccurrenceTime();
 * GTimestamp detected = eventTime.getDetectionTimePoint();
 * long staleness = eventTime.getValidDuration().getAmount();
 * }</pre>
 *
 * <h2>Immutability & Thread Safety</h2>
 * <p>
 * Generated by Lombok @Value annotation. All fields are private final.
 * Instances are immutable and safe to share across threads without synchronization.
 * The builder pattern enables fluent construction of complex temporal specifications.
 * </p>
 *
 * @doc.type value-object
 * @doc.layer domain
 * @doc.purpose multi-dimensional temporal metadata for events
 * @doc.pattern immutable value object (Lombok @Value - final class, private final fields)
 * @doc.test-hints verify time ordering, test gap detection, validate window calculations, test temporal constraints
 *
 * @see com.ghatana.platform.types.time.GTimestamp (point-in-time representation)
 * @see com.ghatana.platform.types.time.GTimeInterval (interval representation)
 * @see com.ghatana.platform.types.time.GTimeValue (duration representation)
 * @see Event (events contain EventTime metadata)
 */
@Builder
@Value
public class EventTime {
    
    private GTimeInterval occurrenceTime;
    private GTimestamp detectionTimePoint;
    private GTimeValue validDuration;
    private GTimeInterval boundingInterval;
    @Builder.Default private long granularity = 1;

    /**
     * Creates an EventTime representing the current moment.
     *
     * @return An EventTime instance representing now
     */
    public static EventTime now() {
        GTimestamp now = GTimestamp.now();
        return EventTime.builder()
                .detectionTimePoint(now)
                .occurrenceTime(GTimeInterval.between(now, now))
                .validDuration(new GTimeValue(Long.MAX_VALUE, GTimeUnit.MILLISECONDS))
                .boundingInterval(GTimeInterval.between(now, now))
                .granularity(1)
                .build();
    }
}
