package com.ghatana.platform.domain.domain.event;

import java.util.Objects;

/**
 * Immutable statistics and metrics for event processing and monitoring.
 * 
 * <p>
 * Encapsulates operational metrics collected during event processing. These statistics
 * enable monitoring, optimization, and debugging of the event pipeline. EventStats are
 * immutable, thread-safe, and generated by instrumentation points throughout the pipeline.
 * </p>
 *
 * <h2>Metrics Tracked</h2>
 * <dl>
 *   <dt><b>sizeInBytes</b></dt>
 *   <dd>Serialized event size - used for storage optimization and bandwidth tracking</dd>
 *
 *   <dt><b>processingTimeNanos</b></dt>
 *   <dd>Time spent processing this event (nanosecond precision for accurate metrics)</dd>
 *
 *   <dt><b>fieldCount</b></dt>
 *   <dd>Number of fields in event payload - indicates event complexity</dd>
 *
 *   <dt><b>tagCount</b></dt>
 *   <dd>Number of tags associated with event - indicates metadata richness</dd>
 * </dl>
 *
 * <h2>Architecture Role</h2>
 * <p>
 * Event statistics support multiple platform concerns:
 * <ul>
 *   <li><b>Performance Monitoring</b>: Track processing latency and throughput</li>
 *   <li><b>Storage Optimization</b>: Monitor event sizes for compression/optimization</li>
 *   <li><b>Debugging</b>: Identify performance bottlenecks by event type</li>
 *   <li><b>Capacity Planning</b>: Track event volume and complexity trends</li>
 *   <li><b>SLA Tracking</b>: Verify processing times meet SLA targets</li>
 *   <li><b>Anomaly Detection</b>: Identify unusual event sizes or processing times</li>
 * </ul>
 * </p>
 *
 * <h2>Creation & Usage</h2>
 * <pre>{@code
 * // Using builder pattern
 * EventStats stats = EventStats.builder()
 *     .withSizeInBytes(1024)
 *     .withProcessingTimeNanos(50_000_000)  // 50 ms
 *     .withFieldCount(12)
 *     .withTagCount(3)
 *     .build();
 *
 * // Access metrics
 * long sizeKb = stats.getSizeInBytes() / 1024;
 * long processingTimeMs = stats.getProcessingTimeNanos() / 1_000_000;
 * int fields = stats.getFieldCount();
 * int tags = stats.getTagCount();
 *
 * // Monitoring
 * if (stats.getProcessingTimeNanos() > slowThresholdNanos) {
 *   logger.warn("Slow event processing: {} ms", processingTimeMs);
 * }
 * }</pre>
 *
 * <h2>Immutability & Thread Safety</h2>
 * <p>
 * All fields are private final. No setters. Instances are immutable and thread-safe.
 * The builder pattern enables fluent construction of metrics. Equality and hashCode
 * semantics include all fields for precise metric comparison.
 * </p>
 *
 * @doc.type value-object
 * @doc.layer domain
 * @doc.purpose event processing metrics and statistics collection
 * @doc.pattern immutable value object (final class, private final fields, builder pattern)
 * @doc.test-hints verify metric accuracy, test builder pattern, validate immutability, test equality semantics
 *
 * @see Event (events contain EventStats)
 * @see com.ghatana.core.observability.EventMetricsCollector (aggregates EventStats for monitoring)
 */
public final class EventStats {
    private final long sizeInBytes;
    private final long processingTimeNanos;
    private final int fieldCount;
    private final int tagCount;

    private EventStats(Builder builder) {
        this.sizeInBytes = builder.sizeInBytes;
        this.processingTimeNanos = builder.processingTimeNanos;
        this.fieldCount = builder.fieldCount;
        this.tagCount = builder.tagCount;
    }

    /**
     * Gets the size of the event in bytes.
     *
     * @return The size in bytes
     */
    public long getSizeInBytes() {
        return sizeInBytes;
    }

    /**
     * Gets the processing time of the event in nanoseconds.
     *
     * @return The processing time in nanoseconds
     */
    public long getProcessingTimeNanos() {
        return processingTimeNanos;
    }

    /**
     * Gets the number of fields in the event.
     *
     * @return The field count
     */
    public int getFieldCount() {
        return fieldCount;
    }

    /**
     * Gets the number of tags associated with the event.
     *
     * @return The tag count
     */
    public int getTagCount() {
        return tagCount;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        EventStats that = (EventStats) o;
        return sizeInBytes == that.sizeInBytes &&
               processingTimeNanos == that.processingTimeNanos &&
               fieldCount == that.fieldCount &&
               tagCount == that.tagCount;
    }

    @Override
    public int hashCode() {
        return Objects.hash(sizeInBytes, processingTimeNanos, fieldCount, tagCount);
    }

    @Override
    public String toString() {
        return "EventStats{" 
               + "sizeInBytes=" + sizeInBytes 
               + ", processingTimeNanos=" + processingTimeNanos 
               + ", fieldCount=" + fieldCount 
               + ", tagCount=" + tagCount 
               + '}';
    }

    /**
     * Creates a new builder for constructing EventStats objects.
     *
     * @return A new builder instance
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Builder for creating EventStats instances.
     */
    public static final class Builder {
        private long sizeInBytes;
        private long processingTimeNanos;
        private int fieldCount;
        private int tagCount;

        private Builder() {
        }

        /**
         * Sets the size of the event in bytes.
         *
         * @param sizeInBytes The size in bytes
         * @return This builder
         */
        public Builder withSizeInBytes(long sizeInBytes) {
            this.sizeInBytes = sizeInBytes;
            return this;
        }

        /**
         * Sets the processing time of the event in nanoseconds.
         *
         * @param processingTimeNanos The processing time in nanoseconds
         * @return This builder
         */
        public Builder withProcessingTimeNanos(long processingTimeNanos) {
            this.processingTimeNanos = processingTimeNanos;
            return this;
        }

        /**
         * Sets the number of fields in the event.
         *
         * @param fieldCount The field count
         * @return This builder
         */
        public Builder withFieldCount(int fieldCount) {
            this.fieldCount = fieldCount;
            return this;
        }

        /**
         * Sets the number of tags associated with the event.
         *
         * @param tagCount The tag count
         * @return This builder
         */
        public Builder withTagCount(int tagCount) {
            this.tagCount = tagCount;
            return this;
        }

        /**
         * Builds a new EventStats instance with the current configuration.
         *
         * @return A new EventStats instance
         */
        public EventStats build() {
            return new EventStats(this);
        }
    }
}
