/**
 * @fileoverview CSS Variables Target Adapter
 *
 * Generates CSS custom properties (CSS variables) from design system tokens.
 * Provides a production-grade adapter with proper formatting and validation.
 *
 * @doc.type module
 * @doc.purpose CSS variables generation from design tokens
 * @doc.layer ds-generator
 */

import type { MaterializedTokens } from '../presets/index.js';

export interface CSSVariablesAdapterOptions {
  /** Prefix for CSS custom properties (default: '') */
  prefix?: string;
  /** Whether to include comments (default: true) */
  includeComments?: boolean;
  /** Indentation for formatting (default: 2 spaces) */
  indent?: string;
}

export function generateCSSVariables(
  tokens: MaterializedTokens,
  options: CSSVariablesAdapterOptions = {},
): string {
  const { prefix = '', includeComments = true, indent = '  ' } = options;

  // Ensure every emitted name is a valid CSS custom property starting with --
  const varPrefix = `--${prefix}`;

  const lines: string[] = [];

  if (includeComments) {
    lines.push('/* Design System CSS Variables */');
    lines.push('/* Generated by Ghatana DS Generator */');
    lines.push('');
  }

  lines.push(':root {');

  // Colors
  lines.push(`${indent}/* Colors */`);
  for (const [key, value] of Object.entries(tokens.colors)) {
    lines.push(`${indent}${varPrefix}color-${key}: ${value};`);
  }
  lines.push('');

  // Typography
  lines.push(`${indent}/* Typography */`);
  lines.push(`${indent}${varPrefix}font-family-base: ${tokens.fontFamily};`);
  for (const [key, value] of Object.entries(tokens.fontSizes)) {
    lines.push(`${indent}${varPrefix}font-size-${key}: ${value}px;`);
  }
  lines.push('');

  // Border Radius
  lines.push(`${indent}/* Border Radius */`);
  for (const [key, value] of Object.entries(tokens.borderRadius)) {
    lines.push(`${indent}${varPrefix}radius-${key}: ${value};`);
  }
  lines.push('');

  // Spacing
  lines.push(`${indent}/* Spacing */`);
  for (const [key, value] of Object.entries(tokens.spacing)) {
    lines.push(`${indent}${varPrefix}spacing-${key}: ${value}px;`);
  }
  lines.push('');

  // Elevation/Shadow
  lines.push(`${indent}/* Elevation */`);
  for (const [key, value] of Object.entries(tokens.elevation)) {
    lines.push(`${indent}${varPrefix}elevation-${key}: ${value};`);
  }

  lines.push('}');

  return lines.join('\n');
}
