package com.ghatana.flashit.agent.dto;

import com.fasterxml.jackson.annotation.JsonProperty;

import java.util.List;

/**
 * A single recommendation generated by the intelligence engine.
 *
 * @doc.type record
 * @doc.purpose Represents one personalized recommendation with reasoning
 * @doc.layer product
 * @doc.pattern ValueObject
 */
public record RecommendationItem(
        @JsonProperty("type") String type,
        @JsonProperty("strategy") String strategy,
        @JsonProperty("title") String title,
        @JsonProperty("content") String content,
        @JsonProperty("score") double score,
        @JsonProperty("reasoning") String reasoning,
        @JsonProperty("relatedMomentIds") List<String> relatedMomentIds,
        @JsonProperty("actionUrl") String actionUrl
) {
}
