#!/bin/bash
#
# dcmaar Agent Linux Installer
# Production-grade installation script with full system integration

set -euo pipefail

# Configuration
readonly SCRIPT_NAME="$(basename "$0")"
readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly DCMAAR_VERSION="${DCMAAR_VERSION:-1.0.0}"
readonly INSTALL_DIR="/opt/dcmaar"
readonly CONFIG_DIR="/etc/dcmaar"
readonly DATA_DIR="/var/lib/dcmaar"
readonly LOG_DIR="/var/log/dcmaar"
readonly SERVICE_NAME="dcmaar-agent"
readonly SERVICE_USER="dcmaar"
readonly SERVICE_GROUP="dcmaar"

# Colors for output
readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly BLUE='\033[0;34m'
readonly NC='\033[0m' # No Color

# Logging functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $*"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $*"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $*"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $*" >&2
}

# Check if running as root
check_root() {
    if [[ $EUID -ne 0 ]]; then
        log_error "This script must be run as root (use sudo)"
        exit 1
    fi
}

# Detect distribution
detect_distro() {
    if command -v lsb_release &> /dev/null; then
        echo "$(lsb_release -si | tr '[:upper:]' '[:lower:]')"
    elif [[ -f /etc/os-release ]]; then
        # shellcheck source=/dev/null
        source /etc/os-release
        echo "${ID}"
    else
        echo "unknown"
    fi
}

# Check system requirements
check_requirements() {
    log_info "Checking system requirements..."
    
    # Check systemd
    if ! command -v systemctl &> /dev/null; then
        log_error "systemd is required but not found"
        exit 1
    fi
    
    # Check available space (minimum 100MB)
    local available_space
    available_space=$(df /opt 2>/dev/null | awk 'NR==2 {print $4}' || echo 0)
    if [[ $available_space -lt 102400 ]]; then
        log_warning "Low disk space available. At least 100MB recommended."
    fi
    
    log_success "System requirements check passed"
}

# Create system user and group
create_user() {
    log_info "Creating system user: ${SERVICE_USER}"
    
    if ! getent group "${SERVICE_GROUP}" &> /dev/null; then
        groupadd --system "${SERVICE_GROUP}"
        log_info "Created group: ${SERVICE_GROUP}"
    fi
    
    if ! getent passwd "${SERVICE_USER}" &> /dev/null; then
        useradd --system --gid "${SERVICE_GROUP}" \
                --home-dir "${DATA_DIR}" \
                --no-create-home \
                --shell /bin/false \
                --comment "dcmaar Agent Service User" \
                "${SERVICE_USER}"
        log_info "Created user: ${SERVICE_USER}"
    fi
    
    log_success "User and group setup complete"
}

# Create directory structure
create_directories() {
    log_info "Creating directory structure..."
    
    local dirs=("${INSTALL_DIR}" "${CONFIG_DIR}" "${DATA_DIR}" "${LOG_DIR}")
    
    for dir in "${dirs[@]}"; do
        mkdir -p "${dir}"
        log_info "Created directory: ${dir}"
    done
    
    # Set permissions
    chown -R "${SERVICE_USER}:${SERVICE_GROUP}" "${DATA_DIR}" "${LOG_DIR}"
    chown -R root:root "${INSTALL_DIR}" "${CONFIG_DIR}"
    chmod 755 "${INSTALL_DIR}" "${CONFIG_DIR}"
    chmod 750 "${DATA_DIR}" "${LOG_DIR}"
    
    log_success "Directory structure created"
}

# Install binaries
install_binaries() {
    log_info "Installing dcmaar agent binary..."
    
    # Create bin directory
    mkdir -p "${INSTALL_DIR}/bin"
    
    # Copy agent binary (assuming it's in the same directory as this script)
    if [[ -f "${SCRIPT_DIR}/dcmaar-agent" ]]; then
        cp "${SCRIPT_DIR}/dcmaar-agent" "${INSTALL_DIR}/bin/"
        chmod +x "${INSTALL_DIR}/bin/dcmaar-agent"
        log_success "Agent binary installed"
    else
        log_error "Agent binary not found: ${SCRIPT_DIR}/dcmaar-agent"
        exit 1
    fi
}

# Install configuration files
install_config() {
    log_info "Installing configuration files..."
    
    # Create default agent configuration
    cat > "${CONFIG_DIR}/agent.toml" << 'EOF'
# dcmaar Agent Configuration
# Generated by installer

[agent]
name = "dcmaar-agent"
version = "1.0.0"
log_level = "info"

[queue]
max_size = 10000
watermark_high = 8000
watermark_low = 2000
encryption = true

[admin]
bind_address = "127.0.0.1:8787"
enable_metrics = true
enable_status = true

[exporters]
# Add your exporters configuration here

[plugins]
# Add your plugins configuration here

[policies]
# Add your policies configuration here
EOF

    # Set config file permissions
    chown root:"${SERVICE_GROUP}" "${CONFIG_DIR}/agent.toml"
    chmod 640 "${CONFIG_DIR}/agent.toml"
    
    log_success "Configuration files installed"
}

# Install systemd service
install_service() {
    log_info "Installing systemd service..."
    
    # Copy service file
    if [[ -f "${SCRIPT_DIR}/../systemd/${SERVICE_NAME}.service" ]]; then
        cp "${SCRIPT_DIR}/../systemd/${SERVICE_NAME}.service" "/etc/systemd/system/"
    else
        # Create service file inline if not found
        cat > "/etc/systemd/system/${SERVICE_NAME}.service" << EOF
[Unit]
Description=dcmaar Agent - Observability Agent Service
Documentation=https://github.com/yappc/dcmaar
After=network-online.target
Wants=network-online.target
StartLimitIntervalSec=0

[Service]
Type=notify
Restart=always
RestartSec=5
User=${SERVICE_USER}
Group=${SERVICE_GROUP}
ExecStart=${INSTALL_DIR}/bin/dcmaar-agent --config=${CONFIG_DIR}/agent.toml
ExecReload=/bin/kill -HUP \$MAINPID
KillMode=mixed
KillSignal=SIGTERM
TimeoutStopSec=30
LimitNOFILE=65536
LimitNPROC=32768

# Security settings
CapabilityBoundingSet=CAP_NET_BIND_SERVICE CAP_SYS_RESOURCE
AmbientCapabilities=CAP_NET_BIND_SERVICE CAP_SYS_RESOURCE
NoNewPrivileges=yes
PrivateTmp=yes
ProtectSystem=strict
ProtectHome=yes
ReadWritePaths=${DATA_DIR} ${LOG_DIR} /tmp
ProtectKernelTunables=yes
ProtectKernelModules=yes
ProtectControlGroups=yes
RestrictRealtime=yes
RestrictSUIDSGID=yes
RemoveIPC=yes
RestrictNamespaces=yes

# Logging
StandardOutput=journal
StandardError=journal
SyslogIdentifier=${SERVICE_NAME}

# Environment
Environment=RUST_LOG=info
Environment=DCMAAR_CONFIG_DIR=${CONFIG_DIR}
Environment=DCMAAR_DATA_DIR=${DATA_DIR}
Environment=DCMAAR_LOG_DIR=${LOG_DIR}

[Install]
WantedBy=multi-user.target
Alias=dcmaar.service
EOF
    fi
    
    # Reload systemd and enable service
    systemctl daemon-reload
    systemctl enable "${SERVICE_NAME}"
    
    log_success "Systemd service installed and enabled"
}

# Install desktop application (if available)
install_desktop() {
    log_info "Checking for desktop application..."
    
    if [[ -f "${SCRIPT_DIR}/dcmaar-desktop.AppImage" ]]; then
        log_info "Installing desktop application..."
        
        # Create applications directory
        mkdir -p /opt/dcmaar/desktop
        cp "${SCRIPT_DIR}/dcmaar-desktop.AppImage" "/opt/dcmaar/desktop/"
        chmod +x "/opt/dcmaar/desktop/dcmaar-desktop.AppImage"
        
        # Create desktop entry
        mkdir -p /usr/share/applications
        cat > /usr/share/applications/dcmaar-desktop.desktop << EOF
[Desktop Entry]
Name=dcmaar Desktop
Comment=dcmaar Observability Dashboard
Exec=/opt/dcmaar/desktop/dcmaar-desktop.AppImage
Icon=dcmaar
Terminal=false
Type=Application
Categories=System;Monitor;
StartupNotify=true
EOF
        
        # Create symlink for easy access
        ln -sf "/opt/dcmaar/desktop/dcmaar-desktop.AppImage" "/usr/local/bin/dcmaar-desktop"
        
        log_success "Desktop application installed"
    else
        log_info "Desktop application not found, skipping"
    fi
}

# Start services
start_services() {
    log_info "Starting dcmaar agent service..."
    
    systemctl start "${SERVICE_NAME}"
    
    # Wait for service to start
    sleep 2
    
    if systemctl is-active --quiet "${SERVICE_NAME}"; then
        log_success "Service started successfully"
        
        # Show service status
        systemctl status "${SERVICE_NAME}" --no-pager --lines=5
    else
        log_error "Failed to start service"
        log_info "Check logs with: journalctl -u ${SERVICE_NAME}"
        exit 1
    fi
}

# Post-installation setup
post_install() {
    log_info "Running post-installation setup..."
    
    # Create CLI symlink
    ln -sf "${INSTALL_DIR}/bin/dcmaar-agent" "/usr/local/bin/dcmaar-agent"
    
    # Update system package database if needed
    local distro
    distro=$(detect_distro)
    case "${distro}" in
        ubuntu|debian)
            if command -v update-desktop-database &> /dev/null; then
                update-desktop-database /usr/share/applications 2>/dev/null || true
            fi
            ;;
        centos|rhel|fedora)
            if command -v update-desktop-database &> /dev/null; then
                update-desktop-database /usr/share/applications 2>/dev/null || true
            fi
            ;;
    esac
    
    log_success "Post-installation setup complete"
}

# Print installation summary
print_summary() {
    log_success "dcmaar installation completed successfully!"
    echo
    echo "Installation Summary:"
    echo "  • Agent binary: ${INSTALL_DIR}/bin/dcmaar-agent"
    echo "  • Configuration: ${CONFIG_DIR}/agent.toml"
    echo "  • Data directory: ${DATA_DIR}"
    echo "  • Log directory: ${LOG_DIR}"
    echo "  • Service name: ${SERVICE_NAME}"
    echo
    echo "Service Management:"
    echo "  • Start:   sudo systemctl start ${SERVICE_NAME}"
    echo "  • Stop:    sudo systemctl stop ${SERVICE_NAME}"
    echo "  • Restart: sudo systemctl restart ${SERVICE_NAME}"
    echo "  • Status:  sudo systemctl status ${SERVICE_NAME}"
    echo "  • Logs:    sudo journalctl -u ${SERVICE_NAME}"
    echo
    echo "Admin Interface:"
    echo "  • Status:  curl http://localhost:8787/status"
    echo "  • Metrics: curl http://localhost:8787/metrics"
    echo
    if [[ -f "/usr/local/bin/dcmaar-desktop" ]]; then
        echo "Desktop Application:"
        echo "  • Launch: dcmaar-desktop"
        echo "  • Or find 'dcmaar Desktop' in your applications menu"
        echo
    fi
    echo "Edit configuration: sudo nano ${CONFIG_DIR}/agent.toml"
    echo "After config changes: sudo systemctl restart ${SERVICE_NAME}"
}

# Uninstall function
uninstall() {
    log_info "Uninstalling dcmaar..."
    
    # Stop and disable service
    if systemctl is-enabled --quiet "${SERVICE_NAME}" 2>/dev/null; then
        systemctl stop "${SERVICE_NAME}" || true
        systemctl disable "${SERVICE_NAME}" || true
    fi
    
    # Remove service file
    rm -f "/etc/systemd/system/${SERVICE_NAME}.service"
    systemctl daemon-reload
    
    # Remove files and directories
    rm -rf "${INSTALL_DIR}"
    rm -f "/usr/local/bin/dcmaar-agent"
    rm -f "/usr/local/bin/dcmaar-desktop"
    rm -f "/usr/share/applications/dcmaar-desktop.desktop"
    
    # Optionally remove config and data (ask user)
    read -p "Remove configuration and data directories? [y/N]: " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        rm -rf "${CONFIG_DIR}" "${DATA_DIR}" "${LOG_DIR}"
        log_info "Configuration and data removed"
    fi
    
    # Optionally remove user
    read -p "Remove system user '${SERVICE_USER}'? [y/N]: " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        userdel "${SERVICE_USER}" 2>/dev/null || true
        groupdel "${SERVICE_GROUP}" 2>/dev/null || true
        log_info "System user removed"
    fi
    
    log_success "dcmaar uninstalled successfully"
}

# Main installation function
main() {
    case "${1:-install}" in
        install)
            log_info "Starting dcmaar installation..."
            check_root
            check_requirements
            create_user
            create_directories
            install_binaries
            install_config
            install_service
            install_desktop
            start_services
            post_install
            print_summary
            ;;
        uninstall)
            check_root
            uninstall
            ;;
        *)
            echo "Usage: $0 {install|uninstall}"
            exit 1
            ;;
    esac
}

# Run main function
main "$@"