import { describe, it, expect, vi, beforeEach } from "vitest";
import { createPathwaysService } from "../../../src/modules/learning/pathways-service";
import { aiClient } from "../../../src/clients/ai-client";

// Mock dependencies
const mockPrisma = {
  module: {
    findMany: vi.fn(),
    findFirst: vi.fn(),
  },
  learningPath: {
    create: vi.fn(),
  },
  enrollment: {
    findMany: vi.fn().mockResolvedValue([]),
  },
  assessmentAttempt: {
    findMany: vi.fn().mockResolvedValue([]),
  },
} as any;

// Mock AI Client
vi.mock("../../../src/clients/ai-client", () => ({
  aiClient: {
    generateLearningPath: vi.fn(),
  },
}));

describe("PathwaysService", () => {
  let service: any;

  beforeEach(() => {
    vi.clearAllMocks();
    service = createPathwaysService(mockPrisma);
  });

  describe("generatePathway", () => {
    it("should use AI client to generate path when successful", async () => {
      // Setup AI response
      const aiResponse = {
        title: "AI Path",
        description: "Generated by AI",
        nodes: [
          { title: "AI Node 1", id: "ai-1" },
          { title: "AI Node 2", id: "ai-2" },
        ],
      };
      vi.mocked(aiClient.generateLearningPath).mockResolvedValue(aiResponse);

      // Setup DB matches
      mockPrisma.module.findFirst
        .mockResolvedValueOnce({
          id: "mod-1",
          title: "DB Module 1",
          estimatedTimeMinutes: 30,
        })
        .mockResolvedValueOnce({
          id: "mod-2",
          title: "DB Module 2",
          estimatedTimeMinutes: 45,
        });

      mockPrisma.learningPath.create.mockResolvedValue({
        id: "path-1",
        title: "AI Path",
        userId: "user-1",
        nodes: [
          { id: "node-1", title: "DB Module 1", orderIndex: 0 },
          { id: "node-2", title: "DB Module 2", orderIndex: 1 },
        ],
      });

      // Execute
      const result = await service.generatePathway({
        tenantId: "tenant-1",
        userId: "user-1",
        goal: "Learn AI",
      });

      // Verify
      expect(aiClient.generateLearningPath).toHaveBeenCalledWith(
        expect.objectContaining({
          subject: "Learn AI",
          goal: "Learn AI",
        }),
      );
      expect(mockPrisma.learningPath.create).toHaveBeenCalled();
      expect(result.nodes).toHaveLength(2);
    });

    it("should fallback to heuristic search when AI fails/returns null", async () => {
      // Setup AI failure
      vi.mocked(aiClient.generateLearningPath).mockRejectedValue(
        new Error("AI Offline"),
      );

      // Setup DB heuristic search results
      mockPrisma.module.findMany.mockResolvedValue([
        {
          id: "mod-1",
          title: "Intro to AI",
          domain: "cs",
          description: "Basics",
          tags: [],
          estimatedTimeMinutes: 30,
          difficulty: "INTRO",
        },
      ]);

      mockPrisma.learningPath.create.mockResolvedValue({
        id: "path-fallback",
        title: "Path: Learn AI",
        nodes: [{ id: "node-1", title: "Intro to AI", orderIndex: 0 }],
      });

      // Execute
      const result = await service.generatePathway({
        tenantId: "tenant-1",
        userId: "user-1",
        goal: "Learn AI",
      });

      // Verify
      expect(aiClient.generateLearningPath).toHaveBeenCalled();
      // Should have called findMany for heuristic fallback
      expect(mockPrisma.module.findMany).toHaveBeenCalled();
      // Heuristic path returns modules array + reasoning, not a persisted path
      expect(result.modules).toBeDefined();
      expect(result.modules).toHaveLength(1);
      expect(result.reasoning).toBeDefined();
    });
  });
});
