{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aep.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aep.labels" . | nindent 4 }}
{{- end }}
{{- if .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "aep.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aep.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
{{- end }}
{{- if and .Values.serviceAccount.create .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "aep.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "aep.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "aep.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "aep.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}