.PHONY: init plan apply destroy fmt validate

init:
terraform init

plan:
terraform plan

apply:
terraform apply

destroy:
terraform destroy

fmt:
terraform fmt -recursive

validate:
terraform validate