#!/usr/bin/env bash

set -euo pipefail

output_dir="${1:-products/yappc/build/release-evidence}"
artifact_root="${2:-artifacts}"
bundle_file="$output_dir/release-evidence-bundle.md"

mkdir -p "$output_dir"

status_for() {
  local path="$1"
  if [[ -e "$path" ]]; then
    printf 'present'
  else
    printf 'missing'
  fi
}

cat > "$bundle_file" <<EOF
# YAPPC Release Evidence Bundle

Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

## Critical Journeys

| Journey | Owning automated path | Evidence artifact | Status |
|---|---|---|---|
| Authenticated access to core web flows | frontend/e2e/auth.spec.ts | $artifact_root/playwright-report | $(status_for "$artifact_root/playwright-report") |
| Intent to generation lifecycle API flow | core/ai/src/test/java/com/ghatana/yappc/ai/integration/AICallPathTest.java | $artifact_root/backend-tests | $(status_for "$artifact_root/backend-tests") |
| Agent execution with provider wiring in release-like startup | core/services-lifecycle startup diagnostics | $artifact_root/startup-diagnostics | $(status_for "$artifact_root/startup-diagnostics") |
| Tenant isolation across API and persistence paths | frontend/apps/api/src/__tests__/routes.integration.test.ts | $artifact_root/frontend-tests | $(status_for "$artifact_root/frontend-tests") |
| Release startup with observability and health endpoints | lifecycle startup + contract diagnostics | $artifact_root/startup-diagnostics, $artifact_root/contract-report | $(status_for "$artifact_root/startup-diagnostics") |

## Downloaded Artifacts

| Artifact | Path | Status |
|---|---|---|
| Backend tests | $artifact_root/backend-tests | $(status_for "$artifact_root/backend-tests") |
| Frontend tests | $artifact_root/frontend-tests | $(status_for "$artifact_root/frontend-tests") |
| Frontend coverage | $artifact_root/frontend-coverage | $(status_for "$artifact_root/frontend-coverage") |
| Playwright report | $artifact_root/playwright-report | $(status_for "$artifact_root/playwright-report") |
| E2E results | $artifact_root/e2e-results | $(status_for "$artifact_root/e2e-results") |
| Startup diagnostics | $artifact_root/startup-diagnostics | $(status_for "$artifact_root/startup-diagnostics") |
| Contract report | $artifact_root/contract-report | $(status_for "$artifact_root/contract-report") |

## Notes

- This bundle is generated by products/yappc/scripts/generate-release-evidence.sh.
- Missing artifacts mean the corresponding job did not publish evidence and the release should not be considered complete.
- Contract-test diagnostics are published by the dedicated contract workflow in addition to the main CI startup probe.
EOF