package com.ghatana.digitalmarketing.domain.optimization;

import java.time.Instant;
import java.util.Map;
import java.util.Objects;

/**
 * Immutable entity representing an AI-detected anomaly in campaign performance metrics.
 *
 * <p>Anomaly detection identifies unusual patterns in campaign metrics such as sudden drops in
 * conversion rates, unexpected spikes in costs, or deviations from expected performance baselines.
 * These results are generated by AI agents analyzing time-series data and statistical models.</p>
 *
 * @doc.type class
 * @doc.purpose Captures AI-detected campaign performance anomalies with severity and context (P3-004)
 * @doc.layer product
 * @doc.pattern Entity
 */
public final class AnomalyDetectionResult {

    private final String id;
    private final String tenantId;
    private final String workspaceId;
    private final String campaignId;
    private final AnomalySeverity severity;
    private final String metricName;
    private final String anomalyType;
    private final double expectedValue;
    private final double actualValue;
    private final double deviationPercentage;
    private final String description;
    private final Map<String, Object> context;
    private final String rationale;
    private final AnomalyStatus status;
    private final String acknowledgedBy;
    private final String mitigationAction;
    private final Instant detectedAt;
    private final Instant acknowledgedAt;
    private final Instant resolvedAt;

    private AnomalyDetectionResult(Builder builder) {
        this.id = builder.id;
        this.tenantId = builder.tenantId;
        this.workspaceId = builder.workspaceId;
        this.campaignId = builder.campaignId;
        this.severity = builder.severity;
        this.metricName = builder.metricName;
        this.anomalyType = builder.anomalyType;
        this.expectedValue = builder.expectedValue;
        this.actualValue = builder.actualValue;
        this.deviationPercentage = builder.deviationPercentage;
        this.description = builder.description;
        this.context = Map.copyOf(builder.context);
        this.rationale = builder.rationale;
        this.status = builder.status;
        this.acknowledgedBy = builder.acknowledgedBy;
        this.mitigationAction = builder.mitigationAction;
        this.detectedAt = builder.detectedAt;
        this.acknowledgedAt = builder.acknowledgedAt;
        this.resolvedAt = builder.resolvedAt;
    }

    /** Acknowledge this anomaly as reviewed by the specified user. */
    public AnomalyDetectionResult acknowledge(String acknowledgedBy) {
        if (this.status != AnomalyStatus.DETECTED) {
            throw new IllegalStateException("Only DETECTED anomalies can be acknowledged, was: " + status);
        }
        Objects.requireNonNull(acknowledgedBy, "acknowledgedBy must not be null");
        return toBuilder()
            .status(AnomalyStatus.ACKNOWLEDGED)
            .acknowledgedBy(acknowledgedBy)
            .acknowledgedAt(Instant.now())
            .build();
    }

    /** Resolve this anomaly with a mitigation action. */
    public AnomalyDetectionResult resolve(String mitigationAction) {
        if (this.status != AnomalyStatus.ACKNOWLEDGED) {
            throw new IllegalStateException("Only ACKNOWLEDGED anomalies can be resolved, was: " + status);
        }
        Objects.requireNonNull(mitigationAction, "mitigationAction must not be null");
        return toBuilder()
            .status(AnomalyStatus.RESOLVED)
            .mitigationAction(mitigationAction)
            .resolvedAt(Instant.now())
            .build();
    }

    /** Dismiss this anomaly as a false positive. */
    public AnomalyDetectionResult dismiss(String reason) {
        if (this.status != AnomalyStatus.DETECTED && this.status != AnomalyStatus.ACKNOWLEDGED) {
            throw new IllegalStateException("Only DETECTED or ACKNOWLEDGED anomalies can be dismissed, was: " + status);
        }
        Objects.requireNonNull(reason, "reason must not be null");
        return toBuilder()
            .status(AnomalyStatus.DISMISSED)
            .mitigationAction(reason)
            .resolvedAt(Instant.now())
            .build();
    }

    /** Whether this anomaly has been resolved or dismissed. */
    public boolean isClosed() {
        return status == AnomalyStatus.RESOLVED || status == AnomalyStatus.DISMISSED;
    }

    public String getId() { return id; }
    public String getTenantId() { return tenantId; }
    public String getWorkspaceId() { return workspaceId; }
    public String getCampaignId() { return campaignId; }
    public AnomalySeverity getSeverity() { return severity; }
    public String getMetricName() { return metricName; }
    public String getAnomalyType() { return anomalyType; }
    public double getExpectedValue() { return expectedValue; }
    public double getActualValue() { return actualValue; }
    public double getDeviationPercentage() { return deviationPercentage; }
    public String getDescription() { return description; }
    public Map<String, Object> getContext() { return context; }
    public String getRationale() { return rationale; }
    public AnomalyStatus getStatus() { return status; }
    public String getAcknowledgedBy() { return acknowledgedBy; }
    public String getMitigationAction() { return mitigationAction; }
    public Instant getDetectedAt() { return detectedAt; }
    public Instant getAcknowledgedAt() { return acknowledgedAt; }
    public Instant getResolvedAt() { return resolvedAt; }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof AnomalyDetectionResult)) return false;
        return id.equals(((AnomalyDetectionResult) o).id);
    }

    @Override
    public int hashCode() { return id.hashCode(); }

    @Override
    public String toString() {
        return "AnomalyDetectionResult{id='" + id + "', campaignId='" + campaignId
            + "', metricName='" + metricName + "', severity=" + severity + ", status=" + status + '}';
    }

    public Builder toBuilder() {
        return new Builder()
            .id(id).tenantId(tenantId).workspaceId(workspaceId).campaignId(campaignId)
            .severity(severity).metricName(metricName).anomalyType(anomalyType)
            .expectedValue(expectedValue).actualValue(actualValue).deviationPercentage(deviationPercentage)
            .description(description).context(context).rationale(rationale)
            .status(status).acknowledgedBy(acknowledgedBy).mitigationAction(mitigationAction)
            .detectedAt(detectedAt).acknowledgedAt(acknowledgedAt).resolvedAt(resolvedAt);
    }

    public static Builder builder() { return new Builder(); }

    public static final class Builder {
        private String id;
        private String tenantId;
        private String workspaceId;
        private String campaignId;
        private AnomalySeverity severity;
        private String metricName;
        private String anomalyType;
        private double expectedValue;
        private double actualValue;
        private double deviationPercentage;
        private String description;
        private Map<String, Object> context = Map.of();
        private String rationale;
        private AnomalyStatus status;
        private String acknowledgedBy;
        private String mitigationAction;
        private Instant detectedAt;
        private Instant acknowledgedAt;
        private Instant resolvedAt;

        public Builder id(String id) { this.id = id; return this; }
        public Builder tenantId(String t) { this.tenantId = t; return this; }
        public Builder workspaceId(String w) { this.workspaceId = w; return this; }
        public Builder campaignId(String c) { this.campaignId = c; return this; }
        public Builder severity(AnomalySeverity s) { this.severity = s; return this; }
        public Builder metricName(String m) { this.metricName = m; return this; }
        public Builder anomalyType(String a) { this.anomalyType = a; return this; }
        public Builder expectedValue(double e) { this.expectedValue = e; return this; }
        public Builder actualValue(double a) { this.actualValue = a; return this; }
        public Builder deviationPercentage(double d) { this.deviationPercentage = d; return this; }
        public Builder description(String d) { this.description = d; return this; }
        public Builder context(Map<String, Object> c) { this.context = c; return this; }
        public Builder rationale(String r) { this.rationale = r; return this; }
        public Builder status(AnomalyStatus s) { this.status = s; return this; }
        public Builder acknowledgedBy(String a) { this.acknowledgedBy = a; return this; }
        public Builder mitigationAction(String m) { this.mitigationAction = m; return this; }
        public Builder detectedAt(Instant t) { this.detectedAt = t; return this; }
        public Builder acknowledgedAt(Instant t) { this.acknowledgedAt = t; return this; }
        public Builder resolvedAt(Instant t) { this.resolvedAt = t; return this; }

        public AnomalyDetectionResult build() {
            Objects.requireNonNull(status, "status must not be null");
            if (id == null || id.isBlank()) throw new IllegalArgumentException("id must not be blank");
            if (tenantId == null || tenantId.isBlank()) throw new IllegalArgumentException("tenantId must not be blank");
            if (workspaceId == null || workspaceId.isBlank()) throw new IllegalArgumentException("workspaceId must not be blank");
            Objects.requireNonNull(severity, "severity must not be null");
            Objects.requireNonNull(metricName, "metricName must not be null");
            Objects.requireNonNull(anomalyType, "anomalyType must not be null");
            Objects.requireNonNull(context, "context must not be null");
            Objects.requireNonNull(detectedAt, "detectedAt must not be null");
            return new AnomalyDetectionResult(this);
        }
    }
}
