package com.ghatana.digitalmarketing.domain.optimization;

import java.time.Instant;
import java.util.List;
import java.util.Map;
import java.util.Objects;

/**
 * Immutable entity representing an AI-generated budget reallocation proposal.
 *
 * <p>Budget reallocation proposals suggest redistributing campaign budgets across channels or campaigns
 * to optimize overall performance. These proposals are generated by AI agents analyzing ROI, ROAS,
 * conversion rates, and market conditions. Proposals require human approval before execution to ensure
 * strategic alignment with business goals.</p>
 *
 * @doc.type class
 * @doc.purpose Captures AI-generated budget reallocation proposals with human approval workflow (P3-004)
 * @doc.layer product
 * @doc.pattern Entity
 */
public final class BudgetReallocationProposal {

    private final String id;
    private final String tenantId;
    private final String workspaceId;
    private final String budgetRecommendationId;
    private final String title;
    private final String description;
    private final List<BudgetAdjustment> adjustments;
    private final double totalReallocatedAmount;
    private final String rationale;
    private final BudgetReallocationStatus status;
    private final String rejectionReason;
    private final String approvedBy;
    private final Instant createdAt;
    private final Instant approvedAt;
    private final Instant executedAt;
    private final Instant expiresAt;

    private BudgetReallocationProposal(Builder builder) {
        this.id = builder.id;
        this.tenantId = builder.tenantId;
        this.workspaceId = builder.workspaceId;
        this.budgetRecommendationId = builder.budgetRecommendationId;
        this.title = builder.title;
        this.description = builder.description;
        this.adjustments = List.copyOf(builder.adjustments);
        this.totalReallocatedAmount = builder.totalReallocatedAmount;
        this.rationale = builder.rationale;
        this.status = builder.status;
        this.rejectionReason = builder.rejectionReason;
        this.approvedBy = builder.approvedBy;
        this.createdAt = builder.createdAt;
        this.approvedAt = builder.approvedAt;
        this.executedAt = builder.executedAt;
        this.expiresAt = builder.expiresAt;
    }

    /** Approve this proposal for execution. */
    public BudgetReallocationProposal approve(String approvedBy) {
        if (this.status != BudgetReallocationStatus.PENDING) {
            throw new IllegalStateException("Only PENDING proposals can be approved, was: " + status);
        }
        Objects.requireNonNull(approvedBy, "approvedBy must not be null");
        return toBuilder()
            .status(BudgetReallocationStatus.APPROVED)
            .approvedBy(approvedBy)
            .approvedAt(Instant.now())
            .build();
    }

    /** Reject this proposal with a reason. */
    public BudgetReallocationProposal reject(String reason) {
        if (this.status != BudgetReallocationStatus.PENDING) {
            throw new IllegalStateException("Only PENDING proposals can be rejected, was: " + status);
        }
        Objects.requireNonNull(reason, "reason must not be null");
        return toBuilder()
            .status(BudgetReallocationStatus.REJECTED)
            .rejectionReason(reason)
            .build();
    }

    /** Mark this proposal as executed. */
    public BudgetReallocationProposal execute() {
        if (this.status != BudgetReallocationStatus.APPROVED) {
            throw new IllegalStateException("Only APPROVED proposals can be executed, was: " + status);
        }
        return toBuilder()
            .status(BudgetReallocationStatus.EXECUTED)
            .executedAt(Instant.now())
            .build();
    }

    /** Mark as expired if it was not processed in time. */
    public BudgetReallocationProposal expire() {
        if (this.status != BudgetReallocationStatus.PENDING) {
            throw new IllegalStateException("Only PENDING proposals can expire, was: " + status);
        }
        return toBuilder()
            .status(BudgetReallocationStatus.EXPIRED)
            .build();
    }

    /** Whether this proposal has been processed (not PENDING). */
    public boolean isProcessed() {
        return status != BudgetReallocationStatus.PENDING;
    }

    public String getId() { return id; }
    public String getTenantId() { return tenantId; }
    public String getWorkspaceId() { return workspaceId; }
    public String getBudgetRecommendationId() { return budgetRecommendationId; }
    public String getTitle() { return title; }
    public String getDescription() { return description; }
    public List<BudgetAdjustment> getAdjustments() { return adjustments; }
    public double getTotalReallocatedAmount() { return totalReallocatedAmount; }
    public String getRationale() { return rationale; }
    public BudgetReallocationStatus getStatus() { return status; }
    public String getRejectionReason() { return rejectionReason; }
    public String getApprovedBy() { return approvedBy; }
    public Instant getCreatedAt() { return createdAt; }
    public Instant getApprovedAt() { return approvedAt; }
    public Instant getExecutedAt() { return executedAt; }
    public Instant getExpiresAt() { return expiresAt; }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof BudgetReallocationProposal)) return false;
        return id.equals(((BudgetReallocationProposal) o).id);
    }

    @Override
    public int hashCode() { return id.hashCode(); }

    @Override
    public String toString() {
        return "BudgetReallocationProposal{id='" + id + "', budgetRecommendationId='" + budgetRecommendationId
            + "', totalReallocatedAmount=" + totalReallocatedAmount + ", status=" + status + '}';
    }

    public Builder toBuilder() {
        return new Builder()
            .id(id).tenantId(tenantId).workspaceId(workspaceId).budgetRecommendationId(budgetRecommendationId)
            .title(title).description(description).adjustments(adjustments)
            .totalReallocatedAmount(totalReallocatedAmount).rationale(rationale)
            .status(status).rejectionReason(rejectionReason).approvedBy(approvedBy)
            .createdAt(createdAt).approvedAt(approvedAt).executedAt(executedAt).expiresAt(expiresAt);
    }

    public static Builder builder() { return new Builder(); }

    /**
     * Represents a single budget adjustment within a reallocation proposal.
     */
    public static final class BudgetAdjustment {
        private final String campaignId;
        private final String channelType;
        private final double currentAmount;
        private final double proposedAmount;
        private final double adjustmentAmount;
        private final String reason;

        public BudgetAdjustment(String campaignId, String channelType, double currentAmount,
                                double proposedAmount, double adjustmentAmount, String reason) {
            this.campaignId = Objects.requireNonNull(campaignId, "campaignId must not be null");
            this.channelType = Objects.requireNonNull(channelType, "channelType must not be null");
            this.currentAmount = currentAmount;
            this.proposedAmount = proposedAmount;
            this.adjustmentAmount = adjustmentAmount;
            this.reason = Objects.requireNonNull(reason, "reason must not be null");
        }

        public String getCampaignId() { return campaignId; }
        public String getChannelType() { return channelType; }
        public double getCurrentAmount() { return currentAmount; }
        public double getProposedAmount() { return proposedAmount; }
        public double getAdjustmentAmount() { return adjustmentAmount; }
        public String getReason() { return reason; }

        @Override
        public String toString() {
            return "BudgetAdjustment{campaignId='" + campaignId + "', channelType='" + channelType
                + "', adjustmentAmount=" + adjustmentAmount + '}';
        }
    }

    public static final class Builder {
        private String id;
        private String tenantId;
        private String workspaceId;
        private String budgetRecommendationId;
        private String title;
        private String description;
        private List<BudgetAdjustment> adjustments = List.of();
        private double totalReallocatedAmount;
        private String rationale;
        private BudgetReallocationStatus status;
        private String rejectionReason;
        private String approvedBy;
        private Instant createdAt;
        private Instant approvedAt;
        private Instant executedAt;
        private Instant expiresAt;

        public Builder id(String id) { this.id = id; return this; }
        public Builder tenantId(String t) { this.tenantId = t; return this; }
        public Builder workspaceId(String w) { this.workspaceId = w; return this; }
        public Builder budgetRecommendationId(String b) { this.budgetRecommendationId = b; return this; }
        public Builder title(String t) { this.title = t; return this; }
        public Builder description(String d) { this.description = d; return this; }
        public Builder adjustments(List<BudgetAdjustment> a) { this.adjustments = a; return this; }
        public Builder totalReallocatedAmount(double t) { this.totalReallocatedAmount = t; return this; }
        public Builder rationale(String r) { this.rationale = r; return this; }
        public Builder status(BudgetReallocationStatus s) { this.status = s; return this; }
        public Builder rejectionReason(String r) { this.rejectionReason = r; return this; }
        public Builder approvedBy(String a) { this.approvedBy = a; return this; }
        public Builder createdAt(Instant t) { this.createdAt = t; return this; }
        public Builder approvedAt(Instant t) { this.approvedAt = t; return this; }
        public Builder executedAt(Instant t) { this.executedAt = t; return this; }
        public Builder expiresAt(Instant t) { this.expiresAt = t; return this; }

        public BudgetReallocationProposal build() {
            Objects.requireNonNull(status, "status must not be null");
            if (id == null || id.isBlank()) throw new IllegalArgumentException("id must not be blank");
            if (tenantId == null || tenantId.isBlank()) throw new IllegalArgumentException("tenantId must not be blank");
            if (workspaceId == null || workspaceId.isBlank()) throw new IllegalArgumentException("workspaceId must not be blank");
            Objects.requireNonNull(adjustments, "adjustments must not be null");
            if (adjustments.isEmpty()) throw new IllegalArgumentException("adjustments must not be empty");
            if (totalReallocatedAmount < 0.0) throw new IllegalArgumentException("totalReallocatedAmount must be non-negative");
            Objects.requireNonNull(createdAt, "createdAt must not be null");
            return new BudgetReallocationProposal(this);
        }
    }
}
