package com.ghatana.digitalmarketing.domain.optimization;

import java.time.Instant;
import java.util.Map;
import java.util.Objects;

/**
 * Immutable entity representing an AI-generated experiment suggestion for A/B testing.
 *
 * <p>Experiment suggestions propose A/B tests to optimize campaign performance, such as testing
 * different creatives, targeting parameters, bidding strategies, or landing pages. These suggestions
 * are generated by AI agents analyzing historical performance, market trends, and statistical models.</p>
 *
 * @doc.type class
 * @doc.purpose Captures AI-generated experiment suggestions for A/B testing with metadata (P3-004)
 * @doc.layer product
 * @doc.pattern Entity
 */
public final class ExperimentSuggestion {

    private final String id;
    private final String tenantId;
    private final String workspaceId;
    private final String campaignId;
    private final ExperimentType experimentType;
    private final String title;
    private final String description;
    private final Map<String, Object> controlVariant;
    private final Map<String, Object> treatmentVariant;
    private final String hypothesis;
    private final String successMetric;
    private final double minimumDetectableEffect;
    private final String rationale;
    private final ExperimentSuggestionStatus status;
    private final String rejectionReason;
    private final String experimentId;
    private final String approvedBy;
    private final Instant createdAt;
    private final Instant approvedAt;
    private final Instant expiresAt;

    private ExperimentSuggestion(Builder builder) {
        this.id = builder.id;
        this.tenantId = builder.tenantId;
        this.workspaceId = builder.workspaceId;
        this.campaignId = builder.campaignId;
        this.experimentType = builder.experimentType;
        this.title = builder.title;
        this.description = builder.description;
        this.controlVariant = Map.copyOf(builder.controlVariant);
        this.treatmentVariant = Map.copyOf(builder.treatmentVariant);
        this.hypothesis = builder.hypothesis;
        this.successMetric = builder.successMetric;
        this.minimumDetectableEffect = builder.minimumDetectableEffect;
        this.rationale = builder.rationale;
        this.status = builder.status;
        this.rejectionReason = builder.rejectionReason;
        this.experimentId = builder.experimentId;
        this.approvedBy = builder.approvedBy;
        this.createdAt = builder.createdAt;
        this.approvedAt = builder.approvedAt;
        this.expiresAt = builder.expiresAt;
    }

    /** Approve this suggestion and link to the created experiment. */
    public ExperimentSuggestion approve(String experimentId, String approvedBy) {
        if (this.status != ExperimentSuggestionStatus.PENDING) {
            throw new IllegalStateException("Only PENDING suggestions can be approved, was: " + status);
        }
        Objects.requireNonNull(experimentId, "experimentId must not be null");
        Objects.requireNonNull(approvedBy, "approvedBy must not be null");
        return toBuilder()
            .status(ExperimentSuggestionStatus.APPROVED)
            .experimentId(experimentId)
            .approvedBy(approvedBy)
            .approvedAt(Instant.now())
            .build();
    }

    /** Reject this suggestion with a reason. */
    public ExperimentSuggestion reject(String reason) {
        if (this.status != ExperimentSuggestionStatus.PENDING) {
            throw new IllegalStateException("Only PENDING suggestions can be rejected, was: " + status);
        }
        Objects.requireNonNull(reason, "reason must not be null");
        return toBuilder()
            .status(ExperimentSuggestionStatus.REJECTED)
            .rejectionReason(reason)
            .build();
    }

    /** Mark as expired if it was not processed in time. */
    public ExperimentSuggestion expire() {
        if (this.status != ExperimentSuggestionStatus.PENDING) {
            throw new IllegalStateException("Only PENDING suggestions can expire, was: " + status);
        }
        return toBuilder()
            .status(ExperimentSuggestionStatus.EXPIRED)
            .build();
    }

    /** Whether this suggestion has been processed (not PENDING). */
    public boolean isProcessed() {
        return status != ExperimentSuggestionStatus.PENDING;
    }

    public String getId() { return id; }
    public String getTenantId() { return tenantId; }
    public String getWorkspaceId() { return workspaceId; }
    public String getCampaignId() { return campaignId; }
    public ExperimentType getExperimentType() { return experimentType; }
    public String getTitle() { return title; }
    public String getDescription() { return description; }
    public Map<String, Object> getControlVariant() { return controlVariant; }
    public Map<String, Object> getTreatmentVariant() { return treatmentVariant; }
    public String getHypothesis() { return hypothesis; }
    public String getSuccessMetric() { return successMetric; }
    public double getMinimumDetectableEffect() { return minimumDetectableEffect; }
    public String getRationale() { return rationale; }
    public ExperimentSuggestionStatus getStatus() { return status; }
    public String getRejectionReason() { return rejectionReason; }
    public String getExperimentId() { return experimentId; }
    public String getApprovedBy() { return approvedBy; }
    public Instant getCreatedAt() { return createdAt; }
    public Instant getApprovedAt() { return approvedAt; }
    public Instant getExpiresAt() { return expiresAt; }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof ExperimentSuggestion)) return false;
        return id.equals(((ExperimentSuggestion) o).id);
    }

    @Override
    public int hashCode() { return id.hashCode(); }

    @Override
    public String toString() {
        return "ExperimentSuggestion{id='" + id + "', campaignId='" + campaignId
            + "', experimentType=" + experimentType + ", status=" + status + '}';
    }

    public Builder toBuilder() {
        return new Builder()
            .id(id).tenantId(tenantId).workspaceId(workspaceId).campaignId(campaignId)
            .experimentType(experimentType).title(title).description(description)
            .controlVariant(controlVariant).treatmentVariant(treatmentVariant)
            .hypothesis(hypothesis).successMetric(successMetric)
            .minimumDetectableEffect(minimumDetectableEffect).rationale(rationale)
            .status(status).rejectionReason(rejectionReason).experimentId(experimentId)
            .approvedBy(approvedBy).createdAt(createdAt).approvedAt(approvedAt).expiresAt(expiresAt);
    }

    public static Builder builder() { return new Builder(); }

    public static final class Builder {
        private String id;
        private String tenantId;
        private String workspaceId;
        private String campaignId;
        private ExperimentType experimentType;
        private String title;
        private String description;
        private Map<String, Object> controlVariant = Map.of();
        private Map<String, Object> treatmentVariant = Map.of();
        private String hypothesis;
        private String successMetric;
        private double minimumDetectableEffect;
        private String rationale;
        private ExperimentSuggestionStatus status;
        private String rejectionReason;
        private String experimentId;
        private String approvedBy;
        private Instant createdAt;
        private Instant approvedAt;
        private Instant expiresAt;

        public Builder id(String id) { this.id = id; return this; }
        public Builder tenantId(String t) { this.tenantId = t; return this; }
        public Builder workspaceId(String w) { this.workspaceId = w; return this; }
        public Builder campaignId(String c) { this.campaignId = c; return this; }
        public Builder experimentType(ExperimentType e) { this.experimentType = e; return this; }
        public Builder title(String t) { this.title = t; return this; }
        public Builder description(String d) { this.description = d; return this; }
        public Builder controlVariant(Map<String, Object> c) { this.controlVariant = c; return this; }
        public Builder treatmentVariant(Map<String, Object> t) { this.treatmentVariant = t; return this; }
        public Builder hypothesis(String h) { this.hypothesis = h; return this; }
        public Builder successMetric(String s) { this.successMetric = s; return this; }
        public Builder minimumDetectableEffect(double m) { this.minimumDetectableEffect = m; return this; }
        public Builder rationale(String r) { this.rationale = r; return this; }
        public Builder status(ExperimentSuggestionStatus s) { this.status = s; return this; }
        public Builder rejectionReason(String r) { this.rejectionReason = r; return this; }
        public Builder experimentId(String e) { this.experimentId = e; return this; }
        public Builder approvedBy(String a) { this.approvedBy = a; return this; }
        public Builder createdAt(Instant t) { this.createdAt = t; return this; }
        public Builder approvedAt(Instant t) { this.approvedAt = t; return this; }
        public Builder expiresAt(Instant t) { this.expiresAt = t; return this; }

        public ExperimentSuggestion build() {
            Objects.requireNonNull(status, "status must not be null");
            if (id == null || id.isBlank()) throw new IllegalArgumentException("id must not be blank");
            if (tenantId == null || tenantId.isBlank()) throw new IllegalArgumentException("tenantId must not be blank");
            if (workspaceId == null || workspaceId.isBlank()) throw new IllegalArgumentException("workspaceId must not be blank");
            Objects.requireNonNull(experimentType, "experimentType must not be null");
            Objects.requireNonNull(controlVariant, "controlVariant must not be null");
            Objects.requireNonNull(treatmentVariant, "treatmentVariant must not be null");
            Objects.requireNonNull(hypothesis, "hypothesis must not be null");
            Objects.requireNonNull(successMetric, "successMetric must not be null");
            if (minimumDetectableEffect <= 0.0) throw new IllegalArgumentException("minimumDetectableEffect must be positive");
            Objects.requireNonNull(createdAt, "createdAt must not be null");
            return new ExperimentSuggestion(this);
        }
    }
}
