package com.ghatana.digitalmarketing.domain.optimization;

import java.time.Instant;
import java.util.Map;
import java.util.Objects;

/**
 * Immutable entity representing an AI-generated next-best-action recommendation for campaign optimization.
 *
 * <p>Next-best-action recommendations suggest the optimal next step to improve campaign performance,
 * such as adjusting budget, changing creative, targeting new audiences, or launching new campaigns.
 * These recommendations are generated by AI agents analyzing campaign metrics, historical performance,
 * and market conditions.</p>
 *
 * @doc.type class
 * @doc.purpose Captures AI-generated next-best-action recommendations with metadata for human approval and execution (P3-004)
 * @doc.layer product
 * @doc.pattern Entity
 */
public final class NextBestActionRecommendation {

    private final String id;
    private final String tenantId;
    private final String workspaceId;
    private final String campaignId;
    private final NextBestActionType actionType;
    private final String title;
    private final String description;
    private final Map<String, Object> parameters;
    private final double confidenceScore;
    private final String rationale;
    private final NextBestActionStatus status;
    private final String rejectionReason;
    private final String executedBy;
    private final Instant createdAt;
    private final Instant processedAt;
    private final Instant expiresAt;

    private NextBestActionRecommendation(Builder builder) {
        this.id = builder.id;
        this.tenantId = builder.tenantId;
        this.workspaceId = builder.workspaceId;
        this.campaignId = builder.campaignId;
        this.actionType = builder.actionType;
        this.title = builder.title;
        this.description = builder.description;
        this.parameters = Map.copyOf(builder.parameters);
        this.confidenceScore = builder.confidenceScore;
        this.rationale = builder.rationale;
        this.status = builder.status;
        this.rejectionReason = builder.rejectionReason;
        this.executedBy = builder.executedBy;
        this.createdAt = builder.createdAt;
        this.processedAt = builder.processedAt;
        this.expiresAt = builder.expiresAt;
    }

    /** Approve and mark this recommendation as executed by the specified user. */
    public NextBestActionRecommendation approve(String executedBy) {
        if (this.status != NextBestActionStatus.PENDING) {
            throw new IllegalStateException("Only PENDING recommendations can be approved, was: " + status);
        }
        Objects.requireNonNull(executedBy, "executedBy must not be null");
        return toBuilder()
            .status(NextBestActionStatus.APPROVED)
            .executedBy(executedBy)
            .processedAt(Instant.now())
            .build();
    }

    /** Reject this recommendation with a reason. */
    public NextBestActionRecommendation reject(String reason) {
        if (this.status != NextBestActionStatus.PENDING) {
            throw new IllegalStateException("Only PENDING recommendations can be rejected, was: " + status);
        }
        Objects.requireNonNull(reason, "reason must not be null");
        return toBuilder()
            .status(NextBestActionStatus.REJECTED)
            .rejectionReason(reason)
            .processedAt(Instant.now())
            .build();
    }

    /** Mark as expired if it was not processed in time. */
    public NextBestActionRecommendation expire() {
        if (this.status != NextBestActionStatus.PENDING) {
            throw new IllegalStateException("Only PENDING recommendations can expire, was: " + status);
        }
        return toBuilder()
            .status(NextBestActionStatus.EXPIRED)
            .processedAt(Instant.now())
            .build();
    }

    /** Whether this recommendation has been processed (not PENDING). */
    public boolean isProcessed() {
        return status != NextBestActionStatus.PENDING;
    }

    public String getId() { return id; }
    public String getTenantId() { return tenantId; }
    public String getWorkspaceId() { return workspaceId; }
    public String getCampaignId() { return campaignId; }
    public NextBestActionType getActionType() { return actionType; }
    public String getTitle() { return title; }
    public String getDescription() { return description; }
    public Map<String, Object> getParameters() { return parameters; }
    public double getConfidenceScore() { return confidenceScore; }
    public String getRationale() { return rationale; }
    public NextBestActionStatus getStatus() { return status; }
    public String getRejectionReason() { return rejectionReason; }
    public String getExecutedBy() { return executedBy; }
    public Instant getCreatedAt() { return createdAt; }
    public Instant getProcessedAt() { return processedAt; }
    public Instant getExpiresAt() { return expiresAt; }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof NextBestActionRecommendation)) return false;
        return id.equals(((NextBestActionRecommendation) o).id);
    }

    @Override
    public int hashCode() { return id.hashCode(); }

    @Override
    public String toString() {
        return "NextBestActionRecommendation{id='" + id + "', campaignId='" + campaignId
            + "', actionType=" + actionType + ", status=" + status + '}';
    }

    public Builder toBuilder() {
        return new Builder()
            .id(id).tenantId(tenantId).workspaceId(workspaceId).campaignId(campaignId)
            .actionType(actionType).title(title).description(description)
            .parameters(parameters).confidenceScore(confidenceScore).rationale(rationale)
            .status(status).rejectionReason(rejectionReason).executedBy(executedBy)
            .createdAt(createdAt).processedAt(processedAt).expiresAt(expiresAt);
    }

    public static Builder builder() { return new Builder(); }

    public static final class Builder {
        private String id;
        private String tenantId;
        private String workspaceId;
        private String campaignId;
        private NextBestActionType actionType;
        private String title;
        private String description;
        private Map<String, Object> parameters = Map.of();
        private double confidenceScore;
        private String rationale;
        private NextBestActionStatus status;
        private String rejectionReason;
        private String executedBy;
        private Instant createdAt;
        private Instant processedAt;
        private Instant expiresAt;

        public Builder id(String id) { this.id = id; return this; }
        public Builder tenantId(String t) { this.tenantId = t; return this; }
        public Builder workspaceId(String w) { this.workspaceId = w; return this; }
        public Builder campaignId(String c) { this.campaignId = c; return this; }
        public Builder actionType(NextBestActionType a) { this.actionType = a; return this; }
        public Builder title(String t) { this.title = t; return this; }
        public Builder description(String d) { this.description = d; return this; }
        public Builder parameters(Map<String, Object> p) { this.parameters = p; return this; }
        public Builder confidenceScore(double s) { this.confidenceScore = s; return this; }
        public Builder rationale(String r) { this.rationale = r; return this; }
        public Builder status(NextBestActionStatus s) { this.status = s; return this; }
        public Builder rejectionReason(String r) { this.rejectionReason = r; return this; }
        public Builder executedBy(String e) { this.executedBy = e; return this; }
        public Builder createdAt(Instant t) { this.createdAt = t; return this; }
        public Builder processedAt(Instant t) { this.processedAt = t; return this; }
        public Builder expiresAt(Instant t) { this.expiresAt = t; return this; }

        public NextBestActionRecommendation build() {
            Objects.requireNonNull(status, "status must not be null");
            if (id == null || id.isBlank()) throw new IllegalArgumentException("id must not be blank");
            if (tenantId == null || tenantId.isBlank()) throw new IllegalArgumentException("tenantId must not be blank");
            if (workspaceId == null || workspaceId.isBlank()) throw new IllegalArgumentException("workspaceId must not be blank");
            Objects.requireNonNull(actionType, "actionType must not be null");
            Objects.requireNonNull(parameters, "parameters must not be null");
            if (confidenceScore < 0.0 || confidenceScore > 1.0) throw new IllegalArgumentException("confidenceScore must be between 0.0 and 1.0");
            Objects.requireNonNull(createdAt, "createdAt must not be null");
            return new NextBestActionRecommendation(this);
        }
    }
}
