package com.ghatana.digitalmarketing.domain.content;

/**
 * Section identifiers for email follow-up draft content generated by DMOS.
 *
 * <p>Each value maps to a named {@link ContentBlock} within a {@link ContentVersion}.
 * The deterministic generator populates all mandatory sections and marks
 * any compliance or unsubscribe section that requires compliance review.</p>
 *
 * @doc.type enum
 * @doc.purpose Identifies the structural sections of a DMOS email follow-up draft
 * @doc.layer product
 * @doc.pattern StatePattern
 */
public enum EmailSection {

    /** Email subject line — must be ≤ 60 characters per common client limits. */
    SUBJECT_LINE,

    /** Personalised greeting or salutation. */
    GREETING,

    /** Primary body copy, including the core offer or value proposition. */
    BODY_COPY,

    /** Call-to-action text or button label. */
    CALL_TO_ACTION,

    /** Mandatory unsubscribe / opt-out instruction placeholder. */
    UNSUBSCRIBE_NOTICE,

    /** Compliance disclosures and required legal notices appended to the email. */
    COMPLIANCE_NOTES
}
