package com.ghatana.digitalmarketing.domain.content;

import java.time.Instant;
import java.util.Objects;

/**
 * Metadata describing how a content version was generated by an AI or automated system.
 *
 * <p>Provides provenance information for compliance, auditing, and reproducibility.</p>
 *
 * @doc.type class
 * @doc.purpose DMOS AI generator metadata for content version provenance
 * @doc.layer product
 * @doc.pattern ValueObject
 */
public record GeneratorMetadata(
        String modelVersion,
        String promptVersion,
        String sourceStrategy,
        Instant generatedAt) {

    /**
     * Compact constructor — validates all fields.
     */
    public GeneratorMetadata {
        Objects.requireNonNull(modelVersion, "modelVersion must not be null");
        Objects.requireNonNull(promptVersion, "promptVersion must not be null");
        Objects.requireNonNull(sourceStrategy, "sourceStrategy must not be null");
        Objects.requireNonNull(generatedAt, "generatedAt must not be null");
        if (modelVersion.isBlank()) throw new IllegalArgumentException("modelVersion must not be blank");
        if (promptVersion.isBlank()) throw new IllegalArgumentException("promptVersion must not be blank");
        if (sourceStrategy.isBlank()) throw new IllegalArgumentException("sourceStrategy must not be blank");
    }
}
