package com.ghatana.orchestrator.deployment.contract;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Value;

/**
 * Contract for pipeline deployment response.
 *
 * <p><b>Purpose</b><br>
 * Encapsulates deployment result (deploymentId, status, pipelineId, tenantId, error, runId)
 * returned from orchestrator deployment endpoint to clients. The runId references the governed
 * Kernel lifecycle run for traceability and evidence correlation.
 *
 * <p><b>Usage</b><br>
 * <pre>{@code
 * DeploymentResponse response = DeploymentResponse.builder()
 *     .deploymentId("deploy-12345")
 *     .pipelineId("fraud-detection-pipeline")
 *     .tenantId("acme-corp")
 *     .status("DEPLOYED")
 *     .runId("kernel-run-67890")
 *     .build();
 * }</pre>
 *
 * @doc.type class
 * @doc.purpose Deployment response contract with Kernel lifecycle integration
 * @doc.layer contracts
 * @doc.pattern Value Object
 */
@Value
@Builder
@AllArgsConstructor
public class DeploymentResponse {
    /**
     * Unique deployment identifier (generated by orchestrator).
     * Non-null, non-empty.
     */
    private final String deploymentId;

    /**
     * Pipeline identifier that was deployed.
     * Non-null, non-empty.
     */
    private final String pipelineId;

    /**
     * Tenant identifier for multi-tenancy.
     * Non-null, non-empty.
     */
    private final String tenantId;

    /**
     * Deployment status (DEPLOYED, UPDATED, UNDEPLOYED, FAILED).
     * Enum: "DEPLOYED", "UPDATED", "UNDEPLOYED", "FAILED".
     * Non-null.
     */
    private final String status;

    /**
     * Error message if deployment failed.
     * Null on success, contains error details on failure.
     */
    private final String error;

    /**
     * Timestamp when deployment was processed (ISO-8601 format).
     * Can be null if not yet set.
     */
    private final String timestamp;

    /**
     * Kernel lifecycle run ID for traceability and evidence correlation.
     * References the governed Kernel lifecycle run that was submitted for this deployment.
     * Null if the deployment did not go through the Kernel lifecycle system.
     */
    private final String runId;

    /**
     * Check if deployment succeeded.
     *
     * @return true if status is DEPLOYED, UPDATED, or UNDEPLOYED; false if FAILED
     */
    public boolean isSuccess() {
        return status != null && (status.equals("DEPLOYED") || status.equals("UPDATED") || status.equals("UNDEPLOYED"));
    }

    /**
     * Check if deployment failed.
     *
     * @return true if status is FAILED, false otherwise
     */
    public boolean isFailed() {
        return status != null && status.equals("FAILED");
    }
}
