/**
 * Artifact Source Indicator Module
 *
 * @doc.type component
 * @doc.purpose Display visible non-authoritative indicator for local-only/recovery artifact drafts
 * @doc.layer product
 * @doc.pattern Widget
 */

import React from 'react';
import { AlertTriangle, Database, RefreshCw } from 'lucide-react';
import { Typography } from '@ghatana/design-system';
import type { PageArtifactSource } from '../pageArtifactDocument';

export interface ArtifactSourceIndicatorProps {
  readonly source: PageArtifactSource;
  readonly syncStatus?: 'dirty' | 'saving' | 'synced' | 'error' | 'offline';
}

export function ArtifactSourceIndicator({
  source,
  syncStatus,
}: ArtifactSourceIndicatorProps): React.JSX.Element | null {
  const isLocalOnly = source === 'local-draft' || source === 'recovered-draft';
  const isRecovered = source === 'recovered-draft';

  if (!isLocalOnly && syncStatus !== 'offline') {
    return null;
  }

  const getIndicatorColor = () => {
    if (isRecovered) {
      return 'border-orange-200 bg-orange-50 dark:border-orange-900/50 dark:bg-orange-950/20';
    }
    if (syncStatus === 'offline') {
      return 'border-yellow-200 bg-yellow-50 dark:border-yellow-900/50 dark:bg-yellow-950/20';
    }
    return 'border-gray-200 bg-gray-50 dark:border-gray-900/50 dark:bg-gray-950/20';
  };

  const getIndicatorIcon = () => {
    if (isRecovered) {
      return <RefreshCw className="h-4 w-4 text-orange-600 dark:text-orange-400" />;
    }
    if (syncStatus === 'offline') {
      return <Database className="h-4 w-4 text-yellow-600 dark:text-yellow-400" />;
    }
    return <AlertTriangle className="h-4 w-4 text-gray-600 dark:text-gray-400" />;
  };

  const getIndicatorText = () => {
    if (isRecovered) {
      return 'Recovered Draft - Local Only';
    }
    if (syncStatus === 'offline') {
      return 'Offline Mode - Local Draft';
    }
    return 'Local Draft - Not Synced';
  };

  const getIndicatorDescription = () => {
    if (isRecovered) {
      return 'This document was recovered from local storage after a server failure. It is not the authoritative production version. Sync with the server to restore the latest version.';
    }
    if (syncStatus === 'offline') {
      return 'Working in offline mode. Changes are saved locally but not synced to the server. They will sync when connection is restored.';
    }
    return 'This is a local draft that has not been synced to the server. It is not the authoritative production version.';
  };

  return (
    <div className={`rounded border p-3 ${getIndicatorColor()}`}>
      <div className="flex items-center gap-2">
        {getIndicatorIcon()}
        <Typography variant="body1" className="font-medium">
          {getIndicatorText()}
        </Typography>
      </div>

      <Typography variant="body2" className="mt-2 text-sm text-gray-700 dark:text-gray-300">
        {getIndicatorDescription()}
      </Typography>

      {isRecovered && (
        <div className="mt-2 flex items-center gap-1 text-xs text-orange-700 dark:text-orange-300">
          <AlertTriangle className="h-3 w-3" />
          <span>Explicit sync required before any production actions</span>
        </div>
      )}
    </div>
  );
}

/**
 * Check if an artifact source is non-authoritative (local-only or recovery)
 */
export function isNonAuthoritativeSource(source: PageArtifactSource): boolean {
  return source === 'local-draft' || source === 'recovered-draft';
}

/**
 * Get a human-readable description of the artifact source
 */
export function getSourceDescription(source: PageArtifactSource): string {
  switch (source) {
    case 'created-in-builder':
      return 'Created directly in the builder';
    case 'decompiled':
      return 'Decompiled from existing code';
    case 'imported':
      return 'Imported from another source';
    case 'generated':
      return 'Generated by AI';
    case 'server':
      return 'Server-authoritative document';
    case 'local-draft':
      return 'Local draft (recovery-only, never becomes production truth)';
    case 'recovered-draft':
      return 'Recovered from local storage after server failure (explicit UX required)';
  }
}
