// Auto-generated from route-compatibility-registry.yaml by generate-route-security-metadata.mjs
// DC-P1-07: Legacy route compatibility metadata - do not edit manually

export interface LegacyRouteMapping {
  path: string;
  canonical: string;
  methods: string[];
  deprecatedSince: string;
  retirementTarget: string;
  featureFlag: string;
}

export const legacyRouteMappings: LegacyRouteMapping[] = [
  {
    path: '"/api/v1/memory/',
    canonical: '"/api/v1/action/memory/',
    methods: ['DELETE'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/pipelines/',
    canonical: '"/api/v1/action/pipelines/',
    methods: ['DELETE'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/agents/catalog"',
    canonical: '"/api/v1/action/agents/catalog"',
    methods: ['GET'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/agents/catalog/',
    canonical: '"/api/v1/action/agents/catalog/',
    methods: ['GET'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/agents/catalog/',
    canonical: '"/api/v1/action/agents/catalog/',
    methods: ['GET'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/autonomy/domains"',
    canonical: '"/api/v1/action/autonomy/domains"',
    methods: ['GET'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/autonomy/domains/',
    canonical: '"/api/v1/action/autonomy/domains/',
    methods: ['GET'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/autonomy/domains/',
    canonical: '"/api/v1/action/autonomy/domains/',
    methods: ['GET'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/autonomy/level"',
    canonical: '"/api/v1/action/autonomy/level"',
    methods: ['GET'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/autonomy/logs"',
    canonical: '"/api/v1/action/autonomy/logs"',
    methods: ['GET'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/autonomy/plan/',
    canonical: '"/api/v1/action/autonomy/plan/',
    methods: ['GET'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/autonomy/plan/',
    canonical: '"/api/v1/action/autonomy/plan/',
    methods: ['GET'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/executions/',
    canonical: '"/api/v1/action/executions/',
    methods: ['GET'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/executions/',
    canonical: '"/api/v1/action/executions/',
    methods: ['GET'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/executions/',
    canonical: '"/api/v1/action/executions/',
    methods: ['GET'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/executions/',
    canonical: '"/api/v1/action/executions/',
    methods: ['GET'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/executions/',
    canonical: '"/api/v1/action/executions/',
    methods: ['GET'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/executions/',
    canonical: '"/api/v1/action/executions/',
    methods: ['GET'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/memory"',
    canonical: '"/api/v1/action/memory"',
    methods: ['GET'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/memory/',
    canonical: '"/api/v1/action/memory/',
    methods: ['GET'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/memory/',
    canonical: '"/api/v1/action/memory/',
    methods: ['GET'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/pipelines"',
    canonical: '"/api/v1/action/pipelines"',
    methods: ['GET'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/pipelines/',
    canonical: '"/api/v1/action/pipelines/',
    methods: ['GET'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/pipelines/',
    canonical: '"/api/v1/action/pipelines/',
    methods: ['GET'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/pipelines/',
    canonical: '"/api/v1/action/pipelines/',
    methods: ['GET'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/pipelines/',
    canonical: '"/api/v1/action/pipelines/',
    methods: ['GET'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/plugins"',
    canonical: '"/api/v1/action/plugins"',
    methods: ['GET'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/plugins/',
    canonical: '"/api/v1/action/plugins/',
    methods: ['GET'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/plugins/',
    canonical: '"/api/v1/action/plugins/',
    methods: ['GET'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/plugins/',
    canonical: '"/api/v1/action/plugins/',
    methods: ['GET'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/plugins/',
    canonical: '"/api/v1/action/plugins/',
    methods: ['GET'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/plugins/marketplace"',
    canonical: '"/api/v1/action/plugins/marketplace"',
    methods: ['GET'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/autonomy/feedback-policy"',
    canonical: '"/api/v1/action/autonomy/feedback-policy"',
    methods: ['POST'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/executions/',
    canonical: '"/api/v1/action/executions/',
    methods: ['POST'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/executions/',
    canonical: '"/api/v1/action/executions/',
    methods: ['POST'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/executions/',
    canonical: '"/api/v1/action/executions/',
    methods: ['POST'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/executions/',
    canonical: '"/api/v1/action/executions/',
    methods: ['POST'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/executions/',
    canonical: '"/api/v1/action/executions/',
    methods: ['POST'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/executions/',
    canonical: '"/api/v1/action/executions/',
    methods: ['POST'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/executions/',
    canonical: '"/api/v1/action/executions/',
    methods: ['POST'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/executions/',
    canonical: '"/api/v1/action/executions/',
    methods: ['POST'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/executions/',
    canonical: '"/api/v1/action/executions/',
    methods: ['POST'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/executions/',
    canonical: '"/api/v1/action/executions/',
    methods: ['POST'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/memory/',
    canonical: '"/api/v1/action/memory/',
    methods: ['POST'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/memory/',
    canonical: '"/api/v1/action/memory/',
    methods: ['POST'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/pipelines"',
    canonical: '"/api/v1/action/pipelines"',
    methods: ['POST'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/pipelines/',
    canonical: '"/api/v1/action/pipelines/',
    methods: ['POST'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/pipelines/',
    canonical: '"/api/v1/action/pipelines/',
    methods: ['POST'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/pipelines/',
    canonical: '"/api/v1/action/pipelines/',
    methods: ['POST'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/pipelines/',
    canonical: '"/api/v1/action/pipelines/',
    methods: ['POST'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/pipelines/draft"',
    canonical: '"/api/v1/action/pipelines/draft"',
    methods: ['POST'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/plugins/',
    canonical: '"/api/v1/action/plugins/',
    methods: ['POST'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/plugins/',
    canonical: '"/api/v1/action/plugins/',
    methods: ['POST'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/plugins/',
    canonical: '"/api/v1/action/plugins/',
    methods: ['POST'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/plugins/',
    canonical: '"/api/v1/action/plugins/',
    methods: ['POST'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/plugins/',
    canonical: '"/api/v1/action/plugins/',
    methods: ['POST'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/plugins/',
    canonical: '"/api/v1/action/plugins/',
    methods: ['POST'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/plugins/',
    canonical: '"/api/v1/action/plugins/',
    methods: ['POST'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/plugins/',
    canonical: '"/api/v1/action/plugins/',
    methods: ['POST'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/plugins/',
    canonical: '"/api/v1/action/plugins/',
    methods: ['POST'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/plugins/',
    canonical: '"/api/v1/action/plugins/',
    methods: ['POST'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/autonomy/level"',
    canonical: '"/api/v1/action/autonomy/level"',
    methods: ['PUT'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/memory/',
    canonical: '"/api/v1/action/memory/',
    methods: ['PUT'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '"/api/v1/pipelines/',
    canonical: '"/api/v1/action/pipelines/',
    methods: ['PUT'],
    deprecatedSince: '2026-03-27',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
];