// Auto-generated from route-compatibility-registry.yaml by generate-route-security-metadata.mjs
// DC-P1-07: Legacy route compatibility metadata - do not edit manually

export interface LegacyRouteMapping {
  path: string;
  canonical: string;
  methods: string[];
  deprecatedSince: string;
  retirementTarget: string;
  featureFlag: string;
}

export const legacyRouteMappings: LegacyRouteMapping[] = [
  {
    path: '/api/v1/agents/catalog',
    canonical: '/api/v1/action/agents/catalog',
    methods: ['GET'],
    deprecatedSince: '2026-05-20',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '/api/v1/agents/catalog/:id',
    canonical: '/api/v1/action/agents/catalog/:id',
    methods: ['GET'],
    deprecatedSince: '2026-05-20',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '/api/v1/autonomy/domains',
    canonical: '/api/v1/action/autonomy/domains',
    methods: ['GET'],
    deprecatedSince: '2026-05-20',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '/api/v1/autonomy/domains/:domain',
    canonical: '/api/v1/action/autonomy/domains/:domain',
    methods: ['GET'],
    deprecatedSince: '2026-05-20',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '/api/v1/autonomy/level',
    canonical: '/api/v1/action/autonomy/level',
    methods: ['GET'],
    deprecatedSince: '2026-05-20',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '/api/v1/autonomy/logs',
    canonical: '/api/v1/action/autonomy/logs',
    methods: ['GET'],
    deprecatedSince: '2026-05-20',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '/api/v1/autonomy/plan/:actionType',
    canonical: '/api/v1/action/autonomy/plan/:actionType',
    methods: ['GET'],
    deprecatedSince: '2026-05-20',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '/api/v1/executions/:executionId',
    canonical: '/api/v1/action/executions/:executionId',
    methods: ['GET'],
    deprecatedSince: '2026-05-20',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '/api/v1/executions/:executionId/checkpoints',
    canonical: '/api/v1/action/executions/:executionId/checkpoints',
    methods: ['GET'],
    deprecatedSince: '2026-05-20',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '/api/v1/executions/:executionId/logs',
    canonical: '/api/v1/action/executions/:executionId/logs',
    methods: ['GET'],
    deprecatedSince: '2026-05-20',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '/api/v1/plugins',
    canonical: '/api/v1/action/plugins',
    methods: ['GET'],
    deprecatedSince: '2026-05-20',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '/api/v1/plugins/:id',
    canonical: '/api/v1/action/plugins/:id',
    methods: ['GET'],
    deprecatedSince: '2026-05-20',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '/api/v1/plugins/:id/sandbox',
    canonical: '/api/v1/action/plugins/:id/sandbox',
    methods: ['GET'],
    deprecatedSince: '2026-05-20',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '/api/v1/plugins/marketplace',
    canonical: '/api/v1/action/plugins/marketplace',
    methods: ['GET'],
    deprecatedSince: '2026-05-20',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '/api/v1/autonomy/feedback-policy',
    canonical: '/api/v1/action/autonomy/feedback-policy',
    methods: ['POST'],
    deprecatedSince: '2026-05-20',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '/api/v1/executions/:executionId/cancel',
    canonical: '/api/v1/action/executions/:executionId/cancel',
    methods: ['POST'],
    deprecatedSince: '2026-05-20',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '/api/v1/executions/:executionId/checkpoint',
    canonical: '/api/v1/action/executions/:executionId/checkpoint',
    methods: ['POST'],
    deprecatedSince: '2026-05-20',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '/api/v1/executions/:executionId/restore',
    canonical: '/api/v1/action/executions/:executionId/restore',
    methods: ['POST'],
    deprecatedSince: '2026-05-20',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '/api/v1/executions/:executionId/retry',
    canonical: '/api/v1/action/executions/:executionId/retry',
    methods: ['POST'],
    deprecatedSince: '2026-05-20',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '/api/v1/executions/:executionId/rollback',
    canonical: '/api/v1/action/executions/:executionId/rollback',
    methods: ['POST'],
    deprecatedSince: '2026-05-20',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '/api/v1/pipelines/:pipelineId/optimise-hint',
    canonical: '/api/v1/action/pipelines/:pipelineId/optimise-hint',
    methods: ['POST'],
    deprecatedSince: '2026-05-20',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '/api/v1/pipelines/draft',
    canonical: '/api/v1/action/pipelines/draft',
    methods: ['POST'],
    deprecatedSince: '2026-05-20',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '/api/v1/plugins/:id/conformance',
    canonical: '/api/v1/action/plugins/:id/conformance',
    methods: ['POST'],
    deprecatedSince: '2026-05-20',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '/api/v1/plugins/:id/disable',
    canonical: '/api/v1/action/plugins/:id/disable',
    methods: ['POST'],
    deprecatedSince: '2026-05-20',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '/api/v1/plugins/:id/enable',
    canonical: '/api/v1/action/plugins/:id/enable',
    methods: ['POST'],
    deprecatedSince: '2026-05-20',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '/api/v1/plugins/:id/upgrade',
    canonical: '/api/v1/action/plugins/:id/upgrade',
    methods: ['POST'],
    deprecatedSince: '2026-05-20',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '/api/v1/plugins/:id/validate',
    canonical: '/api/v1/action/plugins/:id/validate',
    methods: ['POST'],
    deprecatedSince: '2026-05-20',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
  {
    path: '/api/v1/autonomy/level',
    canonical: '/api/v1/action/autonomy/level',
    methods: ['PUT'],
    deprecatedSince: '2026-05-20',
    retirementTarget: '2026-12-31',
    featureFlag: 'DataCloudFeature.LEGACY_ACTION_ROUTES',
  },
];