// Auto-generated from data-cloud.yaml + action-plane.yaml by generate-route-security-metadata.mjs
// DC-P1-07: Do not edit manually - regenerate with the script

export interface RouteCapability {
  path: string;
  method: string;
  sensitivity: 'PUBLIC' | 'INTERNAL' | 'SENSITIVE' | 'CRITICAL';
  accessLevel: 'VIEWER' | 'OPERATOR' | 'AUDITOR' | 'ADMIN';
  requiresAuth: boolean;
  tenantRequired: boolean;
}

export const routeCapabilities: RouteCapability[] = [
  {
    path: '/health',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: false,
    tenantRequired: false,
  },
  {
    path: '/health/detail',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: false,
    tenantRequired: false,
  },
  {
    path: '/health/deep',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: false,
    tenantRequired: false,
  },
  {
    path: '/ready',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: false,
    tenantRequired: false,
  },
  {
    path: '/live',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: false,
    tenantRequired: false,
  },
  {
    path: '/info',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: false,
    tenantRequired: false,
  },
  {
    path: '/metrics',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: false,
    tenantRequired: false,
  },
  {
    path: '/api/v1/entities/{collection}',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'OPERATOR',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/entities/{collection}',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/entities/{collection}/{id}',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/entities/{collection}/{id}',
    method: 'DELETE',
    sensitivity: 'INTERNAL',
    accessLevel: 'ADMIN',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/events',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'OPERATOR',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/events',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/alerts',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/alerts/{alertId}/acknowledge',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'OPERATOR',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/alerts/{alertId}/resolve',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'OPERATOR',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/alerts/{id}/escalate',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'OPERATOR',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/alerts/{id}/auto-remediate',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'OPERATOR',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/alerts/{id}/remediate',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'OPERATOR',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/alerts/{id}/remediate/rollback',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'OPERATOR',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/alerts/{id}/remediations',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/alerts/groups',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/alerts/groups/{groupId}/resolve',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'OPERATOR',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/alerts/suggestions',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/alerts/suggestions/{suggestionId}/apply',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/alerts/rules',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'OPERATOR',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/alerts/rules',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'OPERATOR',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/alerts/rules/{ruleId}',
    method: 'PUT',
    sensitivity: 'INTERNAL',
    accessLevel: 'OPERATOR',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/alerts/rules/{ruleId}',
    method: 'DELETE',
    sensitivity: 'INTERNAL',
    accessLevel: 'OPERATOR',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/alerts/stream',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/compliance/legal-holds',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/compliance/legal-holds',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/compliance/legal-holds/{id}/extend',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/compliance/legal-holds/{id}/release',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/compliance/evidence-package',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/compliance/posture',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/sovereign/profile',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/sovereign/profile',
    method: 'PUT',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/sovereign/models',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/sovereign/audit',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/sovereign/backup',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/sovereign/backup',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/sovereign/restore',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/sovereign/data-subject-controls',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/sovereign/data-subject-controls',
    method: 'PUT',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/sovereign/conformance',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/checkpoints',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/checkpoints',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/checkpoints/{checkpointId}',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/checkpoints/{checkpointId}',
    method: 'DELETE',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/conformance',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/conformance/entity-store',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/conformance/event-log-store',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/sovereign/data-residency',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/sovereign/validate-transfer',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/sovereign/region-policy',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/brain/health',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: false,
    tenantRequired: false,
  },
  {
    path: '/api/v1/brain/config',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/brain/stats',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/brain/workspace',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/brain/workspace/stream',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/brain/attention/elevate',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/brain/attention/thresholds',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/brain/attention/thresholds',
    method: 'PUT',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/brain/patterns',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/brain/patterns/match',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/brain/salience/{itemId}',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/learning/stream',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/mastery/preview/decision',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/mastery/preview/retrieval',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/mastery/learning-deltas/{deltaId}/dry-run-promotion',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/mastery/obsolescence-events/process',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/analytics/query',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/analytics/queries/{queryId}',
    method: 'DELETE',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/analytics/aggregation',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/analytics/query/{queryId}',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/analytics/query/{queryId}/plan',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/analytics/explain',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/events/stream',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/events/notifications',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/events/notifications',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/entities/{collection}/search',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/entities/{collection}/export',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/entities/{collection}/anomalies',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'OPERATOR',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/anomalies',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/entities/{collection}/similar',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/entities/{collection}/validate',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'OPERATOR',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/entities/{collection}/validate/batch',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'OPERATOR',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/entities/{collection}/batch',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'OPERATOR',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/entities/{collection}/batch',
    method: 'DELETE',
    sensitivity: 'INTERNAL',
    accessLevel: 'ADMIN',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/entities/{collection}/stream',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/entities/{collection}/query/stream',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/entities/{collection}/suggest',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'OPERATOR',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/entities/{collection}/infer-schema',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'OPERATOR',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/analytics/suggest',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/analytics/automate',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/query/nlq',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/reports',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/reports',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/reports/{reportId}',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/workflows/analyze-risk',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/workflows/validate',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/governance/recommend',
    method: 'POST',
    sensitivity: 'CRITICAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/brain/explain',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/ai/context/rank',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/ai/quality/drift-detect',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/operations/anomaly-group',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/operations/forecast',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/ai/next-action',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/connectors/suggest-mapping',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/connectors/{connectorId}/sync-health',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/ai/quality-summary',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/ai/suggestions',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/ai/suggestions/{id}/apply',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/ai/correlations',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/ai/actions',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/ai/suggestions/{id}/feedback',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/ai/feedback',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/ai/advisories/workflows/{workflowId}',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/ai/advisories/quality/{collectionId}',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/ai/advisories/fabric/{collectionId}',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/models',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/models',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/models/{modelName}',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/models/{modelName}/promote',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'ADMIN',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/features',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/features/{entityId}',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/voice/intent',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/voice/intents',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/voice/intent/classify',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/governance/retention/classify',
    method: 'POST',
    sensitivity: 'CRITICAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/governance/retention/policy',
    method: 'GET',
    sensitivity: 'CRITICAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/governance/retention/purge',
    method: 'POST',
    sensitivity: 'CRITICAL',
    accessLevel: 'ADMIN',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/governance/privacy/redact',
    method: 'POST',
    sensitivity: 'CRITICAL',
    accessLevel: 'ADMIN',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/governance/privacy/verify',
    method: 'GET',
    sensitivity: 'CRITICAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/governance/privacy/pii-fields',
    method: 'GET',
    sensitivity: 'CRITICAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/governance/compliance/summary',
    method: 'GET',
    sensitivity: 'CRITICAL',
    accessLevel: 'AUDITOR',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/governance/inventory',
    method: 'GET',
    sensitivity: 'CRITICAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/governance/policies',
    method: 'POST',
    sensitivity: 'CRITICAL',
    accessLevel: 'ADMIN',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/governance/policies',
    method: 'GET',
    sensitivity: 'CRITICAL',
    accessLevel: 'ADMIN',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/governance/policies/simulate',
    method: 'POST',
    sensitivity: 'CRITICAL',
    accessLevel: 'ADMIN',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/governance/policies/{id}',
    method: 'GET',
    sensitivity: 'CRITICAL',
    accessLevel: 'ADMIN',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/governance/policies/{id}',
    method: 'PUT',
    sensitivity: 'CRITICAL',
    accessLevel: 'ADMIN',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/governance/policies/{id}',
    method: 'DELETE',
    sensitivity: 'CRITICAL',
    accessLevel: 'ADMIN',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/governance/policies/{id}/toggle',
    method: 'POST',
    sensitivity: 'CRITICAL',
    accessLevel: 'ADMIN',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/surfaces',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/surfaces/schema',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/settings',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/settings',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/settings/security',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'ADMIN',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/settings/security',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'ADMIN',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/settings/keys',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'ADMIN',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/settings/keys',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'ADMIN',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/settings/keys/{id}',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'ADMIN',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/settings/keys/{id}/rotate',
    method: 'POST',
    sensitivity: 'CRITICAL',
    accessLevel: 'ADMIN',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/settings/keys/{id}/revoke',
    method: 'DELETE',
    sensitivity: 'INTERNAL',
    accessLevel: 'ADMIN',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/settings/profile',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'ADMIN',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/settings/profile',
    method: 'PATCH',
    sensitivity: 'INTERNAL',
    accessLevel: 'ADMIN',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/settings/preferences',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'ADMIN',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/settings/preferences',
    method: 'PATCH',
    sensitivity: 'INTERNAL',
    accessLevel: 'ADMIN',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/settings/notifications',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'ADMIN',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/settings/notifications',
    method: 'PATCH',
    sensitivity: 'INTERNAL',
    accessLevel: 'ADMIN',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/settings/approval-request',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'ADMIN',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/settings/approvals',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'ADMIN',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/settings/approvals/{id}/approve',
    method: 'POST',
    sensitivity: 'CRITICAL',
    accessLevel: 'ADMIN',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/settings/approvals/{id}/reject',
    method: 'POST',
    sensitivity: 'CRITICAL',
    accessLevel: 'ADMIN',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/context',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/context',
    method: 'PUT',
    sensitivity: 'INTERNAL',
    accessLevel: 'OPERATOR',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/context/keys/{key}',
    method: 'DELETE',
    sensitivity: 'INTERNAL',
    accessLevel: 'ADMIN',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/context/snapshot',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/context/{collection}',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/context/{collection}/lineage/trust',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/context/{collection}/rag-policy-check',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/ai/rag-feedback',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/ai/memory/retention',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/mcp/v1/tools',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/mcp/v1/tools',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/context/{collection}/rag',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/data-products',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/data-products',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/data-products/{productId}/subscribe',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/data-products/{productId}/sla-monitor',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/data-products/{productId}/contract-check',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/connectors',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/connectors',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/connectors/{connectionId}',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/connectors/{connectionId}/test',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/connectors/{connectionId}/enable',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'ADMIN',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/connectors/{connectionId}/disable',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'ADMIN',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/connectors/{connectionId}/rotate-credentials',
    method: 'POST',
    sensitivity: 'CRITICAL',
    accessLevel: 'ADMIN',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/connectors/{connectionId}/health',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: false,
    tenantRequired: false,
  },
  {
    path: '/api/v1/connectors/{connectionId}/schema',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/connectors/{connectionId}/sync',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/connectors/{connectionId}/sync/status',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/data-fabric/connectors',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/data-fabric/connectors',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/data-fabric/connectors/{connectionId}',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/data-fabric/connectors/{connectionId}',
    method: 'PUT',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/data-fabric/connectors/{connectionId}',
    method: 'DELETE',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/data-fabric/connectors/{connectionId}/test',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/data-fabric/connectors/{connectionId}/disable',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'ADMIN',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/data-fabric/connectors/{connectionId}/enable',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'ADMIN',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/data-fabric/connectors/{connectionId}/statistics',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/data-fabric/connectors/{connectionId}/sync',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/data-fabric/metrics',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: false,
    tenantRequired: false,
  },
  {
    path: '/api/v1/user-activity/recent',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/user-activity/log',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/entities/{collection}/{id}/history',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/events/{offset}',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/queries/estimate',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/queries/federated',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/queries/explain',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/lineage/{collection}',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/lineage/{collection}/impact',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/data-quality/trust-scores',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/collections',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/collections/{collection}/metadata',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/collections/{id}/cost-report',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/collections/{id}/migrate',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/action/agents/catalog',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/action/agents/catalog/{id}',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/action/autonomy/domains',
    method: 'GET',
    sensitivity: 'SENSITIVE',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/action/autonomy/domains/{domain}',
    method: 'GET',
    sensitivity: 'SENSITIVE',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/action/autonomy/feedback-policy',
    method: 'POST',
    sensitivity: 'CRITICAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/action/autonomy/level',
    method: 'GET',
    sensitivity: 'SENSITIVE',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/action/autonomy/level',
    method: 'PUT',
    sensitivity: 'CRITICAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/action/autonomy/logs',
    method: 'GET',
    sensitivity: 'SENSITIVE',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/action/autonomy/plan/{actionType}',
    method: 'GET',
    sensitivity: 'SENSITIVE',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/action/executions/{executionId}',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/action/executions/{executionId}/cancel',
    method: 'POST',
    sensitivity: 'CRITICAL',
    accessLevel: 'OPERATOR',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/action/executions/{executionId}/checkpoint',
    method: 'POST',
    sensitivity: 'SENSITIVE',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/action/executions/{executionId}/checkpoints',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/action/executions/{executionId}/logs',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/action/executions/{executionId}/restore',
    method: 'POST',
    sensitivity: 'CRITICAL',
    accessLevel: 'OPERATOR',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/action/executions/{executionId}/retry',
    method: 'POST',
    sensitivity: 'SENSITIVE',
    accessLevel: 'OPERATOR',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/action/executions/{executionId}/rollback',
    method: 'POST',
    sensitivity: 'CRITICAL',
    accessLevel: 'OPERATOR',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/action/learning/review',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/action/learning/review/{reviewId}/approve',
    method: 'POST',
    sensitivity: 'CRITICAL',
    accessLevel: 'ADMIN',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/action/learning/review/{reviewId}/reject',
    method: 'POST',
    sensitivity: 'CRITICAL',
    accessLevel: 'ADMIN',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/action/learning/status',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/action/learning/trigger',
    method: 'POST',
    sensitivity: 'SENSITIVE',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/action/memory',
    method: 'GET',
    sensitivity: 'SENSITIVE',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/action/memory/{agentId}',
    method: 'GET',
    sensitivity: 'SENSITIVE',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/action/memory/{agentId}',
    method: 'POST',
    sensitivity: 'SENSITIVE',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/action/memory/{agentId}/{memoryId}',
    method: 'DELETE',
    sensitivity: 'CRITICAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/action/memory/{agentId}/{memoryId}/retain',
    method: 'PUT',
    sensitivity: 'CRITICAL',
    accessLevel: 'ADMIN',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/action/memory/{agentId}/{tier}',
    method: 'GET',
    sensitivity: 'SENSITIVE',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/action/memory/{agentId}/search',
    method: 'POST',
    sensitivity: 'SENSITIVE',
    accessLevel: 'OPERATOR',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/action/pipelines',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/action/pipelines',
    method: 'POST',
    sensitivity: 'SENSITIVE',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/action/pipelines/draft',
    method: 'POST',
    sensitivity: 'SENSITIVE',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/action/pipelines/{pipelineId}',
    method: 'DELETE',
    sensitivity: 'CRITICAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/action/pipelines/{pipelineId}',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/action/pipelines/{pipelineId}',
    method: 'PUT',
    sensitivity: 'SENSITIVE',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/action/pipelines/{pipelineId}/optimise-hint',
    method: 'POST',
    sensitivity: 'SENSITIVE',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/action/pipelines/{pipelineId}/execute',
    method: 'POST',
    sensitivity: 'SENSITIVE',
    accessLevel: 'OPERATOR',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/action/pipelines/{pipelineId}/executions',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/action/pipelines/{pipelineId}/executions/{executionId}',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/action/pipelines/{pipelineId}/executions/{executionId}/cancel',
    method: 'POST',
    sensitivity: 'CRITICAL',
    accessLevel: 'OPERATOR',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/action/pipelines/{pipelineId}/executions/{executionId}/logs',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/action/plugins',
    method: 'GET',
    sensitivity: 'SENSITIVE',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/action/plugins/{id}',
    method: 'GET',
    sensitivity: 'SENSITIVE',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/action/plugins/{id}/conformance',
    method: 'POST',
    sensitivity: 'CRITICAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/action/plugins/{id}/disable',
    method: 'POST',
    sensitivity: 'CRITICAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/action/plugins/{id}/enable',
    method: 'POST',
    sensitivity: 'CRITICAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/action/plugins/{id}/sandbox',
    method: 'GET',
    sensitivity: 'SENSITIVE',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/action/plugins/{id}/upgrade',
    method: 'POST',
    sensitivity: 'CRITICAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/action/plugins/{id}/validate',
    method: 'POST',
    sensitivity: 'CRITICAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: '/api/v1/action/plugins/marketplace',
    method: 'GET',
    sensitivity: 'SENSITIVE',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
];

export const sensitivityLevels = {
  INTERNAL: 'INTERNAL',
  CRITICAL: 'CRITICAL',
  SENSITIVE: 'SENSITIVE',
} as const;

export const accessLevels = {
  VIEWER: 'VIEWER',
  OPERATOR: 'OPERATOR',
  ADMIN: 'ADMIN',
  AUDITOR: 'AUDITOR',
} as const;