// Auto-generated from data-cloud.yaml + action-plane.yaml by generate-route-security-metadata.mjs
// DC-P1-07: Do not edit manually - regenerate with the script

export interface RouteCapability {
  path: string;
  method: string;
  sensitivity: 'PUBLIC' | 'INTERNAL' | 'SENSITIVE' | 'CRITICAL';
  accessLevel: 'VIEWER' | 'OPERATOR' | 'AUDITOR' | 'ADMIN';
  requiresAuth: boolean;
  tenantRequired: boolean;
}

export const routeCapabilities: RouteCapability[] = [
  {
    path: 'metrics',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: 'api/v1/entities/{collection}/{id}',
    method: 'DELETE',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: 'api/v1/events',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: 'api/v1/pipelines/{pipelineId}/executions/{executionId}/cancel',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: 'api/v1/alerts/stream',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: 'api/v1/compliance/posture',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: 'api/v1/sovereign/conformance',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: 'api/v1/sovereign/region-policy',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: 'api/v1/memory/{agentId}/{memoryId}/retain',
    method: 'PUT',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: 'api/v1/brain/salience/{itemId}',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: 'api/v1/mastery/obsolescence-events/process',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: 'api/v1/analytics/explain',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: 'api/v1/events/notifications',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: 'api/v1/entities/{collection}/infer-schema',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: 'api/v1/executions/{executionId}/restore',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: 'api/v1/governance/recommend',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: 'api/v1/ai/quality-summary',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: 'api/v1/ai/advisories/fabric/{collectionId}',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: 'api/v1/models/{modelName}/promote',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: 'api/v1/features/{entityId}',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: 'api/v1/voice/intent/classify',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: 'api/v1/governance/policies/{id}/toggle',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: 'api/v1/surfaces/schema',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: 'api/v1/autonomy/feedback-policy',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: 'api/v1/connectors/{connectionId}/sync/status',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: 'data-fabric/metrics',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: 'api/v1/user-activity/log',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: 'api/v1/agents/catalog/{id}',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: 'api/v1/plugins/{id}/upgrade',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: 'api/v1/events/{offset}',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: 'api/v1/collections/{id}/migrate',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: 'metrics/slo',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: 'api/v1/events/batch',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: 'api/v1/patterns/{patternId}/deactivate',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: 'api/v1/compliance/soc2/report',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: 'admin/capabilities/transforms',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: 'api/v1/event-types/{eventTypeId}/schemas/{schemaId}',
    method: 'DELETE',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: 'api/v1/bindings/{bindingId}/simulate',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: 'api/v1/runs/{runId}/cancel',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: 'api/v1/session',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: 'api/v1/sessions/cleanup',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: 'lifecycle/recertification/{recertificationId}',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: 'api/v1/catalog/marketplace/agents/{agentId}/reviews',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: 'api/v1/costs/summary',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: 'api/v1/ai/suggestions',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: 'api/v1/nlp/parse',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: 'api/v1/auth/roles',
    method: 'GET',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
  {
    path: 'api/v1/ai/suggestions/stages',
    method: 'POST',
    sensitivity: 'INTERNAL',
    accessLevel: 'VIEWER',
    requiresAuth: true,
    tenantRequired: true,
  },
];

export const sensitivityLevels = {
  INTERNAL: 'INTERNAL',
} as const;

export const accessLevels = {
  VIEWER: 'VIEWER',
} as const;