// Auto-generated from contracts by generate-route-security-metadata.mjs
// DC-P1-07: Runtime-truth posture metadata for route gating

export interface RuntimeTruthRoutePosture {
  path: string;
  method: string;
  sensitivity: string;
  requiresAuth: boolean;
  requiresTenant: boolean;
  requiredCapabilities: string[];
}

export const runtimeTruthRoutePosture: RuntimeTruthRoutePosture[] = [
  {
    path: 'metrics',
    method: 'GET',
    sensitivity: 'INTERNAL',
    requiresAuth: true,
    requiresTenant: true,
    requiredCapabilities: ['auth', 'tenant'],
  },
  {
    path: 'api/v1/entities/{collection}/{id}',
    method: 'DELETE',
    sensitivity: 'INTERNAL',
    requiresAuth: true,
    requiresTenant: true,
    requiredCapabilities: ['auth', 'tenant'],
  },
  {
    path: 'api/v1/events',
    method: 'GET',
    sensitivity: 'INTERNAL',
    requiresAuth: true,
    requiresTenant: true,
    requiredCapabilities: ['auth', 'tenant'],
  },
  {
    path: 'api/v1/pipelines/{pipelineId}/executions/{executionId}/cancel',
    method: 'POST',
    sensitivity: 'INTERNAL',
    requiresAuth: true,
    requiresTenant: true,
    requiredCapabilities: ['auth', 'tenant'],
  },
  {
    path: 'api/v1/alerts/stream',
    method: 'GET',
    sensitivity: 'INTERNAL',
    requiresAuth: true,
    requiresTenant: true,
    requiredCapabilities: ['auth', 'tenant'],
  },
  {
    path: 'api/v1/compliance/posture',
    method: 'GET',
    sensitivity: 'INTERNAL',
    requiresAuth: true,
    requiresTenant: true,
    requiredCapabilities: ['auth', 'tenant'],
  },
  {
    path: 'api/v1/sovereign/conformance',
    method: 'GET',
    sensitivity: 'INTERNAL',
    requiresAuth: true,
    requiresTenant: true,
    requiredCapabilities: ['auth', 'tenant'],
  },
  {
    path: 'api/v1/sovereign/region-policy',
    method: 'GET',
    sensitivity: 'INTERNAL',
    requiresAuth: true,
    requiresTenant: true,
    requiredCapabilities: ['auth', 'tenant'],
  },
  {
    path: 'api/v1/memory/{agentId}/{memoryId}/retain',
    method: 'PUT',
    sensitivity: 'INTERNAL',
    requiresAuth: true,
    requiresTenant: true,
    requiredCapabilities: ['auth', 'tenant'],
  },
  {
    path: 'api/v1/brain/salience/{itemId}',
    method: 'GET',
    sensitivity: 'INTERNAL',
    requiresAuth: true,
    requiresTenant: true,
    requiredCapabilities: ['auth', 'tenant'],
  },
  {
    path: 'api/v1/mastery/obsolescence-events/process',
    method: 'POST',
    sensitivity: 'INTERNAL',
    requiresAuth: true,
    requiresTenant: true,
    requiredCapabilities: ['auth', 'tenant'],
  },
  {
    path: 'api/v1/analytics/explain',
    method: 'POST',
    sensitivity: 'INTERNAL',
    requiresAuth: true,
    requiresTenant: true,
    requiredCapabilities: ['auth', 'tenant'],
  },
  {
    path: 'api/v1/events/notifications',
    method: 'GET',
    sensitivity: 'INTERNAL',
    requiresAuth: true,
    requiresTenant: true,
    requiredCapabilities: ['auth', 'tenant'],
  },
  {
    path: 'api/v1/entities/{collection}/infer-schema',
    method: 'POST',
    sensitivity: 'INTERNAL',
    requiresAuth: true,
    requiresTenant: true,
    requiredCapabilities: ['auth', 'tenant'],
  },
  {
    path: 'api/v1/executions/{executionId}/restore',
    method: 'POST',
    sensitivity: 'INTERNAL',
    requiresAuth: true,
    requiresTenant: true,
    requiredCapabilities: ['auth', 'tenant'],
  },
  {
    path: 'api/v1/governance/recommend',
    method: 'POST',
    sensitivity: 'INTERNAL',
    requiresAuth: true,
    requiresTenant: true,
    requiredCapabilities: ['auth', 'tenant'],
  },
  {
    path: 'api/v1/ai/quality-summary',
    method: 'GET',
    sensitivity: 'INTERNAL',
    requiresAuth: true,
    requiresTenant: true,
    requiredCapabilities: ['auth', 'tenant'],
  },
  {
    path: 'api/v1/ai/advisories/fabric/{collectionId}',
    method: 'GET',
    sensitivity: 'INTERNAL',
    requiresAuth: true,
    requiresTenant: true,
    requiredCapabilities: ['auth', 'tenant'],
  },
  {
    path: 'api/v1/models/{modelName}/promote',
    method: 'POST',
    sensitivity: 'INTERNAL',
    requiresAuth: true,
    requiresTenant: true,
    requiredCapabilities: ['auth', 'tenant'],
  },
  {
    path: 'api/v1/features/{entityId}',
    method: 'GET',
    sensitivity: 'INTERNAL',
    requiresAuth: true,
    requiresTenant: true,
    requiredCapabilities: ['auth', 'tenant'],
  },
  {
    path: 'api/v1/voice/intent/classify',
    method: 'POST',
    sensitivity: 'INTERNAL',
    requiresAuth: true,
    requiresTenant: true,
    requiredCapabilities: ['auth', 'tenant'],
  },
  {
    path: 'api/v1/governance/policies/{id}/toggle',
    method: 'POST',
    sensitivity: 'INTERNAL',
    requiresAuth: true,
    requiresTenant: true,
    requiredCapabilities: ['auth', 'tenant'],
  },
  {
    path: 'api/v1/surfaces/schema',
    method: 'GET',
    sensitivity: 'INTERNAL',
    requiresAuth: true,
    requiresTenant: true,
    requiredCapabilities: ['auth', 'tenant'],
  },
  {
    path: 'api/v1/autonomy/feedback-policy',
    method: 'POST',
    sensitivity: 'INTERNAL',
    requiresAuth: true,
    requiresTenant: true,
    requiredCapabilities: ['auth', 'tenant'],
  },
  {
    path: 'api/v1/connectors/{connectionId}/sync/status',
    method: 'GET',
    sensitivity: 'INTERNAL',
    requiresAuth: true,
    requiresTenant: true,
    requiredCapabilities: ['auth', 'tenant'],
  },
  {
    path: 'data-fabric/metrics',
    method: 'GET',
    sensitivity: 'INTERNAL',
    requiresAuth: true,
    requiresTenant: true,
    requiredCapabilities: ['auth', 'tenant'],
  },
  {
    path: 'api/v1/user-activity/log',
    method: 'POST',
    sensitivity: 'INTERNAL',
    requiresAuth: true,
    requiresTenant: true,
    requiredCapabilities: ['auth', 'tenant'],
  },
  {
    path: 'api/v1/agents/catalog/{id}',
    method: 'GET',
    sensitivity: 'INTERNAL',
    requiresAuth: true,
    requiresTenant: true,
    requiredCapabilities: ['auth', 'tenant'],
  },
  {
    path: 'api/v1/plugins/{id}/upgrade',
    method: 'POST',
    sensitivity: 'INTERNAL',
    requiresAuth: true,
    requiresTenant: true,
    requiredCapabilities: ['auth', 'tenant'],
  },
  {
    path: 'api/v1/events/{offset}',
    method: 'GET',
    sensitivity: 'INTERNAL',
    requiresAuth: true,
    requiresTenant: true,
    requiredCapabilities: ['auth', 'tenant'],
  },
  {
    path: 'api/v1/collections/{id}/migrate',
    method: 'POST',
    sensitivity: 'INTERNAL',
    requiresAuth: true,
    requiresTenant: true,
    requiredCapabilities: ['auth', 'tenant'],
  },
  {
    path: 'metrics/slo',
    method: 'GET',
    sensitivity: 'INTERNAL',
    requiresAuth: true,
    requiresTenant: true,
    requiredCapabilities: ['auth', 'tenant'],
  },
  {
    path: 'api/v1/events/batch',
    method: 'POST',
    sensitivity: 'INTERNAL',
    requiresAuth: true,
    requiresTenant: true,
    requiredCapabilities: ['auth', 'tenant'],
  },
  {
    path: 'api/v1/patterns/{patternId}/deactivate',
    method: 'POST',
    sensitivity: 'INTERNAL',
    requiresAuth: true,
    requiresTenant: true,
    requiredCapabilities: ['auth', 'tenant'],
  },
  {
    path: 'api/v1/compliance/soc2/report',
    method: 'GET',
    sensitivity: 'INTERNAL',
    requiresAuth: true,
    requiresTenant: true,
    requiredCapabilities: ['auth', 'tenant'],
  },
  {
    path: 'admin/capabilities/transforms',
    method: 'GET',
    sensitivity: 'INTERNAL',
    requiresAuth: true,
    requiresTenant: true,
    requiredCapabilities: ['auth', 'tenant'],
  },
  {
    path: 'api/v1/event-types/{eventTypeId}/schemas/{schemaId}',
    method: 'DELETE',
    sensitivity: 'INTERNAL',
    requiresAuth: true,
    requiresTenant: true,
    requiredCapabilities: ['auth', 'tenant'],
  },
  {
    path: 'api/v1/bindings/{bindingId}/simulate',
    method: 'POST',
    sensitivity: 'INTERNAL',
    requiresAuth: true,
    requiresTenant: true,
    requiredCapabilities: ['auth', 'tenant'],
  },
  {
    path: 'api/v1/runs/{runId}/cancel',
    method: 'POST',
    sensitivity: 'INTERNAL',
    requiresAuth: true,
    requiresTenant: true,
    requiredCapabilities: ['auth', 'tenant'],
  },
  {
    path: 'api/v1/session',
    method: 'POST',
    sensitivity: 'INTERNAL',
    requiresAuth: true,
    requiresTenant: true,
    requiredCapabilities: ['auth', 'tenant'],
  },
  {
    path: 'api/v1/sessions/cleanup',
    method: 'POST',
    sensitivity: 'INTERNAL',
    requiresAuth: true,
    requiresTenant: true,
    requiredCapabilities: ['auth', 'tenant'],
  },
  {
    path: 'lifecycle/recertification/{recertificationId}',
    method: 'GET',
    sensitivity: 'INTERNAL',
    requiresAuth: true,
    requiresTenant: true,
    requiredCapabilities: ['auth', 'tenant'],
  },
  {
    path: 'api/v1/catalog/marketplace/agents/{agentId}/reviews',
    method: 'POST',
    sensitivity: 'INTERNAL',
    requiresAuth: true,
    requiresTenant: true,
    requiredCapabilities: ['auth', 'tenant'],
  },
  {
    path: 'api/v1/costs/summary',
    method: 'GET',
    sensitivity: 'INTERNAL',
    requiresAuth: true,
    requiresTenant: true,
    requiredCapabilities: ['auth', 'tenant'],
  },
  {
    path: 'api/v1/ai/suggestions',
    method: 'GET',
    sensitivity: 'INTERNAL',
    requiresAuth: true,
    requiresTenant: true,
    requiredCapabilities: ['auth', 'tenant'],
  },
  {
    path: 'api/v1/nlp/parse',
    method: 'POST',
    sensitivity: 'INTERNAL',
    requiresAuth: true,
    requiresTenant: true,
    requiredCapabilities: ['auth', 'tenant'],
  },
  {
    path: 'api/v1/auth/roles',
    method: 'GET',
    sensitivity: 'INTERNAL',
    requiresAuth: true,
    requiresTenant: true,
    requiredCapabilities: ['auth', 'tenant'],
  },
  {
    path: 'api/v1/ai/suggestions/stages',
    method: 'POST',
    sensitivity: 'INTERNAL',
    requiresAuth: true,
    requiresTenant: true,
    requiredCapabilities: ['auth', 'tenant'],
  },
];