package com.ghatana.core.operator.adapter;

import com.ghatana.platform.domain.domain.event.*;
import com.ghatana.platform.workflow.operator.*;
import com.ghatana.platform.types.identity.OperatorId;
import com.ghatana.platform.testing.activej.EventloopTestBase;
import com.ghatana.virtualorg.agent.VirtualOrgAgent;
import com.ghatana.virtualorg.v1.*;
import io.activej.promise.Promise;
import io.micrometer.core.instrument.simple.SimpleMeterRegistry;
import org.junit.jupiter.api.*;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;

import java.util.*;

import static org.assertj.core.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

/**
 * Unit tests for AgentStreamOperatorAdapter.
 *
 * <p>Tests validate:
 * <ul>
 *   <li>Event → TaskRequestProto mapping</li>
 *   <li>TaskResponseProto → OperatorResult mapping</li>
 *   <li>AgentState → OperatorState health checks</li>
 *   <li>Lifecycle delegation (start/stop)</li>
 *   <li>Metrics merging (agent + operator)</li>
 *   <li>Capabilities and metadata</li>
 * </ul>
 */
@DisplayName("AgentStreamOperatorAdapter Tests")
class AgentStreamOperatorAdapterTest extends EventloopTestBase {

    @Mock
    private VirtualOrgAgent mockAgent;

    private SimpleMeterRegistry meterRegistry;
    private AgentStreamOperatorAdapter adapter;
    private AutoCloseable mocks;

    @BeforeEach
    void setUp() {
        mocks = MockitoAnnotations.openMocks(this);
        meterRegistry = new SimpleMeterRegistry();

        // Mock agent basics
        when(mockAgent.getRole()).thenReturn(VirtualOrgAgent.Role.CEO);
        when(mockAgent.getAuthority()).thenReturn(VirtualOrgAgent.DecisionAuthority.STRATEGIC);
        when(mockAgent.getTools()).thenReturn(Collections.emptyList());
        when(mockAgent.getState()).thenReturn(
            AgentStateProto.newBuilder()
                .setState(AgentStateProto.State.AGENT_STATE_IDLE)
                .setStatusMessage("Idle")
                .build()
        );
        when(mockAgent.getId()).thenReturn("agent-ceo-001");

        // Mock performance metrics
        when(mockAgent.getPerformance()).thenReturn(
            AgentPerformanceProto.newBuilder()
                .setTasksProcessed(0)
                .setErrorCount(0)
                .setAverageProcessingTimeMs(0)
                .build()
        );

        adapter = AgentStreamOperatorAdapterFactory.create(mockAgent, meterRegistry);
    }

    @AfterEach
    void tearDown() throws Exception {
        if (mocks != null) {
            mocks.close();
        }
    }

    // ========================================================================
    // CONSTRUCTION & METADATA TESTS
    // ========================================================================

    @Nested
    @DisplayName("Construction and Metadata Tests")
    class ConstructionTests {

        @Test
        @DisplayName("Should create adapter with auto-generated OperatorId")
        void shouldCreateAdapterWithAutoGeneratedId() {
            assertThat(adapter).isNotNull();
            assertThat(adapter.getId()).isNotNull();
            assertThat(adapter.getId().toString()).contains("virtualorg", "agent", "ceo", "1.0.0");
        }

        @Test
        @DisplayName("Should set correct operator type")
        void shouldSetCorrectOperatorType() {
            assertThat(adapter.getType()).isEqualTo(OperatorType.STREAM);
        }

        @Test
        @DisplayName("Should build operator name from agent role")
        void shouldBuildOperatorNameFromRole() {
            assertThat(adapter.getName()).contains("Virtual-Org", "CEO", "Agent");
        }

        @Test
        @DisplayName("Should include agent capabilities")
        void shouldIncludeAgentCapabilities() {
            ToolProto tool = ToolProto.newBuilder()
                .setName("code_review")
                .setDescription("Review code changes")
                .build();
            when(mockAgent.getTools()).thenReturn(List.of(tool));

            AgentStreamOperatorAdapter adapterWithTools =
                AgentStreamOperatorAdapterFactory.create(mockAgent, meterRegistry);

            List<String> caps = adapterWithTools.getCapabilities();
            assertThat(caps).contains(
                "agent.task_processing",
                "agent.decision_making",
                "agent.role.ceo",
                "tool.code_review"
            );
        }

        @Test
        @DisplayName("Should reject null agent")
        void shouldRejectNullAgent() {
            OperatorId id = OperatorId.of("test", "agent", "test", "1.0.0");
            assertThatThrownBy(() ->
                new AgentStreamOperatorAdapter(id, null, meterRegistry))
                .isInstanceOf(NullPointerException.class)
                .hasMessageContaining("VirtualOrgAgent must not be null");
        }
    }

    // ========================================================================
    // EVENT → TASK MAPPING TESTS
    // ========================================================================

    @Nested
    @DisplayName("Event to Task Mapping Tests")
    class EventToTaskMappingTests {

        @Test
        @DisplayName("Should map Event to TaskRequestProto correctly")
        void shouldMapEventToTask() {
            EventId eventId = EventId.create("evt-1", "agent.task.code_review", "1.0", "tenant-1");

            Map<String, Object> payload = new HashMap<>();
            payload.put("description", "Review PR #123");
            payload.put("pr_id", "123");
            payload.put("repository", "yappc/ghatana");

            GEvent event = GEvent.builder()
                .id(eventId)
                .time(EventTime.now())
                .payload(payload)
                .headers(Collections.emptyMap())
                .stats(EventStats.builder().build())
                .relations(EventRelations.builder().build())
                .build();

            TaskResponseProto mockResponse = TaskResponseProto.newBuilder()
                .setTaskId("evt-1")
                .setSuccess(true)
                .setResult("LGTM - approved")
                .build();
            when(mockAgent.processTask(any())).thenReturn(Promise.of(mockResponse));

            OperatorResult result = runPromise(() -> adapter.process(event));

            verify(mockAgent).processTask(argThat(taskRequest ->
                taskRequest.getTaskId().equals("evt-1") &&
                taskRequest.getDescription().contains("Review PR #123") &&
                taskRequest.getParametersMap().get("pr_id").equals("123") &&
                taskRequest.getParametersMap().get("repository").equals("yappc/ghatana")
            ));

            assertThat(result.isSuccess()).isTrue();
        }

        @Test
        @DisplayName("Should preserve correlation ID in task mapping")
        void shouldPreserveCorrelationId() {
            EventId eventId = EventId.create("evt-2", "agent.task", "1.0", "tenant-1");
            Map<String, String> headers = new HashMap<>();
            headers.put("correlationId", "corr-12345");
            headers.put("causationId", "cause-67890");

            GEvent event = GEvent.builder()
                .id(eventId)
                .time(EventTime.now())
                .payload(Collections.emptyMap())
                .headers(headers)
                .stats(EventStats.builder().build())
                .relations(EventRelations.builder().build())
                .build();

            when(mockAgent.processTask(any())).thenReturn(Promise.of(
                TaskResponseProto.newBuilder()
                    .setTaskId("task-1")
                    .setSuccess(true)
                    .setResult("done")
                    .build()
            ));

            runPromise(() -> adapter.process(event));

            verify(mockAgent).processTask(argThat(taskRequest ->
                taskRequest.getParametersMap().get("correlation_id").equals("corr-12345") &&
                taskRequest.getParametersMap().get("causation_id").equals("cause-67890")
            ));
        }

        @Test
        @DisplayName("Should use event type as description fallback")
        void shouldUseEventTypeAsFallback() {
            EventId eventId = EventId.create("evt-3", "agent.task.analyze_logs", "1.0", "tenant-1");
            GEvent event = GEvent.builder()
                .id(eventId)
                .time(EventTime.now())
                .payload(Collections.emptyMap())
                .headers(Collections.emptyMap())
                .stats(EventStats.builder().build())
                .relations(EventRelations.builder().build())
                .build();

            when(mockAgent.processTask(any())).thenReturn(Promise.of(
                TaskResponseProto.newBuilder()
                    .setTaskId("task-1")
                    .setSuccess(true)
                    .setResult("done")
                    .build()
            ));

            runPromise(() -> adapter.process(event));

            verify(mockAgent).processTask(argThat(taskRequest ->
                taskRequest.getDescription().contains("agent.task.analyze_logs")
            ));
        }
    }

    // ========================================================================
    // TASK RESPONSE → OPERATOR RESULT MAPPING TESTS
    // ========================================================================

    @Nested
    @DisplayName("Task Response Mapping Tests")
    class TaskResponseMappingTests {

        @Test
        @DisplayName("Should map successful TaskResponse to OperatorResult with output event")
        void shouldMapSuccessfulTaskResponse() {
            TaskResponseProto response = TaskResponseProto.newBuilder()
                .setTaskId("task-1")
                .setSuccess(true)
                .setResult("Code review completed: LGTM")
                .build();
            when(mockAgent.processTask(any())).thenReturn(Promise.of(response));

            EventId inputEventId = EventId.create("evt-4", "agent.task.code_review", "1.0", "tenant-1");
            GEvent inputEvent = GEvent.builder()
                .id(inputEventId)
                .time(EventTime.now())
                .payload(Map.of("description", "Review code"))
                .headers(Collections.emptyMap())
                .stats(EventStats.builder().build())
                .relations(EventRelations.builder().build())
                .build();

            OperatorResult result = runPromise(() -> adapter.process(inputEvent));

            assertThat(result.isSuccess()).isTrue();
            assertThat(result.getOutputEvents()).hasSize(1);

            Event outputEvent = result.getOutputEvents().get(0);
            assertThat(outputEvent.getType()).isEqualTo("agent.task.completed");
            assertThat(outputEvent.getTenantId()).isEqualTo("tenant-1");
            assertThat(outputEvent.getPayload("task_id")).isEqualTo("task-1");
            assertThat(outputEvent.getPayload("result")).isEqualTo("Code review completed: LGTM");
            assertThat(outputEvent.getPayload("agent_role")).asString().contains("CEO");
            assertThat(outputEvent.getPayload("original_event_id")).isEqualTo("evt-4");
        }

        @Test
        @DisplayName("Should map failed TaskResponse to OperatorResult with error")
        void shouldMapFailedTaskResponse() {
            TaskResponseProto response = TaskResponseProto.newBuilder()
                .setTaskId("task-1")
                .setSuccess(false)
                .setErrorMessage("LLM rate limit exceeded")
                .build();
            when(mockAgent.processTask(any())).thenReturn(Promise.of(response));

            GEvent inputEvent = GEvent.builder()
                .id(EventId.create("evt-5", "agent.task", "1.0", "tenant-1"))
                .time(EventTime.now())
                .payload(Collections.emptyMap())
                .headers(Collections.emptyMap())
                .stats(EventStats.builder().build())
                .relations(EventRelations.builder().build())
                .build();

            OperatorResult result = runPromise(() -> adapter.process(inputEvent));

            assertThat(result.isSuccess()).isFalse();
            assertThat(result.getErrorMessage()).contains("LLM rate limit exceeded");
        }

        @Test
        @DisplayName("Should preserve correlation chain in output event")
        void shouldPreserveCorrelationChain() {
            Map<String, String> headers = new HashMap<>();
            headers.put("correlationId", "corr-abc-123");

            EventId inputEventId = EventId.create("evt-6", "agent.task", "1.0", "tenant-1");
            GEvent inputEvent = GEvent.builder()
                .id(inputEventId)
                .time(EventTime.now())
                .payload(Collections.emptyMap())
                .headers(headers)
                .stats(EventStats.builder().build())
                .relations(EventRelations.builder().build())
                .build();

            when(mockAgent.processTask(any())).thenReturn(Promise.of(
                TaskResponseProto.newBuilder()
                    .setTaskId("task-1")
                    .setSuccess(true)
                    .setResult("done")
                    .build()
            ));

            OperatorResult result = runPromise(() -> adapter.process(inputEvent));

            Event outputEvent = result.getOutputEvents().get(0);
            assertThat(outputEvent.getCorrelationId()).isEqualTo("corr-abc-123");
            assertThat(outputEvent.getCausationId()).isEqualTo("evt-6");
        }
    }

    // ========================================================================
    // LIFECYCLE TESTS
    // ========================================================================

    @Nested
    @DisplayName("Lifecycle Tests")
    class LifecycleTests {

        @Test
        @DisplayName("Should delegate start() to agent")
        void shouldDelegateStart() {
            when(mockAgent.start()).thenReturn(Promise.complete());

            runPromise(() -> {
                adapter.initialize(OperatorConfig.builder().build());
                return adapter.start();
            });

            verify(mockAgent).start();
        }

        @Test
        @DisplayName("Should delegate stop() to agent shutdown")
        void shouldDelegateStop() {
            when(mockAgent.start()).thenReturn(Promise.complete());
            when(mockAgent.shutdown()).thenReturn(Promise.complete());

            runPromise(() -> {
                adapter.initialize(OperatorConfig.builder().build());
                adapter.start();
                return adapter.stop();
            });

            verify(mockAgent).shutdown();
        }

        @Test
        @DisplayName("Should be healthy when agent not failed")
        void shouldBeHealthyWhenAgentNotFailed() {
            when(mockAgent.getState()).thenReturn(
                AgentStateProto.newBuilder()
                    .setState(AgentStateProto.State.AGENT_STATE_IDLE)
                    .build()
            );
            assertThat(adapter.isHealthy()).isTrue();
        }

        @Test
        @DisplayName("Should be healthy when agent is busy")
        void shouldBeHealthyWhenAgentBusy() {
            when(mockAgent.getState()).thenReturn(
                AgentStateProto.newBuilder()
                    .setState(AgentStateProto.State.AGENT_STATE_BUSY)
                    .build()
            );
            assertThat(adapter.isHealthy()).isTrue();
        }

        @Test
        @DisplayName("Should be unhealthy when agent terminated")
        void shouldBeUnhealthyWhenAgentTerminated() {
            when(mockAgent.getState()).thenReturn(
                AgentStateProto.newBuilder()
                    .setState(AgentStateProto.State.AGENT_STATE_TERMINATED)
                    .build()
            );
            assertThat(adapter.isHealthy()).isFalse();
        }

        @Test
        @DisplayName("Should initialize without errors")
        void shouldInitializeWithoutErrors() {
            OperatorConfig config = OperatorConfig.builder().build();
            runPromise(() -> adapter.initialize(config));
            // No exception means success
        }
    }

    // ========================================================================
    // METRICS TESTS
    // ========================================================================

    @Nested
    @DisplayName("Metrics Tests")
    class MetricsTests {

        @Test
        @DisplayName("Should merge agent performance metrics")
        void shouldMergeAgentMetrics() {
            AgentPerformanceProto perf = AgentPerformanceProto.newBuilder()
                .setTasksProcessed(100)
                .setErrorCount(5)
                .setAverageProcessingTimeMs(250)
                .build();
            when(mockAgent.getPerformance()).thenReturn(perf);

            Map<String, Object> metrics = adapter.getMetrics();

            assertThat(metrics).containsEntry("agent.tasks_processed", 100L);
            assertThat(metrics).containsEntry("agent.error_count", 5L);
            assertThat(metrics).containsEntry("agent.avg_processing_time_ms", 250.0);
        }

        @Test
        @DisplayName("Should indicate operator is stateful")
        void shouldBeStateful() {
            assertThat(adapter.isStateful()).isTrue();
        }

        @Test
        @DisplayName("Should include AbstractOperator metrics")
        void shouldIncludeBaseMetrics() {
            Map<String, Object> metrics = adapter.getMetrics();
            assertThat(metrics).isNotEmpty();
        }
    }

    // ========================================================================
    // ERROR HANDLING TESTS
    // ========================================================================

    @Nested
    @DisplayName("Error Handling Tests")
    class ErrorHandlingTests {

        @Test
        @DisplayName("Should handle agent promise rejection")
        void shouldHandleAgentPromiseRejection() {
            when(mockAgent.processTask(any()))
                .thenReturn(Promise.ofException(new RuntimeException("Agent internal error")));

            GEvent event = GEvent.builder()
                .id(EventId.create("evt-7", "agent.task", "1.0", "tenant-1"))
                .time(EventTime.now())
                .payload(Collections.emptyMap())
                .headers(Collections.emptyMap())
                .stats(EventStats.builder().build())
                .relations(EventRelations.builder().build())
                .build();

            assertThatThrownBy(() -> runPromise(() -> adapter.process(event)))
                .isInstanceOf(RuntimeException.class)
                .hasMessageContaining("Agent internal error");
        }
    }
}
