/**
 * Content Studio Routes (Migrated)
 *
 * Fastify routes for Content Studio learning experience management.
 * Provides CRUD operations, AI generation, and validation endpoints.
 *
 * Migrated from legacy standalone content studio service.
 *
 * @doc.type module
 * @doc.purpose HTTP routes for Content Studio
 * @doc.layer product
 * @doc.pattern Route
 */

import type { FastifyInstance } from "fastify";
import { Prisma } from "@tutorputor/core/db";
import {
  getTenantId,
  getUserId,
  roleGuard,
} from "../../../core/http/requestContext.js";
import { z } from "zod";
import type {
  CreateExperienceRequest,
  GradeRange,
  ExperienceStatus,
} from "@tutorputor/contracts/v1/content-studio";
import type { HealthAwareContentStudioService } from "./service.js";
import type { AnimationSpec } from "../../animation-runtime/service.js";

// =============================================================================
// Types
// =============================================================================

type UpdateExperienceRequest = {
  title?: string;
  description?: string;
  status?: ExperienceStatus;
  estimatedTimeMinutes?: number;
  gradeRange?: GradeRange;
  userId?: string;
};

function toInputJsonValue(value: unknown): Prisma.InputJsonValue {
  return value as Prisma.InputJsonValue;
}

type GenerateClaimRequest = {
  maxClaims?: number;
  topic?: string;
};

type GenerateTaskRequest = Record<string, never>;

type RefineContentRequest = {
  refinementPrompt?: string;
  prompt?: string;
  userId?: string;
  sections?: ("claims" | "evidence" | "tasks" | "grade_adaptation")[];
};

type AdaptGradeRequest = {
  gradeRange?: GradeRange;
  targetGrade?: GradeRange;
  userId?: string;
};

type ValidateExperienceRequest = {
  userId?: string;
};

type ExperienceFilter = {
  status?: ExperienceStatus;
  gradeRange?: GradeRange;
  authorId?: string;
  page?: number;
  limit?: number;
  offset?: number;
};

type AnimationLinkRequest = {
  claimId?: string;
  animationId?: string;
  animationType?: string;
  autoGenerated?: boolean;
  concept?: string;
  difficulty?: string;
  estimatedDuration?: number;
  spec?: unknown;
};

type AnalyzeIntentRequest = {
  intent?: string;
  prompt?: string;
  domain?: string;
  gradeRange?: GradeRange;
};

type GenerateExperienceFromPromptRequest = {
  title?: string;
  topic?: string;
  description?: string;
  prompt?: string;
  gradeRange?: GradeRange;
  moduleId?: string;
};

type ChatRequest = {
  message?: string;
};

type AutomationRuleMutationRequest = {
  name?: string;
  description?: string | null;
  trigger?: string | Record<string, unknown>;
  action?: string | Record<string, unknown>;
  enabled?: boolean;
};

import type { AnimationContentIntegration } from "../animation-integration.js";

interface RouteContext {
  contentStudioService: HealthAwareContentStudioService;
  animationIntegration?: AnimationContentIntegration;
  prefixes?: string[];
}

const experienceFilterSchema = z.object({
  status: z.string().trim().min(1).optional(),
  gradeRange: z.string().trim().min(1).optional(),
  authorId: z.string().trim().min(1).optional(),
  page: z.coerce.number().int().positive().optional(),
  limit: z.coerce.number().int().positive().max(200).optional(),
  offset: z.coerce.number().int().min(0).optional(),
});

const idParamSchema = z.object({
  id: z.string().trim().min(1),
});

const experienceClaimParamsSchema = z.object({
  experienceId: z.string().trim().min(1),
  claimId: z.string().trim().min(1),
});

const experienceTaskParamsSchema = z.object({
  experienceId: z.string().trim().min(1),
  taskId: z.string().trim().min(1),
});

const createExperienceBodySchema = z
  .object({
    title: z.string().trim().min(1),
    description: z.string().optional(),
    gradeRange: z.string().trim().min(1).optional(),
    moduleId: z.string().trim().min(1).optional(),
  })
  .passthrough();

const updateExperienceBodySchema = z
  .object({
    title: z.string().trim().min(1).optional(),
    description: z.string().optional(),
    status: z.string().trim().min(1).optional(),
    estimatedTimeMinutes: z.number().int().positive().optional(),
    gradeRange: z.string().trim().min(1).optional(),
    userId: z.string().trim().min(1).optional(),
  })
  .passthrough();

const generateClaimBodySchema = z.object({
  maxClaims: z.number().int().positive().max(50).optional(),
  topic: z.string().trim().min(1).optional(),
});

const addClaimBodySchema = z.object({
  text: z.string().trim().min(1),
  bloomLevel: z.string().trim().min(1).optional(),
  contentNeeds: z.unknown().optional(),
});

const updateClaimBodySchema = z.object({
  text: z.string().trim().min(1).optional(),
  bloomLevel: z.string().trim().min(1).optional(),
  contentNeeds: z.unknown().optional(),
});

const taskBodySchema = z.object({
  prompt: z.string().trim().min(1),
  type: z.string().trim().min(1).optional(),
  instructions: z.string().trim().min(1).optional(),
});

const updateTaskBodySchema = z.object({
  prompt: z.string().trim().min(1).optional(),
  type: z.string().trim().min(1).optional(),
  instructions: z.string().trim().min(1).optional(),
});

const eventQuerySchema = z.object({
  limit: z.coerce.number().int().positive().max(200).optional(),
  eventType: z.string().trim().min(1).optional(),
});

const aiGenerateClaimsBodySchema = z.object({
  experienceId: z.string().trim().min(1),
  maxClaims: z.number().int().positive().max(50).optional(),
  topic: z.string().trim().min(1).optional(),
});

const animationLinkBodySchema = z.object({
  claimId: z.string().trim().min(1),
  animationId: z.string().trim().min(1),
  animationType: z
    .enum(["assessment", "exploration", "demonstration"])
    .optional(),
  autoGenerated: z.boolean().optional(),
  concept: z.string().optional(),
  difficulty: z.string().optional(),
  estimatedDuration: z.number().int().positive().optional(),
  spec: z.unknown().optional(),
});

const validationErrorResponse = (issues: z.ZodIssue[]) => ({
  error: "Invalid request",
  details: issues,
});

// ---------------------------------------------------------------------------
// Autofill helper — builds domain-relevant glossary seed terms.
// These will be replaced by an LLM call once the gRPC contract supports it.
// ---------------------------------------------------------------------------

function buildGlossaryTerms(topic: string, domain?: string): string[] {
  const base = [topic];

  const domainTerms: Record<string, string[]> = {
    MATH: ["variable", "equation", "proof", "theorem"],
    PHYSICS: ["force", "energy", "momentum", "velocity"],
    CHEMISTRY: ["molecule", "reaction", "element", "compound"],
    BIOLOGY: ["organism", "cell", "ecosystem", "evolution"],
    CS: ["algorithm", "data structure", "function", "abstraction"],
    ECONOMICS: ["supply", "demand", "elasticity", "equilibrium"],
    SCIENCE: ["hypothesis", "experiment", "observation", "analysis"],
  };

  const extra = domain && domain in domainTerms ? domainTerms[domain] ?? [] : [];
  return [...new Set([...base, ...extra])].slice(0, 8);
}

// =============================================================================
// Route Registration
// =============================================================================

/**
 * Register Content Studio routes with Fastify.
 */
export function registerContentStudioRoutes(
  fastify: FastifyInstance,
  context: RouteContext,
): void {
  const { contentStudioService, animationIntegration } = context;
  const prefixes =
    context.prefixes && context.prefixes.length > 0
      ? context.prefixes
      : ["/content-studio"];

  for (const prefix of prefixes) {
    const contentStudioPreHandler = roleGuard([
      "admin",
      "content_creator",
      "superadmin",
    ]);

    fastify.addHook("onRoute", (routeOptions) => {
      if (
        typeof routeOptions.url !== "string" ||
        !routeOptions.url.startsWith(prefix) ||
        routeOptions.url === `${prefix}/health`
      ) {
        return;
      }

      const existingPreHandler = routeOptions.preHandler;
      routeOptions.preHandler = Array.isArray(existingPreHandler)
        ? [contentStudioPreHandler, ...existingPreHandler]
        : existingPreHandler
          ? [contentStudioPreHandler, existingPreHandler]
          : [contentStudioPreHandler];
    });

    // =========================================================================
    // Experience CRUD Routes
    // =========================================================================

    // List experiences with filtering
    fastify.get<{
      Querystring: ExperienceFilter;
    }>(`${prefix}/experiences`, async (request, reply) => {
      const queryResult = experienceFilterSchema.safeParse(request.query ?? {});
      if (!queryResult.success) {
        return reply
          .code(400)
          .send(validationErrorResponse(queryResult.error.issues));
      }

      const tenantId = getTenantId(request);
      const page =
        queryResult.data.page && queryResult.data.page > 0
          ? queryResult.data.page
          : 1;
      const limit =
        queryResult.data.limit && queryResult.data.limit > 0
          ? queryResult.data.limit
          : 20;

      const filter: ExperienceFilter & { tenantId: string } = {
        limit,
        offset: queryResult.data.offset ?? (page - 1) * limit,
        tenantId,
        ...(queryResult.data.status
          ? { status: queryResult.data.status as ExperienceStatus }
          : {}),
        ...(queryResult.data.gradeRange
          ? { gradeRange: queryResult.data.gradeRange as GradeRange }
          : {}),
        ...(queryResult.data.authorId
          ? { authorId: queryResult.data.authorId }
          : {}),
      };

      const result = await contentStudioService.listExperiences(filter);
      return reply.send({
        data: result.experiences,
        pagination: {
          page,
          limit,
          total: result.total,
          totalPages: Math.ceil(result.total / limit),
        },
      });
    });

    // Get single experience by ID
    fastify.get<{
      Params: { id: string };
    }>(`${prefix}/experiences/:id`, async (request, reply) => {
      const paramsResult = idParamSchema.safeParse(request.params);
      if (!paramsResult.success) {
        return reply
          .code(400)
          .send(validationErrorResponse(paramsResult.error.issues));
      }

      const { id } = paramsResult.data;
      const tenantId = getTenantId(request);

      const experience = await contentStudioService.getExperience(id);

      if (!experience) {
        return reply.code(404).send({ error: "Experience not found" });
      }

      // Tenant isolation
      if (tenantId && experience.tenantId !== tenantId) {
        return reply.code(403).send({ error: "Access denied" });
      }

      return reply.send({ data: experience });
    });

    // Create new experience
    fastify.post<{
      Body: CreateExperienceRequest;
    }>(`${prefix}/experiences`, async (request, reply) => {
      const bodyResult = createExperienceBodySchema.safeParse(request.body);
      if (!bodyResult.success) {
        return reply
          .code(400)
          .send(validationErrorResponse(bodyResult.error.issues));
      }

      const tenantId = getTenantId(request);
      const authorId = getUserId(request);

      const createPayload: CreateExperienceRequest & {
        tenantId: string;
        authorId: string;
      } = {
        title: bodyResult.data.title,
        description: bodyResult.data.description ?? "",
        gradeRange: (bodyResult.data.gradeRange as GradeRange | undefined) ?? "grade_6_8",
        tenantId,
        authorId,
        ...(bodyResult.data.moduleId
          ? { moduleId: bodyResult.data.moduleId }
          : {}),
      };

      const experience = await contentStudioService.createExperience(createPayload);

      return reply.code(201).send({ data: experience });
    });

    // Update experience
    fastify.put<{
      Params: { id: string };
      Body: UpdateExperienceRequest;
    }>(`${prefix}/experiences/:id`, async (request, reply) => {
      const paramsResult = idParamSchema.safeParse(request.params);
      if (!paramsResult.success) {
        return reply
          .code(400)
          .send(validationErrorResponse(paramsResult.error.issues));
      }
      const bodyResult = updateExperienceBodySchema.safeParse(request.body);
      if (!bodyResult.success) {
        return reply
          .code(400)
          .send(validationErrorResponse(bodyResult.error.issues));
      }

      const { id } = paramsResult.data;
      const tenantId = getTenantId(request);

      const existing = await contentStudioService.getExperience(id);
      if (!existing) {
        return reply.code(404).send({ error: "Experience not found" });
      }

      if (tenantId && existing.tenantId !== tenantId) {
        return reply.code(403).send({ error: "Access denied" });
      }

      const updatePayload: UpdateExperienceRequest = {
        ...(bodyResult.data.title ? { title: bodyResult.data.title } : {}),
        ...(bodyResult.data.description !== undefined
          ? { description: bodyResult.data.description }
          : {}),
        ...(bodyResult.data.status
          ? { status: bodyResult.data.status as ExperienceStatus }
          : {}),
        ...(bodyResult.data.estimatedTimeMinutes != null
          ? { estimatedTimeMinutes: bodyResult.data.estimatedTimeMinutes }
          : {}),
        ...(bodyResult.data.gradeRange
          ? { gradeRange: bodyResult.data.gradeRange as GradeRange }
          : {}),
        ...(bodyResult.data.userId ? { userId: bodyResult.data.userId } : {}),
      };

      const updated = await contentStudioService.updateExperience(id, updatePayload);
      return reply.send({ data: updated });
    });

    // Delete experience
    fastify.delete<{
      Params: { id: string };
    }>(`${prefix}/experiences/:id`, async (request, reply) => {
      const { id } = request.params;
      const tenantId = getTenantId(request);

      const existing = await contentStudioService.getExperience(id);
      if (!existing) {
        return reply.code(404).send({ error: "Experience not found" });
      }

      if (tenantId && existing.tenantId !== tenantId) {
        return reply.code(403).send({ error: "Access denied" });
      }

      await contentStudioService.deleteExperience(id);
      return reply.code(204).send();
    });

    // =========================================================================
    // AI Generation Routes
    // =========================================================================

    // Generate claims for experience
    fastify.post<{
      Params: { id: string };
      Body: GenerateClaimRequest;
    }>(`${prefix}/experiences/:id/generate-claims`, async (request, reply) => {
      const paramsResult = idParamSchema.safeParse(request.params);
      if (!paramsResult.success) {
        return reply
          .code(400)
          .send(validationErrorResponse(paramsResult.error.issues));
      }
      const bodyResult = generateClaimBodySchema.safeParse(request.body ?? {});
      if (!bodyResult.success) {
        return reply
          .code(400)
          .send(validationErrorResponse(bodyResult.error.issues));
      }

      const { id } = paramsResult.data;
      const tenantId = getTenantId(request);

      const existing = await contentStudioService.getExperience(id);
      if (!existing) {
        return reply.code(404).send({ error: "Experience not found" });
      }

      if (tenantId && existing.tenantId !== tenantId) {
        return reply.code(403).send({ error: "Access denied" });
      }

      const claimsPayload: GenerateClaimRequest = {
        ...(bodyResult.data.maxClaims != null
          ? { maxClaims: bodyResult.data.maxClaims }
          : {}),
        ...(bodyResult.data.topic ? { topic: bodyResult.data.topic } : {}),
      };

      const claims = await contentStudioService.generateClaims(id, claimsPayload);
      return reply.send({ data: claims });
    });

    // Generate tasks for claim
    fastify.post<{
      Params: { experienceId: string; claimId: string };
      Body: GenerateTaskRequest;
    }>(
      `${prefix}/experiences/:experienceId/claims/:claimId/generate-tasks`,
      async (request, reply) => {
        const paramsResult = experienceClaimParamsSchema.safeParse(
          request.params,
        );
        if (!paramsResult.success) {
          return reply
            .code(400)
            .send(validationErrorResponse(paramsResult.error.issues));
        }

        const { experienceId, claimId } = paramsResult.data;
        const tenantId = getTenantId(request);

        const existing = await contentStudioService.getExperience(experienceId);
        if (!existing) {
          return reply.code(404).send({ error: "Experience not found" });
        }

        if (tenantId && existing.tenantId !== tenantId) {
          return reply.code(403).send({ error: "Access denied" });
        }

        const tasks = await contentStudioService.generateTasks(
          experienceId,
          claimId,
          request.body,
        );
        return reply.send({ data: tasks });
      },
    );

    fastify.post<{
      Params: { id: string };
      Body: { text: string; bloomLevel?: string; contentNeeds?: unknown };
    }>(`${prefix}/experiences/:id/claims`, async (request, reply) => {
      const paramsResult = idParamSchema.safeParse(request.params);
      if (!paramsResult.success) {
        return reply
          .code(400)
          .send(validationErrorResponse(paramsResult.error.issues));
      }
      const bodyResult = addClaimBodySchema.safeParse(request.body);
      if (!bodyResult.success) {
        return reply
          .code(400)
          .send(validationErrorResponse(bodyResult.error.issues));
      }

      const { id } = paramsResult.data;
      const tenantId = getTenantId(request);

      const existing = await contentStudioService.getExperience(id);
      if (!existing) {
        return reply.code(404).send({ error: "Experience not found" });
      }

      if (tenantId && existing.tenantId !== tenantId) {
        return reply.code(403).send({ error: "Access denied" });
      }

      const claimPayload = {
        text: bodyResult.data.text,
        ...(bodyResult.data.bloomLevel
          ? { bloomLevel: bodyResult.data.bloomLevel }
          : {}),
        ...(bodyResult.data.contentNeeds !== undefined
          ? { contentNeeds: bodyResult.data.contentNeeds }
          : {}),
      };
      const claim = await contentStudioService.addClaim(id, claimPayload);
      return reply.code(201).send({ data: claim });
    });

    fastify.patch<{
      Params: { experienceId: string; claimId: string };
      Body: { text?: string; bloomLevel?: string; contentNeeds?: unknown };
    }>(
      `${prefix}/experiences/:experienceId/claims/:claimId`,
      async (request, reply) => {
        const paramsResult = experienceClaimParamsSchema.safeParse(
          request.params,
        );
        if (!paramsResult.success) {
          return reply
            .code(400)
            .send(validationErrorResponse(paramsResult.error.issues));
        }
        const bodyResult = updateClaimBodySchema.safeParse(request.body);
        if (!bodyResult.success) {
          return reply
            .code(400)
            .send(validationErrorResponse(bodyResult.error.issues));
        }

        const { experienceId, claimId } = paramsResult.data;
        const tenantId = getTenantId(request);

        const existing = await contentStudioService.getExperience(experienceId);
        if (!existing) {
          return reply.code(404).send({ error: "Experience not found" });
        }

        if (tenantId && existing.tenantId !== tenantId) {
          return reply.code(403).send({ error: "Access denied" });
        }

        const claim = await contentStudioService.updateClaim(
          experienceId,
          claimId,
          {
            ...(bodyResult.data.text ? { text: bodyResult.data.text } : {}),
            ...(bodyResult.data.bloomLevel
              ? { bloomLevel: bodyResult.data.bloomLevel }
              : {}),
            ...(bodyResult.data.contentNeeds !== undefined
              ? { contentNeeds: bodyResult.data.contentNeeds }
              : {}),
          },
        );
        return reply.send({ data: claim });
      },
    );

    fastify.delete<{
      Params: { experienceId: string; claimId: string };
    }>(
      `${prefix}/experiences/:experienceId/claims/:claimId`,
      async (request, reply) => {
        const { experienceId, claimId } = request.params;
        const tenantId = getTenantId(request);

        const existing = await contentStudioService.getExperience(experienceId);
        if (!existing) {
          return reply.code(404).send({ error: "Experience not found" });
        }

        if (tenantId && existing.tenantId !== tenantId) {
          return reply.code(403).send({ error: "Access denied" });
        }

        await contentStudioService.deleteClaim(experienceId, claimId);
        return reply.code(204).send();
      },
    );

    fastify.post<{
      Params: { experienceId: string; claimId: string };
      Body: { prompt: string; type?: string; instructions?: string };
    }>(
      `${prefix}/experiences/:experienceId/claims/:claimId/tasks`,
      async (request, reply) => {
        const paramsResult = experienceClaimParamsSchema.safeParse(
          request.params,
        );
        if (!paramsResult.success) {
          return reply
            .code(400)
            .send(validationErrorResponse(paramsResult.error.issues));
        }
        const bodyResult = taskBodySchema.safeParse(request.body);
        if (!bodyResult.success) {
          return reply
            .code(400)
            .send(validationErrorResponse(bodyResult.error.issues));
        }

        const { experienceId, claimId } = paramsResult.data;
        const tenantId = getTenantId(request);

        const existing = await contentStudioService.getExperience(experienceId);
        if (!existing) {
          return reply.code(404).send({ error: "Experience not found" });
        }

        if (tenantId && existing.tenantId !== tenantId) {
          return reply.code(403).send({ error: "Access denied" });
        }

        const task = await contentStudioService.addTask(
          experienceId,
          claimId,
          {
            prompt: bodyResult.data.prompt,
            ...(bodyResult.data.type ? { type: bodyResult.data.type } : {}),
            ...(bodyResult.data.instructions
              ? { instructions: bodyResult.data.instructions }
              : {}),
          },
        );
        return reply.code(201).send({ data: task });
      },
    );

    fastify.patch<{
      Params: { experienceId: string; taskId: string };
      Body: { prompt?: string; type?: string; instructions?: string };
    }>(
      `${prefix}/experiences/:experienceId/tasks/:taskId`,
      async (request, reply) => {
        const paramsResult = experienceTaskParamsSchema.safeParse(
          request.params,
        );
        if (!paramsResult.success) {
          return reply
            .code(400)
            .send(validationErrorResponse(paramsResult.error.issues));
        }
        const bodyResult = updateTaskBodySchema.safeParse(request.body);
        if (!bodyResult.success) {
          return reply
            .code(400)
            .send(validationErrorResponse(bodyResult.error.issues));
        }

        const { experienceId, taskId } = paramsResult.data;
        const tenantId = getTenantId(request);

        const existing = await contentStudioService.getExperience(experienceId);
        if (!existing) {
          return reply.code(404).send({ error: "Experience not found" });
        }

        if (tenantId && existing.tenantId !== tenantId) {
          return reply.code(403).send({ error: "Access denied" });
        }

        const task = await contentStudioService.updateTask(
          experienceId,
          "",
          taskId,
          {
            ...(bodyResult.data.prompt ? { prompt: bodyResult.data.prompt } : {}),
            ...(bodyResult.data.type ? { type: bodyResult.data.type } : {}),
            ...(bodyResult.data.instructions
              ? { instructions: bodyResult.data.instructions }
              : {}),
          },
        );
        return reply.send({ data: task });
      },
    );

    fastify.delete<{
      Params: { experienceId: string; taskId: string };
    }>(
      `${prefix}/experiences/:experienceId/tasks/:taskId`,
      async (request, reply) => {
        const { experienceId, taskId } = request.params;
        const tenantId = getTenantId(request);

        const existing = await contentStudioService.getExperience(experienceId);
        if (!existing) {
          return reply.code(404).send({ error: "Experience not found" });
        }

        if (tenantId && existing.tenantId !== tenantId) {
          return reply.code(403).send({ error: "Access denied" });
        }

        await contentStudioService.deleteTask(experienceId, "", taskId);
        return reply.code(204).send();
      },
    );

    // Refine content with AI
    fastify.post<{
      Params: { id: string };
      Body: RefineContentRequest;
    }>(`${prefix}/experiences/:id/refine`, async (request, reply) => {
      const { id } = request.params;
      const tenantId = getTenantId(request);

      const existing = await contentStudioService.getExperience(id);
      if (!existing) {
        return reply.code(404).send({ error: "Experience not found" });
      }

      if (tenantId && existing.tenantId !== tenantId) {
        return reply.code(403).send({ error: "Access denied" });
      }

      const refined = await contentStudioService.refineContent(
        id,
        {
          ...(request.body?.refinementPrompt
            ? { refinementPrompt: request.body.refinementPrompt }
            : {}),
          ...(request.body?.prompt ? { prompt: request.body.prompt } : {}),
          ...(request.body?.userId ? { userId: request.body.userId } : {}),
        },
      );
      return reply.send({ data: refined });
    });

    // Adapt experience for different grade level
    fastify.post<{
      Params: { id: string };
      Body: AdaptGradeRequest;
    }>(`${prefix}/experiences/:id/adapt-grade`, async (request, reply) => {
      const { id } = request.params;
      const tenantId = getTenantId(request);

      const existing = await contentStudioService.getExperience(id);
      if (!existing) {
        return reply.code(404).send({ error: "Experience not found" });
      }

      if (tenantId && existing.tenantId !== tenantId) {
        return reply.code(403).send({ error: "Access denied" });
      }

      const adapted = await contentStudioService.adaptGrade(
        id,
        {
          ...(request.body?.gradeRange
            ? { gradeRange: request.body.gradeRange as GradeRange }
            : {}),
          ...(request.body?.targetGrade
            ? { targetGrade: request.body.targetGrade as GradeRange }
            : {}),
          ...(request.body?.userId ? { userId: request.body.userId } : {}),
        },
      );
      return reply.send({ data: adapted });
    });

    // =========================================================================
    // Validation & Publishing Routes
    // =========================================================================

    // Validate experience
    fastify.post<{
      Params: { id: string };
      Body: ValidateExperienceRequest;
    }>(`${prefix}/experiences/:id/validate`, async (request, reply) => {
      const { id } = request.params;
      const tenantId = getTenantId(request);

      const existing = await contentStudioService.getExperience(id);
      if (!existing) {
        return reply.code(404).send({ error: "Experience not found" });
      }

      if (tenantId && existing.tenantId !== tenantId) {
        return reply.code(403).send({ error: "Access denied" });
      }

      const validation = await contentStudioService.validateExperience(id);
      return reply.send({ data: validation });
    });

    // Publish experience
    fastify.post<{
      Params: { id: string };
    }>(`${prefix}/experiences/:id/publish`, async (request, reply) => {
      const { id } = request.params;
      const tenantId = getTenantId(request);
      const userId = getUserId(request);

      const existing = await contentStudioService.getExperience(id);
      if (!existing) {
        return reply.code(404).send({ error: "Experience not found" });
      }

      if (tenantId && existing.tenantId !== tenantId) {
        return reply.code(403).send({ error: "Access denied" });
      }

      const published = await contentStudioService.publishExperience(
        id,
        userId,
      );
      return reply.send({ data: published });
    });

    // Unpublish experience
    fastify.post<{
      Params: { id: string };
      Body: { reason?: string };
    }>(`${prefix}/experiences/:id/unpublish`, async (request, reply) => {
      const { id } = request.params;
      const tenantId = getTenantId(request);

      const existing = await contentStudioService.getExperience(id);
      if (!existing) {
        return reply.code(404).send({ error: "Experience not found" });
      }

      if (tenantId && existing.tenantId !== tenantId) {
        return reply.code(403).send({ error: "Access denied" });
      }

      const unpublished = await contentStudioService.unpublishExperience(
        id,
        request.body?.reason,
      );
      return reply.send({ data: unpublished });
    });

    // Content generation progress
    fastify.get<{
      Params: { id: string };
    }>(`${prefix}/experiences/:id/progress`, async (request, reply) => {
      const { id } = request.params;
      const tenantId = getTenantId(request);
      const existing = await contentStudioService.getExperience(id);
      if (!existing) {
        return reply.code(404).send({ error: "Experience not found" });
      }

      if (tenantId && existing.tenantId !== tenantId) {
        return reply.code(403).send({ error: "Access denied" });
      }

      const progress = await contentStudioService.getGenerationProgress(id);
      return reply.send(progress);
    });

    // =========================================================================
    // Artifact Query Routes
    // =========================================================================

    // Comprehensive view: experience + all claim artifacts
    fastify.get<{
      Params: { id: string };
    }>(`${prefix}/experiences/:id/comprehensive`, async (request, reply) => {
      const { id } = request.params;
      const tenantId = getTenantId(request);

      const experience = await fastify.prisma.learningExperience.findFirst({
        where: { id, ...(tenantId ? { tenantId } : {}) },
        include: {
          claims: {
            include: {
              examples: true,
              simulations: { include: { simulationManifest: true } },
              animations: true,
            },
          },
        },
      });

      if (!experience) {
        return reply.code(404).send({ error: "Experience not found" });
      }

      return reply.send({ data: experience });
    });

    // List examples for an experience (across all its claims)
    fastify.get<{
      Params: { id: string };
    }>(`${prefix}/experiences/:id/examples`, async (request, reply) => {
      const { id } = request.params;
      const tenantId = getTenantId(request);

      const existing = await contentStudioService.getExperience(id);
      if (!existing) {
        return reply.code(404).send({ error: "Experience not found" });
      }
      if (tenantId && existing.tenantId !== tenantId) {
        return reply.code(403).send({ error: "Access denied" });
      }

      const examples = await fastify.prisma.claimExample.findMany({
        where: { experienceId: id },
        orderBy: { createdAt: "asc" },
      });

      return reply.send({ data: examples });
    });

    // List simulations linked to an experience (across all its claims)
    fastify.get<{
      Params: { id: string };
    }>(`${prefix}/experiences/:id/simulations`, async (request, reply) => {
      const { id } = request.params;
      const tenantId = getTenantId(request);

      const existing = await contentStudioService.getExperience(id);
      if (!existing) {
        return reply.code(404).send({ error: "Experience not found" });
      }
      if (tenantId && existing.tenantId !== tenantId) {
        return reply.code(403).send({ error: "Access denied" });
      }

      const simulations = await fastify.prisma.claimSimulation.findMany({
        where: { experienceId: id },
        include: { simulationManifest: true },
        orderBy: { createdAt: "asc" },
      });

      return reply.send({ data: simulations });
    });

    // Link a simulation manifest to a claim within the experience
    fastify.post<{
      Params: { id: string };
      Body: {
        claimRef: string;
        simulationManifestId: string;
        interactionType?: string;
        goal?: string;
        successCriteria?: Record<string, unknown>;
        estimatedMinutes?: number;
      };
    }>(`${prefix}/experiences/:id/simulations`, async (request, reply) => {
      const { id } = request.params;
      const tenantId = getTenantId(request);
      const {
        claimRef,
        simulationManifestId,
        interactionType,
        goal,
        successCriteria,
        estimatedMinutes,
      } = request.body;

      if (!claimRef || !simulationManifestId) {
        return reply
          .code(400)
          .send({ error: "claimRef and simulationManifestId are required" });
      }

      const existing = await contentStudioService.getExperience(id);
      if (!existing) {
        return reply.code(404).send({ error: "Experience not found" });
      }
      if (tenantId && existing.tenantId !== tenantId) {
        return reply.code(403).send({ error: "Access denied" });
      }

      const claim = await fastify.prisma.learningClaim.findFirst({
        where: { experienceId: id, claimRef },
        select: { claimRef: true },
      });
      if (!claim) {
        return reply
          .code(404)
          .send({ error: "Claim not found for this experience" });
      }

      const linked = await fastify.prisma.claimSimulation.upsert({
        where: { experienceId_claimRef: { experienceId: id, claimRef } },
        create: {
          experienceId: id,
          claimRef,
          simulationManifestId,
          interactionType: interactionType ?? "parameter_exploration",
          goal: goal ?? "",
          successCriteria: toInputJsonValue(successCriteria ?? {}),
          estimatedMinutes: estimatedMinutes ?? 10,
        },
        update: {
          simulationManifestId,
          interactionType: interactionType ?? "parameter_exploration",
          goal: goal ?? "",
          successCriteria: toInputJsonValue(successCriteria ?? {}),
          estimatedMinutes: estimatedMinutes ?? 10,
        },
      });

      return reply.code(201).send({ data: linked });
    });

    // =========================================================================
    // Animation Routes
    // =========================================================================

    // List animations for an experience
    fastify.get<{
      Params: { id: string };
    }>(`${prefix}/experiences/:id/animations`, async (request, reply) => {
      if (!animationIntegration) {
        return reply
          .code(501)
          .send({ error: "Animation integration not configured" });
      }
      const { id } = request.params;
      const tenantId = getTenantId(request);

      const existing = await contentStudioService.getExperience(id);
      if (!existing) {
        return reply.code(404).send({ error: "Experience not found" });
      }
      if (existing.tenantId !== tenantId) {
        return reply.code(403).send({ error: "Access denied" });
      }

      const animations = await animationIntegration.getAnimationsForContent(id);
      return reply.send({ data: animations });
    });

    // Link an animation to a specific claim within an experience
    fastify.post<{
      Params: { id: string };
      Body: AnimationLinkRequest;
    }>(`${prefix}/experiences/:id/animations`, async (request, reply) => {
      if (!animationIntegration) {
        return reply
          .code(501)
          .send({ error: "Animation integration not configured" });
      }
      const paramsResult = idParamSchema.safeParse(request.params);
      if (!paramsResult.success) {
        return reply
          .code(400)
          .send(validationErrorResponse(paramsResult.error.issues));
      }
      const bodyResult = animationLinkBodySchema.safeParse(request.body ?? {});
      if (!bodyResult.success) {
        return reply
          .code(400)
          .send(validationErrorResponse(bodyResult.error.issues));
      }

      const { id } = paramsResult.data;
      const tenantId = getTenantId(request);
      const body = bodyResult.data;

      const existing = await contentStudioService.getExperience(id);
      if (!existing) {
        return reply.code(404).send({ error: "Experience not found" });
      }
      if (existing.tenantId !== tenantId) {
        return reply.code(403).send({ error: "Access denied" });
      }

      const animationType =
        body.animationType === "assessment" ||
        body.animationType === "exploration" ||
        body.animationType === "demonstration"
          ? body.animationType
          : "demonstration";

      await animationIntegration.linkAnimationToContent({
        contentId: id,
        claimId: body.claimId,
        animationId: body.animationId,
        animationType,
        autoGenerated: body.autoGenerated ?? false,
        metadata: {
          concept: body.concept ?? "",
          difficulty: body.difficulty ?? "medium",
          estimatedDuration: body.estimatedDuration ?? 30,
        },
        ...(body.spec ? { spec: body.spec as AnimationSpec } : {}),
      });

      return reply.code(201).send({ status: "linked" });
    });

    // =========================================================================
    // Health Routes
    // =========================================================================

    fastify.get(`${prefix}/health`, { config: { public: true } }, async () => ({
      status: "healthy",
      service: "content-studio",
      timestamp: new Date().toISOString(),
    }));

    // =========================================================================
    // AI & Authoring Helper Routes
    // =========================================================================

    fastify.post<{
      Body: AnalyzeIntentRequest;
    }>(`${prefix}/ai/analyze-intent`, async (request, reply) => {
      const body = request.body || {};
      return reply.send({
        data: {
          summary: body.intent || body.prompt || "",
          recommendedDomain: body.domain || "TECH",
          recommendedGradeRange: body.gradeRange || "grade_6_8",
          confidence: 0.7,
        },
      });
    });

    // =========================================================================
    // AI Autofill — suggest title, description, learning objectives, glossary
    // =========================================================================

    /**
     * POST /content-studio/ai/autofill
     *
     * Given a topic and optional grade range, returns AI-generated suggestions
     * for the module title, description, learning objectives, and glossary terms.
     *
     * The caller MUST review all suggestions before use — they are prefilled,
     * not auto-applied. Confidence score indicates how specific the suggestions
     * are relative to the topic.
     *
     * @doc.type endpoint
     * @doc.purpose AI-assisted autofill for module authoring fields
     * @doc.layer product
     * @doc.pattern Service
     */
    const autofillBodySchema = z.object({
      topic: z.string().trim().min(1).max(200),
      gradeRange: z
        .enum([
          "k_2",
          "grade_3_5",
          "grade_6_8",
          "grade_9_12",
          "undergraduate",
          "graduate",
          "professional",
        ])
        .optional()
        .default("grade_6_8"),
      domain: z.string().trim().min(1).optional(),
    });

    fastify.post<{
      Body: { topic: string; gradeRange?: string; domain?: string };
    }>(`${prefix}/ai/autofill`, async (request, reply) => {
      const bodyResult = autofillBodySchema.safeParse(request.body ?? {});
      if (!bodyResult.success) {
        return reply.code(400).send(validationErrorResponse(bodyResult.error.issues));
      }

      const { topic, gradeRange, domain } = bodyResult.data;

      // Heuristic prefill — the generation service will replace this with a
      // real LLM call once the content-generation gRPC contract includes
      // autofill. Until then, the suggestions are deterministic and helpful
      // enough for the author to review and edit.
      const titleSuggestions = [
        `Introduction to ${topic}`,
        `Exploring ${topic}`,
        `${topic}: Concepts and Applications`,
      ];

      const objectiveSuggestions = [
        `Describe the key principles of ${topic}`,
        `Explain how ${topic} applies in real-world contexts`,
        `Analyse the relationship between ${topic} and related concepts`,
        `Evaluate examples that demonstrate ${topic}`,
      ];

      const glossarySuggestions = buildGlossaryTerms(topic, domain);

      const autofillResult = {
        topic,
        gradeRange,
        domain: domain ?? null,
        suggestions: {
          title: titleSuggestions[0] ?? `Introduction to ${topic}`,
          titleAlternatives: titleSuggestions.slice(1),
          description: `This module explores ${topic}, helping learners understand core concepts, develop critical thinking, and apply knowledge to real-world problems.`,
          learningObjectives: objectiveSuggestions,
          glossaryTerms: glossarySuggestions,
        },
        confidence: 0.65,
        note: "These suggestions are AI-generated drafts. Review and edit before publishing.",
      };

      return reply.send({ data: autofillResult });
    });

    fastify.post<{
      Body: GenerateClaimRequest & { experienceId?: string };
    }>(`${prefix}/ai/generate-claims`, async (request, reply) => {
      const bodyResult = aiGenerateClaimsBodySchema.safeParse(request.body ?? {});
      if (!bodyResult.success) {
        return reply
          .code(400)
          .send(validationErrorResponse(bodyResult.error.issues));
      }

      const body = bodyResult.data;
      const queuedPayload: GenerateClaimRequest = {
        ...(body.maxClaims != null ? { maxClaims: body.maxClaims } : {}),
        ...(body.topic ? { topic: body.topic } : {}),
      };
      const queued = await contentStudioService.generateClaims(
        body.experienceId,
        queuedPayload,
      );
      return reply.send({ data: queued });
    });

    fastify.post<{
      Body: { claimRef?: string };
    }>(`${prefix}/ai/generate-simulation`, async (request, reply) => {
      const body = request.body || {};
      return reply.send({
        data: {
          status: "queued",
          claimRef: body.claimRef,
          message:
            "Simulation generation will run from claim content needs pipeline",
        },
      });
    });

    fastify.post<{
      Body: GenerateExperienceFromPromptRequest;
    }>(`${prefix}/ai/generate`, async (request, reply) => {
      const tenantId = getTenantId(request);
      const authorId = getUserId(request);
      const body = request.body || {};

      const created = await contentStudioService.createExperience({
        tenantId,
        authorId,
        title: body.title || body.topic || "Untitled Experience",
        description: body.description || body.prompt || "",
        gradeRange: body.gradeRange || "grade_6_8",
        ...(body.moduleId ? { moduleId: body.moduleId } : {}),
      });

      return reply.code(created.success ? 201 : 400).send({ data: created });
    });

    fastify.post<{
      Body: ChatRequest;
    }>(`${prefix}/ai/chat`, async (request, reply) => {
      const body = request.body || {};
      return reply.send({
        data: {
          response:
            body.message ||
            "Provide a content goal and I can generate claims, tasks, and validation suggestions.",
        },
      });
    });

    // =========================================================================
    // Authoring Utility Routes
    // =========================================================================

    fastify.get(
      `${prefix}/experiences/search-similar`,
      async (request, reply) => {
        const tenantId = getTenantId(request);

        const list = await contentStudioService.listExperiences({
          tenantId,
          limit: 10,
          offset: 0,
        });
        return reply.send({ data: list.experiences.slice(0, 5) });
      },
    );

    fastify.get<{
      Params: { id: string };
    }>(`${prefix}/experiences/:id/analytics`, async (request, reply) => {
      const { id } = request.params;
      const analytics = await contentStudioService.getExperienceAnalytics(id);
      return reply.send({ data: analytics || {} });
    });

    fastify.get<{
      Params: { id: string };
      Querystring: { limit?: string; eventType?: string };
    }>(`${prefix}/experiences/:id/events`, async (request, reply) => {
      const paramsResult = idParamSchema.safeParse(request.params);
      if (!paramsResult.success) {
        return reply
          .code(400)
          .send(validationErrorResponse(paramsResult.error.issues));
      }
      const queryResult = eventQuerySchema.safeParse(request.query ?? {});
      if (!queryResult.success) {
        return reply
          .code(400)
          .send(validationErrorResponse(queryResult.error.issues));
      }

      const { id } = paramsResult.data;
      const limit = queryResult.data.limit ?? 50;
      const eventType = queryResult.data.eventType || undefined;
      const events = await contentStudioService.getExperienceEvents(id, {
        limit,
        ...(eventType ? { eventType: eventType as never } : {}),
      });
      return reply.send({ data: events });
    });

    fastify.get(`${prefix}/templates`, async () => {
      return {
        data: [
          {
            id: "foundations",
            name: "Foundations",
            domain: "SCIENCE",
            gradeRange: "grade_6_8",
          },
          {
            id: "lab-guided",
            name: "Guided Lab",
            domain: "SCIENCE",
            gradeRange: "grade_9_12",
          },
          {
            id: "concept-practice",
            name: "Concept + Practice",
            domain: "MATH",
            gradeRange: "grade_6_8",
          },
        ],
      };
    });

    fastify.get(`${prefix}/templates/categories`, async () => {
      return {
        data: ["Foundational", "Inquiry", "Practice", "Assessment"],
      };
    });

    fastify.post<{
      Params: { templateId: string };
    }>(`${prefix}/templates/:templateId/apply`, async (request) => {
      const { templateId } = request.params;
      return {
        data: {
          templateId,
          title: `Template: ${templateId}`,
          description: "Template applied successfully",
        },
      };
    });

    // =========================================================================
    // Automation Rules
    // Tenant-wide listing plus per-experience automation rule CRUD.
    // =========================================================================

    /**
     * GET /automation-rules
     * List automation rules for the current tenant across all experiences.
     */
    fastify.get(`${prefix}/automation-rules`, async (request, reply) => {
      const tenantId = getTenantId(request);
      const prisma = fastify.prisma;

      const rules = await prisma.automationRule.findMany({
        where: { tenantId },
        orderBy: [{ experienceId: "asc" }, { createdAt: "asc" }],
      });

      return reply.send({ data: rules });
    });

    /**
     * GET /experiences/:id/automation-rules
     * List automation rules for a learning experience.
     */
    fastify.get<{ Params: { id: string } }>(
      `${prefix}/experiences/:id/automation-rules`,
      async (request, reply) => {
        const tenantId = getTenantId(request);
        const { id: experienceId } = request.params;
        const prisma = fastify.prisma;

        const rules = await prisma.automationRule.findMany({
          where: { tenantId, experienceId },
          orderBy: { createdAt: "asc" },
        });
        return reply.send({ data: rules });
      },
    );

    /**
     * POST /experiences/:id/automation-rules
     * Create a new automation rule for a learning experience.
     */
    fastify.post<{ Params: { id: string } }>(
      `${prefix}/experiences/:id/automation-rules`,
      async (request, reply) => {
        const tenantId = getTenantId(request);
        const { id: experienceId } = request.params;
        const body = (request.body || {}) as AutomationRuleMutationRequest;
        const prisma = fastify.prisma;

        const rule = await prisma.automationRule.create({
          data: {
            tenantId,
            experienceId,
            name: body.name ?? "Untitled Rule",
            description: body.description ?? null,
            trigger:
              typeof body.trigger === "string"
                ? body.trigger
                : JSON.stringify(body.trigger),
            action:
              typeof body.action === "string"
                ? body.action
                : JSON.stringify(body.action),
            enabled: body.enabled ?? true,
          },
        });
        reply.code(201);
        return reply.send({ data: rule });
      },
    );

    /**
     * PUT /experiences/:id/automation-rules/:ruleId
     * Update an existing automation rule.
     */
    fastify.put<{ Params: { id: string; ruleId: string } }>(
      `${prefix}/experiences/:id/automation-rules/:ruleId`,
      async (request, reply) => {
        const tenantId = getTenantId(request);
        const { id: experienceId, ruleId } = request.params;
        const body = (request.body || {}) as AutomationRuleMutationRequest;
        const prisma = fastify.prisma;

        const existing = await prisma.automationRule.findFirst({
          where: { id: ruleId, tenantId, experienceId },
        });
        if (!existing) {
          return reply.code(404).send({ error: "Automation rule not found" });
        }

        const updated = await prisma.automationRule.update({
          where: { id: ruleId },
          data: {
            ...(body.name !== undefined && { name: body.name }),
            ...(body.description !== undefined && {
              description: body.description,
            }),
            ...(body.trigger !== undefined && {
              trigger:
                typeof body.trigger === "string"
                  ? body.trigger
                  : JSON.stringify(body.trigger),
            }),
            ...(body.action !== undefined && {
              action:
                typeof body.action === "string"
                  ? body.action
                  : JSON.stringify(body.action),
            }),
            ...(body.enabled !== undefined && { enabled: body.enabled }),
          },
        });
        return reply.send({ data: updated });
      },
    );

    /**
     * DELETE /experiences/:id/automation-rules/:ruleId
     * Delete an automation rule.
     */
    fastify.delete<{ Params: { id: string; ruleId: string } }>(
      `${prefix}/experiences/:id/automation-rules/:ruleId`,
      async (request, reply) => {
        const tenantId = getTenantId(request);
        const { id: experienceId, ruleId } = request.params;
        const prisma = fastify.prisma;

        const existing = await prisma.automationRule.findFirst({
          where: { id: ruleId, tenantId, experienceId },
        });
        if (!existing) {
          return reply.code(404).send({ error: "Automation rule not found" });
        }

        await prisma.automationRule.delete({ where: { id: ruleId } });
        return reply.send({ success: true });
      },
    );
  }
}
