export {
  Typography,
  type TypographyProps,
  type TypographyVariant,
  Text,
  type TextProps,
  Heading,
  type HeadingProps,
  Link,
  type LinkProps,
  List,
  type ListProps,
  Code,
  type CodeProps,
} from '@ghatana/yappc-ui';
