/*
 * YAPPC - Yet Another Project/Package Creator
 * Copyright (c) 2025 Ghatana
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.ghatana.yappc.core.docs.adr.template;

import com.ghatana.yappc.core.docs.adr.model.ADREnums.ADRTemplateType;
import com.ghatana.yappc.core.docs.adr.model.ADRModels.*;

import java.util.Map;

/**
 * MADR (Markdown Any Decision Records) template.
 * Structured format with metadata, decision drivers, options comparison, and validation checklist.
 *
 * @doc.type class
 * @doc.purpose MADR (Markdown Any Decision Records) template.
 * @doc.layer platform
 * @doc.pattern Component
 */
public class MADRADRTemplate implements ADRTemplate {
    
    @Override
    public ADRTemplateType templateType() {
        return ADRTemplateType.MADR;
    }

    @Override
    public String generate(Map<String, Object> data) {
        ADRRequest request = (ADRRequest) data.get("request");
        AIAnalysisResult analysis = (AIAnalysisResult) data.get("analysis");
        String date = (String) data.get("date");

        return String.format(
                """
            # %s

            ## Metadata

            * **Status:** %s
            * **Deciders:** %s
            * **Date:** %s
            * **Tags:** %s

            ## Context and Problem Statement

            %s

            ## Decision Drivers

            * Driver 1
            * Driver 2
            * Driver 3

            ## Considered Options

            %s

            ## Decision Outcome

            **Chosen option:** %s

            **Justification:** %s

            ## Consequences

            **Good:**
            %s

            **Bad:**
            %s

            **Neutral:**
            * To be determined during implementation

            ## Validation

            * [ ] Decision implemented
            * [ ] Stakeholders informed
            * [ ] Documentation updated
            * [ ] Team trained

            ## Notes

            %s

            ---
            *MADR-format ADR generated by YAPPC AI*
            """,
                request.title(),
                request.status(),
                request.stakeholders().isEmpty()
                        ? "*To be identified*"
                        : String.join(", ", request.stakeholders()),
                date,
                String.join(", ", analysis.suggestedTags()),
                request.context().isEmpty()
                        ? "*Context and problem statement to be added*"
                        : request.context(),
                request.alternatives().isEmpty()
                        ? "* *No options documented*"
                        : request.alternatives().stream()
                                .map(alt -> "* " + alt)
                                .reduce("", (a, b) -> a + "\n" + b),
                request.decision().isEmpty()
                        ? "*Chosen option to be documented*"
                        : request.decision(),
                request.rationale().isEmpty()
                        ? "*Justification to be added*"
                        : request.rationale(),
                request.consequences().stream()
                        .filter(
                                c ->
                                        !c.toLowerCase().contains("negative")
                                                && !c.toLowerCase().contains("bad"))
                        .map(c -> "* " + c)
                        .reduce("", (a, b) -> a + "\n" + b),
                request.consequences().stream()
                        .filter(
                                c ->
                                        c.toLowerCase().contains("negative")
                                                || c.toLowerCase().contains("bad"))
                        .map(c -> "* " + c)
                        .reduce("", (a, b) -> a + "\n" + b),
                analysis.recommendations().isEmpty()
                        ? "*No additional notes*"
                        : "**AI Recommendations:**\n"
                                + analysis.recommendations().stream()
                                        .map(rec -> "* " + rec)
                                        .reduce("", (a, b) -> a + "\n" + b));
    }
}
