/**
 * Mock DevSecOps Items
 *
 * Sample work items mapped to DevSecOps format for demonstration.
 * In production, these would come from the WorkItem API.
 *
 * @doc.type mock-data
 * @doc.purpose Sample DevSecOps items for stage dashboards
 */

import type { DevSecOpsItem } from '@/lib/devsecops/mapWorkItemToDevSecOpsItem';

// Re-export for convenience
export type { DevSecOpsItem };

export const mockDevSecOpsItems: Record<string, DevSecOpsItem[]> = {
    // Planning stages use table view
    plan: [
        {
            id: 'STORY-101',
            title: 'Implement payment gateway integration',
            description: 'Add Stripe payment processing to checkout flow',
            status: 'not-started',
            priority: 'high',
            phaseId: 'plan',
            labels: ['payments', 'backend'],
            tenantId: 'acme-payments',
        },
        {
            id: 'STORY-102',
            title: 'Design fraud detection dashboard',
            description: 'Create UI mockups for fraud alerts and metrics',
            status: 'in-progress',
            priority: 'medium',
            phaseId: 'plan',
            labels: ['fraud', 'ui', 'design'],
            tenantId: 'acme-payments',
        },
        {
            id: 'STORY-103',
            title: 'Customer notification system',
            description: 'Real-time notifications for order status updates',
            status: 'not-started',
            priority: 'medium',
            phaseId: 'plan',
            labels: ['notifications', 'customer-experience'],
            tenantId: 'beta-retail',
        },
    ],

    design: [
        {
            id: 'ARCH-201',
            title: 'Microservices architecture for checkout',
            description: 'Design service boundaries and API contracts',
            status: 'in-review',
            priority: 'high',
            phaseId: 'plan',
            labels: ['architecture', 'checkout'],
            tenantId: 'acme-payments',
        },
        {
            id: 'ARCH-202',
            title: 'Database schema for order management',
            description: 'Design tables, indexes, and relationships',
            status: 'in-progress',
            priority: 'high',
            phaseId: 'plan',
            labels: ['database', 'orders'],
            tenantId: 'acme-payments',
        },
    ],

    // Development stages use kanban view
    develop: [
        {
            id: 'DEV-301',
            title: 'Payment API endpoints',
            description: 'Implement REST APIs for payment processing',
            status: 'in-progress',
            priority: 'critical',
            phaseId: 'build',
            labels: ['api', 'payments'],
            tenantId: 'acme-payments',
            relatedIncidentId: 'incident-789',
        },
        {
            id: 'DEV-302',
            title: 'Checkout service refactoring',
            description: 'Split monolith into separate checkout service',
            status: 'blocked',
            priority: 'high',
            phaseId: 'build',
            labels: ['refactoring', 'checkout'],
            tenantId: 'acme-payments',
            relatedIncidentId: 'incident-456',
        },
        {
            id: 'DEV-303',
            title: 'User authentication module',
            description: 'OAuth2 + JWT token management',
            status: 'in-progress',
            priority: 'high',
            phaseId: 'build',
            labels: ['auth', 'security'],
            tenantId: 'acme-payments',
        },
        {
            id: 'DEV-304',
            title: 'Order history API',
            description: 'GET /orders endpoint with pagination',
            status: 'completed',
            priority: 'medium',
            phaseId: 'build',
            labels: ['api', 'orders'],
            tenantId: 'beta-retail',
        },
        {
            id: 'DEV-305',
            title: 'Inventory service integration',
            description: 'Connect to inventory API for stock checks',
            status: 'not-started',
            priority: 'medium',
            phaseId: 'build',
            labels: ['integration', 'inventory'],
            tenantId: 'beta-retail',
        },
    ],

    build: [
        {
            id: 'BUILD-401',
            title: 'CI/CD pipeline for payment service',
            description: 'GitHub Actions workflow with automated tests',
            status: 'in-progress',
            priority: 'high',
            phaseId: 'build',
            labels: ['cicd', 'payments'],
            tenantId: 'acme-payments',
        },
        {
            id: 'BUILD-402',
            title: 'Docker images for microservices',
            description: 'Containerize all services with multi-stage builds',
            status: 'completed',
            priority: 'high',
            phaseId: 'build',
            labels: ['docker', 'infrastructure'],
            tenantId: 'acme-payments',
        },
        {
            id: 'BUILD-403',
            title: 'Build optimization',
            description: 'Reduce build time from 12min to <5min',
            status: 'in-progress',
            priority: 'medium',
            phaseId: 'build',
            labels: ['performance', 'cicd'],
            tenantId: 'beta-retail',
        },
    ],

    test: [
        {
            id: 'TEST-501',
            title: 'Integration tests for checkout flow',
            description: 'End-to-end tests covering happy path and errors',
            status: 'blocked',
            priority: 'critical',
            phaseId: 'verify',
            labels: ['testing', 'checkout'],
            tenantId: 'acme-payments',
            relatedIncidentId: 'incident-456',
        },
        {
            id: 'TEST-502',
            title: 'Load testing payment gateway',
            description: 'Test 1000 concurrent payment requests',
            status: 'in-progress',
            priority: 'high',
            phaseId: 'verify',
            labels: ['load-testing', 'payments'],
            tenantId: 'acme-payments',
        },
        {
            id: 'TEST-503',
            title: 'Fix flaky E2E tests',
            description: 'Stabilize tests failing intermittently',
            status: 'blocked',
            priority: 'high',
            phaseId: 'verify',
            labels: ['testing', 'flakiness'],
            tenantId: 'acme-payments',
        },
        {
            id: 'TEST-504',
            title: 'Unit test coverage > 80%',
            description: 'Add missing tests for business logic',
            status: 'in-progress',
            priority: 'medium',
            phaseId: 'verify',
            labels: ['testing', 'coverage'],
            tenantId: 'beta-retail',
        },
    ],

    secure: [
        {
            id: 'SEC-601',
            title: 'Critical SQL injection vulnerability',
            description: 'Payment API vulnerable to SQL injection attacks',
            status: 'blocked',
            priority: 'critical',
            phaseId: 'verify',
            labels: ['security', 'vulnerability', 'sql'],
            tenantId: 'acme-payments',
            relatedIncidentId: 'incident-123',
        },
        {
            id: 'SEC-602',
            title: 'Update TLS certificates',
            description: 'Renew expiring certificates before Jan 15',
            status: 'in-progress',
            priority: 'high',
            phaseId: 'verify',
            labels: ['security', 'certificates'],
            tenantId: 'acme-payments',
        },
        {
            id: 'SEC-603',
            title: 'Secrets rotation',
            description: 'Rotate API keys and database passwords',
            status: 'blocked',
            priority: 'critical',
            phaseId: 'verify',
            labels: ['security', 'secrets'],
            tenantId: 'acme-payments',
        },
        {
            id: 'SEC-604',
            title: 'Security audit findings',
            description: 'Address 8 medium-severity findings from pen test',
            status: 'blocked',
            priority: 'high',
            phaseId: 'review',
            labels: ['security', 'audit'],
            tenantId: 'acme-payments',
        },
        {
            id: 'SEC-605',
            title: 'OWASP dependency scan',
            description: 'Update vulnerable npm packages',
            status: 'in-progress',
            priority: 'medium',
            phaseId: 'verify',
            labels: ['security', 'dependencies'],
            tenantId: 'beta-retail',
        },
    ],

    compliance: [
        {
            id: 'COMP-701',
            title: 'PCI DSS compliance documentation',
            description: 'Complete SAQ-D questionnaire for payment processing',
            status: 'in-review',
            priority: 'high',
            phaseId: 'review',
            labels: ['compliance', 'pci-dss'],
            tenantId: 'acme-payments',
        },
        {
            id: 'COMP-702',
            title: 'GDPR data retention policies',
            description: 'Implement automated data deletion after 90 days',
            status: 'in-progress',
            priority: 'medium',
            phaseId: 'review',
            labels: ['compliance', 'gdpr', 'privacy'],
            tenantId: 'beta-retail',
        },
    ],

    staging: [
        {
            id: 'UAT-801',
            title: 'UAT for payment flow',
            description: 'Business users validate end-to-end checkout',
            status: 'in-progress',
            priority: 'high',
            phaseId: 'staging',
            labels: ['uat', 'payments'],
            tenantId: 'acme-payments',
        },
        {
            id: 'UAT-802',
            title: 'Performance testing in staging',
            description: 'Validate response times under load',
            status: 'not-started',
            priority: 'medium',
            phaseId: 'staging',
            labels: ['performance', 'testing'],
            tenantId: 'beta-retail',
        },
    ],

    deploy: [
        {
            id: 'DEPLOY-901',
            title: 'Deploy payment-api v2.3.0 to production',
            description: 'Canary deployment with 10% traffic',
            status: 'blocked',
            priority: 'critical',
            phaseId: 'deploy',
            labels: ['deployment', 'payments', 'canary'],
            tenantId: 'acme-payments',
            relatedQueueItemId: 'queue-deploy-payments-api-to-prod',
            relatedIncidentId: 'incident-123',
        },
        {
            id: 'DEPLOY-902',
            title: 'Rollback checkout-service',
            description: 'Revert v1.5.2 due to critical bug',
            status: 'blocked',
            priority: 'critical',
            phaseId: 'deploy',
            labels: ['rollback', 'checkout', 'incident'],
            tenantId: 'acme-payments',
            relatedIncidentId: 'incident-456',
        },
        {
            id: 'DEPLOY-903',
            title: 'Deploy fraud-detection model v2',
            description: 'Update ML model with improved accuracy',
            status: 'in-progress',
            priority: 'high',
            phaseId: 'deploy',
            labels: ['ml', 'fraud', 'model'],
            tenantId: 'acme-payments',
        },
        {
            id: 'DEPLOY-904',
            title: 'Database migration for orders table',
            description: 'Add new columns for shipping preferences',
            status: 'not-started',
            priority: 'medium',
            phaseId: 'deploy',
            labels: ['database', 'migration'],
            tenantId: 'beta-retail',
        },
    ],

    operate: [
        {
            id: 'OPS-1001',
            title: 'Monitor payment API latency',
            description: 'P95 latency increasing above 500ms threshold',
            status: 'in-progress',
            priority: 'high',
            phaseId: 'operate',
            labels: ['monitoring', 'performance'],
            tenantId: 'acme-payments',
            relatedIncidentId: 'incident-789',
        },
        {
            id: 'OPS-1002',
            title: 'Scale checkout service',
            description: 'Increase replicas from 5 to 10 for Black Friday',
            status: 'in-progress',
            priority: 'high',
            phaseId: 'operate',
            labels: ['scaling', 'capacity'],
            tenantId: 'acme-payments',
        },
    ],

    monitor: [
        {
            id: 'MON-1101',
            title: 'Dashboard for fraud detection metrics',
            description: 'Real-time dashboard with alert thresholds',
            status: 'in-progress',
            priority: 'medium',
            phaseId: 'learn',
            labels: ['monitoring', 'fraud', 'dashboard'],
            tenantId: 'acme-payments',
        },
        {
            id: 'MON-1102',
            title: 'Log aggregation improvements',
            description: 'Reduce log volume by 40% with better filtering',
            status: 'not-started',
            priority: 'low',
            phaseId: 'learn',
            labels: ['logs', 'observability'],
            tenantId: 'beta-retail',
        },
    ],
};
