package com.ghatana.digitalmarketing.application.optimization;

import com.ghatana.digitalmarketing.contracts.DmOperationContext;
import com.ghatana.digitalmarketing.domain.optimization.AnomalyDetectionResult;
import com.ghatana.digitalmarketing.domain.optimization.AnomalySeverity;
import com.ghatana.digitalmarketing.domain.optimization.AnomalyStatus;
import io.activej.promise.Promise;

import java.time.Instant;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Application service for anomaly detection result management.
 *
 * <p>Anomaly detection identifies unusual patterns in campaign metrics such as sudden drops in
 * conversion rates, unexpected spikes in costs, or deviations from expected performance baselines.
 * These results are generated by AI agents analyzing time-series data and statistical models.</p>
 *
 * @doc.type interface
 * @doc.purpose Handles creation, review, and lifecycle of anomaly detection results (P3-004)
 * @doc.layer product
 * @doc.pattern Service
 */
public interface AnomalyDetectionService {

    /**
     * Publish a new anomaly detection result.
     *
     * @param ctx the operation context
     * @param command the publish command
     * @return Promise containing the created anomaly result
     */
    Promise<AnomalyDetectionResult> publish(DmOperationContext ctx, PublishAnomalyCommand command);

    /**
     * Acknowledge an anomaly as reviewed.
     *
     * @param ctx the operation context
     * @param anomalyId the anomaly ID
     * @param acknowledgedBy the user who acknowledged it
     * @return Promise containing the acknowledged anomaly
     */
    Promise<AnomalyDetectionResult> acknowledge(DmOperationContext ctx, String anomalyId, String acknowledgedBy);

    /**
     * Resolve an anomaly with a mitigation action.
     *
     * @param ctx the operation context
     * @param anomalyId the anomaly ID
     * @param mitigationAction the mitigation action taken
     * @return Promise containing the resolved anomaly
     */
    Promise<AnomalyDetectionResult> resolve(DmOperationContext ctx, String anomalyId, String mitigationAction);

    /**
     * Dismiss an anomaly as a false positive.
     *
     * @param ctx the operation context
     * @param anomalyId the anomaly ID
     * @param reason the dismissal reason
     * @return Promise containing the dismissed anomaly
     */
    Promise<AnomalyDetectionResult> dismiss(DmOperationContext ctx, String anomalyId, String reason);

    /**
     * Find an anomaly by ID.
     *
     * @param ctx the operation context
     * @param anomalyId the anomaly ID
     * @return Promise containing optional anomaly
     */
    Promise<Optional<AnomalyDetectionResult>> findById(DmOperationContext ctx, String anomalyId);

    /**
     * List all anomalies for a workspace.
     *
     * @param ctx the operation context
     * @return Promise containing list of anomalies
     */
    Promise<List<AnomalyDetectionResult>> listByWorkspace(DmOperationContext ctx);

    /**
     * List anomalies for a campaign.
     *
     * @param ctx the operation context
     * @param campaignId the campaign ID
     * @return Promise containing list of anomalies
     */
    Promise<List<AnomalyDetectionResult>> listByCampaign(DmOperationContext ctx, String campaignId);

    /**
     * List anomalies by severity.
     *
     * @param ctx the operation context
     * @param severity the severity to filter by
     * @return Promise containing list of anomalies
     */
    Promise<List<AnomalyDetectionResult>> listBySeverity(DmOperationContext ctx, AnomalySeverity severity);

    /**
     * List anomalies by status.
     *
     * @param ctx the operation context
     * @param status the status to filter by
     * @return Promise containing list of anomalies
     */
    Promise<List<AnomalyDetectionResult>> listByStatus(DmOperationContext ctx, AnomalyStatus status);

    /**
     * Command to publish an anomaly detection result.
     */
    record PublishAnomalyCommand(
        String campaignId,
        AnomalySeverity severity,
        String metricName,
        String anomalyType,
        double expectedValue,
        double actualValue,
        double deviationPercentage,
        String description,
        Map<String, Object> context,
        String rationale
    ) {
        public PublishAnomalyCommand {
            Objects.requireNonNull(campaignId, "campaignId must not be null");
            if (campaignId.isBlank()) throw new IllegalArgumentException("campaignId must not be blank");
            Objects.requireNonNull(severity, "severity must not be null");
            Objects.requireNonNull(metricName, "metricName must not be null");
            if (metricName.isBlank()) throw new IllegalArgumentException("metricName must not be blank");
            Objects.requireNonNull(anomalyType, "anomalyType must not be null");
            if (anomalyType.isBlank()) throw new IllegalArgumentException("anomalyType must not be blank");
            Objects.requireNonNull(description, "description must not be null");
            Objects.requireNonNull(context, "context must not be null");
            Objects.requireNonNull(rationale, "rationale must not be null");
            if (deviationPercentage < 0.0) throw new IllegalArgumentException("deviationPercentage must be non-negative");
        }
    }
}
