package com.ghatana.digitalmarketing.application.optimization;

import com.ghatana.digitalmarketing.contracts.DmOperationContext;
import com.ghatana.digitalmarketing.domain.optimization.BudgetReallocationProposal;
import com.ghatana.digitalmarketing.domain.optimization.BudgetReallocationStatus;
import io.activej.promise.Promise;

import java.time.Instant;
import java.util.List;
import java.util.Objects;
import java.util.Optional;

/**
 * Application service for budget reallocation proposal management.
 *
 * <p>Budget reallocation proposals suggest redistributing campaign budgets across channels or campaigns
 * to optimize overall performance. These proposals are generated by AI agents analyzing ROI, ROAS,
 * conversion rates, and market conditions. Proposals require human approval before execution to ensure
 * strategic alignment with business goals.</p>
 *
 * @doc.type interface
 * @doc.purpose Handles creation, review, and lifecycle of budget reallocation proposals (P3-004)
 * @doc.layer product
 * @doc.pattern Service
 */
public interface BudgetReallocationProposalService {

    /**
     * Publish a new budget reallocation proposal.
     *
     * @param ctx the operation context
     * @param command the publish command
     * @return Promise containing the created proposal
     */
    Promise<BudgetReallocationProposal> publish(DmOperationContext ctx, PublishProposalCommand command);

    /**
     * Approve a proposal for execution.
     *
     * @param ctx the operation context
     * @param proposalId the proposal ID
     * @param approvedBy the user who approved it
     * @return Promise containing the approved proposal
     */
    Promise<BudgetReallocationProposal> approve(DmOperationContext ctx, String proposalId, String approvedBy);

    /**
     * Reject a proposal with a reason.
     *
     * @param ctx the operation context
     * @param proposalId the proposal ID
     * @param reason the rejection reason
     * @return Promise containing the rejected proposal
     */
    Promise<BudgetReallocationProposal> reject(DmOperationContext ctx, String proposalId, String reason);

    /**
     * Execute an approved proposal.
     *
     * @param ctx the operation context
     * @param proposalId the proposal ID
     * @return Promise containing the executed proposal
     */
    Promise<BudgetReallocationProposal> execute(DmOperationContext ctx, String proposalId);

    /**
     * Expire a proposal that was not processed in time.
     *
     * @param ctx the operation context
     * @param proposalId the proposal ID
     * @return Promise containing the expired proposal
     */
    Promise<BudgetReallocationProposal> expire(DmOperationContext ctx, String proposalId);

    /**
     * Find a proposal by ID.
     *
     * @param ctx the operation context
     * @param proposalId the proposal ID
     * @return Promise containing optional proposal
     */
    Promise<Optional<BudgetReallocationProposal>> findById(DmOperationContext ctx, String proposalId);

    /**
     * List all proposals for a workspace.
     *
     * @param ctx the operation context
     * @return Promise containing list of proposals
     */
    Promise<List<BudgetReallocationProposal>> listByWorkspace(DmOperationContext ctx);

    /**
     * List proposals for a budget recommendation.
     *
     * @param ctx the operation context
     * @param budgetRecommendationId the budget recommendation ID
     * @return Promise containing list of proposals
     */
    Promise<List<BudgetReallocationProposal>> listByBudgetRecommendation(DmOperationContext ctx, String budgetRecommendationId);

    /**
     * List proposals by status.
     *
     * @param ctx the operation context
     * @param status the status to filter by
     * @return Promise containing list of proposals
     */
    Promise<List<BudgetReallocationProposal>> listByStatus(DmOperationContext ctx, BudgetReallocationStatus status);

    /**
     * Command to publish a budget reallocation proposal.
     */
    record PublishProposalCommand(
        String budgetRecommendationId,
        String title,
        String description,
        List<BudgetReallocationProposal.BudgetAdjustment> adjustments,
        double totalReallocatedAmount,
        String rationale,
        Instant expiresAt
    ) {
        public PublishProposalCommand {
            Objects.requireNonNull(budgetRecommendationId, "budgetRecommendationId must not be null");
            if (budgetRecommendationId.isBlank()) throw new IllegalArgumentException("budgetRecommendationId must not be blank");
            Objects.requireNonNull(title, "title must not be null");
            if (title.isBlank()) throw new IllegalArgumentException("title must not be blank");
            Objects.requireNonNull(description, "description must not be null");
            Objects.requireNonNull(adjustments, "adjustments must not be null");
            if (adjustments.isEmpty()) throw new IllegalArgumentException("adjustments must not be empty");
            if (totalReallocatedAmount < 0.0) throw new IllegalArgumentException("totalReallocatedAmount must be non-negative");
            Objects.requireNonNull(rationale, "rationale must not be null");
            Objects.requireNonNull(expiresAt, "expiresAt must not be null");
        }
    }
}
