package com.ghatana.digitalmarketing.application.optimization;

import com.ghatana.digitalmarketing.contracts.DmOperationContext;
import com.ghatana.digitalmarketing.domain.optimization.ExperimentSuggestion;
import com.ghatana.digitalmarketing.domain.optimization.ExperimentSuggestionStatus;
import com.ghatana.digitalmarketing.domain.optimization.ExperimentType;
import io.activej.promise.Promise;

import java.time.Instant;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Application service for experiment suggestion management.
 *
 * <p>Experiment suggestions propose A/B tests to optimize campaign performance, such as testing
 * different creatives, targeting parameters, bidding strategies, or landing pages. These suggestions
 * are generated by AI agents analyzing historical performance, market trends, and statistical models.</p>
 *
 * @doc.type interface
 * @doc.purpose Handles creation, review, and lifecycle of experiment suggestions (P3-004)
 * @doc.layer product
 * @doc.pattern Service
 */
public interface ExperimentSuggestionService {

    /**
     * Publish a new experiment suggestion.
     *
     * @param ctx the operation context
     * @param command the publish command
     * @return Promise containing the created suggestion
     */
    Promise<ExperimentSuggestion> publish(DmOperationContext ctx, PublishSuggestionCommand command);

    /**
     * Approve a suggestion and link to the created experiment.
     *
     * @param ctx the operation context
     * @param suggestionId the suggestion ID
     * @param experimentId the created experiment ID
     * @param approvedBy the user who approved it
     * @return Promise containing the approved suggestion
     */
    Promise<ExperimentSuggestion> approve(DmOperationContext ctx, String suggestionId, String experimentId, String approvedBy);

    /**
     * Reject a suggestion with a reason.
     *
     * @param ctx the operation context
     * @param suggestionId the suggestion ID
     * @param reason the rejection reason
     * @return Promise containing the rejected suggestion
     */
    Promise<ExperimentSuggestion> reject(DmOperationContext ctx, String suggestionId, String reason);

    /**
     * Expire a suggestion that was not processed in time.
     *
     * @param ctx the operation context
     * @param suggestionId the suggestion ID
     * @return Promise containing the expired suggestion
     */
    Promise<ExperimentSuggestion> expire(DmOperationContext ctx, String suggestionId);

    /**
     * Find a suggestion by ID.
     *
     * @param ctx the operation context
     * @param suggestionId the suggestion ID
     * @return Promise containing optional suggestion
     */
    Promise<Optional<ExperimentSuggestion>> findById(DmOperationContext ctx, String suggestionId);

    /**
     * List all suggestions for a workspace.
     *
     * @param ctx the operation context
     * @return Promise containing list of suggestions
     */
    Promise<List<ExperimentSuggestion>> listByWorkspace(DmOperationContext ctx);

    /**
     * List suggestions for a campaign.
     *
     * @param ctx the operation context
     * @param campaignId the campaign ID
     * @return Promise containing list of suggestions
     */
    Promise<List<ExperimentSuggestion>> listByCampaign(DmOperationContext ctx, String campaignId);

    /**
     * List suggestions by status.
     *
     * @param ctx the operation context
     * @param status the status to filter by
     * @return Promise containing list of suggestions
     */
    Promise<List<ExperimentSuggestion>> listByStatus(DmOperationContext ctx, ExperimentSuggestionStatus status);

    /**
     * Command to publish an experiment suggestion.
     */
    record PublishSuggestionCommand(
        String campaignId,
        ExperimentType experimentType,
        String title,
        String description,
        Map<String, Object> controlVariant,
        Map<String, Object> treatmentVariant,
        String hypothesis,
        String successMetric,
        double minimumDetectableEffect,
        String rationale,
        Instant expiresAt
    ) {
        public PublishSuggestionCommand {
            Objects.requireNonNull(campaignId, "campaignId must not be null");
            if (campaignId.isBlank()) throw new IllegalArgumentException("campaignId must not be blank");
            Objects.requireNonNull(experimentType, "experimentType must not be null");
            Objects.requireNonNull(title, "title must not be null");
            if (title.isBlank()) throw new IllegalArgumentException("title must not be blank");
            Objects.requireNonNull(description, "description must not be null");
            Objects.requireNonNull(controlVariant, "controlVariant must not be null");
            Objects.requireNonNull(treatmentVariant, "treatmentVariant must not be null");
            Objects.requireNonNull(hypothesis, "hypothesis must not be null");
            Objects.requireNonNull(successMetric, "successMetric must not be null");
            if (minimumDetectableEffect <= 0.0) throw new IllegalArgumentException("minimumDetectableEffect must be positive");
            Objects.requireNonNull(rationale, "rationale must not be null");
            Objects.requireNonNull(expiresAt, "expiresAt must not be null");
        }
    }
}
