package com.ghatana.digitalmarketing.application.optimization;

import com.ghatana.digitalmarketing.contracts.DmOperationContext;
import com.ghatana.digitalmarketing.domain.optimization.NextBestActionRecommendation;
import com.ghatana.digitalmarketing.domain.optimization.NextBestActionStatus;
import io.activej.promise.Promise;

import java.time.Instant;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Application service for next-best-action recommendation management.
 *
 * <p>Next-best-action recommendations suggest optimal next steps to improve campaign performance,
 * such as adjusting budget, changing creative, targeting new audiences, or launching new campaigns.
 * These recommendations are generated by AI agents analyzing campaign metrics, historical performance,
 * and market conditions.</p>
 *
 * @doc.type interface
 * @doc.purpose Handles creation, review, and lifecycle of next-best-action recommendations (P3-004)
 * @doc.layer product
 * @doc.pattern Service
 */
public interface NextBestActionRecommendationService {

    /**
     * Publish a new next-best-action recommendation.
     *
     * @param ctx the operation context
     * @param command the publish command
     * @return Promise containing the created recommendation
     */
    Promise<NextBestActionRecommendation> publish(DmOperationContext ctx, PublishRecommendationCommand command);

    /**
     * Approve a recommendation for execution.
     *
     * @param ctx the operation context
     * @param recommendationId the recommendation ID
     * @param executedBy the user who approved it
     * @return Promise containing the approved recommendation
     */
    Promise<NextBestActionRecommendation> approve(DmOperationContext ctx, String recommendationId, String executedBy);

    /**
     * Reject a recommendation with a reason.
     *
     * @param ctx the operation context
     * @param recommendationId the recommendation ID
     * @param reason the rejection reason
     * @return Promise containing the rejected recommendation
     */
    Promise<NextBestActionRecommendation> reject(DmOperationContext ctx, String recommendationId, String reason);

    /**
     * Expire a recommendation that was not processed in time.
     *
     * @param ctx the operation context
     * @param recommendationId the recommendation ID
     * @return Promise containing the expired recommendation
     */
    Promise<NextBestActionRecommendation> expire(DmOperationContext ctx, String recommendationId);

    /**
     * Find a recommendation by ID.
     *
     * @param ctx the operation context
     * @param recommendationId the recommendation ID
     * @return Promise containing optional recommendation
     */
    Promise<Optional<NextBestActionRecommendation>> findById(DmOperationContext ctx, String recommendationId);

    /**
     * List all recommendations for a workspace.
     *
     * @param ctx the operation context
     * @return Promise containing list of recommendations
     */
    Promise<List<NextBestActionRecommendation>> listByWorkspace(DmOperationContext ctx);

    /**
     * List recommendations for a campaign.
     *
     * @param ctx the operation context
     * @param campaignId the campaign ID
     * @return Promise containing list of recommendations
     */
    Promise<List<NextBestActionRecommendation>> listByCampaign(DmOperationContext ctx, String campaignId);

    /**
     * List recommendations by status.
     *
     * @param ctx the operation context
     * @param status the status to filter by
     * @return Promise containing list of recommendations
     */
    Promise<List<NextBestActionRecommendation>> listByStatus(DmOperationContext ctx, NextBestActionStatus status);

    /**
     * Command to publish a next-best-action recommendation.
     */
    record PublishRecommendationCommand(
        String campaignId,
        NextBestActionType actionType,
        String title,
        String description,
        Map<String, Object> parameters,
        double confidenceScore,
        String rationale,
        Instant expiresAt
    ) {
        public PublishRecommendationCommand {
            Objects.requireNonNull(campaignId, "campaignId must not be null");
            if (campaignId.isBlank()) throw new IllegalArgumentException("campaignId must not be blank");
            Objects.requireNonNull(actionType, "actionType must not be null");
            Objects.requireNonNull(title, "title must not be null");
            if (title.isBlank()) throw new IllegalArgumentException("title must not be blank");
            Objects.requireNonNull(description, "description must not be null");
            Objects.requireNonNull(parameters, "parameters must not be null");
            if (confidenceScore < 0.0 || confidenceScore > 1.0) {
                throw new IllegalArgumentException("confidenceScore must be between 0.0 and 1.0");
            }
            Objects.requireNonNull(rationale, "rationale must not be null");
            Objects.requireNonNull(expiresAt, "expiresAt must not be null");
        }
    }
}
