/*
 * Copyright (c) 2026 Ghatana Platform Contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.ghatana.yappc.kernel;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.regex.Pattern;

/**
 * Validates ProductUnitIntent structure and content according to Kernel contract rules.
 *
 * <p>This service enforces validation rules to ensure ProductUnitIntent generated by YAPPC
 * conforms to Kernel requirements and security boundaries. It validates structure,
 * naming conventions, provider configuration, and ensures no sensitive data or
 * Kernel-specific file paths are included.
 *
 * <p><b>Validation Rules</b></p>
 * <ul>
 *   <li>Product ID must be kebab-case (lowercase with hyphens)</li>
 *   <li>Target provider must exist or be explicitly marked as external</li>
 *   <li>Surface list must be non-empty</li>
 *   <li>Lifecycle profile must be recognized if requested</li>
 *   <li>No raw secrets or sensitive values in metadata</li>
 *   <li>No Kernel-specific file paths unless target provider is ghatana-file-registry</li>
 * </ul>
 *
 * <p><b>Usage Example</b></p>
 * <pre>{@code
 * ProductUnitIntentValidationService validator = new ProductUnitIntentValidationService();
 *
 * Map<String, Object> intent = ...; // built intent map
 *
 * ValidationResult result = validator.validate(intent);
 * if (result.isValid()) {
 *     // proceed with export
 * } else {
 *     // handle validation errors
 *     result.errors().forEach(error -> log.error("Validation error: {}", error));
 * }
 * }</pre>
 *
 * @doc.type class
 * @doc.purpose Validates ProductUnitIntent structure and content against Kernel contract rules
 * @doc.layer product
 * @doc.pattern Service
 */
public final class ProductUnitIntentValidationService {

    private static final Logger log = LoggerFactory.getLogger(ProductUnitIntentValidationService.class);

    private static final Pattern KEBAB_CASE_PATTERN = Pattern.compile("^[a-z0-9]+(?:-[a-z0-9]+)*$");
    private static final java.util.Set<String> SECRET_KEY_PATTERNS = java.util.Set.of(
            "password",
            "secret",
            "token",
            "key",
            "credential",
            "api_key",
            "private_key"
    );
    private final ProductUnitKernelContractRegistry contractRegistry;

    /**
     * Creates a validation service using the default Kernel ProductUnit contract registry.
     */
    public ProductUnitIntentValidationService() {
        this(new ProductUnitKernelContractRegistry());
    }

    /**
     * Creates a validation service with an explicit Kernel contract registry.
     *
     * @param contractRegistry Kernel contract registry
     */
    public ProductUnitIntentValidationService(@NotNull ProductUnitKernelContractRegistry contractRegistry) {
        this.contractRegistry = contractRegistry;
    }

    /**
     * Result of ProductUnitIntent validation.
     */
    public static final class ValidationResult {
        private final boolean valid;
        private final List<String> errors;

        public ValidationResult(boolean valid, List<String> errors) {
            this.valid = valid;
            this.errors = List.copyOf(errors);
        }

        public boolean isValid() {
            return valid;
        }

        public List<String> errors() {
            return errors;
        }

        public static ValidationResult valid() {
            return new ValidationResult(true, List.of());
        }

        public static ValidationResult invalid(List<String> errors) {
            return new ValidationResult(false, errors);
        }
    }

    /**
     * Validates a ProductUnitIntent map against all validation rules.
     *
     * @param intent the ProductUnitIntent map to validate
     * @return ValidationResult indicating validity and any errors
     */
    public ValidationResult validate(@NotNull Map<String, Object> intent) {
        List<String> errors = new ArrayList<>();

        // Validate schema version
        validateSchemaVersion(intent, errors);

        // Validate intent ID
        validateIntentId(intent, errors);

        // Validate canonical Kernel intent fields
        validateIntentType(intent, errors);

        validateScope(intent, errors);

        // Validate producer
        validateProducer(intent, errors);

        // Validate target
        validateTarget(intent, errors);

        // Validate productUnit
        validateProductUnit(intent, errors);

        // Validate requestedLifecycle if present
        validateRequestedLifecycle(intent, errors);

        return errors.isEmpty() ? ValidationResult.valid() : ValidationResult.invalid(errors);
    }

    private void validateSchemaVersion(Map<String, Object> intent, List<String> errors) {
        Object schemaVersion = intent.get("schemaVersion");
        if (schemaVersion == null) {
            errors.add("schemaVersion is required");
        } else if (!"1.0.0".equals(schemaVersion)) {
            errors.add("schemaVersion must be '1.0.0', got: " + schemaVersion);
        }
    }

    private void validateIntentId(Map<String, Object> intent, List<String> errors) {
        Object intentId = intent.get("intentId");
        if (intentId == null) {
            errors.add("intentId is required");
        } else if (!(intentId instanceof String) || ((String) intentId).isBlank()) {
            errors.add("intentId must be a non-empty string");
        }
    }

    private void validateIntentType(Map<String, Object> intent, List<String> errors) {
        Object intentType = intent.get("intentType");
        if (intentType == null) {
            errors.add("intentType is required");
        } else if (!"create".equals(intentType)) {
            errors.add("intentType must be 'create', got: " + intentType);
        }
    }

    private void validateScope(Map<String, Object> intent, List<String> errors) {
        Object scope = intent.get("scope");
        if (scope == null) {
            errors.add("scope is required");
            return;
        }
        if (!(scope instanceof Map)) {
            errors.add("scope must be an object");
            return;
        }
        @SuppressWarnings("unchecked")
        Map<String, Object> scopeMap = (Map<String, Object>) scope;
        validateRequiredString(scopeMap, "scope.tenantId", "tenantId", errors);
        validateRequiredString(scopeMap, "scope.workspaceId", "workspaceId", errors);
        validateRequiredString(scopeMap, "scope.projectId", "projectId", errors);
    }

    private void validateProducer(Map<String, Object> intent, List<String> errors) {
        Object producer = intent.get("producer");
        if (producer == null) {
            errors.add("producer is required");
            return;
        }

        if (!(producer instanceof Map)) {
            errors.add("producer must be an object");
            return;
        }

        @SuppressWarnings("unchecked")
        Map<String, Object> producerMap = (Map<String, Object>) producer;

        Object producerId = producerMap.get("id");
        if (producerId == null) {
            errors.add("producer.id is required");
        } else if (!(producerId instanceof String) || ((String) producerId).isBlank()) {
            errors.add("producer.id must be a non-empty string");
        }

        Object producerType = producerMap.get("type");
        if (producerType == null) {
            errors.add("producer.type is required");
        } else if (!"yappc".equals(producerType)) {
            errors.add("producer.type must be 'yappc', got: " + producerType);
        }

        validateRequiredString(producerMap, "producer.correlationId", "correlationId", errors);
    }

    private void validateTarget(Map<String, Object> intent, List<String> errors) {
        Object target = intent.get("target");
        if (target == null) {
            errors.add("target is required");
            return;
        }

        if (!(target instanceof Map)) {
            errors.add("target must be an object");
            return;
        }

        @SuppressWarnings("unchecked")
        Map<String, Object> targetMap = (Map<String, Object>) target;

        Object registryProvider = targetMap.get("registryProvider");
        if (registryProvider == null) {
            errors.add("target.registryProvider is required");
        } else if (!(registryProvider instanceof String) || ((String) registryProvider).isBlank()) {
            errors.add("target.registryProvider must be a non-empty string");
        } else if (!contractRegistry.isProviderKnown((String) registryProvider)) {
            errors.add("target.registryProvider '" + registryProvider + "' is not a known provider. Mark as 'external' if intentional.");
        }

        Object sourceProvider = targetMap.get("sourceProvider");
        if (sourceProvider == null) {
            errors.add("target.sourceProvider is required");
        } else if (!(sourceProvider instanceof String) || ((String) sourceProvider).isBlank()) {
            errors.add("target.sourceProvider must be a non-empty string");
        }
    }

    private void validateProductUnit(Map<String, Object> intent, List<String> errors) {
        Object productUnit = intent.get("productUnit");
        if (productUnit == null) {
            errors.add("productUnit is required");
            return;
        }

        if (!(productUnit instanceof Map)) {
            errors.add("productUnit must be an object");
            return;
        }

        @SuppressWarnings("unchecked")
        Map<String, Object> productUnitMap = (Map<String, Object>) productUnit;

        // Validate id
        Object id = productUnitMap.get("id");
        if (id == null) {
            errors.add("productUnit.id is required");
        } else if (!(id instanceof String)) {
            errors.add("productUnit.id must be a string");
        } else if (!KEBAB_CASE_PATTERN.matcher((String) id).matches()) {
            errors.add("productUnit.id must be kebab-case (lowercase with hyphens), got: " + id);
        }

        // Validate name
        Object name = productUnitMap.get("name");
        if (name == null) {
            errors.add("productUnit.name is required");
        } else if (!(name instanceof String) || ((String) name).isBlank()) {
            errors.add("productUnit.name must be a non-empty string");
        }

        // Validate kind
        Object kind = productUnitMap.get("kind");
        if (kind == null) {
            errors.add("productUnit.kind is required");
        } else if (!(kind instanceof String) || ((String) kind).isBlank()) {
            errors.add("productUnit.kind must be a non-empty string");
        } else if (!contractRegistry.isProductUnitKindKnown((String) kind)) {
            errors.add("productUnit.kind '" + kind + "' is not a known Kernel ProductUnit kind");
        }

        // Validate surfaces
        Object surfaces = productUnitMap.get("surfaces");
        if (surfaces == null) {
            errors.add("productUnit.surfaces is required");
        } else if (!(surfaces instanceof List)) {
            errors.add("productUnit.surfaces must be a list");
        } else {
            @SuppressWarnings("unchecked")
            List<?> surfacesList = (List<?>) surfaces;
            if (surfacesList.isEmpty()) {
                errors.add("productUnit.surfaces must be non-empty");
            } else {
                for (Object surface : surfacesList) {
                    validateSurface(surface, errors);
                }
            }
        }

        // Validate lifecycle profile if present
        Object lifecycleProfile = productUnitMap.get("lifecycleProfile");
        if (lifecycleProfile != null) {
            if (!(lifecycleProfile instanceof String)) {
                errors.add("productUnit.lifecycleProfile must be a string");
            } else if (!contractRegistry.isLifecycleProfileKnown((String) lifecycleProfile)) {
                errors.add("productUnit.lifecycleProfile '" + lifecycleProfile + "' is not a recognized profile");
            }
        }

        // Validate metadata for secrets and Kernel file paths
        validateMetadata(productUnitMap, intent, errors);
    }

    private void validateMetadata(Map<String, Object> productUnitMap, Map<String, Object> intent, List<String> errors) {
        Object metadata = productUnitMap.get("metadata");
        if (metadata == null) {
            return;
        }

        if (!(metadata instanceof Map)) {
            errors.add("productUnit.metadata must be an object");
            return;
        }

        @SuppressWarnings("unchecked")
        Map<String, Object> metadataMap = (Map<String, Object>) metadata;

        // Check for secret keys
        for (String key : metadataMap.keySet()) {
            String lowerKey = key.toLowerCase();
            for (String secretPattern : SECRET_KEY_PATTERNS) {
                if (lowerKey.contains(secretPattern)) {
                    errors.add("productUnit.metadata contains potential secret key: " + key);
                }
            }
        }

        // Check for Kernel file paths
        Object target = intent.get("target");
        if (target instanceof Map) {
            @SuppressWarnings("unchecked")
            Map<String, Object> targetMap = (Map<String, Object>) target;
            Object registryProvider = targetMap.get("registryProvider");

            if (!"ghatana-file-registry".equals(registryProvider)) {
                // Check metadata values for Kernel file paths
                for (Object value : metadataMap.values()) {
                    if (value instanceof String) {
                        String strValue = (String) value;
                        if (strValue.contains("config/canonical-product-registry.json") ||
                            strValue.contains(".kernel/") ||
                            strValue.contains("/kernel/")) {
                            errors.add("productUnit.metadata contains Kernel-specific file path: " + strValue + 
                                      " (only allowed when registryProvider is ghatana-file-registry)");
                        }
                    }
                }
            }
        }
    }

    private void validateSurface(Object surface, List<String> errors) {
        if (!(surface instanceof Map)) {
            errors.add("productUnit.surfaces entries must be Kernel ProductUnitSurface objects");
            return;
        }
        @SuppressWarnings("unchecked")
        Map<String, Object> surfaceMap = (Map<String, Object>) surface;
        validateRequiredString(surfaceMap, "productUnit.surfaces[].id", "id", errors);

        Object type = surfaceMap.get("type");
        if (!(type instanceof String surfaceType) || surfaceType.isBlank()) {
            errors.add("productUnit.surfaces[].type must be a non-empty string");
        } else if (!contractRegistry.isSurfaceKnown(surfaceType)) {
            errors.add("productUnit.surfaces contains unknown surface type: " + surfaceType);
        }

        Object implementationStatus = surfaceMap.get("implementationStatus");
        if (implementationStatus != null) {
            if (!(implementationStatus instanceof String status) || status.isBlank()) {
                errors.add("productUnit.surfaces[].implementationStatus must be a non-empty string");
            } else if (!contractRegistry.isImplementationStatusKnown(status)) {
                errors.add("productUnit.surfaces contains unknown implementation status: " + status);
            }
        }
    }

    private void validateRequiredString(Map<String, Object> map, String fieldName, String key, List<String> errors) {
        Object value = map.get(key);
        if (value == null) {
            errors.add(fieldName + " is required");
        } else if (!(value instanceof String) || ((String) value).isBlank()) {
            errors.add(fieldName + " must be a non-empty string");
        }
    }

    private void validateRequestedLifecycle(Map<String, Object> intent, List<String> errors) {
        Object requestedLifecycle = intent.get("requestedLifecycle");
        if (requestedLifecycle == null) {
            return;
        }

        if (!(requestedLifecycle instanceof Map)) {
            errors.add("requestedLifecycle must be an object");
            return;
        }

        @SuppressWarnings("unchecked")
        Map<String, Object> lifecycleMap = (Map<String, Object>) requestedLifecycle;

        Object profile = lifecycleMap.get("profile");
        if (profile != null) {
            if (!(profile instanceof String)) {
                errors.add("requestedLifecycle.profile must be a string");
            } else if (!contractRegistry.isLifecycleProfileKnown((String) profile)) {
                errors.add("requestedLifecycle.profile '" + profile + "' is not a recognized profile");
            }
        }

        Object enableExecution = lifecycleMap.get("enableExecution");
        if (enableExecution != null && !(enableExecution instanceof Boolean)) {
            errors.add("requestedLifecycle.enableExecution must be a boolean");
        }
    }

    /**
     * Validates that a string is kebab-case.
     *
     * @param value the string to validate
     * @return true if kebab-case, false otherwise
     */
    public boolean isKebabCase(@Nullable String value) {
        return value != null && KEBAB_CASE_PATTERN.matcher(value).matches();
    }

    /**
     * Checks if a lifecycle profile is recognized.
     *
     * @param profile the profile name to check
     * @return true if recognized, false otherwise
     */
    public boolean isRecognizedLifecycleProfile(@Nullable String profile) {
        return contractRegistry.isLifecycleProfileKnown(profile);
    }

    /**
     * Gets the set of recognized lifecycle profiles.
     *
     * @return unmodifiable set of recognized profile names
     */
    public java.util.Set<String> getRecognizedLifecycleProfiles() {
        return contractRegistry.lifecycleProfiles();
    }
}
