.PHONY: build run test clean docker-build docker-run

APP_NAME={{projectName}}
VERSION?=0.1.0

build:
cargo build --release

run:
cargo run

test:
cargo test

test-coverage:
cargo tarpaulin --out Html

clean:
cargo clean

docker-build:
docker build -t $(APP_NAME):$(VERSION) .

docker-run:
docker run -p 8080:8080 $(APP_NAME):$(VERSION)

lint:
cargo clippy -- -D warnings

fmt:
cargo fmt

check:
cargo check