$target = "d:\samuj\Developments\ghatana\products\phr\src\main\java\com\ghatana\phr\api\routes\PhrRouteSupport.java"
$enc = New-Object System.Text.UTF8Encoding($false)
$lines = [System.Collections.Generic.List[string]]::new()
$lines.Add("package com.ghatana.phr.api.routes;")
$lines.Add("")
$lines.Add("import com.fasterxml.jackson.core.JsonProcessingException;")
$lines.Add("import com.fasterxml.jackson.databind.ObjectMapper;")
$lines.Add("import io.activej.http.HttpHeaders;")
$lines.Add("import io.activej.http.HttpRequest;")
$lines.Add("import io.activej.http.HttpResponse;")
$lines.Add("import io.activej.promise.Promise;")
$lines.Add("")
$lines.Add("import java.util.LinkedHashMap;")
$lines.Add("import java.util.Map;")
$lines.Add("import java.util.Set;")
$lines.Add("")
$lines.Add("/**")
$lines.Add(" * Shared helpers for PHR ActiveJ route adapters.")
$lines.Add(" *")
$lines.Add(" * <p>Security contract:")
$lines.Add(" * <ul>")
$lines.Add(" *   <li>All inbound context headers are validated for presence, non-blank content,")
$lines.Add(" *       and role membership before any business logic executes.</li>")
$lines.Add(" *   <li>Unknown roles throw {@link IllegalArgumentException};</li>")
$lines.Add(" *   <li>Header values are trimmed but not further sanitised.</li>")
$lines.Add(" * </ul>")
$lines.Add(" *")
$lines.Add(" * @doc.type class")
$lines.Add(" * @doc.purpose Common JSON and identity handling for PHR route adapters")
$lines.Add(" * @doc.layer product")
$lines.Add(" * @doc.pattern Adapter Helper")
$lines.Add(" */")
$lines.Add("final class PhrRouteSupport {")
$lines.Add("")
$lines.Add("    static final String CONTENT_JSON = `"application/json`";")
$lines.Add("    static final ObjectMapper JSON = new ObjectMapper().findAndRegisterModules();")
$lines.Add("")
$lines.Add("    /** Roles permitted to call PHR routes. */")
$lines.Add("    static final Set<String> ALLOWED_ROLES = Set.of(`"patient`", `"caregiver`", `"clinician`", `"admin`");")
$lines.Add("")
$lines.Add("    /** Roles with elevated access beyond basic patient operations. */")
$lines.Add("    private static final Set<String> PRIVILEGED_ROLES = Set.of(`"admin`", `"clinician`");")
$lines.Add("")
$lines.Add("    private PhrRouteSupport() {}")
$lines.Add("")
$lines.Add("    /**")
$lines.Add("     * Extracts and validates the request context from inbound security headers.")
$lines.Add("     *")
$lines.Add("     * @param request the inbound HTTP request")
$lines.Add("     * @return a validated request context")
$lines.Add("     * @throws IllegalArgumentException if any required header is absent, blank, or unrecognised")
$lines.Add("     */")
$lines.Add("    static PhrRequestContext requireContext(HttpRequest request) {")
$lines.Add("        String tenantId = firstHeader(request, `"X-Tenant-ID`", `"X-Tenant-Id`");")
$lines.Add("        String principalId = firstHeader(request, `"X-Principal-ID`", `"X-Principal-Id`");")
$lines.Add("        String role = firstHeader(request, `"X-Role`");")
$lines.Add("")
$lines.Add("        if (tenantId == null || tenantId.isBlank()) {")
$lines.Add("            throw new IllegalArgumentException(`"X-Tenant-ID header is required`");")
$lines.Add("        }")
$lines.Add("        if (principalId == null || principalId.isBlank()) {")
$lines.Add("            throw new IllegalArgumentException(`"X-Principal-ID header is required`");")
$lines.Add("        }")
$lines.Add("        if (role == null || role.isBlank()) {")
$lines.Add("            throw new IllegalArgumentException(`"X-Role header is required`");")
$lines.Add("        }")
$lines.Add("        String normalisedRole = role.strip().toLowerCase();")
$lines.Add("        if (!ALLOWED_ROLES.contains(normalisedRole)) {")
$lines.Add("            throw new IllegalArgumentException(`"Unrecognised role: `" + role);")
$lines.Add("        }")
$lines.Add("        String correlationId = extractCorrelationId(request);")
$lines.Add("        return new PhrRequestContext(tenantId.strip(), principalId.strip(), normalisedRole, correlationId);")
$lines.Add("    }")
$lines.Add("")
$lines.Add("    /**")
$lines.Add("     * Extracts the correlation ID from the inbound request headers.")
$lines.Add("     * Returns a fallback string if no correlation header is present.")
$lines.Add("     *")
$lines.Add("     * @param request the inbound HTTP request")
$lines.Add("     * @return the correlation ID string; never null")
$lines.Add("     */")
$lines.Add("    static String extractCorrelationId(HttpRequest request) {")
$lines.Add("        String value = firstHeader(request, `"X-Correlation-ID`", `"X-Correlation-Id`", `"X-Request-ID`");")
$lines.Add("        return (value != null && !value.isBlank()) ? value.strip() : `"no-correlation-id`";")
$lines.Add("    }")
$lines.Add("")
$lines.Add("    /**")
$lines.Add("     * Returns true if the context holder has elevated (clinician/admin) access.")
$lines.Add("     *")
$lines.Add("     * @deprecated Prefer explicit policy methods such as hasClinicalRole.")
$lines.Add("     */")
$lines.Add("    @Deprecated(forRemoval = true)")
$lines.Add("    static boolean isPrivileged(PhrRequestContext context) {")
$lines.Add("        return PRIVILEGED_ROLES.contains(context.role());")
$lines.Add("    }")
$lines.Add("")
$lines.Add("    /**")
$lines.Add("     * Returns true if the context holder has clinical read access (clinician or admin).")
$lines.Add("     *")
$lines.Add("     * @param context the validated request context")
$lines.Add("     * @return true for clinician or admin roles")
$lines.Add("     */")
$lines.Add("    static boolean hasClinicalRole(PhrRequestContext context) {")
$lines.Add("        return `"clinician`".equals(context.role()) || `"admin`".equals(context.role());")
$lines.Add("    }")
$lines.Add("")
$lines.Add("    /**")
$lines.Add("     * Returns true if the context holder may perform administrative operations.")
$lines.Add("     *")
$lines.Add("     * @param context the validated request context")
$lines.Add("     * @return true only for admin role")
$lines.Add("     */")
$lines.Add("    static boolean canPerformAdminOperation(PhrRequestContext context) {")
$lines.Add("        return `"admin`".equals(context.role());")
$lines.Add("    }")
$lines.Add("")
$lines.Add("    /**")
$lines.Add("     * Determines whether the context holder may access a given patient record.")
$lines.Add("     *")
$lines.Add("     * <p>Patients may only access their own record. Clinicians and admins may access any record.")
$lines.Add("     * Caregivers are provisionally granted access; consent must be verified in the service layer.")
$lines.Add("     *")
$lines.Add("     * @param context   the validated request context")
$lines.Add("     * @param patientId the target patient ID")
$lines.Add("     * @return true if access is provisionally allowed")
$lines.Add("     */")
$lines.Add("    static boolean canAccessPatientRecordForRole(PhrRequestContext context, String patientId) {")
$lines.Add("        return switch (context.role()) {")
$lines.Add("            case `"admin`", `"clinician`" -> true;")
$lines.Add("            case `"caregiver`" -> true; // consent verified by service layer")
$lines.Add("            case `"patient`" -> context.principalId().equals(patientId);")
$lines.Add("            default -> false;")
$lines.Add("        };")
$lines.Add("    }")
$lines.Add("")
$lines.Add("    static Promise<HttpResponse> jsonResponse(int statusCode, Object body) {")
$lines.Add("        try {")
$lines.Add("            String json = body instanceof String s ? s : JSON.writeValueAsString(body);")
$lines.Add("            return Promise.of(HttpResponse.ofCode(statusCode)")
$lines.Add("                .withHeader(HttpHeaders.CONTENT_TYPE, CONTENT_JSON)")
$lines.Add("                .withJson(json)")
$lines.Add("                .build());")
$lines.Add("        } catch (JsonProcessingException ex) {")
$lines.Add("            return Promise.of(HttpResponse.ofCode(500)")
$lines.Add("                .withHeader(HttpHeaders.CONTENT_TYPE, CONTENT_JSON)")
$lines.Add("                .withJson(`"{`\`"error`\`":`\`"SERIALIZATION_ERROR`\`",`\`"message`\`":`\`"Failed to serialize response`\`"}`")")
$lines.Add("                .build());")
$lines.Add("        }")
$lines.Add("    }")
$lines.Add("")
$lines.Add("    static Promise<HttpResponse> jsonResponse(int statusCode, Object body, String correlationId) {")
$lines.Add("        try {")
$lines.Add("            String json = body instanceof String s ? s : JSON.writeValueAsString(body);")
$lines.Add("            return Promise.of(HttpResponse.ofCode(statusCode)")
$lines.Add("                .withHeader(HttpHeaders.CONTENT_TYPE, CONTENT_JSON)")
$lines.Add("                .withHeader(HttpHeaders.of(`"X-Correlation-ID`"), correlationId)")
$lines.Add("                .withJson(json)")
$lines.Add("                .build());")
$lines.Add("        } catch (JsonProcessingException ex) {")
$lines.Add("            return Promise.of(HttpResponse.ofCode(500)")
$lines.Add("                .withHeader(HttpHeaders.CONTENT_TYPE, CONTENT_JSON)")
$lines.Add("                .withJson(`"{`\`"error`\`":`\`"SERIALIZATION_ERROR`\`",`\`"message`\`":`\`"Failed to serialize response`\`"}`")")
$lines.Add("                .build());")
$lines.Add("        }")
$lines.Add("    }")
$lines.Add("")
$lines.Add("    static Promise<HttpResponse> errorResponse(int statusCode, String code, String message) {")
$lines.Add("        Map<String, Object> body = new LinkedHashMap<>();")
$lines.Add("        body.put(`"error`", code);")
$lines.Add("        body.put(`"message`", message);")
$lines.Add("        return jsonResponse(statusCode, body);")
$lines.Add("    }")
$lines.Add("")
$lines.Add("    static Promise<HttpResponse> errorResponse(int statusCode, String code, String message, String correlationId) {")
$lines.Add("        Map<String, Object> body = new LinkedHashMap<>();")
$lines.Add("        body.put(`"error`", code);")
$lines.Add("        body.put(`"message`", message);")
$lines.Add("        body.put(`"correlationId`", correlationId);")
$lines.Add("        return jsonResponse(statusCode, body, correlationId);")
$lines.Add("    }")
$lines.Add("")
$lines.Add("    static String requiredQuery(HttpRequest request, String name) {")
$lines.Add("        String value = request.getQueryParameter(name);")
$lines.Add("        if (value == null || value.isBlank()) {")
$lines.Add("            throw new IllegalArgumentException(name + `" query parameter is required`");")
$lines.Add("        }")
$lines.Add("        return value;")
$lines.Add("    }")
$lines.Add("")
$lines.Add("    static int intQuery(HttpRequest request, String name, int defaultValue, int maxValue) {")
$lines.Add("        String value = request.getQueryParameter(name);")
$lines.Add("        if (value == null || value.isBlank()) {")
$lines.Add("            return defaultValue;")
$lines.Add("        }")
$lines.Add("        int parsed = Integer.parseInt(value);")
$lines.Add("        if (parsed < 0 || parsed > maxValue) {")
$lines.Add("            throw new IllegalArgumentException(name + `" must be between 0 and `" + maxValue);")
$lines.Add("        }")
$lines.Add("        return parsed;")
$lines.Add("    }")
$lines.Add("")
$lines.Add("    private static String firstHeader(HttpRequest request, String... names) {")
$lines.Add("        for (String name : names) {")
$lines.Add("            String value = request.getHeader(HttpHeaders.of(name));")
$lines.Add("            if (value != null) {")
$lines.Add("                return value;")
$lines.Add("            }")
$lines.Add("        }")
$lines.Add("        return null;")
$lines.Add("    }")
$lines.Add("")
$lines.Add("    record PhrRequestContext(String tenantId, String principalId, String role, String correlationId) {}")
$lines.Add("}")
[System.IO.File]::WriteAllLines($target, $lines, $enc)
Write-Host "Done. Lines: $($lines.Count)"
