/**
 * Unified Authoring Page
 *
 * Single canvas for all content authoring that combines:
 * - Content Studio (creation flow)
 * - AI Kernel (invisible infrastructure)
 * - Dashboard (default view when no content selected)
 * - Templates & Seeding (part of library)
 *
 * Design Principles:
 * - AI is the medium, not a destination
 * - Zero modal wizards - inline progressive disclosure
 * - Everything happens in one canvas
 * - Command palette for power users (Cmd+K)
 *
 * @doc.type page
 * @doc.purpose Unified AI-first content authoring
 * @doc.layer product
 * @doc.pattern Canvas
 */

import { useState, useCallback, useEffect, useMemo } from "react";
import { Provider as JotaiProvider } from "jotai";
import {
  useNavigate,
  useParams,
  Link,
} from "react-router-dom";
import {
  ContextIndicator,
  Button,
  ConfirmDialog,
  Tour,
  useTour,
  useFormValidation,
  validators,
  FormField,
  PullToRefresh,
  Skeleton,
} from "@ghatana/design-system";
import type { TourStep } from "@ghatana/design-system";
import {
  Plus,
  Search,
  Grid3X3,
  List,
  Sparkles,
  BookOpen,
  Beaker,
  Play,
  CheckCircle,
  Lightbulb,
  AlertTriangle,
  FileText,
  Settings,
  MoreHorizontal,
  Trash2,
  Share2,
  Eye,
  X,
  Send,
  Bot,
  User,
  Zap,
  Film,
} from "lucide-react";

import { AnimationStudio } from "../components/animation/AnimationStudio";
import { AnalyticsDashboard } from "../components/content-studio/AnalyticsDashboard";
import { GenerationGovernancePanel } from "../components/content-studio/GenerationGovernancePanel";
import { PublicationReadinessPanel } from "../components/content-studio/PublicationReadinessPanel";
import {
  AuthoringStepperPanel,
  type AuthoringStep,
} from "../components/content-studio/AuthoringStepperPanel";
import { FailedJobsPanel } from "../components/content-studio/FailedJobsPanel";
import {
  contentStudioApi,
  type AdminContentAsset,
  type AdminContentAssetDetail,
  type AdminExperience,
} from "../services/contentStudioApi";
import type {
  SimulationManifest,
  SimulationDomain,
} from "@tutorputor/contracts/v1/simulation";
import {
  AUTHORING_WORKFLOW_STEPS,
  getAuthoringWorkflowCurrentStep,
} from "./authoring-workflow";

const SimulationStudio = (_props: Record<string, unknown>) => null;
type AnimationSpec = Record<string, unknown>;

// Types
interface ContentItem {
  id: string;
  assetId?: string;
  legacyExperienceId?: string;
  title: string;
  description: string;
  type: "learning_experience" | "simulation" | "animation" | "assessment";
  status: "draft" | "review" | "published" | "archived";
  domain: string;
  gradeRange: string;
  currentVersion?: number;
  updatedAt: Date;
  author: string;
  metrics?: {
    views: number;
    completions: number;
    rating: number;
  };
}

interface AISuggestion {
  id: string;
  type: "action" | "insight" | "warning";
  title: string;
  description: string;
  action?: () => void;
}

type ViewMode = "library" | "editor" | "preview";
type LibraryView = "grid" | "list";

interface ComprehensiveExperienceResponse {
  data: {
    id: string;
    title?: string;
    intentProblem?: string;
    status?: string;
    domain?: string;
    targetGrades?: string[];
    updatedAt?: string;
    createdBy?: string;
    claims?: Array<{
      id: string;
      claimRef?: string;
      text?: string;
      bloomLevel?: string;
      tasks?: Array<{
        id: string;
        taskRef?: string;
        prompt?: string;
        type?: string;
      }>;
    }>;
  };
}

interface PersistedAnimationLink {
  contentId: string;
  claimId: string;
  animationId: string;
  animationType: "demonstration" | "exploration" | "assessment";
  autoGenerated: boolean;
  metadata?: {
    concept?: string;
    difficulty?: string;
    estimatedDuration?: number;
  };
  spec?: AnimationSpec;
}

interface PersistedSimulationLink {
  id: string;
  claimRef: string;
  simulationManifestId: string;
  interactionType?: string;
  goal?: string;
  estimatedMinutes?: number;
  simulationManifest?: {
    id: string;
    title?: string;
    description?: string;
    domain?: string;
    version?: string;
    manifest?: SimulationManifest;
  };
}

interface SimulationRefinementResult {
  success: boolean;
  manifest?: SimulationManifest;
  response: string;
  suggestions: string[];
}

type ToastLevel = "success" | "error" | "info";

const toast = {
  success(message: string) {
    console.info(`[authoring:${"success" satisfies ToastLevel}] ${message}`);
  },
  error(message: string) {
    console.error(`[authoring:${"error" satisfies ToastLevel}] ${message}`);
  },
  info(message: string) {
    console.info(`[authoring:${"info" satisfies ToastLevel}] ${message}`);
  },
};

function useAnnouncer() {
  return (message: string, delayMs: number = 0) => {
    if (typeof window === "undefined") {
      return;
    }

    window.setTimeout(() => {
      const liveRegion = document.getElementById("authoring-live-region");
      if (liveRegion) {
        liveRegion.textContent = message;
      }
    }, delayMs);
  };
}

function SkeletonCard() {
  return (
    <div className="rounded-lg border border-gray-200 p-4 dark:border-gray-700">
      <Skeleton className="h-5 w-1/2" />
      <Skeleton className="mt-3 h-4 w-full" />
      <Skeleton className="mt-2 h-4 w-2/3" />
    </div>
  );
}

function BreadcrumbRouter({
  items,
  LinkComponent,
  className,
}: {
  items: Array<{ id: string; label: string; href?: string }>;
  LinkComponent: typeof Link;
  showHomeIcon?: boolean;
  className?: string;
}) {
  return (
    <nav aria-label="Breadcrumb" className={className}>
      <ol className="flex flex-wrap items-center gap-2 text-sm text-gray-500 dark:text-gray-400">
        {items.map((item, index) => {
          const isLast = index === items.length - 1;
          return (
            <li key={item.id} className="flex items-center gap-2">
              {item.href && !isLast ? (
                <LinkComponent to={item.href} className="hover:text-primary-600">
                  {item.label}
                </LinkComponent>
              ) : (
                <span className={isLast ? "font-medium text-gray-900 dark:text-white" : undefined}>
                  {item.label}
                </span>
              )}
              {!isLast ? <span aria-hidden="true">/</span> : null}
            </li>
          );
        })}
      </ol>
    </nav>
  );
}

type ConfirmDialogState = {
  title: string;
  message: string;
  confirmText?: string;
  confirmVariant?: "primary" | "danger" | "warning" | "destructive";
};

function getAuthoringApiHeaders(
  includeContentType: boolean = true,
): HeadersInit {
  const token = localStorage.getItem("auth_token");

  return {
    ...(includeContentType ? { "Content-Type": "application/json" } : {}),
    ...(token ? { Authorization: `Bearer ${token}` } : {}),
  };
}

function mapExperienceSummaryToContentItem(
  experience: Record<string, unknown>,
  existing?: Partial<ContentItem>,
): ContentItem {
  return {
    id: experience.id as string,
    assetId: existing?.assetId,
    legacyExperienceId:
      existing?.legacyExperienceId ?? (experience.id as string),
    title: (experience.title as string) ?? "Untitled",
    description: (experience.intentProblem as string) ?? "",
    type: "learning_experience",
    status: ((experience.status as string) ?? "draft").toLowerCase() as ContentItem["status"],
    domain: (experience.domain as string) ?? "",
    gradeRange: Array.isArray(experience.targetGrades)
      ? (experience.targetGrades as string[]).join(", ")
      : "",
    currentVersion: existing?.currentVersion,
    updatedAt: new Date((experience.updatedAt as string) ?? Date.now()),
    author: (experience.createdBy as string) ?? "Unknown",
  };
}

function mapAssetTypeToContentType(
  assetType: AdminContentAsset["assetType"],
): ContentItem["type"] {
  switch (assetType) {
    case "simulation":
      return "simulation";
    case "animation":
      return "animation";
    case "assessment":
      return "assessment";
    default:
      return "learning_experience";
  }
}

function mapContentAssetToContentItem(asset: AdminContentAsset): ContentItem {
  const routeId = asset.legacyExperienceId ?? asset.id;

  return {
    id: routeId,
    assetId: asset.id,
    legacyExperienceId: asset.legacyExperienceId,
    title: asset.title,
    description: "",
    type: mapAssetTypeToContentType(asset.assetType),
    status: asset.status as ContentItem["status"],
    domain: asset.domain,
    gradeRange: (asset.targetGrades ?? []).join(", "),
    currentVersion: asset.currentVersion,
    updatedAt: new Date(asset.updatedAt),
    author: asset.authorId,
  };
}

function getExperienceRouteId(
  content: Pick<ContentItem, "id" | "legacyExperienceId">,
): string {
  return content.legacyExperienceId ?? content.id;
}

function mapAdminExperienceToContentItem(
  experience: AdminExperience,
): ContentItem {
  return {
    id: experience.id,
    legacyExperienceId: experience.id,
    title: experience.title,
    description: experience.description,
    type: "learning_experience",
    status: experience.status,
    domain: experience.subject,
    gradeRange: experience.gradeLevel,
    updatedAt: new Date(experience.updatedAt),
    author: "system",
  };
}

function applyCanonicalAssetDetailToContentItem(
  item: ContentItem,
  detail: AdminContentAssetDetail,
): ContentItem {
  const snapshot = detail.currentRevision?.snapshot ?? {};
  const snapshotDescription =
    typeof snapshot.intentProblem === "string"
      ? snapshot.intentProblem
      : typeof snapshot.description === "string"
        ? snapshot.description
        : item.description;
  const snapshotDomain =
    typeof snapshot.domain === "string" ? snapshot.domain : item.domain;
  const snapshotTargetGrades = Array.isArray(snapshot.targetGrades)
    ? snapshot.targetGrades.filter(
      (grade): grade is string => typeof grade === "string",
    )
    : [];

  return {
    ...item,
    assetId: detail.asset.id,
    legacyExperienceId: detail.asset.legacyExperienceId ?? item.legacyExperienceId,
    title: detail.asset.title || item.title,
    description: snapshotDescription,
    status: detail.asset.status as ContentItem["status"],
    domain: detail.asset.domain || snapshotDomain,
    gradeRange:
      snapshotTargetGrades.length > 0
        ? snapshotTargetGrades.join(", ")
        : item.gradeRange || detail.asset.targetGrades.join(", "),
    currentVersion: detail.asset.currentVersion,
    updatedAt: new Date(detail.asset.updatedAt),
    author: detail.asset.authorId || item.author,
  };
}

// Main component wrapped with Jotai provider for simulation state
export function AuthoringPage() {
  return (
    <JotaiProvider>
      <AuthoringPageContent />
    </JotaiProvider>
  );
}

// Main page content
function AuthoringPageContent() {
  const navigate = useNavigate();
  const { id: editId } = useParams();
  const announce = useAnnouncer();

  // State
  const [_viewMode, setViewMode] = useState<ViewMode>(
    editId ? "editor" : "library",
  );
  const [libraryView, setLibraryView] = useState<LibraryView>("grid");
  const [selectedContent, setSelectedContent] = useState<ContentItem | null>(
    null,
  );
  const [searchQuery, setSearchQuery] = useState("");
  const [filterStatus, setFilterStatus] = useState<string>("all");
  const [filterType, setFilterType] = useState<string>("all");
  const [isAICoPilotOpen, setIsAICoPilotOpen] = useState(true);
  const [newContentInput, setNewContentInput] = useState("");
  const [isCreating, setIsCreating] = useState(false);
  const [aiSuggestions, setAiSuggestions] = useState<AISuggestion[]>([]);
  const [isLoading, _setIsLoading] = useState(false);
  const [isDeleting, setIsDeleting] = useState(false);
  const [_isRefreshing, setIsRefreshing] = useState(false);
  const [contentItems, setContentItems] = useState<ContentItem[]>([]);

  const loadContentItems = useCallback(async () => {
    const assetLibrary = await contentStudioApi.getContentAssets({
      assetType: "explainer",
      limit: 50,
    });
    const items: ContentItem[] = assetLibrary.items
      .filter((asset) => Boolean(asset.legacyExperienceId))
      .map(mapContentAssetToContentItem);

    setContentItems(items);
    return items;
  }, []);

  const openContentItem = useCallback(async (item: ContentItem) => {
    setSelectedContent(item);
    setViewMode("editor");

    if (!item.assetId) {
      return;
    }

    try {
      const detail = await contentStudioApi.getContentAsset(item.assetId);
      if (!detail) {
        return;
      }

      const enriched = applyCanonicalAssetDetailToContentItem(item, detail);
      setSelectedContent(enriched);
      setContentItems((prev) =>
        prev.map((candidate) =>
          candidate.id === enriched.id ? enriched : candidate,
        ),
      );
    } catch (error) {
      console.error("Failed to load canonical content detail", error);
    }
  }, []);

  // Pull-to-refresh handler for mobile
  const handleRefreshContent = useCallback(async () => {
    setIsRefreshing(true);
    try {
      await loadContentItems();
      announce("Content library refreshed");
      toast.success("Content refreshed");
    } catch (_error) {
      toast.error("Failed to refresh content.");
    } finally {
      setIsRefreshing(false);
    }
  }, [announce, loadContentItems]);

  // Delete confirmation dialog
  const {
    dialogProps,
    confirmDelete,
    closeDeleteDialog,
  } = useDeleteDialogController();
  const [contentToDelete, setContentToDelete] = useState<ContentItem | null>(
    null,
  );

  // Onboarding tour
  const {
    active: isTourActive,
    complete: completeTour,
    skip: skipTour,
  } = useTour("authoring-tour");

  const tourSteps: TourStep[] = useMemo(
    () => [
      {
        id: "create-button",
        target: "#create-content-btn",
        title: "Create Content",
        content:
          "Start by describing what you want to create. Our AI will help structure your learning experience.",
        placement: "bottom",
      },
      {
        id: "content-library",
        target: "#content-library",
        title: "Your Content Library",
        content:
          "All your learning experiences, simulations, and animations appear here. Use filters to find what you need.",
        placement: "right",
      },
      {
        id: "ai-copilot",
        target: "#ai-copilot",
        title: "AI Co-Pilot",
        content:
          "Your AI assistant is always ready to help. Ask questions, get suggestions, or generate content.",
        placement: "left",
      },
      {
        id: "editor-tabs",
        target: "#editor-tabs",
        title: "Content Editor",
        content:
          "Each piece of content has claims, tasks, simulations, and animations. Navigate between them using these tabs.",
        placement: "bottom",
      },
    ],
    [],
  );

  // Delete handler with confirmation
  const handleDeleteContent = useCallback(
    async (content: ContentItem) => {
      setContentToDelete(content);
      confirmDelete({
        title: "Delete Content",
        message: `Are you sure you want to delete "${content.title}"? This action cannot be undone.`,
        confirmText: "Delete",
        confirmVariant: "destructive",
      });
    },
    [confirmDelete],
  );

  const executeDelete = useCallback(async () => {
    if (!contentToDelete) return;

    setIsDeleting(true);
    try {
      await contentStudioApi.deleteExperience(
        getExperienceRouteId(contentToDelete),
      );

      setContentItems((prev) =>
        prev.filter((item) => item.id !== contentToDelete.id),
      );

      if (selectedContent?.id === contentToDelete.id) {
        setSelectedContent(null);
        setViewMode("library");
      }

      toast.success(`"${contentToDelete.title}" has been deleted`);
      announce(`${contentToDelete.title} deleted`);
    } catch (_error) {
      toast.error("Failed to delete content. Please try again.");
    } finally {
      setIsDeleting(false);
      setContentToDelete(null);
      closeDeleteDialog();
    }
  }, [closeDeleteDialog, contentToDelete, selectedContent, announce]);

  // Load content from API
  useEffect(() => {
    void loadContentItems().catch((err) =>
      console.error("Failed to load content items", err),
    );
  }, [loadContentItems]);

  useEffect(() => {
    if (!editId || editId === "new") {
      return;
    }

    const existing = contentItems.find((item) => item.id === editId);
    if (existing) {
      void openContentItem(existing);
      return;
    }

    void contentStudioApi
      .getExperience(editId)
      .then((experience) => {
        if (!experience) {
          return;
        }

        const mapped = mapAdminExperienceToContentItem(experience);
        setSelectedContent(mapped);
        setViewMode("editor");
        setContentItems((prev) => {
          if (prev.some((item) => item.id === mapped.id)) {
            return prev;
          }
          return [mapped, ...prev];
        });
      })
      .catch((error) => {
        console.error("Failed to load experience for authoring route", error);
      });
  }, [contentItems, editId, openContentItem]);

  // Initialize AI suggestions based on context
  useEffect(() => {
    const suggestions: AISuggestion[] = [
      {
        id: "1",
        type: "insight",
        title: "Trending Topic",
        description:
          "Climate change content is in high demand. Consider creating related materials.",
        action: () =>
          setNewContentInput(
            "Create an interactive learning experience about climate change",
          ),
      },
      {
        id: "2",
        type: "action",
        title: "Review Needed",
        description: "3 items are waiting for your review",
        action: () => {
          setFilterStatus("review");
        },
      },
      {
        id: "3",
        type: "warning",
        title: "Low Engagement",
        description:
          '"Algebra Basics" has declining completion rates. Consider revising.',
      },
    ];
    setAiSuggestions(suggestions);
  }, []);

  // Handle new content creation via natural language
  const handleCreateContent = useCallback(async () => {
    if (!newContentInput.trim()) return;

    setIsCreating(true);
    try {
      // Call AI to analyze intent and generate structure
      const token = localStorage.getItem("auth_token");
      const response = await fetch("/api/content-studio/ai/analyze-intent", {
        method: "POST",
        headers: getAuthoringApiHeaders(),
        body: JSON.stringify({ intent: newContentInput }),
      });

      if (response.ok) {
        await response.json();
        // Navigate to editor with generated structure
        navigate(
          `/authoring/new?intent=${encodeURIComponent(newContentInput)}`,
        );
      } else {
        // Fallback: create with basic structure
        navigate(
          `/authoring/new?intent=${encodeURIComponent(newContentInput)}`,
        );
      }
    } catch (error) {
      console.error("Failed to analyze intent:", error);
      // Fallback: navigate anyway
      navigate(`/authoring/new?intent=${encodeURIComponent(newContentInput)}`);
    } finally {
      setIsCreating(false);
    }
  }, [newContentInput, navigate]);

  // Filter content items
  const filteredContent = contentItems.filter((item) => {
    const matchesSearch =
      item.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
      item.description.toLowerCase().includes(searchQuery.toLowerCase());
    const matchesStatus =
      filterStatus === "all" || item.status === filterStatus;
    const matchesType = filterType === "all" || item.type === filterType;
    return matchesSearch && matchesStatus && matchesType;
  });

  // Announce filter results for screen readers
  useEffect(() => {
    if (searchQuery || filterStatus !== "all" || filterType !== "all") {
      const count = filteredContent.length;
      const message =
        count === 0
          ? "No content found matching filters"
          : `${count} ${count === 1 ? "item" : "items"} found`;
      announce(message, 1000);
    }
  }, [filteredContent.length, searchQuery, filterStatus, filterType, announce]);

  // Content type icons
  const getTypeIcon = (type: ContentItem["type"]) => {
    switch (type) {
      case "learning_experience":
        return <BookOpen className="w-4 h-4" />;
      case "simulation":
        return <Beaker className="w-4 h-4" />;
      case "animation":
        return <Play className="w-4 h-4" />;
      case "assessment":
        return <FileText className="w-4 h-4" />;
    }
  };

  // Status badges
  const getStatusBadge = (status: ContentItem["status"]) => {
    const styles = {
      draft: "bg-gray-100 text-gray-700 dark:bg-gray-700 dark:text-gray-300",
      review:
        "bg-yellow-100 text-yellow-700 dark:bg-yellow-900/30 dark:text-yellow-400",
      published:
        "bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400",
      archived: "bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400",
    };
    return (
      <span
        className={`inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium ${styles[status]}`}
      >
        {status.charAt(0).toUpperCase() + status.slice(1)}
      </span>
    );
  };

  const currentWorkflowStep = getAuthoringWorkflowCurrentStep({
    hasSelectedContent: selectedContent != null,
    contentStatus: selectedContent?.status,
  });

  return (
    <>
      <div id="authoring-live-region" aria-live="polite" className="sr-only" />
      <div className="h-screen flex bg-gray-50 dark:bg-gray-900 overflow-hidden">
        {/* Content Library Sidebar */}
        <aside
          id="content-library"
          className="w-72 bg-white dark:bg-gray-800 border-r border-gray-200 dark:border-gray-700 flex flex-col"
        >
          {/* Library Header */}
          <div className="p-4 border-b border-gray-200 dark:border-gray-700">
            <h2 className="text-lg font-semibold text-gray-900 dark:text-white">
              Content Library
            </h2>

            {/* Search */}
            <div className="mt-3 relative">
              <label htmlFor="content-search" className="sr-only">
                Search content
              </label>
              <Search
                className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400"
                aria-hidden="true"
              />
              <input
                id="content-search"
                type="text"
                placeholder="Search content..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                aria-label="Search content by title, description, or domain"
                className="w-full pl-9 pr-3 py-2 text-sm bg-gray-50 dark:bg-gray-700 border border-gray-200 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-primary-500 focus:border-transparent"
              />
            </div>

            {/* Filters */}
            <div className="mt-3 flex gap-2">
              <div className="flex-1">
                <label htmlFor="filter-status" className="sr-only">
                  Filter by status
                </label>
                <select
                  id="filter-status"
                  value={filterStatus}
                  onChange={(e) => setFilterStatus(e.target.value)}
                  aria-label="Filter content by status"
                  className="w-full text-xs bg-gray-50 dark:bg-gray-700 border border-gray-200 dark:border-gray-600 rounded-lg px-2 py-1.5 focus:ring-2 focus:ring-primary-500 focus:border-transparent"
                >
                  <option value="all">All Status</option>
                  <option value="draft">Draft</option>
                  <option value="review">Review</option>
                  <option value="published">Published</option>
                </select>
              </div>
              <div className="flex-1">
                <label htmlFor="filter-type" className="sr-only">
                  Filter by type
                </label>
                <select
                  id="filter-type"
                  value={filterType}
                  onChange={(e) => setFilterType(e.target.value)}
                  aria-label="Filter content by type"
                  className="w-full text-xs bg-gray-50 dark:bg-gray-700 border border-gray-200 dark:border-gray-600 rounded-lg px-2 py-1.5 focus:ring-2 focus:ring-primary-500 focus:border-transparent"
                >
                  <option value="all">All Types</option>
                  <option value="learning_experience">Learning</option>
                  <option value="simulation">Simulation</option>
                  <option value="animation">Animation</option>
                </select>
              </div>
            </div>

            {/* View Toggle */}
            <div className="mt-3 flex items-center justify-between">
              <span className="text-xs text-gray-500">
                {filteredContent.length} items
              </span>
              <div className="flex gap-1">
                <button
                  onClick={() => setLibraryView("grid")}
                  aria-label="Show content library as grid"
                  className={`p-1.5 rounded ${libraryView === "grid"
                    ? "bg-primary-100 text-primary-600"
                    : "text-gray-400 hover:bg-gray-100"
                    }`}
                >
                  <Grid3X3 className="w-4 h-4" />
                </button>
                <button
                  onClick={() => setLibraryView("list")}
                  aria-label="Show content library as list"
                  className={`p-1.5 rounded ${libraryView === "list"
                    ? "bg-primary-100 text-primary-600"
                    : "text-gray-400 hover:bg-gray-100"
                    }`}
                >
                  <List className="w-4 h-4" />
                </button>
              </div>
            </div>
          </div>

          {/* Content List */}
          <div className="flex-1 overflow-hidden">
            <PullToRefresh onRefresh={handleRefreshContent}>
              <div className="h-full overflow-y-auto p-2">
                {isLoading ? (
                  <div className="space-y-2">
                    <SkeletonCard />
                    <SkeletonCard />
                    <SkeletonCard />
                  </div>
                ) : filteredContent.length === 0 ? (
                  <div className="flex flex-col items-center justify-center h-40 text-center">
                    <BookOpen className="w-8 h-8 text-gray-300 dark:text-gray-600 mb-2" />
                    <p className="text-sm text-gray-500 dark:text-gray-400">
                      No content found
                    </p>
                    <p className="text-xs text-gray-400 dark:text-gray-500">
                      Try adjusting your filters
                    </p>
                  </div>
                ) : (
                  filteredContent.map((item) => (
                    <div
                      key={item.id}
                      className={`group relative w-full text-left p-3 rounded-lg mb-1 transition-all ${selectedContent?.id === item.id
                        ? "bg-primary-50 dark:bg-primary-900/20 border border-primary-200 dark:border-primary-700"
                        : "hover:bg-gray-50 dark:hover:bg-gray-700 border border-transparent"
                        }`}
                    >
                      <button
                        onClick={() => {
                          void openContentItem(item);
                        }}
                        className="w-full text-left"
                      >
                        <div className="flex items-start gap-2">
                          <div
                            className={`p-1.5 rounded ${selectedContent?.id === item.id
                              ? "bg-primary-100 text-primary-600"
                              : "bg-gray-100 dark:bg-gray-600 text-gray-600 dark:text-gray-300"
                              }`}
                          >
                            {getTypeIcon(item.type)}
                          </div>
                          <div className="flex-1 min-w-0">
                            <div className="font-medium text-sm text-gray-900 dark:text-white truncate">
                              {item.title}
                            </div>
                            <div className="flex items-center gap-2 mt-1">
                              {getStatusBadge(item.status)}
                              <span className="text-xs text-gray-500">
                                {item.domain}
                              </span>
                            </div>
                          </div>
                        </div>
                      </button>
                      {/* Delete button - visible on hover */}
                      <button
                        onClick={(e) => {
                          e.stopPropagation();
                          handleDeleteContent(item);
                        }}
                        className="absolute top-2 right-2 p-1.5 text-gray-400 hover:text-red-500 hover:bg-red-50 dark:hover:bg-red-900/20 rounded opacity-0 group-hover:opacity-100 transition-opacity focus:opacity-100"
                        aria-label={`Delete ${item.title}`}
                      >
                        <Trash2 className="w-4 h-4" />
                      </button>
                    </div>
                  ))
                )}
              </div>
            </PullToRefresh>
          </div>

          {/* Quick Stats */}
          <div className="p-3 border-t border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-800/50">
            <div className="grid grid-cols-3 gap-2 text-center">
              <div>
                <div className="text-lg font-bold text-gray-900 dark:text-white">
                  {contentItems.filter((c) => c.status === "published").length}
                </div>
                <div className="text-xs text-gray-500">Published</div>
              </div>
              <div>
                <div className="text-lg font-bold text-yellow-600">
                  {contentItems.filter((c) => c.status === "review").length}
                </div>
                <div className="text-xs text-gray-500">In Review</div>
              </div>
              <div>
                <div className="text-lg font-bold text-gray-500">
                  {contentItems.filter((c) => c.status === "draft").length}
                </div>
                <div className="text-xs text-gray-500">Drafts</div>
              </div>
            </div>
          </div>
        </aside>

        {/* Main Authoring Canvas */}
        <main className="flex-1 flex flex-col overflow-hidden">
          {/* Canvas Header */}
          <header className="h-14 bg-white dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700 flex items-center justify-between px-4">
            <div className="flex items-center gap-4">
              {selectedContent ? (
                <>
                  <h2 className="text-lg font-semibold text-gray-900 dark:text-white">
                    {selectedContent.title}
                  </h2>
                  {getStatusBadge(selectedContent.status)}
                </>
              ) : (
                <h2 className="text-lg font-semibold text-gray-900 dark:text-white">
                  Create New Content
                </h2>
              )}
            </div>

            <div className="flex items-center gap-2">
              {selectedContent && (
                <>
                  <button className="px-3 py-1.5 text-sm text-gray-600 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-lg flex items-center gap-2">
                    <Eye className="w-4 h-4" />
                    Preview
                  </button>
                  <button className="px-3 py-1.5 text-sm bg-primary-600 text-white hover:bg-primary-700 rounded-lg flex items-center gap-2">
                    <CheckCircle className="w-4 h-4" />
                    Publish
                  </button>
                </>
              )}
              <button
                onClick={() => setIsAICoPilotOpen(!isAICoPilotOpen)}
                aria-label={isAICoPilotOpen ? "Close AI Co-Pilot" : "Open AI Co-Pilot"}
                className={`p-2 rounded-lg transition-colors ${isAICoPilotOpen
                  ? "bg-purple-100 text-purple-600 dark:bg-purple-900/30"
                  : "text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700"
                  }`}
                title="Toggle AI Co-Pilot"
              >
                <Sparkles className="w-5 h-5" />
              </button>
            </div>
          </header>

          <section className="border-b border-gray-200 bg-gray-50 px-4 py-3 dark:border-gray-700 dark:bg-gray-800/60">
            <div className="mb-2 flex items-center justify-between text-xs">
              <span className="font-semibold uppercase tracking-wide text-gray-600 dark:text-gray-300">
                Author Journey
              </span>
              <span className="text-gray-500 dark:text-gray-400">
                Step {currentWorkflowStep + 1} of {AUTHORING_WORKFLOW_STEPS.length}
              </span>
            </div>
            <ol className="grid grid-cols-1 gap-2 md:grid-cols-7">
              {AUTHORING_WORKFLOW_STEPS.map((step, index) => {
                const isCompleted = index < currentWorkflowStep;
                const isCurrent = index === currentWorkflowStep;

                return (
                  <li
                    key={step.id}
                    className={`rounded-md border px-2 py-2 text-xs ${isCurrent
                      ? "border-primary-500 bg-primary-50 text-primary-700 dark:bg-primary-900/30 dark:text-primary-200"
                      : isCompleted
                        ? "border-emerald-200 bg-emerald-50 text-emerald-700 dark:border-emerald-800 dark:bg-emerald-900/20 dark:text-emerald-200"
                        : "border-gray-200 bg-white text-gray-500 dark:border-gray-700 dark:bg-gray-800 dark:text-gray-400"
                      }`}
                  >
                    <div className="font-semibold">{step.label}</div>
                    <div className="mt-1 line-clamp-2 text-[11px] opacity-90">
                      {step.description}
                    </div>
                  </li>
                );
              })}
            </ol>
          </section>

          {/* Canvas Content Area */}
          <div className="flex-1 flex overflow-hidden">
            {/* Main Content */}
            <div className="flex-1 overflow-y-auto p-6">
              {selectedContent ? (
                /* Content Editor */
                <ContentEditor
                  content={selectedContent}
                  onContentUpdated={(updatedContent) => {
                    setSelectedContent(updatedContent);
                    setContentItems((prev) =>
                      prev.map((item) =>
                        item.id === updatedContent.id ? updatedContent : item,
                      ),
                    );
                  }}
                />
              ) : (
                /* New Content Creation - Inline, No Modal */
                <div className="max-w-3xl mx-auto">
                  {/* Natural Language Input */}
                  <div className="bg-white dark:bg-gray-800 rounded-xl shadow-sm border border-gray-200 dark:border-gray-700 p-6">
                    <div className="text-center mb-6">
                      <div className="w-16 h-16 mx-auto bg-gradient-to-br from-purple-500 to-blue-500 rounded-2xl flex items-center justify-center mb-4">
                        <Sparkles className="w-8 h-8 text-white" />
                      </div>
                      <h2 className="text-2xl font-bold text-gray-900 dark:text-white">
                        What do you want to teach?
                      </h2>
                      <p className="text-gray-500 mt-2">
                        Describe your content idea in natural language. AI will
                        help structure it.
                      </p>
                    </div>

                    <div className="relative">
                      <textarea
                        value={newContentInput}
                        onChange={(e) => setNewContentInput(e.target.value)}
                        placeholder="e.g., Create an interactive physics lesson about Newton's laws for 8th grade students with hands-on simulations..."
                        className="w-full h-32 px-4 py-3 text-lg bg-gray-50 dark:bg-gray-700 border border-gray-200 dark:border-gray-600 rounded-xl resize-none focus:ring-2 focus:ring-purple-500 focus:border-transparent"
                        onKeyDown={(e) => {
                          if (e.key === "Enter" && (e.metaKey || e.ctrlKey)) {
                            handleCreateContent();
                          }
                        }}
                      />
                      <div className="absolute bottom-3 right-3 flex items-center gap-2">
                        <span className="text-xs text-gray-400">⌘+Enter</span>
                        <Button
                          onClick={handleCreateContent}
                          disabled={!newContentInput.trim() || isCreating}
                          isLoading={isCreating}
                          loadingText="Analyzing..."
                          variant="primary"
                          leftIcon={<Sparkles className="w-4 h-4" />}
                          id="create-content-btn"
                        >
                          Create with AI
                        </Button>
                      </div>
                    </div>

                    {/* Quick Suggestions */}
                    <div className="mt-6">
                      <div className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-3">
                        Popular templates:
                      </div>
                      <div className="flex flex-wrap gap-2">
                        {[
                          "Physics simulation for grade 9",
                          "Biology visual explanation",
                          "Math problem solver",
                          "Chemistry lab safety",
                        ].map((template) => (
                          <button
                            key={template}
                            onClick={() => setNewContentInput(template)}
                            className="px-3 py-1.5 text-sm bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300 rounded-lg hover:bg-gray-200 dark:hover:bg-gray-600 transition-colors"
                          >
                            {template}
                          </button>
                        ))}
                      </div>
                    </div>
                  </div>

                  {/* Recent Activity */}
                  <div className="mt-8">
                    <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-4">
                      Recent Activity
                    </h3>
                    <div className="grid grid-cols-2 gap-4">
                      {contentItems.slice(0, 4).map((item) => (
                        <button
                          key={item.id}
                          onClick={() => {
                            void openContentItem(item);
                          }}
                          className="bg-white dark:bg-gray-800 rounded-lg border border-gray-200 dark:border-gray-700 p-4 text-left hover:shadow-md transition-shadow"
                        >
                          <div className="flex items-start gap-3">
                            <div className="p-2 bg-gray-100 dark:bg-gray-700 rounded-lg">
                              {getTypeIcon(item.type)}
                            </div>
                            <div className="flex-1 min-w-0">
                              <div className="font-medium text-gray-900 dark:text-white truncate">
                                {item.title}
                              </div>
                              <div className="text-sm text-gray-500 mt-1">
                                {item.domain} · {item.gradeRange}
                              </div>
                              <div className="flex items-center gap-2 mt-2">
                                {getStatusBadge(item.status)}
                                <span className="text-xs text-gray-400">
                                  {new Date(
                                    item.updatedAt,
                                  ).toLocaleDateString()}
                                </span>
                              </div>
                            </div>
                          </div>
                        </button>
                      ))}
                    </div>
                  </div>
                </div>
              )}
            </div>

            {/* AI Co-Pilot Panel */}
            {isAICoPilotOpen && (
              <aside
                id="ai-copilot"
                className="w-80 bg-white dark:bg-gray-800 border-l border-gray-200 dark:border-gray-700 flex flex-col"
              >
                <AICoPilot
                  context={selectedContent}
                  suggestions={aiSuggestions}
                  onClose={() => setIsAICoPilotOpen(false)}
                />
              </aside>
            )}
          </div>
        </main>
      </div>

      {/* Delete Confirmation Dialog */}
      {dialogProps ? (
        <ConfirmDialog
          title={dialogProps.title}
          message={dialogProps.message}
          confirmText={dialogProps.confirmText}
          confirmVariant={
            dialogProps.confirmVariant === "destructive"
              ? "danger"
              : dialogProps.confirmVariant
          }
          loading={isDeleting}
          onConfirm={executeDelete}
          onCancel={() => {
            setContentToDelete(null);
            closeDeleteDialog();
          }}
        />
      ) : null}

      {/* Onboarding Tour */}
      <Tour
        steps={tourSteps}
        active={isTourActive}
        onComplete={completeTour}
        onSkip={skipTour}
      />
    </>
  );
}

function useDeleteDialogController() {
  const [dialogProps, setDialogProps] = useState<ConfirmDialogState | null>(null);

  const confirmDelete = useCallback((nextDialog: ConfirmDialogState) => {
    setDialogProps(nextDialog);
  }, []);

  const closeDeleteDialog = useCallback(() => {
    setDialogProps(null);
  }, []);

  return {
    dialogProps,
    confirmDelete,
    closeDeleteDialog,
  };
}

// Content Editor Component
function ContentEditor({
  content,
  onContentUpdated,
}: {
  content: ContentItem;
  onContentUpdated: (content: ContentItem) => void;
}) {
  const [activeTab, setActiveTab] = useState<
    "claims" | "tasks" | "simulation" | "animation" | "settings"
  >("claims");
  const [authoringStep, setAuthoringStep] = useState<AuthoringStep>("outline");

  /** Map a stepper step to the most relevant editor tab. */
  const handleStepChange = useCallback((step: AuthoringStep) => {
    setAuthoringStep(step);
    if (step === "outline" || step === "generate") setActiveTab("claims");
    else if (step === "review") setActiveTab("tasks");
    else if (step === "validate" || step === "publish") setActiveTab("claims");
  }, []);
  const [saveStatus, _setSaveStatus] = useState<
    "saved" | "unsaved" | "saving" | "error"
  >("saved");
  const experienceRouteId = useMemo(
    () => getExperienceRouteId(content),
    [content],
  );

  const handleRegenerateRequested = useCallback(() => {
    setActiveTab("claims");
    toast.info(
      "Review the latest validation findings and regenerate claims or artifacts from the editor tools.",
    );
  }, []);

  // Build breadcrumb items based on content
  const breadcrumbItems = useMemo(() => {
    const items: Array<{ id: string; label: string; href?: string }> = [
      { id: "authoring", label: "Authoring", href: "/authoring" },
      { id: "library", label: "Content Library", href: "/authoring" },
    ];

    // Add content name if available
    if (content) {
      items.push({
        id: "content",
        label: content.title || "Untitled Content",
        href: undefined, // Current page
      });
    }

    return items;
  }, [content]);

  // Get tab-specific subtitle
  const getTabSubtitle = () => {
    const tabLabels = {
      claims: "Claims & Evidence",
      tasks: "Tasks & Activities",
      simulation: "Simulation Builder",
      animation: "Animation Studio",
      settings: "Settings & Metadata",
    };
    return tabLabels[activeTab];
  };

  // Build metadata for context indicator
  const metadata = useMemo(
    () => [
      { label: "Domain", value: content.domain },
      { label: "Grade", value: content.gradeRange },
      {
        label: "Status",
        value: content.status.charAt(0).toUpperCase() + content.status.slice(1),
      },
    ],
    [content],
  );

  // Get icon based on content type
  const getContentIcon = () => {
    switch (content.type) {
      case "learning_experience":
        return <BookOpen className="w-5 h-5" />;
      case "simulation":
        return <Beaker className="w-5 h-5" />;
      case "animation":
        return <Film className="w-5 h-5" />;
      case "assessment":
        return <FileText className="w-5 h-5" />;
    }
  };

  return (
    <div className="h-full flex flex-col">
      {/* Context Indicator - shows what user is editing */}
      <ContextIndicator
        title={content.title}
        subtitle={getTabSubtitle()}
        status={saveStatus}
        icon={getContentIcon()}
        metadata={metadata}
        actions={
          <>
            <button className="px-3 py-1.5 text-sm font-medium text-gray-700 dark:text-gray-300 bg-gray-100 dark:bg-gray-700 rounded-lg hover:bg-gray-200 dark:hover:bg-gray-600 transition-colors">
              <Eye className="w-4 h-4 inline mr-1" />
              Preview
            </button>
            <button className="px-3 py-1.5 text-sm font-medium text-white bg-primary-600 rounded-lg hover:bg-primary-700 transition-colors">
              <Share2 className="w-4 h-4 inline mr-1" />
              Publish
            </button>
          </>
        }
      />
      {/* Breadcrumbs */}
      <div className="px-6 py-3 border-b border-gray-200 dark:border-gray-700">
        <BreadcrumbRouter
          items={breadcrumbItems}
          LinkComponent={Link}
          showHomeIcon={false}
          className="text-sm"
        />
      </div>
      {/* Main Editor Content */}
      <div className="flex-1 overflow-y-auto px-6 py-4">
        {/* Authoring stepper — guides author through Outline→Generate→Review→Validate→Publish (F-008) */}
        {content.type === "learning_experience" && (
          <AuthoringStepperPanel
            currentStep={authoringStep}
            onStepChange={handleStepChange}
            className="mb-6"
          />
        )}
        {/* Editor Tabs */}
        <div
          id="editor-tabs"
          className="flex items-center gap-1 border-b border-gray-200 dark:border-gray-700 mb-6"
        >
          {(
            [
              { id: "claims", label: "Claims & Evidence", icon: BookOpen },
              { id: "tasks", label: "Tasks", icon: FileText },
              { id: "simulation", label: "Simulation", icon: Beaker },
              { id: "animation", label: "Animation", icon: Film },
              { id: "settings", label: "Settings", icon: Settings },
            ] as const
          ).map((tab) => (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={`flex items-center gap-2 px-4 py-3 text-sm font-medium border-b-2 transition-colors ${activeTab === tab.id
                ? "border-primary-500 text-primary-600"
                : "border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300"
                }`}
            >
              <tab.icon className="w-4 h-4" />
              {tab.label}
            </button>
          ))}
        </div>

        {/* Tab Content */}
        <div className="bg-white dark:bg-gray-800 rounded-xl border border-gray-200 dark:border-gray-700 p-6">
          {activeTab === "claims" && <ClaimsEditor contentId={experienceRouteId} />}
          {activeTab === "tasks" && <TasksEditor contentId={experienceRouteId} />}
          {activeTab === "simulation" && (
            <SimulationEditor contentId={experienceRouteId} domain={content.domain} />
          )}
          {activeTab === "animation" && (
            <AnimationEditor contentId={experienceRouteId} />
          )}
          {activeTab === "settings" && (
            <SettingsEditor
              content={content}
              onContentUpdated={onContentUpdated}
            />
          )}
        </div>

        {content.type === "learning_experience" && (
          <div className="mt-6">
            <PublicationReadinessPanel
              experienceId={experienceRouteId}
              experienceTitle={content.title}
              onPublished={() => {
                onContentUpdated({
                  ...content,
                  status: "published",
                });
              }}
            />
          </div>
        )}

        {/* F-013: Failed jobs surface — always shown for learning experiences */}
        {content.type === "learning_experience" && (
          <div className="mt-4">
            <FailedJobsPanel experienceId={experienceRouteId} />
          </div>
        )}

        {content.type === "learning_experience" && (
          <div className="mt-6">
            <AnalyticsDashboard
              experienceId={experienceRouteId}
              experienceTitle={content.title}
              onRegenerateRequested={handleRegenerateRequested}
            />
          </div>
        )}

        <div className="mt-6">
          <GenerationGovernancePanel />
        </div>
      </div>{" "}
      {/* End of flex-1 overflow-y-auto */}
    </div>
  );
}

// Claims Editor Component
function ClaimsEditor({ contentId }: { contentId: string }) {
  const [claims, setClaims] = useState<
    Array<{ id: string; text: string; bloom: string; mastery: number }>
  >([]);
  const [isGenerating, setIsGenerating] = useState(false);

  const loadClaims = useCallback(async () => {
    const response = await fetch(
      `/api/content-studio/experiences/${contentId}/comprehensive`,
      { headers: getAuthoringApiHeaders(false) },
    );

    if (!response.ok) {
      throw new Error(`Failed to load claims (${response.status})`);
    }

    const result = (await response.json()) as ComprehensiveExperienceResponse;
    setClaims(
      (result.data.claims ?? []).map((claim, index) => ({
        id: claim.id,
        text: claim.text ?? "",
        bloom: claim.bloomLevel ?? "UNDERSTAND",
        mastery: Math.max(0.6, 0.85 - index * 0.05),
      })),
    );
  }, [contentId]);

  useEffect(() => {
    void loadClaims().catch(() => {
      toast.error("Failed to load claims");
    });
  }, [loadClaims]);

  // Form validation for new claims
  const { values, isValid, getFieldProps, reset } =
    useFormValidation({
      initialValues: {
        newClaim: "",
        bloomLevel: "Understand",
      },
      schema: {
        newClaim: [
          validators.required("Claim text is required"),
          validators.minLength(10, "Claim must be at least 10 characters"),
          validators.maxLength(300, "Claim must be under 300 characters"),
        ],
      },
    });

  const newClaimField = getFieldProps("newClaim");

  const addClaim = useCallback(() => {
    if (!isValid || !values.newClaim.trim()) return;

    void fetch(`/api/content-studio/experiences/${contentId}/claims`, {
      method: "POST",
      headers: getAuthoringApiHeaders(),
      body: JSON.stringify({
        text: values.newClaim,
        bloomLevel: values.bloomLevel,
      }),
    })
      .then(async (response) => {
        if (!response.ok) {
          throw new Error(`Failed to add claim (${response.status})`);
        }
        await loadClaims();
        reset();
        toast.success("Claim added successfully");
      })
      .catch(() => {
        toast.error("Failed to add claim");
      });
  }, [contentId, isValid, loadClaims, reset, values]);

  const generateClaims = async () => {
    setIsGenerating(true);
    try {
      const response = await fetch("/api/content-studio/ai/generate-claims", {
        method: "POST",
        headers: getAuthoringApiHeaders(),
        body: JSON.stringify({ contentId }),
      });
      if (response.ok) {
        await loadClaims();
        toast.success("Claims generated");
      }
    } catch {
      toast.error("Failed to generate claims");
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <h3 className="text-lg font-semibold text-gray-900 dark:text-white">
          Learning Claims
        </h3>
        <button
          onClick={generateClaims}
          disabled={isGenerating}
          className="px-3 py-1.5 text-sm bg-purple-100 text-purple-600 rounded-lg hover:bg-purple-200 flex items-center gap-2 disabled:opacity-50"
        >
          <Sparkles className="w-4 h-4" />
          {isGenerating ? "Generating..." : "AI Generate"}
        </button>
      </div>

      <div className="space-y-3">
        {claims.map((claim, index) => (
          <div
            key={claim.id}
            className="p-4 bg-gray-50 dark:bg-gray-700/50 rounded-lg border border-gray-200 dark:border-gray-600"
          >
            <div className="flex items-start gap-3">
              <div className="w-6 h-6 bg-primary-100 text-primary-600 rounded-full flex items-center justify-center text-sm font-medium">
                {index + 1}
              </div>
              <div className="flex-1">
                <p className="text-gray-900 dark:text-white">{claim.text}</p>
                <div className="flex items-center gap-3 mt-2">
                  <span className="px-2 py-0.5 text-xs bg-blue-100 text-blue-600 rounded">
                    {claim.bloom}
                  </span>
                  <span className="text-xs text-gray-500">
                    Mastery: {Math.round(claim.mastery * 100)}%
                  </span>
                </div>
              </div>
              <button className="p-1 text-gray-400 hover:text-gray-600">
                <MoreHorizontal className="w-4 h-4" />
              </button>
            </div>
          </div>
        ))}
      </div>

      {/* Add new claim with validation */}
      {/* Add new claim with validation */}
      <FormField
        label="New Claim"
        error={newClaimField.touched ? newClaimField.error ?? undefined : undefined}
        helperText={`${values.newClaim.length}/300 characters`}
        validating={false}
      >
        <div className="flex gap-2">
          <div className="flex-1">
            <input
              type="text"
              value={newClaimField.value}
              onChange={(e) => newClaimField.onChange(e.target.value)}
              onBlur={newClaimField.onBlur}
              placeholder="Add a new learning claim..."
              className={`w-full px-4 py-2 bg-white dark:bg-gray-700 border rounded-lg
                ${newClaimField.touched && newClaimField.error
                  ? "border-red-500 focus:ring-red-500"
                  : "border-gray-200 dark:border-gray-600 focus:ring-primary-500"
                }`}
              onKeyDown={(e) => {
                if (e.key === "Enter" && isValid) {
                  e.preventDefault();
                  addClaim();
                }
              }}
            />
          </div>
          <select
            value={values.bloomLevel}
            onChange={(e) => getFieldProps("bloomLevel").onChange(e.target.value)}
            className="px-3 py-2 bg-white dark:bg-gray-700 border border-gray-200 dark:border-gray-600 rounded-lg text-sm"
          >
            <option value="Remember">Remember</option>
            <option value="Understand">Understand</option>
            <option value="Apply">Apply</option>
            <option value="Analyze">Analyze</option>
            <option value="Evaluate">Evaluate</option>
            <option value="Create">Create</option>
          </select>
          <button
            onClick={addClaim}
            disabled={!isValid || !values.newClaim.trim()}
            className="px-4 py-2 bg-primary-600 text-white rounded-lg hover:bg-primary-700 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <Plus className="w-4 h-4" />
          </button>
        </div>
      </FormField>
    </div>
  );
}

// Tasks Editor Component
function TasksEditor({ contentId }: { contentId: string }) {
  const [tasks, setTasks] = useState<
    Array<{ id: string; prompt: string; type: string; claimRef?: string }>
  >([]);

  useEffect(() => {
    void fetch(`/api/content-studio/experiences/${contentId}/comprehensive`, {
      headers: getAuthoringApiHeaders(false),
    })
      .then((response) =>
        response.ok
          ? (response.json() as Promise<ComprehensiveExperienceResponse>)
          : Promise.reject(new Error(String(response.status))),
      )
      .then((result) => {
        setTasks(
          (result.data.claims ?? []).flatMap((claim) =>
            (claim.tasks ?? []).map((task) => ({
              id: task.id,
              prompt: task.prompt ?? "",
              type: task.type ?? "explanation",
              claimRef: claim.claimRef,
            })),
          ),
        );
      })
      .catch(() => {
        toast.error("Failed to load tasks");
      });
  }, [contentId]);

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <h3 className="text-lg font-semibold text-gray-900 dark:text-white">
          Learning Tasks
        </h3>
        <button className="px-3 py-1.5 text-sm bg-purple-100 text-purple-600 rounded-lg hover:bg-purple-200 flex items-center gap-2">
          <Sparkles className="w-4 h-4" />
          AI Generate Tasks
        </button>
      </div>
      <p className="text-gray-500">
        Tasks will be auto-generated based on your claims. You can also add
        custom tasks.
      </p>

      <div className="space-y-3">
        {tasks.length === 0 ? (
          <div className="rounded-lg border border-dashed border-gray-300 p-4 text-sm text-gray-500 dark:border-gray-700 dark:text-gray-400">
            No persisted tasks yet for this experience.
          </div>
        ) : (
          tasks.map((task) => (
            <div
              key={task.id}
              className="rounded-lg border border-gray-200 bg-gray-50 p-4 dark:border-gray-700 dark:bg-gray-700/40"
            >
              <div className="flex items-center gap-2 text-xs text-gray-500">
                <span>{task.type}</span>
                {task.claimRef ? <span>• {task.claimRef}</span> : null}
              </div>
              <p className="mt-2 text-sm text-gray-900 dark:text-white">
                {task.prompt}
              </p>
            </div>
          ))
        )}
      </div>
    </div>
  );
}

// Simulation Editor Component - Full Featured Physics Builder
function SimulationEditor({
  contentId,
  domain,
}: {
  contentId: string;
  domain: string;
}) {
  const [claims, setClaims] = useState<
    Array<{ id: string; text: string; claimRef?: string }>
  >([]);
  const [selectedClaimRef, setSelectedClaimRef] = useState("");
  const [manifestId, setManifestId] = useState<string | null>(null);
  const [initialManifest, setInitialManifest] = useState<SimulationManifest | undefined>(
    undefined,
  );
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    let cancelled = false;

    const loadSimulationContext = async () => {
      setIsLoading(true);
      try {
        const [experienceResponse, simulationsResponse] = await Promise.all([
          fetch(`/api/content-studio/experiences/${contentId}/comprehensive`, {
            headers: getAuthoringApiHeaders(false),
          }),
          fetch(`/api/content-studio/experiences/${contentId}/simulations`, {
            headers: getAuthoringApiHeaders(false),
          }),
        ]);

        if (!experienceResponse.ok) {
          throw new Error(`Failed to load experience (${experienceResponse.status})`);
        }
        if (!simulationsResponse.ok) {
          throw new Error(`Failed to load simulations (${simulationsResponse.status})`);
        }

        const experience =
          (await experienceResponse.json()) as ComprehensiveExperienceResponse;
        const simulations = (await simulationsResponse.json()) as {
          data: PersistedSimulationLink[];
        };

        if (cancelled) {
          return;
        }

        const mappedClaims = (experience.data.claims ?? []).map((claim) => ({
          id: claim.id,
          text: claim.text ?? claim.claimRef ?? "Untitled claim",
          claimRef: claim.claimRef ?? claim.id,
        }));
        const linkedSimulation = simulations.data?.[0];

        setClaims(mappedClaims);
        setSelectedClaimRef(
          linkedSimulation?.claimRef ?? mappedClaims[0]?.claimRef ?? "",
        );
        setManifestId(linkedSimulation?.simulationManifestId ?? null);
        setInitialManifest(
          (linkedSimulation?.simulationManifest?.manifest as SimulationManifest | undefined) ??
          undefined,
        );
      } catch (_error) {
        toast.error("Failed to load simulation context");
      } finally {
        if (!cancelled) {
          setIsLoading(false);
        }
      }
    };

    void loadSimulationContext();

    return () => {
      cancelled = true;
    };
  }, [contentId]);

  const normalizedDomain = ((domain || "PHYSICS").toUpperCase() === "MATH"
    ? "MATHEMATICS"
    : (domain || "PHYSICS").toUpperCase()) as SimulationDomain;

  const saveManifest = useCallback(
    async (manifest: SimulationManifest) => {
      if (!selectedClaimRef) {
        toast.error("Select a claim before saving the simulation.");
        return;
      }

      const payload = {
        ...manifest,
        domain: normalizedDomain,
        title: manifest.title || `Simulation for ${contentId}`,
        description: manifest.description || "",
        version: manifest.version || "1.0.0",
      };

      try {
        let currentManifestId = manifestId;

        if (!currentManifestId) {
          const createResponse = await fetch("/api/sim-author/manifests", {
            method: "POST",
            headers: getAuthoringApiHeaders(),
            body: JSON.stringify(payload),
          });

          if (!createResponse.ok) {
            throw new Error(`Create failed (${createResponse.status})`);
          }

          const created = (await createResponse.json()) as {
            id: string;
            manifest?: SimulationManifest;
          };
          currentManifestId = created.id;
          setManifestId(created.id);
        } else {
          const updateResponse = await fetch(
            `/api/sim-author/manifests/${currentManifestId}`,
            {
              method: "PUT",
              headers: getAuthoringApiHeaders(),
              body: JSON.stringify(payload),
            },
          );

          if (!updateResponse.ok) {
            throw new Error(`Save failed (${updateResponse.status})`);
          }
        }

        const linkResponse = await fetch(
          `/api/sim-author/manifests/${currentManifestId}/link-claim`,
          {
            method: "POST",
            headers: getAuthoringApiHeaders(),
            body: JSON.stringify({
              experienceId: contentId,
              claimRef: selectedClaimRef,
              interactionType: "parameter_exploration",
              goal: `Explore ${domain || "the concept"}`,
              estimatedMinutes: 10,
            }),
          },
        );

        if (!linkResponse.ok) {
          throw new Error(`Link failed (${linkResponse.status})`);
        }

        setInitialManifest(payload as SimulationManifest);
        toast.success("Simulation saved successfully");
      } catch (error) {
        console.error("Simulation save error:", error);
        toast.error("Failed to save simulation. Please try again.");
      }
    },
    [contentId, domain, manifestId, normalizedDomain, selectedClaimRef],
  );

  const handleAIGenerate = useCallback(
    async (prompt: string, aiDomain: SimulationDomain) => {
      const response = await fetch("/api/sim-author/generate", {
        method: "POST",
        headers: getAuthoringApiHeaders(),
        body: JSON.stringify({
          prompt,
          domain: aiDomain,
        }),
      });

      if (!response.ok) {
        throw new Error(`Generation failed (${response.status})`);
      }

      const result = (await response.json()) as {
        manifest?: SimulationManifest;
      };

      if (!result.manifest) {
        throw new Error("Simulation generation returned no manifest");
      }

      return result.manifest;
    },
    [],
  );

  const handleNLRefine = useCallback(
    async (input: string): Promise<SimulationRefinementResult> => {
      const manifest = initialManifest;
      if (!manifest) {
        return {
          success: false,
          response: "Generate or load a simulation before refining it.",
          suggestions: [],
        };
      }

      const response = await fetch("/api/sim-author/refine", {
        method: "POST",
        headers: getAuthoringApiHeaders(),
        body: JSON.stringify({
          manifest,
          refinement: input,
        }),
      });

      if (!response.ok) {
        throw new Error(`Refinement failed (${response.status})`);
      }

      const result = (await response.json()) as {
        manifest?: SimulationManifest;
        suggestions?: string[];
      };

      if (result.manifest) {
        setInitialManifest(result.manifest);
      }

      return {
        success: Boolean(result.manifest),
        manifest: result.manifest,
        response: result.manifest
          ? "I refined the simulation manifest based on your instructions."
          : "No manifest changes were returned.",
        suggestions: result.suggestions ?? [],
      };
    },
    [initialManifest],
  );

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <h3 className="text-lg font-semibold text-gray-900 dark:text-white">
          Simulation Studio
        </h3>
        <div className="flex items-center gap-2">
          <select
            value={selectedClaimRef}
            onChange={(event) => setSelectedClaimRef(event.target.value)}
            className="rounded-lg border border-gray-200 bg-white px-3 py-2 text-sm text-gray-700 dark:border-gray-600 dark:bg-gray-700 dark:text-white"
          >
            <option value="">Select claim</option>
            {claims.map((claim) => (
              <option key={claim.id} value={claim.claimRef}>
                {claim.text}
              </option>
            ))}
          </select>
          <span className="text-sm text-gray-500">
            Manifest-based simulation authoring
          </span>
        </div>
      </div>

      <div className="h-[760px] overflow-hidden rounded-lg border border-gray-200 bg-white dark:border-gray-700 dark:bg-gray-800">
        {isLoading ? (
          <div className="flex h-full items-center justify-center text-sm text-gray-500">
            Loading simulation context...
          </div>
        ) : (
          <SimulationStudio
            key={manifestId ?? selectedClaimRef ?? "new-simulation"}
            initialManifest={initialManifest}
            onSave={(manifest: Record<string, unknown>) => {
              void saveManifest(manifest as unknown as SimulationManifest);
            }}
            onAIGenerate={handleAIGenerate}
            onNLRefine={handleNLRefine}
          />
        )}
      </div>
    </div>
  );
}

// Animation Editor Component - Full Featured Timeline-Based Animation
function AnimationEditor({ contentId }: { contentId: string }) {
  const [claims, setClaims] = useState<
    Array<{ id: string; text: string; claimRef?: string }>
  >([]);
  const [selectedClaimId, setSelectedClaimId] = useState<string>("");
  const [initialAnimation, setInitialAnimation] = useState<AnimationSpec | undefined>(
    undefined,
  );
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    let cancelled = false;

    const loadAnimationContext = async () => {
      setIsLoading(true);
      try {
        const [experienceResponse, animationsResponse] = await Promise.all([
          fetch(`/api/content-studio/experiences/${contentId}/comprehensive`, {
            headers: getAuthoringApiHeaders(false),
          }),
          fetch(`/api/content-studio/experiences/${contentId}/animations`, {
            headers: getAuthoringApiHeaders(false),
          }),
        ]);

        if (!experienceResponse.ok) {
          throw new Error(`Failed to load claims (${experienceResponse.status})`);
        }
        if (!animationsResponse.ok) {
          throw new Error(`Failed to load animations (${animationsResponse.status})`);
        }

        const experience =
          (await experienceResponse.json()) as ComprehensiveExperienceResponse;
        const animations = (await animationsResponse.json()) as {
          data: PersistedAnimationLink[];
        };

        if (cancelled) {
          return;
        }

        const mappedClaims = (experience.data.claims ?? []).map((claim) => ({
          id: claim.id,
          text: claim.text ?? claim.claimRef ?? "Untitled claim",
          claimRef: claim.claimRef ?? claim.id,
        }));

        setClaims(mappedClaims);

        const firstClaimRef = mappedClaims[0]?.claimRef ?? "";
        const firstAnimation = animations.data?.[0];
        const claimRefToUse = firstAnimation?.claimId ?? firstClaimRef;

        setSelectedClaimId(claimRefToUse);
        setInitialAnimation(firstAnimation?.spec);
      } catch (_error) {
        toast.error("Failed to load animation context");
      } finally {
        if (!cancelled) {
          setIsLoading(false);
        }
      }
    };

    void loadAnimationContext();

    return () => {
      cancelled = true;
    };
  }, [contentId]);

  const handleSave = async (animation: AnimationSpec) => {
    if (!selectedClaimId) {
      toast.error("Select a claim before saving the animation.");
      return;
    }

    try {
      const selectedClaim = claims.find((claim) => claim.claimRef === selectedClaimId);
      const response = await fetch(`/api/content-studio/experiences/${contentId}/animations`, {
        method: "POST",
        headers: getAuthoringApiHeaders(),
        body: JSON.stringify({
          claimId: selectedClaimId,
          animationId: (animation['id'] as string | undefined) ?? `anim-${contentId}`,
          animationType: "assessment",
          autoGenerated: false,
          concept: selectedClaim?.text ?? (animation['title'] as string | undefined),
          difficulty: "medium",
          estimatedDuration: Math.max(1, Math.round((animation['durationSeconds'] as number | undefined) ?? 30)),
          spec: animation,
        }),
      });
      if (!response.ok) {
        throw new Error(`Save failed: ${response.status}`);
      }
      setInitialAnimation(animation);
      toast.success("Animation saved successfully");
    } catch (err) {
      toast.error("Failed to save animation. Please try again.");
      console.error("Animation save error:", err);
    }
  };

  const handleExport = (animation: AnimationSpec, format: string) => {
    try {
      const blob = new Blob([JSON.stringify(animation, null, 2)], {
        type: "application/json",
      });
      const title = (animation['id'] as string | undefined) ?? contentId;
      const ext = format === "json" ? "json" : format === "gif" ? "gif" : "mp4";
      const filename = `animation-${title}.${ext}`;

      if (format !== "json") {
        // Video/GIF export requires server-side rendering; notify user
        toast.success(
          `${format.toUpperCase()} export has been queued. You will be notified when it is ready.`,
        );
        fetch(`/api/content-studio/content/${contentId}/animation/export`, {
          method: "POST",
          headers: getAuthoringApiHeaders(),
          body: JSON.stringify({ animation, format }),
        }).catch((err) => console.error("Export queue error:", err));
        return;
      }

      // JSON export is immediate (client-side)
      const url = URL.createObjectURL(blob);
      const anchor = document.createElement("a");
      anchor.href = url;
      anchor.download = filename;
      anchor.click();
      URL.revokeObjectURL(url);
      toast.success(`Animation exported as ${filename}`);
    } catch (err) {
      toast.error("Export failed. Please try again.");
      console.error("Animation export error:", err);
    }
  };

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <h3 className="text-lg font-semibold text-gray-900 dark:text-white">
          Timeline-Based Animation
        </h3>
        <div className="flex items-center gap-2">
          <select
            value={selectedClaimId}
            onChange={(event) => setSelectedClaimId(event.target.value)}
            className="rounded-lg border border-gray-200 bg-white px-3 py-2 text-sm text-gray-700 dark:border-gray-600 dark:bg-gray-700 dark:text-white"
          >
            <option value="">Select claim</option>
            {claims.map((claim) => (
              <option key={claim.id} value={claim.claimRef}>
                {claim.text}
              </option>
            ))}
          </select>
          <span className="text-sm text-gray-500">
            Create smooth animations with keyframes
          </span>
        </div>
      </div>

      <div className="h-[600px] bg-white dark:bg-gray-800 rounded-lg border border-gray-200 dark:border-gray-700 overflow-hidden">
        {isLoading ? (
          <div className="flex h-full items-center justify-center text-sm text-gray-500">
            Loading animation context...
          </div>
        ) : (
          <AnimationStudio
            key={selectedClaimId || "default-animation"}
            initialAnimation={initialAnimation as unknown as Parameters<typeof AnimationStudio>[0]['initialAnimation']}
            onSave={handleSave as unknown as Parameters<typeof AnimationStudio>[0]['onSave']}
            onExport={handleExport as unknown as Parameters<typeof AnimationStudio>[0]['onExport']}
          />
        )}
      </div>

      <div className="flex items-center justify-between p-4 bg-purple-50 dark:bg-purple-900/20 rounded-lg">
        <div className="flex items-center gap-2 text-sm text-purple-700 dark:text-purple-300">
          <Sparkles className="w-4 h-4" />
          <span>
            Tip: Add keyframes at different times to create smooth transitions.
            Use the timeline to preview your animation.
          </span>
        </div>
      </div>
    </div>
  );
}

// Settings Editor Component
function SettingsEditor({
  content,
  onContentUpdated,
}: {
  content: ContentItem;
  onContentUpdated: (content: ContentItem) => void;
}) {
  const submitHandler = async (formValues: { title: string; description: string; domain: string; gradeRange: string }) => {
      const response = await fetch(`/api/content-studio/experiences/${getExperienceRouteId(content)}`, {
        method: "PUT",
        headers: getAuthoringApiHeaders(),
        body: JSON.stringify(formValues),
      });

      if (!response.ok) {
        throw new Error(`Save failed: ${response.status}`);
      }

      const result = (await response.json()) as { data: Record<string, unknown> };
      onContentUpdated(mapExperienceSummaryToContentItem(result.data, content));
      toast.success("Settings saved successfully");
  };

  const {
    values,
    fieldStates,
    isValid,
    getFieldProps,
    handleSubmit,
    setValue: setFieldValue,
  } = useFormValidation({
    initialValues: {
      title: content.title,
      description: content.description,
      domain: content.domain,
      gradeRange: content.gradeRange,
    },
    schema: {
      title: [
        validators.required("Title is required"),
        validators.minLength(3, "Title must be at least 3 characters"),
        validators.maxLength(100, "Title must be under 100 characters"),
      ],
      description: [
        validators.required("Description is required"),
        validators.minLength(10, "Description must be at least 10 characters"),
        validators.maxLength(500, "Description must be under 500 characters"),
      ],
    },
  });

  const errors = Object.fromEntries(
    Object.entries(fieldStates).map(([k, v]) => [k, v.error])
  ) as Record<string, string | null>;
  const touched = Object.fromEntries(
    Object.entries(fieldStates).map(([k, v]) => [k, v.touched])
  ) as Record<string, boolean>;

  return (
    <form onSubmit={handleSubmit(submitHandler)} className="space-y-6">
      <FormField
        label="Title"
        required
        error={touched['title'] && errors['title'] ? errors['title'] : undefined}
      >
        <input
          type="text"
          value={getFieldProps("title").value}
          onChange={(e) => getFieldProps("title").onChange(e.target.value)}
          onBlur={getFieldProps("title").onBlur}
          aria-invalid={touched['title'] && !!errors['title']}
          className={`w-full px-4 py-2 bg-gray-50 dark:bg-gray-700 border rounded-lg
            ${touched['title'] && errors['title']
              ? "border-red-500 focus:ring-red-500"
              : "border-gray-200 dark:border-gray-600 focus:ring-primary-500"
            }`}
        />
      </FormField>

      <FormField
        label="Description"
        required
        error={touched['description'] && errors['description'] ? errors['description'] : undefined}
        hint={`${String(values.description).length}/500 characters`}
      >
        <textarea
          value={getFieldProps("description").value}
          onChange={(e) => getFieldProps("description").onChange(e.target.value)}
          onBlur={getFieldProps("description").onBlur}
          rows={3}
          aria-invalid={touched['description'] && !!errors['description']}
          className={`w-full px-4 py-2 bg-gray-50 dark:bg-gray-700 border rounded-lg resize-none
            ${touched['description'] && errors['description']
              ? "border-red-500 focus:ring-red-500"
              : "border-gray-200 dark:border-gray-600 focus:ring-primary-500"
            }`}
        />
      </FormField>

      <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
        <FormField label="Domain">
          <select
            value={values.domain}
            onChange={(e) => setFieldValue("domain", e.target.value)}
            className="w-full px-4 py-2 bg-gray-50 dark:bg-gray-700 border border-gray-200 dark:border-gray-600 rounded-lg"
          >
            <option value="Physics">Physics</option>
            <option value="Chemistry">Chemistry</option>
            <option value="Biology">Biology</option>
            <option value="Mathematics">Mathematics</option>
          </select>
        </FormField>
        <FormField label="Grade Range">
          <select
            value={values.gradeRange}
            onChange={(e) => setFieldValue("gradeRange", e.target.value)}
            className="w-full px-4 py-2 bg-gray-50 dark:bg-gray-700 border border-gray-200 dark:border-gray-600 rounded-lg"
          >
            <option value="K-2">K-2</option>
            <option value="3-5">3-5</option>
            <option value="6-8">6-8</option>
            <option value="9-12">9-12</option>
            <option value="Undergraduate">Undergraduate</option>
          </select>
        </FormField>
      </div>

      <div className="flex justify-end pt-4 border-t border-gray-200 dark:border-gray-700">
        <Button type="submit" disabled={!isValid} className="min-w-[120px]">
          Save Settings
        </Button>
      </div>
    </form>
  );
}

// AI Co-Pilot Component
function AICoPilot({
  context,
  suggestions,
  onClose,
}: {
  context: ContentItem | null;
  suggestions: AISuggestion[];
  onClose: () => void;
}) {
  const [messages, setMessages] = useState<
    Array<{ id: string; role: "user" | "ai"; content: string }>
  >([
    {
      id: "1",
      role: "ai",
      content: context
        ? `I'm ready to help you improve "${context.title}". What would you like to do?`
        : "Hi! I can help you create educational content. Describe what you want to build, and I'll guide you through it.",
    },
  ]);
  const [input, setInput] = useState("");
  const [isTyping, setIsTyping] = useState(false);

  const handleSend = async () => {
    if (!input.trim()) return;

    const userMessage = {
      id: Date.now().toString(),
      role: "user" as const,
      content: input,
    };
    setMessages((prev) => [...prev, userMessage]);
    setInput("");
    setIsTyping(true);

    // Call AI
    try {
      const response = await fetch("/api/content-studio/ai/chat", {
        method: "POST",
        headers: getAuthoringApiHeaders(),
        body: JSON.stringify({
          message: input,
          context: context
            ? { contentId: context.id, title: context.title }
            : null,
        }),
      });

      const aiResponse = {
        id: (Date.now() + 1).toString(),
        role: "ai" as const,
        content: response.ok
          ? (await response.json()).response ||
          "I can help with that. Let me analyze your request..."
          : "I understand. Let me help you with that.",
      };
      setMessages((prev) => [...prev, aiResponse]);
    } catch {
      setMessages((prev) => [
        ...prev,
        {
          id: (Date.now() + 1).toString(),
          role: "ai",
          content:
            "I can help with that. What specific aspect would you like to focus on?",
        },
      ]);
    } finally {
      setIsTyping(false);
    }
  };

  return (
    <>
      {/* Header */}
      <div className="p-4 border-b border-gray-200 dark:border-gray-700 flex items-center justify-between bg-gradient-to-r from-purple-50 to-blue-50 dark:from-purple-900/20 dark:to-blue-900/20">
        <div className="flex items-center gap-2">
          <Sparkles className="w-5 h-5 text-purple-600" />
          <span className="font-semibold text-gray-900 dark:text-white">
            AI Co-Pilot
          </span>
        </div>
        <button
          onClick={onClose}
          aria-label="Close AI Co-Pilot"
          className="p-1 text-gray-400 hover:text-gray-600 rounded"
        >
          <X className="w-4 h-4" />
        </button>
      </div>

      {/* Suggestions */}
      {suggestions.length > 0 && (
        <div className="p-3 border-b border-gray-200 dark:border-gray-700 space-y-2">
          {suggestions.slice(0, 2).map((suggestion) => (
            <button
              key={suggestion.id}
              onClick={suggestion.action}
              className="w-full p-2 text-left text-sm bg-gray-50 dark:bg-gray-700 rounded-lg hover:bg-gray-100 dark:hover:bg-gray-600 flex items-start gap-2"
            >
              {suggestion.type === "insight" && (
                <Lightbulb className="w-4 h-4 text-yellow-500 mt-0.5" />
              )}
              {suggestion.type === "action" && (
                <Zap className="w-4 h-4 text-blue-500 mt-0.5" />
              )}
              {suggestion.type === "warning" && (
                <AlertTriangle className="w-4 h-4 text-orange-500 mt-0.5" />
              )}
              <div>
                <div className="font-medium text-gray-900 dark:text-white">
                  {suggestion.title}
                </div>
                <div className="text-xs text-gray-500">
                  {suggestion.description}
                </div>
              </div>
            </button>
          ))}
        </div>
      )}

      {/* Chat Messages */}
      <div className="flex-1 overflow-y-auto p-4 space-y-4">
        {messages.map((msg) => (
          <div
            key={msg.id}
            className={`flex gap-2 ${msg.role === "user" ? "flex-row-reverse" : ""
              }`}
          >
            <div
              className={`w-7 h-7 rounded-full flex items-center justify-center flex-shrink-0 ${msg.role === "ai"
                ? "bg-purple-100 text-purple-600"
                : "bg-blue-100 text-blue-600"
                }`}
            >
              {msg.role === "ai" ? (
                <Bot className="w-4 h-4" />
              ) : (
                <User className="w-4 h-4" />
              )}
            </div>
            <div
              className={`max-w-[85%] px-3 py-2 rounded-xl text-sm ${msg.role === "user"
                ? "bg-blue-600 text-white rounded-tr-none"
                : "bg-gray-100 dark:bg-gray-700 text-gray-800 dark:text-gray-200 rounded-tl-none"
                }`}
            >
              {msg.content}
            </div>
          </div>
        ))}
        {isTyping && (
          <div className="flex gap-2">
            <div className="w-7 h-7 rounded-full bg-purple-100 flex items-center justify-center">
              <Bot className="w-4 h-4 text-purple-600" />
            </div>
            <div className="px-3 py-2 bg-gray-100 dark:bg-gray-700 rounded-xl rounded-tl-none">
              <div className="flex gap-1">
                <span className="w-2 h-2 bg-gray-400 rounded-full animate-bounce" />
                <span
                  className="w-2 h-2 bg-gray-400 rounded-full animate-bounce"
                  style={{ animationDelay: "0.1s" }}
                />
                <span
                  className="w-2 h-2 bg-gray-400 rounded-full animate-bounce"
                  style={{ animationDelay: "0.2s" }}
                />
              </div>
            </div>
          </div>
        )}
      </div>

      {/* Input */}
      <div className="p-3 border-t border-gray-200 dark:border-gray-700">
        <div className="flex gap-2">
          <input
            type="text"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder="Ask AI for help..."
            aria-label="Ask AI Co-Pilot for help"
            className="flex-1 px-3 py-2 text-sm bg-gray-50 dark:bg-gray-700 border border-gray-200 dark:border-gray-600 rounded-lg"
            onKeyDown={(e) => {
              if (e.key === "Enter" && !e.shiftKey) {
                e.preventDefault();
                handleSend();
              }
            }}
          />
          <button
            onClick={handleSend}
            disabled={!input.trim()}
            aria-label="Send AI Co-Pilot message"
            className="p-2 bg-purple-600 text-white rounded-lg hover:bg-purple-700 disabled:opacity-50"
          >
            <Send className="w-4 h-4" />
          </button>
        </div>
      </div>
    </>
  );
}

// Export default for compatibility
export default AuthoringPage;
