/**
 * Phase graph - tracks execution dependencies and state across lifecycle phases.
 *
 * This module provides contracts for tracking the execution graph of lifecycle phases,
 * enabling replay-safe and queryable run history.
 *
 * @doc.type module
 * @doc.purpose Phase graph contracts for lifecycle execution tracking
 * @doc.layer platform
 * @doc.pattern DomainModel
 */

import type { ProductLifecyclePhase } from "./ProductLifecyclePhase.js";

/**
 * Node in the phase graph representing a lifecycle phase.
 */
export interface PhaseGraphNode {
  /**
   * The lifecycle phase this node represents.
   */
  readonly phase: ProductLifecyclePhase;

  /**
   * Unique identifier for this node in the graph.
   */
  readonly nodeId: string;

  /**
   * Nodes that this phase depends on (must complete before this phase can start).
   */
  readonly dependsOn: readonly string[];

  /**
   * Current execution state of this phase.
   */
  readonly state: PhaseNodeState;

  /**
   * Timestamp when this phase started execution.
   */
  readonly startedAt?: string;

  /**
   * Timestamp when this phase completed execution.
   */
  readonly completedAt?: string;

  /**
   * Duration in milliseconds for this phase execution.
   */
  readonly durationMs?: number;

  /**
   * Error message if the phase failed.
   */
  readonly error?: string;

  /**
   * Evidence references generated by this phase.
   */
  readonly evidenceRefs?: readonly string[];
}

/**
 * Execution state of a phase graph node.
 */
export type PhaseNodeState =
  | "pending"
  | "running"
  | "succeeded"
  | "failed"
  | "skipped"
  | "blocked";

/**
 * The complete phase graph for a product lifecycle run.
 */
export interface PhaseGraph {
  /**
   * Schema version for contract compatibility.
   */
  readonly schemaVersion: "1.0.0";

  /**
   * Product identifier.
   */
  readonly productId: string;

  /**
   * Run identifier for this execution.
   */
  readonly runId: string;

  /**
   * Correlation identifier for tracing.
   */
  readonly correlationId?: string;

  /**
   * All nodes in the graph.
   */
  readonly nodes: readonly PhaseGraphNode[];

  /**
   * Current overall state of the graph.
   */
  readonly state: PhaseGraphState;

  /**
   * Timestamp when the graph was created.
   */
  readonly createdAt: string;

  /**
   * Timestamp when the graph was last updated.
   */
  readonly updatedAt: string;

  /**
   * Metadata about the execution.
   */
  readonly metadata?: PhaseGraphMetadata;
}

/**
 * Overall state of the phase graph.
 */
export type PhaseGraphState =
  | "pending"
  | "running"
  | "succeeded"
  | "failed"
  | "partially-succeeded"
  | "blocked";

/**
 * Metadata for the phase graph.
 */
export interface PhaseGraphMetadata {
  /**
   * Lifecycle profile used for this execution.
   */
  readonly lifecycleProfile?: string;

  /**
   * Provider mode used for this execution.
   */
  readonly providerMode?: "bootstrap" | "platform";

  /**
   * Environment for this execution.
   */
  readonly environment?: string;

  /**
   * Source reference for this execution.
   */
  readonly sourceRef?: string;

  /**
   * Product unit reference for this execution.
   */
  readonly productUnitRef?: string;
}

/**
 * Phase graph query result.
 */
export interface PhaseGraphQuery {
  /**
   * The phase graph.
   */
  readonly graph: PhaseGraph;

  /**
   * Nodes that can be executed next (dependencies satisfied).
   */
  readonly readyNodes: readonly PhaseGraphNode[];

  /**
   * Nodes that are blocked (dependencies not satisfied).
   */
  readonly blockedNodes: readonly PhaseGraphNode[];

  /**
   * Nodes that have succeeded.
   */
  readonly succeededNodes: readonly PhaseGraphNode[];

  /**
   * Nodes that have failed.
   */
  readonly failedNodes: readonly PhaseGraphNode[];

  /**
   * Overall progress percentage (0-100).
   */
  readonly progress: number;
}

/**
 * Phase graph update operation.
 */
export interface PhaseGraphUpdate {
  /**
   * Node identifier to update.
   */
  readonly nodeId: string;

  /**
   * New state for the node.
   */
  readonly state: PhaseNodeState;

  /**
   * Timestamp when the update occurred.
   */
  readonly timestamp: string;

  /**
   * Error message if the update represents a failure.
   */
  readonly error?: string;

  /**
   * Evidence references to add.
   */
  readonly evidenceRefs?: readonly string[];
}

/**
 * Phase graph snapshot for a specific point in time.
 */
export interface PhaseGraphSnapshot {
  /**
   * The phase graph at this point in time.
   */
  readonly graph: PhaseGraph;

  /**
   * Snapshot timestamp.
   */
  readonly snapshotAt: string;

  /**
   * Snapshot reason (e.g., "phase-started", "phase-completed", "error").
   */
  readonly reason: string;
}
