package com.ghatana.yappc.services.artifact;

import com.ghatana.yappc.domain.artifact.ResidualIslandDto;

import java.util.LinkedHashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.regex.Pattern;

/**
 * Classifies residual islands without dropping source fidelity.
 *
 * @doc.type class
 * @doc.purpose Analyzes artifact residual islands to classify secrets, PII, generated code, and confidence signals
 * @doc.layer product
 * @doc.pattern Service
 */
public final class ResidualIslandService {

    private static final Pattern SECRET_PATTERN = Pattern.compile(
            "(?i)(api[_-]?key|secret|password|token|BEGIN\\s+(RSA\\s+)?PRIVATE\\s+KEY|aws_access_key_id)");
    private static final Pattern PII_PATTERN = Pattern.compile(
            "(?i)(\\b\\d{3}-\\d{2}-\\d{4}\\b|[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,}|patient|diagnosis|dob|date\\s+of\\s+birth)");

    public ResidualIslandDto analyze(ArtifactRequestScope scope, ResidualIslandDto island) {
        Objects.requireNonNull(scope, "scope must not be null");
        Objects.requireNonNull(island, "island must not be null");

        String source = island.originalSource();
        String sourceLower = source.toLowerCase(Locale.ROOT);
        boolean secretHint = SECRET_PATTERN.matcher(source).find();
        boolean piiHint = PII_PATTERN.matcher(source).find();
        boolean generatedHint = sourceLower.contains("@generated") || sourceLower.contains("generated by");
        boolean lowConfidence = island.confidence() == null || island.confidence() < 0.7d;

        String reason = firstNonBlank(island.reason(),
                secretHint ? "contains-secret-like-fragment"
                        : piiHint ? "contains-pii-like-fragment"
                        : generatedHint ? "generated-source-fragment"
                        : "unsupported-source-fragment");

        double riskScore = Math.max(
                island.riskScore() != null ? island.riskScore() : 0.0d,
                secretHint ? 0.95d : piiHint ? 0.85d : lowConfidence ? 0.55d : 0.35d);
        boolean reviewRequired = Boolean.TRUE.equals(island.reviewRequired()) || riskScore >= 0.5d || lowConfidence;

        Map<String, String> metadata = new LinkedHashMap<>();
        if (island.metadata() != null) {
            metadata.putAll(island.metadata());
        }
        metadata.put("analysisVersion", "residual-island-service-v1");
        metadata.put("preservationStrategy", "preserve-original-source");
        metadata.put("reviewRequiredReason", reviewRequired ? reason : "confidence-acceptable");
        metadata.put("secretHint", Boolean.toString(secretHint));
        metadata.put("piiHint", Boolean.toString(piiHint));

        return new ResidualIslandDto(
                island.id(),
                firstNonBlank(island.islandType(), "unmodeled-source"),
                firstNonBlank(island.summary(), "Unsupported source fragment"),
                source,
                island.sourceLocation(),
                island.sourceSpan(),
                island.checksum(),
                firstNonBlank(island.rawFragmentRef(), "residual://" + island.id()),
                reason,
                island.confidence(),
                reviewRequired,
                riskScore,
                Map.copyOf(metadata),
                island.fileCount() != null ? island.fileCount() : 1,
                firstNonBlank(island.tenantId(), scope.tenantId()),
                firstNonBlank(island.projectId(), scope.projectId()),
                firstNonBlank(island.workspaceId(), scope.workspaceId()),
                island.snapshotId());
    }

    private static String firstNonBlank(String preferred, String fallback) {
        return preferred != null && !preferred.isBlank() ? preferred : fallback;
    }
}
