/**
 * @doc.type service
 * @doc.purpose Animation integration with Content Studio
 * @doc.layer product
 * @doc.pattern Integration Service
 */

import type { AnimationSpec } from '../animation-runtime/service';
import { animationTemplateLibrary } from '../animation-runtime/templates';

export interface AnimationContentLink {
    contentId: string;
    claimId: string;
    animationId: string;
    animationType: 'demonstration' | 'exploration' | 'assessment';
    autoGenerated: boolean;
    metadata: {
        concept: string;
        difficulty: string;
        estimatedDuration: number;
    };
}

/**
 * Animation Content Integration Service
 * Links animations with learning content and claims
 */
export class AnimationContentIntegration {
    /**
     * Generate animation for a claim
     */
    async generateAnimationForClaim(claim: {
        id: string;
        text: string;
        bloomLevel: string;
        domain: string;
    }): Promise<AnimationSpec | null> {
        // Determine appropriate animation template based on claim
        const templateId = this.selectTemplateForClaim(claim);
        if (!templateId) return null;

        // Create animation from template
        const animation = animationTemplateLibrary.createFromTemplate(templateId, {
            title: `Animation for: ${claim.text.substring(0, 50)}...`,
            description: `Demonstrates: ${claim.text}`,
        });

        return animation;
    }

    /**
     * Select appropriate template for a claim
     */
    private selectTemplateForClaim(claim: {
        text: string;
        bloomLevel: string;
        domain: string;
    }): string | null {
        const domain = claim.domain.toLowerCase();
        const text = claim.text.toLowerCase();

        // Physics domain
        if (domain === 'physics') {
            if (text.includes('projectile') || text.includes('trajectory')) {
                return 'physics-projectile';
            }
            if (text.includes('oscillat') || text.includes('pendulum') || text.includes('spring')) {
                return 'physics-shm';
            }
            if (text.includes('circular') || text.includes('rotation') || text.includes('orbit')) {
                return 'physics-circular';
            }
        }

        // Chemistry domain
        if (domain === 'chemistry') {
            if (text.includes('vibrat') || text.includes('bond') || text.includes('molecule')) {
                return 'chemistry-vibration';
            }
        }

        // Biology domain
        if (domain === 'biology') {
            if (text.includes('cell') || text.includes('mitosis') || text.includes('division')) {
                return 'biology-cell-division';
            }
        }

        // Math domain
        if (domain === 'math' || domain === 'mathematics') {
            if (text.includes('transform') || text.includes('function') || text.includes('graph')) {
                return 'math-transformation';
            }
        }

        // Default to general animations
        if (text.includes('appear') || text.includes('show') || text.includes('reveal')) {
            return 'general-fade';
        }
        if (text.includes('grow') || text.includes('expand') || text.includes('enlarge')) {
            return 'general-zoom';
        }
        if (text.includes('move') || text.includes('slide') || text.includes('enter')) {
            return 'general-slide';
        }

        return null;
    }

    /**
     * Link animation to content
     */
    async linkAnimationToContent(link: AnimationContentLink): Promise<void> {
        // In production, this would save to database
        console.log('Linking animation to content:', link);
    }

    /**
     * Get animations for content
     */
    async getAnimationsForContent(contentId: string): Promise<AnimationContentLink[]> {
        // In production, this would query database
        return [];
    }

    /**
     * Get animations for claim
     */
    async getAnimationsForClaim(claimId: string): Promise<AnimationContentLink[]> {
        // In production, this would query database
        return [];
    }

    /**
     * Suggest animations for content
     */
    async suggestAnimations(content: {
        claims: Array<{ id: string; text: string; bloomLevel: string; domain: string }>;
    }): Promise<Array<{ claimId: string; suggestions: string[] }>> {
        const suggestions = content.claims.map(claim => {
            const templateId = this.selectTemplateForClaim(claim);
            const relatedTemplates = this.findRelatedTemplates(claim.domain);

            return {
                claimId: claim.id,
                suggestions: templateId
                    ? [templateId, ...relatedTemplates.filter(t => t !== templateId)]
                    : relatedTemplates,
            };
        });

        return suggestions;
    }

    /**
     * Find related templates by domain
     */
    private findRelatedTemplates(domain: string): string[] {
        const category = this.mapDomainToCategory(domain);
        const templates = animationTemplateLibrary.getTemplatesByCategory(category);
        return templates.map(t => t.id);
    }

    /**
     * Map domain to animation category
     */
    private mapDomainToCategory(domain: string): 'physics' | 'chemistry' | 'biology' | 'math' | 'general' {
        const domainLower = domain.toLowerCase();
        if (domainLower.includes('physic')) return 'physics';
        if (domainLower.includes('chemis')) return 'chemistry';
        if (domainLower.includes('biolog')) return 'biology';
        if (domainLower.includes('math')) return 'math';
        return 'general';
    }

    /**
     * Batch generate animations for multiple claims
     */
    async batchGenerateAnimations(claims: Array<{
        id: string;
        text: string;
        bloomLevel: string;
        domain: string;
    }>): Promise<Map<string, AnimationSpec | null>> {
        const results = new Map<string, AnimationSpec | null>();

        for (const claim of claims) {
            const animation = await this.generateAnimationForClaim(claim);
            results.set(claim.id, animation);
        }

        return results;
    }

    /**
     * Get animation statistics for content
     */
    async getAnimationStats(contentId: string): Promise<{
        total: number;
        byType: Record<string, number>;
        byDomain: Record<string, number>;
        autoGenerated: number;
        manual: number;
    }> {
        // In production, this would aggregate from database
        return {
            total: 0,
            byType: {},
            byDomain: {},
            autoGenerated: 0,
            manual: 0,
        };
    }
}

/**
 * Singleton instance
 */
export const animationContentIntegration = new AnimationContentIntegration();
