/**
 * @doc.type service
 * @doc.purpose Animation integration with Content Studio
 * @doc.layer product
 * @doc.pattern Integration Service
 */

import type { AnimationSpec } from "../animation-runtime/service";
import { animationTemplateLibrary } from "../animation-runtime/templates";
import type { TutorPrismaClient } from "@tutorputor/core/db";

export interface AnimationContentLink {
  contentId: string;
  claimId: string;
  animationId: string;
  animationType: "demonstration" | "exploration" | "assessment";
  autoGenerated: boolean;
  metadata: {
    concept: string;
    difficulty: string;
    estimatedDuration: number;
  };
  spec?: AnimationSpec;
}

/**
 * Animation Content Integration Service
 * Links animations with learning content and claims.
 * Persists links to ClaimAnimation model in the database.
 */
export class AnimationContentIntegration {
  constructor(private readonly prisma: TutorPrismaClient) {}
  /**
   * Generate animation for a claim
   */
  async generateAnimationForClaim(claim: {
    id: string;
    text: string;
    bloomLevel: string;
    domain: string;
  }): Promise<AnimationSpec | null> {
    // Determine appropriate animation template based on claim
    const templateId = this.selectTemplateForClaim(claim);
    if (!templateId) return null;

    // Create animation from template
    const animation = animationTemplateLibrary.createFromTemplate(templateId, {
      title: `Animation for: ${claim.text.substring(0, 50)}...`,
      description: `Demonstrates: ${claim.text}`,
    });

    return animation;
  }

  /**
   * Select appropriate template for a claim
   */
  private selectTemplateForClaim(claim: {
    text: string;
    bloomLevel: string;
    domain: string;
  }): string | null {
    const domain = claim.domain.toLowerCase();
    const text = claim.text.toLowerCase();

    // Physics domain
    if (domain === "physics") {
      if (text.includes("projectile") || text.includes("trajectory")) {
        return "physics-projectile";
      }
      if (
        text.includes("oscillat") ||
        text.includes("pendulum") ||
        text.includes("spring")
      ) {
        return "physics-shm";
      }
      if (
        text.includes("circular") ||
        text.includes("rotation") ||
        text.includes("orbit")
      ) {
        return "physics-circular";
      }
    }

    // Chemistry domain
    if (domain === "chemistry") {
      if (
        text.includes("vibrat") ||
        text.includes("bond") ||
        text.includes("molecule")
      ) {
        return "chemistry-vibration";
      }
    }

    // Biology domain
    if (domain === "biology") {
      if (
        text.includes("cell") ||
        text.includes("mitosis") ||
        text.includes("division")
      ) {
        return "biology-cell-division";
      }
    }

    // Math domain
    if (domain === "math" || domain === "mathematics") {
      if (
        text.includes("transform") ||
        text.includes("function") ||
        text.includes("graph")
      ) {
        return "math-transformation";
      }
    }

    // Default to general animations
    if (
      text.includes("appear") ||
      text.includes("show") ||
      text.includes("reveal")
    ) {
      return "general-fade";
    }
    if (
      text.includes("grow") ||
      text.includes("expand") ||
      text.includes("enlarge")
    ) {
      return "general-zoom";
    }
    if (
      text.includes("move") ||
      text.includes("slide") ||
      text.includes("enter")
    ) {
      return "general-slide";
    }

    return null;
  }

  /**
   * Link animation to content by persisting a ClaimAnimation record.
   * Uses upsert to handle re-linking without duplicates.
   */
  async linkAnimationToContent(link: AnimationContentLink): Promise<void> {
    const config = {
      animationId: link.animationId,
      autoGenerated: link.autoGenerated,
      animationType: link.animationType,
      metadata: link.metadata,
      spec: link.spec,
    } as object;

    const existingAnimation = await this.prisma.claimAnimation.findFirst({
      where: {
        experienceId: link.contentId,
        claimRef: link.claimId,
        variantKey: "primary",
      },
      select: { id: true },
    });

    const animationData = {
      manifestId: link.animationId,
      manifestVersion: "1.0.0",
      title: `Animation: ${link.metadata.concept}`,
      description: `Type: ${link.animationType} | Difficulty: ${link.metadata.difficulty}`,
      type:
        link.animationType === "demonstration"
          ? "2d"
          : link.animationType === "exploration"
            ? "3d"
            : "timeline",
      duration: link.metadata.estimatedDuration,
      config,
    };

    if (existingAnimation) {
      await this.prisma.claimAnimation.update({
        where: { id: existingAnimation.id },
        data: animationData,
      });
      return;
    }

    await this.prisma.claimAnimation.create({
      data: {
        experienceId: link.contentId,
        claimRef: link.claimId,
        variantKey: "primary",
        isPrimary: true,
        ...animationData,
      },
    });
  }

  /**
   * Get all animation links for a content experience.
   */
  async getAnimationsForContent(
    contentId: string,
  ): Promise<AnimationContentLink[]> {
    const records = await this.prisma.claimAnimation.findMany({
      where: { experienceId: contentId },
    });
    return records.map((r) => this.recordToLink(r, contentId));
  }

  /**
   * Get all animation links for a specific claim within any experience.
   */
  async getAnimationsForClaim(
    claimId: string,
  ): Promise<AnimationContentLink[]> {
    const records = await this.prisma.claimAnimation.findMany({
      where: { claimRef: claimId },
    });
    return records.map((r) => this.recordToLink(r, r.experienceId));
  }

  private recordToLink(
    record: {
      id: string;
      experienceId: string;
      claimRef: string;
      config: unknown;
    },
    contentId: string,
  ): AnimationContentLink {
    const config = (record.config ?? {}) as Record<string, unknown>;
    return {
      contentId,
      claimId: record.claimRef,
      animationId: (config["animationId"] as string) ?? record.id,
      animationType:
        (config["animationType"] as AnimationContentLink["animationType"]) ??
        "demonstration",
      autoGenerated: (config["autoGenerated"] as boolean) ?? false,
      metadata: (config["metadata"] as AnimationContentLink["metadata"]) ?? {
        concept: "",
        difficulty: "INTERMEDIATE",
        estimatedDuration: 30,
      },
      ...(config["spec"] ? { spec: config["spec"] as AnimationSpec } : {}),
    };
  }

  /**
   * Suggest animations for content
   */
  async suggestAnimations(content: {
    claims: Array<{
      id: string;
      text: string;
      bloomLevel: string;
      domain: string;
    }>;
  }): Promise<Array<{ claimId: string; suggestions: string[] }>> {
    const suggestions = content.claims.map((claim) => {
      const templateId = this.selectTemplateForClaim(claim);
      const relatedTemplates = this.findRelatedTemplates(claim.domain);

      return {
        claimId: claim.id,
        suggestions: templateId
          ? [templateId, ...relatedTemplates.filter((t) => t !== templateId)]
          : relatedTemplates,
      };
    });

    return suggestions;
  }

  /**
   * Find related templates by domain
   */
  private findRelatedTemplates(domain: string): string[] {
    const category = this.mapDomainToCategory(domain);
    const templates = animationTemplateLibrary.getTemplatesByCategory(category);
    return templates.map((t) => t.id);
  }

  /**
   * Map domain to animation category
   */
  private mapDomainToCategory(
    domain: string,
  ): "physics" | "chemistry" | "biology" | "math" | "general" {
    const domainLower = domain.toLowerCase();
    if (domainLower.includes("physic")) return "physics";
    if (domainLower.includes("chemis")) return "chemistry";
    if (domainLower.includes("biolog")) return "biology";
    if (domainLower.includes("math")) return "math";
    return "general";
  }

  /**
   * Batch generate animations for multiple claims
   */
  async batchGenerateAnimations(
    claims: Array<{
      id: string;
      text: string;
      bloomLevel: string;
      domain: string;
    }>,
  ): Promise<Map<string, AnimationSpec | null>> {
    const results = new Map<string, AnimationSpec | null>();

    for (const claim of claims) {
      const animation = await this.generateAnimationForClaim(claim);
      results.set(claim.id, animation);
    }

    return results;
  }

  /**
   * Get animation statistics for content
   */
  async getAnimationStats(_contentId: string): Promise<{
    total: number;
    byType: Record<string, number>;
    byDomain: Record<string, number>;
    autoGenerated: number;
    manual: number;
  }> {
    // In production, this would aggregate from database
    return {
      total: 0,
      byType: {},
      byDomain: {},
      autoGenerated: 0,
      manual: 0,
    };
  }
}

/**
 * Factory function to create an AnimationContentIntegration instance with Prisma.
 * Call this from the content module plugin, passing the shared Prisma client.
 */
export function createAnimationContentIntegration(
  prisma: TutorPrismaClient,
): AnimationContentIntegration {
  return new AnimationContentIntegration(prisma);
}
