package com.ghatana.refactorer.shared;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Objects;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Provides precondition validation for edit ranges to avoid applying stale patches.
 *
 * <p>This component prevents applying fixes to files that have changed since the diagnostic was
 * generated by:
 *
 * <ul>
 *   <li>Computing hashes of specific line ranges in files
 *   <li>Validating that the content hasn't changed before applying fixes
 *   <li>Supporting both full file and range-based validation
 * </ul>
 *
 * <p>Example usage:
 *
 * <pre>{@code
 * PreconditionHash validator = new PreconditionHash();
 *
 * // Create a precondition for lines 10-15
 * Path file = Paths.get("src/main.py");
 * Precondition precondition = validator.createPrecondition(file, 10, 15);
 *
 * // Later, validate before applying a fix
 * if (validator.validate(precondition)) {
 *     // Safe to apply the fix
 * } else {
 *     // File has changed, skip the fix
 * }
 * }</pre>
 
 * @doc.type class
 * @doc.purpose Handles precondition hash operations
 * @doc.layer core
 * @doc.pattern Enum
*/
public class PreconditionHash {

    private static final Logger log = LoggerFactory.getLogger(PreconditionHash.class);

    private static final String HASH_ALGORITHM = "SHA-256";

    /**
     * Creates a precondition for the entire file.
     *
     * @param filePath The file to create a precondition for
     * @return Precondition containing the file hash
     * @throws IOException if the file cannot be read
     */
    public Precondition createPrecondition(Path filePath) throws IOException {
        Objects.requireNonNull(filePath, "filePath cannot be null");

        if (!Files.exists(filePath)) {
            throw new IOException("File does not exist: " + filePath);
        }

        String content = Files.readString(filePath);
        String hash = computeHash(content);

        // Debug: Created full file precondition for filePath: hash

        return new Precondition(
                filePath.toAbsolutePath().toString(),
                1,
                countLines(content),
                hash,
                PreconditionType.FULL_FILE);
    }

    /**
     * Creates a precondition for a specific line range in a file.
     *
     * @param filePath The file to create a precondition for
     * @param startLine The starting line number (1-based)
     * @param endLine The ending line number (1-based, inclusive)
     * @return Precondition containing the range hash
     * @throws IOException if the file cannot be read
     * @throws IllegalArgumentException if the line range is invalid
     */
    public Precondition createPrecondition(Path filePath, int startLine, int endLine)
            throws IOException {
        Objects.requireNonNull(filePath, "filePath cannot be null");

        if (startLine < 1) {
            throw new IllegalArgumentException("Start line must be >= 1, got: " + startLine);
        }
        if (endLine < startLine) {
            throw new IllegalArgumentException(
                    "End line must be >= start line, got: " + endLine + " < " + startLine);
        }

        if (!Files.exists(filePath)) {
            throw new IOException("File does not exist: " + filePath);
        }

        String content = Files.readString(filePath);
        String[] lines = content.split("\n", -1);

        if (startLine > lines.length) {
            throw new IllegalArgumentException(
                    "Start line " + startLine + " exceeds file length " + lines.length);
        }

        // Adjust endLine if it exceeds file length
        int actualEndLine = Math.min(endLine, lines.length);

        // Extract the range content (convert to 0-based indexing)
        StringBuilder rangeContent = new StringBuilder();
        for (int i = startLine - 1; i < actualEndLine; i++) {
            if (i > startLine - 1) {
                rangeContent.append("\n");
            }
            rangeContent.append(lines[i]);
        }

        String hash = computeHash(rangeContent.toString());

        // Debug: Created range precondition for filePath:startLine-actualEndLine: hash

        return new Precondition(
                filePath.toAbsolutePath().toString(),
                startLine,
                actualEndLine,
                hash,
                PreconditionType.LINE_RANGE);
    }

    /**
     * Creates a precondition for a single line in a file.
     *
     * @param filePath The file to create a precondition for
     * @param lineNumber The line number (1-based)
     * @return Precondition containing the line hash
     * @throws IOException if the file cannot be read
     */
    public Precondition createPrecondition(Path filePath, int lineNumber) throws IOException {
        return createPrecondition(filePath, lineNumber, lineNumber);
    }

    /**
     * Validates a precondition against the current state of the file.
     *
     * @param precondition The precondition to validate
     * @return true if the precondition is still valid, false otherwise
     */
    public boolean validate(Precondition precondition) {
        Objects.requireNonNull(precondition, "precondition cannot be null");

        try {
            Path filePath = Path.of(precondition.filePath());

            if (!Files.exists(filePath)) {
                log.warn("Warning: File no longer exists for precondition validation: {}", filePath);
                return false;
            }

            Precondition current;
            if (precondition.type() == PreconditionType.FULL_FILE) {
                current = createPrecondition(filePath);
            } else {
                current =
                        createPrecondition(
                                filePath, precondition.startLine(), precondition.endLine());
            }

            boolean valid = precondition.hash().equals(current.hash());

            if (!valid) {
                // Debug: Precondition validation failed for filePath: expected precondition.hash(),
                // got current.hash()
            }

            return valid;

        } catch (IOException | IllegalArgumentException e) {
            log.error("Warning: Error validating precondition for {}: {}", precondition.filePath(), e.getMessage());
            return false;
        }
    }

    /**
     * Validates a precondition and provides detailed information about the validation result.
     *
     * @param precondition The precondition to validate
     * @return ValidationResult with details about the validation
     */
    public ValidationResult validateWithDetails(Precondition precondition) {
        Objects.requireNonNull(precondition, "precondition cannot be null");

        try {
            Path filePath = Path.of(precondition.filePath());

            if (!Files.exists(filePath)) {
                return new ValidationResult(
                        false,
                        ValidationFailureReason.FILE_NOT_FOUND,
                        "File no longer exists: " + filePath);
            }

            Precondition current;
            if (precondition.type() == PreconditionType.FULL_FILE) {
                current = createPrecondition(filePath);
            } else {
                current =
                        createPrecondition(
                                filePath, precondition.startLine(), precondition.endLine());
            }

            if (precondition.hash().equals(current.hash())) {
                return new ValidationResult(true, null, null);
            } else {
                return new ValidationResult(
                        false,
                        ValidationFailureReason.CONTENT_CHANGED,
                        String.format(
                                "Hash mismatch: expected %s, got %s",
                                precondition.hash(), current.hash()));
            }

        } catch (IOException e) {
            return new ValidationResult(
                    false, ValidationFailureReason.IO_ERROR, "IO error: " + e.getMessage());
        } catch (IllegalArgumentException e) {
            return new ValidationResult(
                    false,
                    ValidationFailureReason.INVALID_RANGE,
                    "Invalid range: " + e.getMessage());
        }
    }

    private String computeHash(String content) {
        try {
            MessageDigest digest = MessageDigest.getInstance(HASH_ALGORITHM);
            byte[] hashBytes = digest.digest(content.getBytes());

            StringBuilder hexString = new StringBuilder();
            for (byte b : hashBytes) {
                String hex = Integer.toHexString(0xff & b);
                if (hex.length() == 1) {
                    hexString.append('0');
                }
                hexString.append(hex);
            }

            return hexString.toString();
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException("Hash algorithm not available: " + HASH_ALGORITHM, e);
        }
    }

    private int countLines(String content) {
        if (content.isEmpty()) {
            return 0;
        }
        return content.split("\n", -1).length;
    }

    /**
 * Represents a precondition for validating file content before applying edits. */
    public record Precondition(
            String filePath, int startLine, int endLine, String hash, PreconditionType type) {
        public Precondition {
            Objects.requireNonNull(filePath, "filePath cannot be null");
            Objects.requireNonNull(hash, "hash cannot be null");
            Objects.requireNonNull(type, "type cannot be null");

            if (startLine < 1) {
                throw new IllegalArgumentException("Start line must be >= 1");
            }
            if (endLine < startLine) {
                throw new IllegalArgumentException("End line must be >= start line");
            }
        }
    }

    /**
 * Type of precondition validation. */
    public enum PreconditionType {
        /**
 * Validates the entire file content */
        FULL_FILE,

        /**
 * Validates a specific line range */
        LINE_RANGE
    }

    /**
 * Result of precondition validation. */
    public record ValidationResult(
            boolean isValid, ValidationFailureReason failureReason, String message) {}

    /**
 * Reasons why precondition validation might fail. */
    public enum ValidationFailureReason {
        /**
 * The file no longer exists */
        FILE_NOT_FOUND,

        /**
 * The file content has changed */
        CONTENT_CHANGED,

        /**
 * The specified line range is invalid */
        INVALID_RANGE,

        /**
 * An IO error occurred while reading the file */
        IO_ERROR
    }
}
