/**
 * CloudCost Entity - Represents cloud infrastructure spending records
 *
 * <p><b>Purpose</b><br>
 * Persistent entity for storing cloud cost data from multiple providers.
 * Used as primary data source for cost analysis, optimization, and forecasting.
 *
 * <p><b>Usage</b><br>
 * <pre>{@code
 * const cost = new CloudCost();
 * cost.date = new Date('2025-01-13');
 * cost.provider = 'AWS';
 * cost.service = 'EC2';
 * cost.cost = 125.50;
 * cost.currency = 'USD';
 * cost.tags = { 'Environment': 'Production', 'Team': 'Platform' };
 * await costRepository.save(cost);
 * }</pre>
 *
 * <p><b>Database</b><br>
 * PostgreSQL table with columns: id, date, provider, service, cost, currency, tags, createdAt, updatedAt
 *
 * <p><b>Indexes</b><br>
 * - Composite: (date, provider, service) for efficient aggregation queries
 * - Single: date for time-range queries
 *
 * @doc.type class
 * @doc.purpose Cloud cost storage entity
 * @doc.layer product
 * @doc.pattern Value Object
 */
export class CloudCost {
  /**
   * Unique identifier
   * Generated by database (UUID)
   */
  id!: string;

  /**
   * Cost record date (day-level granularity)
   * Used for aggregation and time-series analysis
   */
  date!: Date;

  /**
   * Cloud provider name (AWS, GCP, Azure)
   * Used for cost breakdown by provider
   */
  provider!: string;

  /**
   * Service category (EC2, S3, Lambda, etc.)
   * Used for cost breakdown by service
   */
  service!: string;

  /**
   * Cost amount in specified currency
   * Always positive value
   * Precision: 2 decimal places for currency
   */
  cost!: number;

  /**
   * Currency code (USD, EUR, etc.)
   * Defaults to USD
   */
  currency!: string;

  /**
   * Resource tags for cost allocation
   * Key-value pairs (e.g., { 'Environment': 'Prod', 'Team': 'Platform' })
   * Used for cost center allocation and filtering
   */
  tags!: Record<string, string>;

  /**
   * Record creation timestamp
   * Set automatically by database
   */
  createdAt!: Date;

  /**
   * Record last update timestamp
   * Updated automatically on modifications
   */
  updatedAt!: Date;

  /**
   * Validates CloudCost entity
   * @returns true if entity is valid
   * @throws Error if validation fails
   */
  validate(): boolean {
    if (!this.date) {
      throw new Error('CloudCost: date is required');
    }
    if (!this.provider || this.provider.trim().length === 0) {
      throw new Error('CloudCost: provider is required');
    }
    if (!this.service || this.service.trim().length === 0) {
      throw new Error('CloudCost: service is required');
    }
    if (this.cost === undefined || this.cost < 0) {
      throw new Error('CloudCost: cost must be non-negative number');
    }
    if (!this.currency || this.currency.trim().length === 0) {
      throw new Error('CloudCost: currency is required');
    }
    if (!this.tags || typeof this.tags !== 'object') {
      throw new Error('CloudCost: tags must be object');
    }
    return true;
  }
}
