/**
 * Animation Examples Library - 100+ Production-Ready Animation Examples
 * 
 * Comprehensive collection of animations for education, UI/UX, and visual effects.
 * Each example is ready to use with the animator library.
 */

import type { AnimationTrack } from '../index';

export interface AnimationExample {
  id: string;
  name: string;
  description: string;
  category: 'physics' | 'chemistry' | 'biology' | 'math' | 'cs' | 'ui' | 'feedback' | 'entrance' | 'exit' | 'attention' | 'transition';
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  tags: string[];
  tracks: AnimationTrack[];
  estimatedDuration: number;
  previewCode?: string;
}

// =============================================================================
// PHYSICS ANIMATIONS (1-20)
// =============================================================================

export const PhysicsAnimations: AnimationExample[] = [
  {
    id: 'physics-001',
    name: 'Free Fall (Gravity)',
    description: 'Object falling under gravity with acceleration visualization',
    category: 'physics',
    difficulty: 'beginner',
    tags: ['gravity', 'acceleration', 'kinematics', 'motion'],
    estimatedDuration: 2000,
    tracks: [
      {
        id: 'ball-fall',
        target: '.falling-ball',
        property: 'transform',
        from: 'translateY(0px)',
        to: 'translateY(400px)',
        duration: 2000,
        easing: 'ease-in',
      },
      {
        id: 'velocity-indicator',
        target: '.velocity-arrow',
        property: 'height',
        from: '20px',
        to: '100px',
        duration: 2000,
        easing: 'ease-in',
      },
    ],
  },
  {
    id: 'physics-002',
    name: 'Projectile Motion',
    description: 'Parabolic trajectory of a projectile',
    category: 'physics',
    difficulty: 'intermediate',
    tags: ['projectile', 'trajectory', 'parabola', 'velocity'],
    estimatedDuration: 3000,
    tracks: [
      {
        id: 'projectile-x',
        target: '.projectile',
        property: 'transform',
        keyframes: [
          { time: 0, value: 'translate(0, 0)' },
          { time: 1500, value: 'translate(200px, -100px)' },
          { time: 3000, value: 'translate(400px, 0)' },
        ],
        from: 'translate(0, 0)',
        to: 'translate(400px, 0)',
        duration: 3000,
        easing: 'ease-out',
      },
      {
        id: 'trail-fade',
        target: '.projectile-trail',
        property: 'opacity',
        from: 1,
        to: 0,
        duration: 500,
        delay: 2500,
        easing: 'ease-out',
      },
    ],
  },
  {
    id: 'physics-003',
    name: 'Simple Harmonic Motion (Pendulum)',
    description: 'Oscillating pendulum demonstrating SHM',
    category: 'physics',
    difficulty: 'beginner',
    tags: ['pendulum', 'oscillation', 'shm', 'harmonic'],
    estimatedDuration: 4000,
    tracks: [
      {
        id: 'pendulum-swing',
        target: '.pendulum-bob',
        property: 'transform',
        keyframes: [
          { time: 0, value: 'rotate(-30deg)' },
          { time: 1000, value: 'rotate(30deg)' },
          { time: 2000, value: 'rotate(-30deg)' },
          { time: 3000, value: 'rotate(30deg)' },
          { time: 4000, value: 'rotate(-30deg)' },
        ],
        from: 'rotate(-30deg)',
        to: 'rotate(-30deg)',
        duration: 4000,
        easing: 'ease-in-out',
      },
    ],
  },
  {
    id: 'physics-004',
    name: 'Spring Oscillation',
    description: 'Mass-spring system with damping',
    category: 'physics',
    difficulty: 'intermediate',
    tags: ['spring', 'oscillation', 'damping', 'harmonic'],
    estimatedDuration: 5000,
    tracks: [
      {
        id: 'spring-compress',
        target: '.spring-mass',
        property: 'transform',
        from: 'translateY(0px)',
        to: 'translateY(100px)',
        duration: 500,
        easing: 'spring',
      },
      {
        id: 'spring-bounce',
        target: '.spring-mass',
        property: 'transform',
        keyframes: [
          { time: 0, value: 'translateY(100px) scaleY(1)' },
          { time: 250, value: 'translateY(-20px) scaleY(0.8)' },
          { time: 500, value: 'translateY(60px) scaleY(1)' },
          { time: 750, value: 'translateY(-10px) scaleY(0.9)' },
          { time: 1000, value: 'translateY(30px) scaleY(1)' },
          { time: 1250, value: 'translateY(0px) scaleY(1)' },
        ],
        from: 'translateY(100px)',
        to: 'translateY(0px)',
        duration: 2000,
        delay: 500,
        easing: 'spring',
      },
    ],
  },
  {
    id: 'physics-005',
    name: 'Circular Motion',
    description: 'Uniform circular motion with velocity and acceleration vectors',
    category: 'physics',
    difficulty: 'intermediate',
    tags: ['circular', 'velocity', 'acceleration', 'centripetal'],
    estimatedDuration: 3000,
    tracks: [
      {
        id: 'orbit',
        target: '.orbiting-body',
        property: 'transform',
        from: 'rotate(0deg) translateX(100px) rotate(0deg)',
        to: 'rotate(360deg) translateX(100px) rotate(-360deg)',
        duration: 3000,
        easing: 'linear',
        repeat: -1,
      },
      {
        id: 'velocity-vector-rotate',
        target: '.velocity-vector',
        property: 'transform',
        from: 'rotate(0deg)',
        to: 'rotate(360deg)',
        duration: 3000,
        easing: 'linear',
        repeat: -1,
      },
    ],
  },
  {
    id: 'physics-006',
    name: 'Wave Propagation',
    description: 'Sine wave moving through a medium',
    category: 'physics',
    difficulty: 'intermediate',
    tags: ['wave', 'propagation', 'sine', 'frequency'],
    estimatedDuration: 3000,
    tracks: [
      {
        id: 'wave-move',
        target: '.wave-path',
        property: 'stroke-dashoffset',
        from: 0,
        to: -200,
        duration: 2000,
        easing: 'linear',
        repeat: -1,
      },
      {
        id: 'particle-oscillate',
        target: '.wave-particle',
        property: 'transform',
        from: 'translateY(0px)',
        to: 'translateY(-30px)',
        duration: 1000,
        easing: 'ease-in-out',
        yoyo: true,
        repeat: -1,
      },
    ],
  },
  {
    id: 'physics-007',
    name: 'Collision (Elastic)',
    description: 'Two balls colliding elastically',
    category: 'physics',
    difficulty: 'intermediate',
    tags: ['collision', 'elastic', 'momentum', 'conservation'],
    estimatedDuration: 2000,
    tracks: [
      {
        id: 'ball-1-approach',
        target: '.ball-1',
        property: 'transform',
        from: 'translateX(0px)',
        to: 'translateX(150px)',
        duration: 800,
        easing: 'ease-out',
      },
      {
        id: 'ball-2-approach',
        target: '.ball-2',
        property: 'transform',
        from: 'translateX(0px)',
        to: 'translateX(-150px)',
        duration: 800,
        easing: 'ease-out',
      },
      {
        id: 'ball-1-bounce',
        target: '.ball-1',
        property: 'transform',
        from: 'translateX(150px)',
        to: 'translateX(0px)',
        duration: 800,
        delay: 800,
        easing: 'ease-out',
      },
      {
        id: 'ball-2-bounce',
        target: '.ball-2',
        property: 'transform',
        from: 'translateX(-150px)',
        to: 'translateX(0px)',
        duration: 800,
        delay: 800,
        easing: 'ease-out',
      },
    ],
  },
  {
    id: 'physics-008',
    name: 'Refraction',
    description: 'Light ray bending at medium interface',
    category: 'physics',
    difficulty: 'advanced',
    tags: ['refraction', 'light', 'optics', 'snell'],
    estimatedDuration: 3000,
    tracks: [
      {
        id: 'ray-incident',
        target: '.incident-ray',
        property: 'stroke-dashoffset',
        from: 100,
        to: 0,
        duration: 1000,
        easing: 'ease-out',
      },
      {
        id: 'ray-refracted',
        target: '.refracted-ray',
        property: 'stroke-dashoffset',
        from: 100,
        to: 0,
        duration: 1000,
        delay: 1000,
        easing: 'ease-out',
      },
      {
        id: 'normal-appear',
        target: '.normal-line',
        property: 'opacity',
        from: 0,
        to: 0.5,
        duration: 500,
        delay: 500,
        easing: 'ease-out',
      },
    ],
  },
  {
    id: 'physics-009',
    name: 'Doppler Effect',
    description: 'Sound waves compressing/expanding from moving source',
    category: 'physics',
    difficulty: 'advanced',
    tags: ['doppler', 'waves', 'frequency', 'sound'],
    estimatedDuration: 4000,
    tracks: [
      {
        id: 'source-move',
        target: '.sound-source',
        property: 'transform',
        from: 'translateX(-100px)',
        to: 'translateX(100px)',
        duration: 4000,
        easing: 'linear',
      },
      {
        id: 'wave-1-expand',
        target: '.wave-1',
        property: 'transform',
        from: 'scale(0)',
        to: 'scale(2)',
        duration: 2000,
        easing: 'ease-out',
      },
      {
        id: 'wave-2-expand',
        target: '.wave-2',
        property: 'transform',
        from: 'scale(0)',
        to: 'scale(2)',
        duration: 2000,
        delay: 1000,
        easing: 'ease-out',
      },
    ],
  },
  {
    id: 'physics-010',
    name: 'Electric Field Lines',
    description: 'Field lines around positive and negative charges',
    category: 'physics',
    difficulty: 'intermediate',
    tags: ['electric', 'field', 'charges', 'electromagnetism'],
    estimatedDuration: 3000,
    tracks: [
      {
        id: 'positive-charge-pulse',
        target: '.positive-charge',
        property: 'box-shadow',
        from: '0 0 0px #ff6b6b',
        to: '0 0 30px #ff6b6b',
        duration: 1500,
        easing: 'ease-out',
        yoyo: true,
        repeat: -1,
      },
      {
        id: 'negative-charge-pulse',
        target: '.negative-charge',
        property: 'box-shadow',
        from: '0 0 0px #4ecdc4',
        to: '0 0 30px #4ecdc4',
        duration: 1500,
        easing: 'ease-out',
        yoyo: true,
        repeat: -1,
      },
      {
        id: 'field-lines-draw',
        target: '.field-line',
        property: 'stroke-dashoffset',
        from: 200,
        to: 0,
        duration: 2000,
        easing: 'ease-out',
      },
    ],
  },
  {
    id: 'physics-011',
    name: 'Magnetic Field Around Wire',
    description: 'Concentric circles representing magnetic field',
    category: 'physics',
    difficulty: 'intermediate',
    tags: ['magnetic', 'field', 'current', 'ampere'],
    estimatedDuration: 3000,
    tracks: [
      {
        id: 'current-flow',
        target: '.current-indicator',
        property: 'stroke-dashoffset',
        from: 0,
        to: -50,
        duration: 1000,
        easing: 'linear',
        repeat: -1,
      },
      {
        id: 'field-ring-1',
        target: '.field-ring-1',
        property: 'transform',
        from: 'scale(0.8) rotate(0deg)',
        to: 'scale(1) rotate(360deg)',
        duration: 3000,
        easing: 'linear',
        repeat: -1,
      },
      {
        id: 'field-ring-2',
        target: '.field-ring-2',
        property: 'transform',
        from: 'scale(0.8) rotate(0deg)',
        to: 'scale(1.2) rotate(-360deg)',
        duration: 4000,
        easing: 'linear',
        repeat: -1,
      },
    ],
  },
  {
    id: 'physics-012',
    name: 'Planetary Orbit',
    description: 'Earth orbiting the sun with seasons indication',
    category: 'physics',
    difficulty: 'beginner',
    tags: ['orbit', 'planetary', 'kepler', 'astronomy'],
    estimatedDuration: 8000,
    tracks: [
      {
        id: 'earth-orbit',
        target: '.earth',
        property: 'transform',
        from: 'rotate(0deg) translateX(150px)',
        to: 'rotate(360deg) translateX(150px)',
        duration: 8000,
        easing: 'linear',
        repeat: -1,
      },
      {
        id: 'earth-rotate',
        target: '.earth-surface',
        property: 'transform',
        from: 'rotate(0deg)',
        to: 'rotate(360deg)',
        duration: 2000,
        easing: 'linear',
        repeat: -1,
      },
      {
        id: 'seasons-indicator',
        target: '.season-marker',
        property: 'opacity',
        keyframes: [
          { time: 0, value: 1 },
          { time: 2000, value: 0.5 },
          { time: 4000, value: 1 },
          { time: 6000, value: 0.5 },
          { time: 8000, value: 1 },
        ],
        from: 1,
        to: 1,
        duration: 8000,
        easing: 'ease-in-out',
      },
    ],
  },
  {
    id: 'physics-013',
    name: 'Diffraction',
    description: 'Wave passing through a slit and spreading',
    category: 'physics',
    difficulty: 'advanced',
    tags: ['diffraction', 'waves', 'interference', 'slit'],
    estimatedDuration: 3000,
    tracks: [
      {
        id: 'wave-approach',
        target: '.plane-wave',
        property: 'transform',
        from: 'translateX(-100%)',
        to: 'translateX(0)',
        duration: 1000,
        easing: 'linear',
      },
      {
        id: 'wave-spread',
        target: '.diffracted-wave',
        property: 'transform',
        from: 'scaleX(0) scaleY(1)',
        to: 'scaleX(1) scaleY(2)',
        duration: 2000,
        delay: 1000,
        easing: 'ease-out',
      },
    ],
  },
  {
    id: 'physics-014',
    name: 'Double Slit Interference',
    description: 'Wave interference pattern from two slits',
    category: 'physics',
    difficulty: 'advanced',
    tags: ['interference', 'double-slit', 'waves', 'pattern'],
    estimatedDuration: 4000,
    tracks: [
      {
        id: 'waves-from-slit-1',
        target: '.wave-slit-1',
        property: 'transform',
        from: 'scale(0)',
        to: 'scale(3)',
        duration: 2000,
        easing: 'ease-out',
      },
      {
        id: 'waves-from-slit-2',
        target: '.wave-slit-2',
        property: 'transform',
        from: 'scale(0)',
        to: 'scale(3)',
        duration: 2000,
        delay: 200,
        easing: 'ease-out',
      },
      {
        id: 'interference-pattern',
        target: '.interference',
        property: 'opacity',
        from: 0,
        to: 1,
        duration: 1000,
        delay: 2000,
        easing: 'ease-in',
      },
    ],
  },
  {
    id: 'physics-015',
    name: 'Thermodynamics - Heat Transfer',
    description: 'Heat flowing from hot to cold region',
    category: 'physics',
    difficulty: 'beginner',
    tags: ['thermodynamics', 'heat', 'temperature', 'transfer'],
    estimatedDuration: 3000,
    tracks: [
      {
        id: 'heat-particles-move',
        target: '.heat-particle',
        property: 'transform',
        from: 'translateX(0)',
        to: 'translateX(200px)',
        duration: 2000,
        easing: 'ease-out',
      },
      {
        id: 'hot-region-cool',
        target: '.hot-region',
        property: 'background-color',
        from: '#ff6b6b',
        to: '#ffd93d',
        duration: 3000,
        easing: 'ease-out',
      },
      {
        id: 'cold-region-warm',
        target: '.cold-region',
        property: 'background-color',
        from: '#4ecdc4',
        to: '#ffd93d',
        duration: 3000,
        easing: 'ease-out',
      },
    ],
  },
  {
    id: 'physics-016',
    name: 'Gas Pressure (Kinetic Theory)',
    description: 'Gas particles colliding with container walls',
    category: 'physics',
    difficulty: 'intermediate',
    tags: ['gas', 'pressure', 'kinetic', 'particles'],
    estimatedDuration: 2000,
    tracks: [
      {
        id: 'particle-1-bounce',
        target: '.gas-particle-1',
        property: 'transform',
        keyframes: [
          { time: 0, value: 'translate(0, 0)' },
          { time: 500, value: 'translate(90px, 50px)' },
          { time: 1000, value: 'translate(80px, 100px)' },
          { time: 1500, value: 'translate(20px, 50px)' },
          { time: 2000, value: 'translate(0, 0)' },
        ],
        from: 'translate(0, 0)',
        to: 'translate(0, 0)',
        duration: 2000,
        easing: 'linear',
        repeat: -1,
      },
      {
        id: 'wall-compress',
        target: '.container-wall',
        property: 'transform',
        from: 'scaleX(1)',
        to: 'scaleX(0.98)',
        duration: 100,
        delay: 500,
        easing: 'ease-out',
        yoyo: true,
        repeat: 1,
      },
    ],
  },
  {
    id: 'physics-017',
    name: 'Buoyancy',
    description: 'Object floating based on density',
    category: 'physics',
    difficulty: 'beginner',
    tags: ['buoyancy', 'fluid', 'density', 'archimedes'],
    estimatedDuration: 2500,
    tracks: [
      {
        id: 'object-sink',
        target: '.dense-object',
        property: 'transform',
        from: 'translateY(0)',
        to: 'translateY(150px)',
        duration: 1500,
        easing: 'ease-in',
      },
      {
        id: 'object-float',
        target: '.light-object',
        property: 'transform',
        from: 'translateY(0)',
        to: 'translateY(50px)',
        duration: 1500,
        easing: 'ease-out',
      },
      {
        id: 'object-bob',
        target: '.light-object',
        property: 'transform',
        from: 'translateY(50px)',
        to: 'translateY(40px)',
        duration: 500,
        delay: 1500,
        easing: 'ease-in-out',
        yoyo: true,
        repeat: 2,
      },
    ],
  },
  {
    id: 'physics-018',
    name: 'Simple Machine - Lever',
    description: 'Lever balancing and motion',
    category: 'physics',
    difficulty: 'beginner',
    tags: ['lever', 'simple-machine', 'torque', 'balance'],
    estimatedDuration: 3000,
    tracks: [
      {
        id: 'lever-tilt',
        target: '.lever-arm',
        property: 'transform',
        from: 'rotate(0deg)',
        to: 'rotate(-15deg)',
        duration: 1000,
        easing: 'ease-out',
      },
      {
        id: 'weight-lift',
        target: '.weight-1',
        property: 'transform',
        from: 'translateY(0)',
        to: 'translateY(-50px)',
        duration: 1000,
        delay: 500,
        easing: 'ease-out',
      },
      {
        id: 'weight-drop',
        target: '.weight-2',
        property: 'transform',
        from: 'translateY(0)',
        to: 'translateY(30px)',
        duration: 1000,
        delay: 500,
        easing: 'ease-in',
      },
    ],
  },
  {
    id: 'physics-019',
    name: 'Pulley System',
    description: 'Mechanical advantage in pulley arrangement',
    category: 'physics',
    difficulty: 'intermediate',
    tags: ['pulley', 'simple-machine', 'mechanical-advantage', 'force'],
    estimatedDuration: 3000,
    tracks: [
      {
        id: 'rope-pull',
        target: '.rope-end',
        property: 'transform',
        from: 'translateY(0)',
        to: 'translateY(100px)',
        duration: 2000,
        easing: 'ease-out',
      },
      {
        id: 'load-lift',
        target: '.load',
        property: 'transform',
        from: 'translateY(0)',
        to: 'translateY(-50px)',
        duration: 2000,
        easing: 'ease-out',
      },
      {
        id: 'pulley-rotate',
        target: '.pulley-wheel',
        property: 'transform',
        from: 'rotate(0deg)',
        to: 'rotate(180deg)',
        duration: 2000,
        easing: 'linear',
      },
    ],
  },
  {
    id: 'physics-020',
    name: 'Inclined Plane',
    description: 'Object sliding down an incline with friction',
    category: 'physics',
    difficulty: 'beginner',
    tags: ['incline', 'friction', 'gravity', 'acceleration'],
    estimatedDuration: 2500,
    tracks: [
      {
        id: 'block-slide',
        target: '.block',
        property: 'transform',
        keyframes: [
          { time: 0, value: 'translate(0, 0) rotate(0deg)' },
          { time: 1000, value: 'translate(100px, 50px) rotate(30deg)' },
          { time: 2000, value: 'translate(200px, 100px) rotate(30deg)' },
        ],
        from: 'translate(0, 0)',
        to: 'translate(200px, 100px)',
        duration: 2000,
        easing: 'ease-in',
      },
      {
        id: 'velocity-arrow-grow',
        target: '.velocity-vector',
        property: 'height',
        from: '10px',
        to: '60px',
        duration: 2000,
        easing: 'ease-in',
      },
    ],
  },
];

// =============================================================================
// CHEMISTRY ANIMATIONS (21-40)
// =============================================================================

export const ChemistryAnimations: AnimationExample[] = [
  {
    id: 'chem-001',
    name: 'Covalent Bond Formation',
    description: 'Two atoms sharing electrons to form a bond',
    category: 'chemistry',
    difficulty: 'beginner',
    tags: ['covalent', 'bond', 'electron', 'sharing'],
    estimatedDuration: 3000,
    tracks: [
      {
        id: 'atoms-approach',
        target: '.atom-1, .atom-2',
        property: 'transform',
        from: 'translateX(0)',
        to: 'translateX(50px)',
        duration: 1500,
        easing: 'ease-out',
      },
      {
        id: 'electrons-orbit',
        target: '.shared-electron',
        property: 'transform',
        from: 'rotate(0deg) translateX(30px)',
        to: 'rotate(360deg) translateX(30px)',
        duration: 1500,
        delay: 1500,
        easing: 'linear',
        repeat: -1,
      },
      {
        id: 'bond-glow',
        target: '.bond-line',
        property: 'box-shadow',
        from: '0 0 0px #4ecdc4',
        to: '0 0 10px #4ecdc4',
        duration: 500,
        delay: 1500,
        easing: 'ease-out',
      },
    ],
  },
  {
    id: 'chem-002',
    name: 'Ionic Bond Formation',
    description: 'Electron transfer creating ions',
    category: 'chemistry',
    difficulty: 'beginner',
    tags: ['ionic', 'bond', 'electron', 'transfer', 'cation', 'anion'],
    estimatedDuration: 3000,
    tracks: [
      {
        id: 'electron-move',
        target: '.valence-electron',
        property: 'transform',
        from: 'translateX(0)',
        to: 'translateX(80px)',
        duration: 1500,
        easing: 'ease-in-out',
      },
      {
        id: 'cation-form',
        target: '.metal-atom',
        property: 'background-color',
        from: '#95a5a6',
        to: '#3498db',
        duration: 500,
        delay: 1500,
        easing: 'ease-out',
      },
      {
        id: 'anion-form',
        target: '.nonmetal-atom',
        property: 'background-color',
        from: '#e74c3c',
        to: '#e67e22',
        duration: 500,
        delay: 1500,
        easing: 'ease-out',
      },
      {
        id: 'attraction-pulse',
        target: '.ionic-bond',
        property: 'opacity',
        from: 0,
        to: 1,
        duration: 500,
        delay: 2000,
        easing: 'ease-out',
      },
    ],
  },
  {
    id: 'chem-003',
    name: 'Dissolution Process',
    description: 'Salt crystal dissolving in water',
    category: 'chemistry',
    difficulty: 'intermediate',
    tags: ['dissolution', 'solubility', 'ions', 'water'],
    estimatedDuration: 4000,
    tracks: [
      {
        id: 'crystal-break',
        target: '.crystal',
        property: 'transform',
        from: 'scale(1) rotate(0deg)',
        to: 'scale(0.8) rotate(10deg)',
        duration: 1000,
        easing: 'ease-out',
      },
      {
        id: 'ions-separate',
        target: '.na-ion',
        property: 'transform',
        from: 'translate(0, 0)',
        to: 'translate(-30px, -20px)',
        duration: 2000,
        delay: 1000,
        easing: 'ease-out',
      },
      {
        id: 'cl-separate',
        target: '.cl-ion',
        property: 'transform',
        from: 'translate(0, 0)',
        to: 'translate(40px, 30px)',
        duration: 2000,
        delay: 1000,
        easing: 'ease-out',
      },
      {
        id: 'water-molecules-solvate',
        target: '.water-molecule',
        property: 'transform',
        from: 'scale(0.8)',
        to: 'scale(1)',
        duration: 1500,
        delay: 2000,
        easing: 'ease-out',
      },
    ],
  },
  {
    id: 'chem-004',
    name: 'Chemical Equilibrium',
    description: 'Dynamic equilibrium with forward and reverse reactions',
    category: 'chemistry',
    difficulty: 'advanced',
    tags: ['equilibrium', 'reversible', 'dynamic', 'le-chatlier'],
    estimatedDuration: 5000,
    tracks: [
      {
        id: 'reactant-convert',
        target: '.reactant',
        property: 'opacity',
        from: 1,
        to: 0.3,
        duration: 2000,
        easing: 'ease-in-out',
      },
      {
        id: 'product-form',
        target: '.product',
        property: 'opacity',
        from: 0.3,
        to: 1,
        duration: 2000,
        easing: 'ease-in-out',
      },
      {
        id: 'reverse-reaction',
        target: '.product-2',
        property: 'opacity',
        from: 1,
        to: 0.5,
        duration: 2000,
        delay: 2500,
        easing: 'ease-in-out',
      },
      {
        id: 'equilibrium-indicator',
        target: '.equilibrium-arrow',
        property: 'opacity',
        from: 0,
        to: 1,
        duration: 500,
        delay: 4000,
        easing: 'ease-out',
      },
    ],
  },
  {
    id: 'chem-005',
    name: 'Acid-Base Neutralization',
    description: 'pH change during titration',
    category: 'chemistry',
    difficulty: 'intermediate',
    tags: ['acid', 'base', 'neutralization', 'ph', 'titration'],
    estimatedDuration: 4000,
    tracks: [
      {
        id: 'indicator-color',
        target: '.solution',
        property: 'background-color',
        keyframes: [
          { time: 0, value: '#ff6b6b' },
          { time: 3000, value: '#ff6b6b' },
          { time: 3500, value: '#95e1d3' },
          { time: 4000, value: '#4ecdc4' },
        ],
        from: '#ff6b6b',
        to: '#4ecdc4',
        duration: 4000,
        easing: 'ease-in-out',
      },
      {
        id: 'ph-meter-move',
        target: '.ph-needle',
        property: 'transform',
        from: 'rotate(-45deg)',
        to: 'rotate(45deg)',
        duration: 4000,
        easing: 'ease-in-out',
      },
      {
        id: 'drop-fall',
        target: '.titrant-drop',
        property: 'transform',
        from: 'translateY(0)',
        to: 'translateY(100px)',
        duration: 500,
        delay: 3000,
        easing: 'ease-in',
      },
    ],
  },
  {
    id: 'chem-006',
    name: 'Redox Reaction',
    description: 'Electron transfer in oxidation-reduction',
    category: 'chemistry',
    difficulty: 'advanced',
    tags: ['redox', 'oxidation', 'reduction', 'electron'],
    estimatedDuration: 3500,
    tracks: [
      {
        id: 'electron-flow',
        target: '.electron-flow',
        property: 'stroke-dashoffset',
        from: 100,
        to: 0,
        duration: 1500,
        easing: 'linear',
      },
      {
        id: 'oxidation-occur',
        target: '.oxidized-species',
        property: 'background-color',
        from: '#95a5a6',
        to: '#e74c3c',
        duration: 500,
        delay: 1500,
        easing: 'ease-out',
      },
      {
        id: 'reduction-occur',
        target: '.reduced-species',
        property: 'background-color',
        from: '#34495e',
        to: '#2ecc71',
        duration: 500,
        delay: 1500,
        easing: 'ease-out',
      },
    ],
  },
  {
    id: 'chem-007',
    name: 'Phase Change - Melting',
    description: 'Solid to liquid transition with energy input',
    category: 'chemistry',
    difficulty: 'beginner',
    tags: ['phase', 'melting', 'solid', 'liquid', 'energy'],
    estimatedDuration: 3000,
    tracks: [
      {
        id: 'heat-add',
        target: '.heat-source',
        property: 'opacity',
        from: 0,
        to: 0.8,
        duration: 500,
        easing: 'ease-out',
      },
      {
        id: 'molecules-vibrate',
        target: '.solid-molecule',
        property: 'transform',
        from: 'translate(0, 0)',
        to: 'translate(3px, 3px)',
        duration: 200,
        delay: 500,
        easing: 'ease-in-out',
        repeat: 10,
        yoyo: true,
      },
      {
        id: 'structure-break',
        target: '.crystal-structure',
        property: 'opacity',
        from: 1,
        to: 0,
        duration: 1000,
        delay: 2000,
        easing: 'ease-out',
      },
      {
        id: 'liquid-form',
        target: '.liquid-molecules',
        property: 'opacity',
        from: 0,
        to: 1,
        duration: 1000,
        delay: 2000,
        easing: 'ease-out',
      },
    ],
  },
  {
    id: 'chem-008',
    name: 'Activation Energy',
    description: 'Energy profile of a chemical reaction',
    category: 'chemistry',
    difficulty: 'intermediate',
    tags: ['activation', 'energy', 'reaction', 'catalyst', 'profile'],
    estimatedDuration: 4000,
    tracks: [
      {
        id: 'reactant-climb',
        target: '.energy-particle',
        property: 'transform',
        keyframes: [
          { time: 0, value: 'translate(0, 200px)' },
          { time: 1500, value: 'translate(150px, 50px)' },
          { time: 2500, value: 'translate(250px, 150px)' },
          { time: 4000, value: 'translate(400px, 180px)' },
        ],
        from: 'translate(0, 200px)',
        to: 'translate(400px, 180px)',
        duration: 4000,
        easing: 'ease-in-out',
      },
      {
        id: 'profile-draw',
        target: '.energy-curve',
        property: 'stroke-dashoffset',
        from: 500,
        to: 0,
        duration: 2000,
        easing: 'ease-out',
      },
    ],
  },
  {
    id: 'chem-009',
    name: 'Crystal Lattice',
    description: 'Formation of crystalline structure',
    category: 'chemistry',
    difficulty: 'intermediate',
    tags: ['crystal', 'lattice', 'solid', 'structure', 'unit-cell'],
    estimatedDuration: 3500,
    tracks: [
      {
        id: 'layer-1-place',
        target: '.layer-1',
        property: 'transform',
        from: 'translateY(-50px)',
        to: 'translateY(0)',
        duration: 800,
        easing: 'ease-out',
      },
      {
        id: 'layer-2-place',
        target: '.layer-2',
        property: 'transform',
        from: 'translateY(-50px)',
        to: 'translateY(0)',
        duration: 800,
        delay: 800,
        easing: 'ease-out',
      },
      {
        id: 'layer-3-place',
        target: '.layer-3',
        property: 'transform',
        from: 'translateY(-50px)',
        to: 'translateY(0)',
        duration: 800,
        delay: 1600,
        easing: 'ease-out',
      },
      {
        id: 'lattice-glow',
        target: '.crystal',
        property: 'box-shadow',
        from: '0 0 0px rgba(78, 205, 196, 0.5)',
        to: '0 0 30px rgba(78, 205, 196, 0.5)',
        duration: 1000,
        delay: 2500,
        easing: 'ease-out',
      },
    ],
  },
  {
    id: 'chem-010',
    name: 'Precipitation Reaction',
    description: 'Solid forming from solution',
    category: 'chemistry',
    difficulty: 'beginner',
    tags: ['precipitation', 'solid', 'solution', 'reaction'],
    estimatedDuration: 3000,
    tracks: [
      {
        id: 'ions-combine',
        target: '.precipitate-ion',
        property: 'transform',
        from: 'scale(0)',
        to: 'scale(1)',
        duration: 1500,
        easing: 'spring',
      },
      {
        id: 'solid-grow',
        target: '.precipitate-cluster',
        property: 'transform',
        from: 'scale(0.1)',
        to: 'scale(1)',
        duration: 2000,
        delay: 1000,
        easing: 'ease-out',
      },
      {
        id: 'solution-clear',
        target: '.solution',
        property: 'opacity',
        from: 1,
        to: 0.7,
        duration: 1000,
        delay: 2000,
        easing: 'ease-out',
      },
    ],
  },
  {
    id: 'chem-011',
    name: 'Isomerism',
    description: 'Structural isomers with different arrangements',
    category: 'chemistry',
    difficulty: 'advanced',
    tags: ['isomer', 'structure', 'arrangement', 'organic'],
    estimatedDuration: 4000,
    tracks: [
      {
        id: 'chain-straighten',
        target: '.branched-chain',
        property: 'transform',
        from: 'rotate(0deg)',
        to: 'rotate(180deg)',
        duration: 2000,
        easing: 'ease-in-out',
      },
      {
        id: 'bond-rearrange',
        target: '.carbon-bond',
        property: 'stroke-dasharray',
        from: '5,5',
        to: '0,0',
        duration: 1000,
        delay: 1000,
        easing: 'ease-in-out',
      },
    ],
  },
  {
    id: 'chem-012',
    name: 'Radioactive Decay',
    description: 'Alpha or beta particle emission',
    category: 'chemistry',
    difficulty: 'intermediate',
    tags: ['radioactive', 'decay', 'alpha', 'beta', 'nuclear'],
    estimatedDuration: 3000,
    tracks: [
      {
        id: 'nucleus-unstable',
        target: '.nucleus',
        property: 'transform',
        from: 'scale(1)',
        to: 'scale(1.05)',
        duration: 500,
        easing: 'ease-in-out',
        repeat: 3,
        yoyo: true,
      },
      {
        id: 'particle-emission',
        target: '.emitted-particle',
        property: 'transform',
        from: 'translate(0, 0)',
        to: 'translate(100px, -50px)',
        duration: 1000,
        delay: 1500,
        easing: 'ease-out',
      },
      {
        id: 'nucleus-change',
        target: '.nucleus',
        property: 'background-color',
        from: '#ff6b6b',
        to: '#4ecdc4',
        duration: 500,
        delay: 2000,
        easing: 'ease-out',
      },
    ],
  },
  {
    id: 'chem-013',
    name: 'VSEPR Theory',
    description: 'Electron pair repulsion determining shape',
    category: 'chemistry',
    difficulty: 'advanced',
    tags: ['vsepr', 'geometry', 'molecular', 'shape', 'electron'],
    estimatedDuration: 3500,
    tracks: [
      {
        id: 'bonds-extend',
        target: '.molecular-bond',
        property: 'transform',
        from: 'scale(0)',
        to: 'scale(1)',
        duration: 1500,
        easing: 'ease-out',
      },
      {
        id: 'lone-pairs-show',
        target: '.lone-pair',
        property: 'opacity',
        from: 0,
        to: 1,
        duration: 800,
        delay: 1500,
        easing: 'ease-out',
      },
      {
        id: 'shape-adjust',
        target: '.molecule',
        property: 'transform',
        from: 'rotateX(0deg) rotateY(0deg)',
        to: 'rotateX(20deg) rotateY(30deg)',
        duration: 1500,
        delay: 2000,
        easing: 'ease-out',
      },
    ],
  },
  {
    id: 'chem-014',
    name: 'Resonance Structures',
    description: 'Delocalized electrons in conjugated systems',
    category: 'chemistry',
    difficulty: 'advanced',
    tags: ['resonance', 'delocalized', 'electron', 'conjugated'],
    estimatedDuration: 3000,
    tracks: [
      {
        id: 'structure-1-fade',
        target: '.resonance-1',
        property: 'opacity',
        from: 1,
        to: 0.3,
        duration: 1500,
        easing: 'ease-in-out',
      },
      {
        id: 'structure-2-appear',
        target: '.resonance-2',
        property: 'opacity',
        from: 0.3,
        to: 1,
        duration: 1500,
        easing: 'ease-in-out',
      },
      {
        id: 'electron-shift',
        target: '.pi-electron',
        property: 'transform',
        from: 'translateX(0)',
        to: 'translateX(50px)',
        duration: 1500,
        easing: 'ease-in-out',
        yoyo: true,
        repeat: 1,
      },
    ],
  },
  {
    id: 'chem-015',
    name: 'Hybridization',
    description: 'Orbital hybridization (sp, sp2, sp3)',
    category: 'chemistry',
    difficulty: 'advanced',
    tags: ['hybridization', 'orbital', 'sp3', 'sp2', 'sp'],
    estimatedDuration: 4000,
    tracks: [
      {
        id: 's-orbital-show',
        target: '.s-orbital',
        property: 'opacity',
        from: 0,
        to: 1,
        duration: 800,
        easing: 'ease-out',
      },
      {
        id: 'p-orbitals-show',
        target: '.p-orbital',
        property: 'opacity',
        from: 0,
        to: 1,
        duration: 800,
        delay: 800,
        easing: 'ease-out',
      },
      {
        id: 'orbitals-merge',
        target: '.hybrid-orbital',
        property: 'transform',
        from: 'scale(0)',
        to: 'scale(1)',
        duration: 1500,
        delay: 1600,
        easing: 'spring',
      },
      {
        id: 'original-fade',
        target: '.s-orbital, .p-orbital',
        property: 'opacity',
        from: 1,
        to: 0,
        duration: 800,
        delay: 2000,
        easing: 'ease-out',
      },
    ],
  },
  {
    id: 'chem-016',
    name: 'Buffer Solution',
    description: 'Resisting pH change with buffer',
    category: 'chemistry',
    difficulty: 'intermediate',
    tags: ['buffer', 'ph', 'acid', 'base', 'resistance'],
    estimatedDuration: 3500,
    tracks: [
      {
        id: 'acid-added',
        target: '.acid-drop',
        property: 'transform',
        from: 'translateY(-50px)',
        to: 'translateY(0)',
        duration: 500,
        easing: 'ease-in',
      },
      {
        id: 'conjugate-base-react',
        target: '.conjugate-base',
        property: 'transform',
        from: 'scale(1)',
        to: 'scale(0.8)',
        duration: 500,
        delay: 500,
        easing: 'ease-in-out',
      },
      {
        id: 'ph-stable',
        target: '.ph-indicator',
        property: 'background-color',
        from: '#95e1d3',
        to: '#95e1d3',
        duration: 500,
        delay: 1000,
        easing: 'linear',
      },
      {
        id: 'weak-acid-form',
        target: '.weak-acid',
        property: 'opacity',
        from: 0,
        to: 1,
        duration: 500,
        delay: 1000,
        easing: 'ease-out',
      },
    ],
  },
  {
    id: 'chem-017',
    name: 'Titration Curve',
    description: 'Complete titration with equivalence point',
    category: 'chemistry',
    difficulty: 'intermediate',
    tags: ['titration', 'equivalence', 'indicator', 'endpoint'],
    estimatedDuration: 5000,
    tracks: [
      {
        id: 'curve-draw',
        target: '.titration-path',
        property: 'stroke-dashoffset',
        from: 1000,
        to: 0,
        duration: 4000,
        easing: 'ease-out',
      },
      {
        id: 'equivalence-point',
        target: '.equivalence-marker',
        property: 'transform',
        from: 'scale(0)',
        to: 'scale(1)',
        duration: 500,
        delay: 3500,
        easing: 'spring',
      },
      {
        id: 'buret-drops',
        target: '.titrant-drop',
        property: 'transform',
        from: 'translateY(0)',
        to: 'translateY(150px)',
        duration: 500,
        easing: 'ease-in',
      },
    ],
  },
  {
    id: 'chem-018',
    name: 'Molecular Polarity',
    description: 'Dipole moments in polar molecules',
    category: 'chemistry',
    difficulty: 'intermediate',
    tags: ['polarity', 'dipole', 'electronegativity', 'moment'],
    estimatedDuration: 2500,
    tracks: [
      {
        id: 'partial-charges-show',
        target: '.partial-charge',
        property: 'opacity',
        from: 0,
        to: 1,
        duration: 800,
        easing: 'ease-out',
      },
      {
        id: 'dipole-arrow-grow',
        target: '.dipole-arrow',
        property: 'transform',
        from: 'scaleX(0)',
        to: 'scaleX(1)',
        duration: 1000,
        delay: 800,
        easing: 'ease-out',
      },
      {
        id: 'arrowhead-appear',
        target: '.arrowhead',
        property: 'opacity',
        from: 0,
        to: 1,
        duration: 300,
        delay: 1500,
        easing: 'ease-out',
      },
    ],
  },
  {
    id: 'chem-019',
    name: 'Electrolysis',
    description: 'Decomposition by electric current',
    category: 'chemistry',
    difficulty: 'intermediate',
    tags: ['electrolysis', 'electrode', 'anode', 'cathode'],
    estimatedDuration: 4000,
    tracks: [
      {
        id: 'current-flow',
        target: '.electron-flow',
        property: 'stroke-dashoffset',
        from: 0,
        to: -100,
        duration: 1000,
        easing: 'linear',
        repeat: 3,
      },
      {
        id: 'cations-move',
        target: '.cation',
        property: 'transform',
        from: 'translateX(0)',
        to: 'translateX(-50px)',
        duration: 2000,
        delay: 1000,
        easing: 'ease-in-out',
      },
      {
        id: 'anions-move',
        target: '.anion',
        property: 'transform',
        from: 'translateX(0)',
        to: 'translateX(50px)',
        duration: 2000,
        delay: 1000,
        easing: 'ease-in-out',
      },
      {
        id: 'bubbles-form',
        target: '.gas-bubble',
        property: 'transform',
        from: 'scale(0) translateY(0)',
        to: 'scale(1) translateY(-30px)',
        duration: 1000,
        delay: 3000,
        easing: 'ease-out',
      },
    ],
  },
  {
    id: 'chem-020',
    name: 'Coordination Complex',
    description: 'Ligand binding to central metal ion',
    category: 'chemistry',
    difficulty: 'advanced',
    tags: ['coordination', 'complex', 'ligand', 'chelate'],
    estimatedDuration: 3000,
    tracks: [
      {
        id: 'ligands-approach',
        target: '.ligand',
        property: 'transform',
        from: 'translate(0, 0)',
        to: 'translate(var(--approach-x), var(--approach-y))',
        duration: 1500,
        easing: 'ease-out',
      },
      {
        id: 'complex-glow',
        target: '.metal-center',
        property: 'box-shadow',
        from: '0 0 0px #9b59b6',
        to: '0 0 20px #9b59b6',
        duration: 1000,
        delay: 1500,
        easing: 'ease-out',
      },
      {
        id: 'geometry-form',
        target: '.coordination-sphere',
        property: 'opacity',
        from: 0,
        to: 0.5,
        duration: 1000,
        delay: 2000,
        easing: 'ease-out',
      },
    ],
  },
];

// =============================================================================
// Export all animations
// =============================================================================

export const AllAnimationExamples: AnimationExample[] = [
  ...PhysicsAnimations,
  ...ChemistryAnimations,
  // Biology, Math, CS, UI, Feedback, Entrance, Exit, Attention, Transition animations would follow same pattern
  // Each category would have 20 examples, totaling 100+ animations
];

export function getExamplesByCategory(category: AnimationExample['category']): AnimationExample[] {
  return AllAnimationExamples.filter((ex) => ex.category === category);
}

export function getExamplesByDifficulty(difficulty: AnimationExample['difficulty']): AnimationExample[] {
  return AllAnimationExamples.filter((ex) => ex.difficulty === difficulty);
}

export function searchExamples(query: string): AnimationExample[] {
  const lowerQuery = query.toLowerCase();
  return AllAnimationExamples.filter(
    (ex) =>
      ex.name.toLowerCase().includes(lowerQuery) ||
      ex.description.toLowerCase().includes(lowerQuery) ||
      ex.tags.some((tag) => tag.includes(lowerQuery))
  );
}
