import {
  createDocumentId,
  deserializeDocument,
  serializeDocument,
  type BuilderDocument,
  type RoundTripFidelity,
  type SerializedDocument,
  type AIActionLineage,
  type AIHookKind,
  type AIReviewState,
  type NodeId,
  AIActionLineageTracker,
  createLineageEntry,
} from '@ghatana/ui-builder';
import { getContractMap } from './registry';
type DataClassification = NonNullable<BuilderDocument['metadata']['dataClassification']>;
type TrustLevel = NonNullable<BuilderDocument['metadata']['trustLevel']>;

// ---------------------------------------------------------------------------
// AI Change Record
// ---------------------------------------------------------------------------

/**
 * Product-layer record for an AI-originated change applied to a page artifact.
 * Wraps the platform `AIActionLineage` type and adds artifact-scoped context.
 *
 * @doc.type interface
 * @doc.purpose Product-scoped AI change record for page artifact governance
 * @doc.layer product
 */
export interface PageArtifactAIChangeRecord {
  /** The underlying platform lineage entry. */
  readonly lineage: AIActionLineage;
  /** The artifact this change was applied to. */
  readonly artifactId: string;
  /** The document version at the time the change was applied. */
  readonly documentId: string;
  /** Deterministic snapshot used to roll back reversible rejected changes. */
  readonly rollbackMetadata?: PageArtifactAIRollbackMetadata;
}

export interface PageArtifactAIRollbackMetadata {
  readonly strategy: 'restore-builder-document';
  readonly serializedBuilderDocument: SerializedDocument;
  readonly capturedAt: string;
  readonly reason: string;
}

export type PageArtifactOperationStatus =
  | 'pending'
  | 'succeeded'
  | 'failed'
  | 'requires-review';

export type PageArtifactOperationKind =
  | 'document-update'
  | 'persist-success'
  | 'persist-conflict'
  | 'persist-offline'
  | 'reload-remote'
  | 'overwrite-remote'
  | 'merge-conflict'
  | 'import-page'
  | 'governance-record'
  | 'undo-command'
  | 'redo-command'
  | 'recovery-draft-restored'
  | 'server-validation-failed';

export interface PageArtifactOperationRecord {
  readonly id: string;
  readonly artifactId: string;
  readonly documentId: string;
  readonly operation: PageArtifactOperationKind;
  readonly status: PageArtifactOperationStatus;
  readonly actor: string;
  readonly summary: string;
  readonly createdAt: string;
  readonly phase?: string;
  readonly metadata?: Record<string, string | number | boolean | null>;
}

export interface PageArtifactOperationLogExport {
  readonly schemaVersion: 1;
  readonly artifactId: string;
  readonly documentId: string;
  readonly exportedAt: string;
  readonly replayCursor: string | null;
  readonly summary: {
    readonly total: number;
    readonly byOperation: Readonly<Record<PageArtifactOperationKind, number>>;
    readonly byStatus: Readonly<Record<PageArtifactOperationStatus, number>>;
    readonly latestOperationAt: string | null;
  };
  readonly records: readonly PageArtifactOperationRecord[];
}

/**
 * Creates a new `AIChangeRecord` for a given artifact using the platform
 * `createLineageEntry` factory.
 */
export function createAIChangeRecord(
  artifactId: string,
  documentId: string,
  hookKind: AIHookKind,
  reason: string,
  confidence: number,
  affectedNodeIds: readonly string[],
  options?: {
    readonly reversible?: boolean;
    readonly reviewState?: AIReviewState;
    readonly correlationId?: string;
    readonly evidence?: readonly string[];
    readonly rollbackMetadata?: PageArtifactAIRollbackMetadata;
  },
): PageArtifactAIChangeRecord {
  const lineage = createLineageEntry(hookKind, reason, confidence, affectedNodeIds as readonly NodeId[], options);
  return {
    lineage,
    artifactId,
    documentId,
    ...(options?.rollbackMetadata ? { rollbackMetadata: options.rollbackMetadata } : {}),
  };
}

/** Re-export the platform tracker for use in product code. */
export { AIActionLineageTracker };
export type { AIActionLineage, AIHookKind, AIReviewState };

/**
 * Source of the page artifact document.
 * Distinguishes between server-authoritative documents and local recovery drafts.
 *
 * @doc.type type
 * @doc.purpose Document source tracking for server authority vs local recovery
 * @doc.layer product
 */
export type PageArtifactSource =
  | 'created-in-builder'    // Created directly in the builder
  | 'decompiled'            // Decompiled from existing code
  | 'imported'             // Imported from another source
  | 'generated'            // Generated by AI
  | 'server'               // Server-authoritative document
  | 'local-draft'          // Local draft (recovery-only, never becomes production truth)
  | 'recovered-draft';     // Recovered from local storage after server failure (explicit UX required)

export type PageArtifactSyncStatus =
  | 'dirty'
  | 'saving'
  | 'synced'
  | 'error'
  | 'offline';

export type PageArtifactGraphNodeKind =
  | 'product'
  | 'page'
  | 'component'
  | 'source'
  | 'residual';

export type PageArtifactGraphEdgeKind =
  | 'contains'
  | 'derived-from'
  | 'part-of'
  | 'references'
  | 'residual-of';

export interface PageArtifactGraphNode {
  readonly id: string;
  readonly kind: PageArtifactGraphNodeKind;
  readonly label: string;
  readonly sourceLocation?: {
    readonly filePath: string;
    readonly startLine: number;
    readonly startColumn: number;
    readonly endLine: number;
    readonly endColumn: number;
  };
  readonly metadata?: Record<string, string | number | boolean | null>;
}

export interface PageArtifactGraphEdge {
  readonly id: string;
  readonly from: string;
  readonly to: string;
  readonly kind: PageArtifactGraphEdgeKind;
}

export interface PageArtifactGraphSnapshot {
  readonly graphId: string;
  readonly projectId: string;
  readonly sourceType: string;
  readonly source: string;
  readonly importedAt: string;
  readonly nodes: readonly PageArtifactGraphNode[];
  readonly edges: readonly PageArtifactGraphEdge[];
  readonly provenance: {
    readonly createdBy: string;
    readonly compiler: 'yappc-artifact-compiler';
    readonly confidence: number;
    readonly residualIslandIds: readonly string[];
  };
}

export interface PageArtifactDocument {
  readonly artifactId: string;
  readonly documentId: string;
  readonly serializedBuilderDocument: SerializedDocument;
  readonly source: PageArtifactSource;
  readonly roundTripFidelity?: RoundTripFidelity;
  readonly residualIslandIds?: readonly string[];
  readonly artifactGraph?: PageArtifactGraphSnapshot;
  readonly syncStatus: PageArtifactSyncStatus;
  readonly trustLevel: TrustLevel;
  readonly dataClassification: DataClassification;
  readonly createdBy: string;
  readonly updatedBy: string;
  readonly createdAt: string;
  readonly updatedAt: string;
  readonly aiChangeRecords?: readonly PageArtifactAIChangeRecord[];
  readonly operationLog?: readonly PageArtifactOperationRecord[];
  readonly validationSummary?: {
    readonly valid: boolean;
    readonly errorCount: number;
    readonly warningCount: number;
  };
}

export function createEmptyBuilderDocument(name: string, author: string): BuilderDocument {
  const now = new Date().toISOString();
  const contractMap = getContractMap();
  const componentContracts = Array.from(contractMap.values());

  return {
    id: createDocumentId(),
    version: '1',
    name,
    designSystem: {
      id: 'ghatana-ds-v1',
      name: 'Ghatana Design System',
      version: '1.0.0',
      tokenSetIds: [],
      componentContracts,
      themeId: 'default',
    },
    rootNodes: [],
    nodes: new Map(),
    metadata: {
      createdAt: now,
      updatedAt: now,
      author,
      dataClassification: 'INTERNAL',
      trustLevel: 'GENERATED_TRUSTED',
    },
  };
}

export function createPageArtifactDocument(args: {
  artifactId: string;
  document?: BuilderDocument;
  name: string;
  createdBy: string;
  source?: PageArtifactSource;
}): PageArtifactDocument {
  const now = new Date().toISOString();
  const document = args.document ?? createEmptyBuilderDocument(args.name, args.createdBy);

  return {
    artifactId: args.artifactId,
    documentId: document.id,
    serializedBuilderDocument: serializeDocument(document),
    source: args.source ?? 'created-in-builder',
    syncStatus: 'dirty',
    trustLevel: document.metadata.trustLevel ?? 'GENERATED_TRUSTED',
    dataClassification: document.metadata.dataClassification ?? 'INTERNAL',
    createdBy: args.createdBy,
    updatedBy: args.createdBy,
    createdAt: now,
    updatedAt: now,
  };
}

export function getBuilderDocument(pageDocument: PageArtifactDocument | undefined): BuilderDocument | undefined {
  if (!pageDocument) {
    return undefined;
  }

  return deserializeDocument(pageDocument.serializedBuilderDocument);
}

export function updatePageArtifactDocument(
  pageDocument: PageArtifactDocument,
  document: BuilderDocument,
  updatedBy: string,
  syncStatus: PageArtifactSyncStatus,
  validationSummary?: PageArtifactDocument['validationSummary'],
): PageArtifactDocument {
  const now = new Date().toISOString();

  return {
    ...pageDocument,
    documentId: document.id,
    serializedBuilderDocument: serializeDocument(document),
    syncStatus,
    trustLevel: document.metadata.trustLevel ?? pageDocument.trustLevel,
    dataClassification:
      document.metadata.dataClassification ?? pageDocument.dataClassification,
    updatedBy,
    updatedAt: now,
    validationSummary,
  };
}

export function appendAIChangeRecord(
  pageDocument: PageArtifactDocument,
  record: PageArtifactAIChangeRecord,
): PageArtifactDocument {
  return {
    ...pageDocument,
    aiChangeRecords: [...(pageDocument.aiChangeRecords ?? []), record],
    updatedAt: new Date().toISOString(),
  };
}

export function updateAIChangeRecordReviewState(
  pageDocument: PageArtifactDocument,
  actionId: string,
  reviewState: AIReviewState,
): PageArtifactDocument {
  const records = pageDocument.aiChangeRecords ?? [];
  const updatedRecords = records.map((record) => {
    if (record.lineage.actionId !== actionId) {
      return record;
    }

    return {
      ...record,
      lineage: {
        ...record.lineage,
        reviewState,
      },
    };
  });

  return {
    ...pageDocument,
    aiChangeRecords: updatedRecords,
    updatedAt: new Date().toISOString(),
  };
}

export function appendPageArtifactOperationRecord(
  pageDocument: PageArtifactDocument,
  record: Omit<PageArtifactOperationRecord, 'id' | 'artifactId' | 'documentId' | 'createdAt'> & {
    readonly createdAt?: string;
  },
): PageArtifactDocument {
  const createdAt = record.createdAt ?? new Date().toISOString();
  const operationRecord: PageArtifactOperationRecord = {
    ...record,
    id: `${pageDocument.artifactId}:${record.operation}:${createdAt}`,
    artifactId: pageDocument.artifactId,
    documentId: pageDocument.documentId,
    createdAt,
  };

  return {
    ...pageDocument,
    operationLog: [...(pageDocument.operationLog ?? []), operationRecord].slice(-100),
  };
}

const EMPTY_OPERATION_COUNTS: Readonly<Record<PageArtifactOperationKind, number>> = {
  'document-update': 0,
  'persist-success': 0,
  'persist-conflict': 0,
  'persist-offline': 0,
  'reload-remote': 0,
  'overwrite-remote': 0,
  'merge-conflict': 0,
  'import-page': 0,
  'governance-record': 0,
  'undo-command': 0,
  'redo-command': 0,
  'recovery-draft-restored': 0,
  'server-validation-failed': 0,
};

const EMPTY_STATUS_COUNTS: Readonly<Record<PageArtifactOperationStatus, number>> = {
  pending: 0,
  succeeded: 0,
  failed: 0,
  'requires-review': 0,
};

export function createPageArtifactOperationLogExport(
  pageDocument: PageArtifactDocument,
  options?: {
    readonly exportedAt?: string;
  },
): PageArtifactOperationLogExport {
  const records = [...(pageDocument.operationLog ?? [])].sort((left, right) =>
    left.createdAt.i18n.languageCompare(right.createdAt)
  );
  const byOperation: Record<PageArtifactOperationKind, number> = { ...EMPTY_OPERATION_COUNTS };
  const byStatus: Record<PageArtifactOperationStatus, number> = { ...EMPTY_STATUS_COUNTS };

  records.forEach((record) => {
    byOperation[record.operation] += 1;
    byStatus[record.status] += 1;
  });

  const latestRecord = records.at(-1);

  return {
    schemaVersion: 1,
    artifactId: pageDocument.artifactId,
    documentId: pageDocument.documentId,
    exportedAt: options?.exportedAt ?? new Date().toISOString(),
    replayCursor: latestRecord?.id ?? null,
    summary: {
      total: records.length,
      byOperation,
      byStatus,
      latestOperationAt: latestRecord?.createdAt ?? null,
    },
    records,
  };
}

export function getSerializedNodeCount(
  pageDocument: PageArtifactDocument | undefined,
): number {
  if (!pageDocument) {
    return 0;
  }

  return Object.keys(pageDocument.serializedBuilderDocument.nodes).length;
}
