FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ["{{projectName}}.csproj", "./"]
RUN dotnet restore "{{projectName}}.csproj"

COPY . .
RUN dotnet build "{{projectName}}.csproj" -c Release -o /app/build
RUN dotnet publish "{{projectName}}.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .

EXPOSE 5000
ENV ASPNETCORE_URLS=http://+:5000

ENTRYPOINT ["dotnet", "{{projectName}}.dll"]
