// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/onboarding": {
    params: {};
  };
  "/workspaces": {
    params: {};
  };
  "/projects": {
    params: {};
  };
  "/p/:projectId": {
    params: {
      "projectId": string;
    };
  };
  "/p/:projectId/canvas": {
    params: {
      "projectId": string;
    };
  };
  "/p/:projectId/canvas-workspace": {
    params: {
      "projectId": string;
    };
  };
  "/p/:projectId/preview": {
    params: {
      "projectId": string;
    };
  };
  "/p/:projectId/deploy": {
    params: {
      "projectId": string;
    };
  };
  "/p/:projectId/settings": {
    params: {
      "projectId": string;
    };
  };
  "/p/:projectId/lifecycle": {
    params: {
      "projectId": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/onboarding" | "/workspaces" | "/projects" | "/p/:projectId" | "/p/:projectId/canvas" | "/p/:projectId/canvas-workspace" | "/p/:projectId/preview" | "/p/:projectId/deploy" | "/p/:projectId/settings" | "/p/:projectId/lifecycle";
  };
  "routes/_root.tsx": {
    id: "routes/_root";
    page: "/" | "/login" | "/onboarding" | "/workspaces" | "/projects" | "/p/:projectId" | "/p/:projectId/canvas" | "/p/:projectId/canvas-workspace" | "/p/:projectId/preview" | "/p/:projectId/deploy" | "/p/:projectId/settings" | "/p/:projectId/lifecycle";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/onboarding.tsx": {
    id: "routes/onboarding";
    page: "/onboarding";
  };
  "routes/_shell.tsx": {
    id: "routes/_shell";
    page: "/workspaces" | "/projects" | "/p/:projectId" | "/p/:projectId/canvas" | "/p/:projectId/canvas-workspace" | "/p/:projectId/preview" | "/p/:projectId/deploy" | "/p/:projectId/settings" | "/p/:projectId/lifecycle";
  };
  "routes/app/workspaces.tsx": {
    id: "routes/app/workspaces";
    page: "/workspaces";
  };
  "routes/app/projects.tsx": {
    id: "routes/app/projects";
    page: "/projects";
  };
  "routes/app/project/_shell.tsx": {
    id: "routes/app/project/_shell";
    page: "/p/:projectId" | "/p/:projectId/canvas" | "/p/:projectId/canvas-workspace" | "/p/:projectId/preview" | "/p/:projectId/deploy" | "/p/:projectId/settings" | "/p/:projectId/lifecycle";
  };
  "routes/app/project/index.tsx": {
    id: "routes/app/project/index";
    page: "/p/:projectId";
  };
  "routes/app/project/canvas.tsx": {
    id: "routes/app/project/canvas";
    page: "/p/:projectId/canvas";
  };
  "routes/app/project/canvas-workspace.tsx": {
    id: "routes/app/project/canvas-workspace";
    page: "/p/:projectId/canvas-workspace";
  };
  "routes/app/project/preview.tsx": {
    id: "routes/app/project/preview";
    page: "/p/:projectId/preview";
  };
  "routes/app/project/deploy.tsx": {
    id: "routes/app/project/deploy";
    page: "/p/:projectId/deploy";
  };
  "routes/app/project/settings.tsx": {
    id: "routes/app/project/settings";
    page: "/p/:projectId/settings";
  };
  "routes/app/project/lifecycle.tsx": {
    id: "routes/app/project/lifecycle";
    page: "/p/:projectId/lifecycle";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/_root": typeof import("./src/routes/_root.tsx");
  "routes/dashboard": typeof import("./src/routes/dashboard.tsx");
  "routes/login": typeof import("./src/routes/login.tsx");
  "routes/onboarding": typeof import("./src/routes/onboarding.tsx");
  "routes/_shell": typeof import("./src/routes/_shell.tsx");
  "routes/app/workspaces": typeof import("./src/routes/app/workspaces.tsx");
  "routes/app/projects": typeof import("./src/routes/app/projects.tsx");
  "routes/app/project/_shell": typeof import("./src/routes/app/project/_shell.tsx");
  "routes/app/project/index": typeof import("./src/routes/app/project/index.tsx");
  "routes/app/project/canvas": typeof import("./src/routes/app/project/canvas.tsx");
  "routes/app/project/canvas-workspace": typeof import("./src/routes/app/project/canvas-workspace.tsx");
  "routes/app/project/preview": typeof import("./src/routes/app/project/preview.tsx");
  "routes/app/project/deploy": typeof import("./src/routes/app/project/deploy.tsx");
  "routes/app/project/settings": typeof import("./src/routes/app/project/settings.tsx");
  "routes/app/project/lifecycle": typeof import("./src/routes/app/project/lifecycle.tsx");
};