package com.ghatana.yappc.packs;

import com.ghatana.yappc.core.io.ScaffoldFile;
import com.ghatana.yappc.core.model.WorkspaceSpec;
import java.nio.file.Path;
import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

/**
 * Generate scaffold assets for an Nx + PNPM workspace layout.
 *
 * @doc.type class
 * @doc.purpose Generate scaffold assets for an Nx + PNPM workspace layout
 * @doc.layer platform
 * @doc.pattern Template
 */
final class NxPnpmMonorepoPack implements PackTemplate {
    static final String ID = "nx-pnpm-monorepo";

    @Override
    public String id() {
        return ID;
    }

    @Override
    public List<ScaffoldFile> render(WorkspaceSpec spec) {
        String name = spec.getName();
        return List.of(
                new ScaffoldFile(Path.of("nx.json"), nxJson(name)),
                new ScaffoldFile(Path.of("workspace.json"), workspaceJson(name)),
                new ScaffoldFile(Path.of("package.json"), packageJson(name)),
                new ScaffoldFile(Path.of("pnpm-workspace.yaml"), pnpmWorkspace()),
                new ScaffoldFile(Path.of("apps/.gitkeep"), ""),
                new ScaffoldFile(Path.of("libs/.gitkeep"), ""),
                new ScaffoldFile(Path.of(".gitignore"), gitignore()),
                new ScaffoldFile(Path.of("README.md"), readme(name)));
    }

    private String nxJson(String name) {
        return "{\n"
                + "  \"npmScope\": \""
                + name.replace("-", "")
                + "\",\n"
                + "  \"targetDefaults\": {\n"
                + "    \"build\": { \"dependsOn\": [\"^build\"] },\n"
                + "    \"test\": { \"dependsOn\": [\"^test\"] }\n"
                + "  }\n"
                + "}\n";
    }

    private String workspaceJson(String name) {
        return "{\n"
                + "  \"name\": \""
                + name
                + "\",\n"
                + "  \"version\": 1,\n"
                + "  \"scaffoldedAt\": \""
                + DateTimeFormatter.ISO_OFFSET_DATE_TIME.format(OffsetDateTime.now())
                + "\"\n"
                + "}\n";
    }

    private String packageJson(String name) {
        return "{\n"
                + "  \"name\": \""
                + name
                + "\",\n"
                + "  \"private\": true,\n"
                + "  \"devDependencies\": {\n"
                + "    \"nx\": \"^19.0.0\",\n"
                + "    \"@nrwl/js\": \"^19.0.0\"\n"
                + "  }\n"
                + "}\n";
    }

    private String pnpmWorkspace() {
        return "packages:\n  - apps/*\n  - libs/*\n";
    }

    private String gitignore() {
        return String.join(
                "\n", "node_modules", "dist", ".nx", ".idea", "out", "build", ".yappc/cache", "");
    }

    private String readme(String name) {
        return "# " + name + "\n\nGenerated by yappc scaffold.\n";
    }
}
