package com.ghatana.yappc.packs;

import com.ghatana.yappc.core.io.ScaffoldFile;
import com.ghatana.yappc.core.model.WorkspaceSpec;
import java.nio.file.Path;
import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

/**
 * Generate scaffold assets for an Nx + PNPM workspace layout.
 *
 * @doc.type class
 * @doc.purpose Generate scaffold assets for an Nx + PNPM workspace layout
 * @doc.layer platform
 * @doc.pattern Template
 */
final class NxPnpmMonorepoPack implements PackTemplate {
    static final String ID = "nx-pnpm-monorepo";

    @Override
    public String id() { // GH-90000
        return ID;
    }

    @Override
    public List<ScaffoldFile> render(WorkspaceSpec spec) { // GH-90000
        String name = spec.getName(); // GH-90000
        return List.of( // GH-90000
                new ScaffoldFile(Path.of("nx.json [GH-90000]"), nxJson(name)),
                new ScaffoldFile(Path.of("workspace.json [GH-90000]"), workspaceJson(name)),
                new ScaffoldFile(Path.of("package.json [GH-90000]"), packageJson(name)),
                new ScaffoldFile(Path.of("pnpm-workspace.yaml [GH-90000]"), pnpmWorkspace()),
                new ScaffoldFile(Path.of("apps/.gitkeep [GH-90000]"), ""),
                new ScaffoldFile(Path.of("libs/.gitkeep [GH-90000]"), ""),
                new ScaffoldFile(Path.of(".gitignore [GH-90000]"), gitignore()),
                new ScaffoldFile(Path.of("README.md [GH-90000]"), readme(name)));
    }

    private String nxJson(String name) { // GH-90000
        return "{\n"
                + "  \"npmScope\": \""
                + name.replace("-", "") // GH-90000
                + "\",\n"
                + "  \"targetDefaults\": {\n"
                + "    \"build\": { \"dependsOn\": [\"^build\"] },\n"
                + "    \"test\": { \"dependsOn\": [\"^test\"] }\n"
                + "  }\n"
                + "}\n";
    }

    private String workspaceJson(String name) { // GH-90000
        return "{\n"
                + "  \"name\": \""
                + name
                + "\",\n"
                + "  \"version\": 1,\n"
                + "  \"scaffoldedAt\": \""
                + DateTimeFormatter.ISO_OFFSET_DATE_TIME.format(OffsetDateTime.now()) // GH-90000
                + "\"\n"
                + "}\n";
    }

    private String packageJson(String name) { // GH-90000
        return "{\n"
                + "  \"name\": \""
                + name
                + "\",\n"
                + "  \"private\": true,\n"
                + "  \"devDependencies\": {\n"
                + "    \"nx\": \"^19.0.0\",\n"
                + "    \"@nrwl/js\": \"^19.0.0\"\n"
                + "  }\n"
                + "}\n";
    }

    private String pnpmWorkspace() { // GH-90000
        return "packages:\n  - apps/*\n  - libs/*\n";
    }

    private String gitignore() { // GH-90000
        return String.join( // GH-90000
                "\n", "node_modules", "dist", ".nx", ".idea", "out", "build", ".yappc/cache", "");
    }

    private String readme(String name) { // GH-90000
        return "# " + name + "\n\nGenerated by yappc scaffold.\n";
    }
}
