/*
 * Copyright (c) 2025 Ghatana Platform Contributors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.ghatana.yappc.core.orchestration;

import com.ghatana.yappc.core.model.ProjectSpec;
import com.ghatana.yappc.core.multirepo.MultiRepoWorkspaceSpec;
import com.ghatana.yappc.core.multirepo.MultiRepoWorkspaceSpec.MultiRepoServiceSpec;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Generates unified Makefile for polyglot workspaces that delegates to language-specific
 * build systems (Gradle, Cargo, Go, pnpm, etc.).
 *
 * <p>Provides a consistent interface across all services:
 * <ul>
 *   <li>{@code make build} - Build all services</li>
 *   <li>{@code make test} - Test all services</li>
 *   <li>{@code make lint} - Lint all services</li>
 *   <li>{@code make docker} - Build Docker images</li>
 *   <li>{@code make clean} - Clean all build artifacts</li>
 *   <li>{@code make <service>-<target>} - Per-service targets</li>
 * </ul>
 *
 * @doc.type class
 * @doc.purpose Generate unified Makefile for multi-language workspaces
 * @doc.layer platform
 * @doc.pattern Generator
 */
public class PolyglotBuildOrchestrator {

    private static final String MAKEFILE_HEADER = """
            # =============================================================================
            # Polyglot Workspace Makefile
            # Generated by YAPPC - Yet Another Project/Package Creator
            # =============================================================================
            
            .PHONY: all build test lint format clean docker help
            .DEFAULT_GOAL := help
            
            # Colors for output
            CYAN := \\033[36m
            GREEN := \\033[32m
            YELLOW := \\033[33m
            RED := \\033[31m
            RESET := \\033[0m
            
            """;

    private static final Map<String, BuildSystemCommands> BUILD_SYSTEM_COMMANDS = Map.of(
            "gradle", new BuildSystemCommands(
                    "./gradlew build",
                    "./gradlew test",
                    "./gradlew spotlessCheck",
                    "./gradlew spotlessApply",
                    "./gradlew clean",
                    "./gradlew docker"
            ),
            "gradle-kts", new BuildSystemCommands(
                    "./gradlew build",
                    "./gradlew test",
                    "./gradlew spotlessCheck",
                    "./gradlew spotlessApply",
                    "./gradlew clean",
                    "./gradlew docker"
            ),
            "cargo", new BuildSystemCommands(
                    "cargo build --release",
                    "cargo test",
                    "cargo clippy -- -D warnings",
                    "cargo fmt",
                    "cargo clean",
                    "docker build -t $(SERVICE_NAME) ."
            ),
            "go", new BuildSystemCommands(
                    "go build -o bin/$(SERVICE_NAME) ./cmd/...",
                    "go test ./...",
                    "golangci-lint run",
                    "go fmt ./...",
                    "rm -rf bin/",
                    "docker build -t $(SERVICE_NAME) ."
            ),
            "pnpm", new BuildSystemCommands(
                    "pnpm build",
                    "pnpm test",
                    "pnpm lint",
                    "pnpm format",
                    "pnpm clean",
                    "docker build -t $(SERVICE_NAME) ."
            ),
            "npm", new BuildSystemCommands(
                    "npm run build",
                    "npm test",
                    "npm run lint",
                    "npm run format",
                    "npm run clean",
                    "docker build -t $(SERVICE_NAME) ."
            ),
            "maven", new BuildSystemCommands(
                    "mvn package -DskipTests",
                    "mvn test",
                    "mvn checkstyle:check",
                    "mvn spotless:apply",
                    "mvn clean",
                    "mvn spring-boot:build-image"
            ),
            "make", new BuildSystemCommands(
                    "make build",
                    "make test",
                    "make lint",
                    "make format",
                    "make clean",
                    "make docker"
            )
    );

    /**
     * Generate a unified Makefile for a multi-repo workspace.
     *
     * @param spec The workspace specification
     * @return Generated Makefile content
     */
    public String generateWorkspaceMakefile(MultiRepoWorkspaceSpec spec) {
        StringBuilder makefile = new StringBuilder();
        makefile.append(MAKEFILE_HEADER);

        // Generate workspace variables
        generateWorkspaceVariables(makefile, spec);

        // Generate service list
        List<String> serviceNames = generateServiceList(makefile, spec);

        // Generate aggregate targets
        generateAggregateTargets(makefile, serviceNames);

        // Generate per-service targets
        for (MultiRepoServiceSpec service : spec.services()) {
            generateServiceTargets(makefile, service);
        }

        // Generate help target
        generateHelpTarget(makefile, spec);

        return makefile.toString();
    }

    /**
     * Generate a unified Makefile from a list of ProjectSpecs.
     *
     * @param workspaceName The workspace name
     * @param projects List of project specifications
     * @return Generated Makefile content
     */
    public String generateProjectsMakefile(String workspaceName, List<ProjectSpec> projects) {
        StringBuilder makefile = new StringBuilder();
        makefile.append(MAKEFILE_HEADER);

        // Workspace name
        makefile.append("WORKSPACE_NAME := ").append(workspaceName).append("\n\n");

        // Generate service variables
        List<String> serviceNames = new ArrayList<>();
        for (ProjectSpec project : projects) {
            String name = project.getName();
            serviceNames.add(name);
            makefile.append(toMakeVar(name)).append("_DIR := ").append(name).append("\n");
        }
        makefile.append("\n");

        // Services list
        makefile.append("SERVICES := ").append(String.join(" ", serviceNames)).append("\n\n");

        // Aggregate targets
        generateAggregateTargets(makefile, serviceNames);

        // Per-project targets
        for (ProjectSpec project : projects) {
            generateProjectTargets(makefile, project);
        }

        // Help target
        generateSimpleHelpTarget(makefile, serviceNames);

        return makefile.toString();
    }

    private void generateWorkspaceVariables(StringBuilder makefile, MultiRepoWorkspaceSpec spec) {
        makefile.append("# Workspace Configuration\n");
        makefile.append("WORKSPACE_NAME := ").append(spec.workspaceName()).append("\n");
        makefile.append("VERSION := ").append(spec.version()).append("\n\n");

        // Service directories
        makefile.append("# Service Directories\n");
        for (MultiRepoServiceSpec service : spec.services()) {
            String varName = toMakeVar(service.serviceName()) + "_DIR";
            makefile.append(varName).append(" := ").append(service.serviceName()).append("\n");
        }
        makefile.append("\n");
    }

    private List<String> generateServiceList(StringBuilder makefile, MultiRepoWorkspaceSpec spec) {
        List<String> names = new ArrayList<>();
        for (MultiRepoServiceSpec service : spec.services()) {
            names.add(service.serviceName());
        }

        makefile.append("# All Services\n");
        makefile.append("SERVICES := ").append(String.join(" ", names)).append("\n\n");

        return names;
    }

    private void generateAggregateTargets(StringBuilder makefile, List<String> serviceNames) {
        makefile.append("# =============================================================================\n");
        makefile.append("# Aggregate Targets\n");
        makefile.append("# =============================================================================\n\n");

        // Build all
        makefile.append("## Build all services\n");
        makefile.append("build:");
        for (String name : serviceNames) {
            makefile.append(" ").append(name).append("-build");
        }
        makefile.append("\n\n");

        // Test all
        makefile.append("## Test all services\n");
        makefile.append("test:");
        for (String name : serviceNames) {
            makefile.append(" ").append(name).append("-test");
        }
        makefile.append("\n\n");

        // Lint all
        makefile.append("## Lint all services\n");
        makefile.append("lint:");
        for (String name : serviceNames) {
            makefile.append(" ").append(name).append("-lint");
        }
        makefile.append("\n\n");

        // Format all
        makefile.append("## Format all services\n");
        makefile.append("format:");
        for (String name : serviceNames) {
            makefile.append(" ").append(name).append("-format");
        }
        makefile.append("\n\n");

        // Clean all
        makefile.append("## Clean all services\n");
        makefile.append("clean:");
        for (String name : serviceNames) {
            makefile.append(" ").append(name).append("-clean");
        }
        makefile.append("\n\n");

        // Docker all
        makefile.append("## Build Docker images for all services\n");
        makefile.append("docker:");
        for (String name : serviceNames) {
            makefile.append(" ").append(name).append("-docker");
        }
        makefile.append("\n\n");
    }

    private void generateServiceTargets(StringBuilder makefile, MultiRepoServiceSpec service) {
        String name = service.serviceName();
        String buildSystem = service.buildSystem().toLowerCase();
        String dirVar = "$(" + toMakeVar(name) + "_DIR)";

        BuildSystemCommands commands = BUILD_SYSTEM_COMMANDS.getOrDefault(
                buildSystem, BUILD_SYSTEM_COMMANDS.get("make"));

        makefile.append("# =============================================================================\n");
        makefile.append("# ").append(name).append(" (").append(service.language())
                .append(" / ").append(buildSystem).append(")\n");
        makefile.append("# =============================================================================\n\n");

        makefile.append(".PHONY: ").append(name).append("-build ").append(name).append("-test ")
                .append(name).append("-lint ").append(name).append("-format ")
                .append(name).append("-clean ").append(name).append("-docker\n\n");

        // Build
        makefile.append(name).append("-build:\n");
        makefile.append("\t@echo \"$(CYAN)Building ").append(name).append("...$(RESET)\"\n");
        makefile.append("\t@cd ").append(dirVar).append(" && ").append(commands.build()).append("\n\n");

        // Test
        makefile.append(name).append("-test:\n");
        makefile.append("\t@echo \"$(CYAN)Testing ").append(name).append("...$(RESET)\"\n");
        makefile.append("\t@cd ").append(dirVar).append(" && ").append(commands.test()).append("\n\n");

        // Lint
        makefile.append(name).append("-lint:\n");
        makefile.append("\t@echo \"$(CYAN)Linting ").append(name).append("...$(RESET)\"\n");
        makefile.append("\t@cd ").append(dirVar).append(" && ").append(commands.lint()).append("\n\n");

        // Format
        makefile.append(name).append("-format:\n");
        makefile.append("\t@echo \"$(CYAN)Formatting ").append(name).append("...$(RESET)\"\n");
        makefile.append("\t@cd ").append(dirVar).append(" && ").append(commands.format()).append("\n\n");

        // Clean
        makefile.append(name).append("-clean:\n");
        makefile.append("\t@echo \"$(YELLOW)Cleaning ").append(name).append("...$(RESET)\"\n");
        makefile.append("\t@cd ").append(dirVar).append(" && ").append(commands.clean()).append("\n\n");

        // Docker
        makefile.append(name).append("-docker:\n");
        makefile.append("\t@echo \"$(CYAN)Building Docker image for ").append(name).append("...$(RESET)\"\n");
        makefile.append("\t@cd ").append(dirVar).append(" && SERVICE_NAME=").append(name)
                .append(" ").append(commands.docker()).append("\n\n");
    }

    private void generateProjectTargets(StringBuilder makefile, ProjectSpec project) {
        String name = project.getName();
        String buildSystem = project.getBuildSystem() != null
                ? project.getBuildSystem().toLowerCase()
                : detectBuildSystem(project.getLanguage());
        String dirVar = "$(" + toMakeVar(name) + "_DIR)";

        BuildSystemCommands commands = BUILD_SYSTEM_COMMANDS.getOrDefault(
                buildSystem, BUILD_SYSTEM_COMMANDS.get("make"));

        makefile.append("# ").append(name).append(" (").append(project.getLanguage())
                .append(" / ").append(buildSystem).append(")\n");

        makefile.append(".PHONY: ").append(name).append("-build ").append(name).append("-test ")
                .append(name).append("-lint ").append(name).append("-clean\n");

        makefile.append(name).append("-build:\n");
        makefile.append("\t@cd ").append(dirVar).append(" && ").append(commands.build()).append("\n\n");

        makefile.append(name).append("-test:\n");
        makefile.append("\t@cd ").append(dirVar).append(" && ").append(commands.test()).append("\n\n");

        makefile.append(name).append("-lint:\n");
        makefile.append("\t@cd ").append(dirVar).append(" && ").append(commands.lint()).append("\n\n");

        makefile.append(name).append("-format:\n");
        makefile.append("\t@cd ").append(dirVar).append(" && ").append(commands.format()).append("\n\n");

        makefile.append(name).append("-clean:\n");
        makefile.append("\t@cd ").append(dirVar).append(" && ").append(commands.clean()).append("\n\n");

        makefile.append(name).append("-docker:\n");
        makefile.append("\t@cd ").append(dirVar).append(" && SERVICE_NAME=").append(name)
                .append(" ").append(commands.docker()).append("\n\n");
    }

    private void generateHelpTarget(StringBuilder makefile, MultiRepoWorkspaceSpec spec) {
        makefile.append("# =============================================================================\n");
        makefile.append("# Help\n");
        makefile.append("# =============================================================================\n\n");

        makefile.append("## Show this help\n");
        makefile.append("help:\n");
        makefile.append("\t@echo \"$(GREEN)").append(spec.workspaceName())
                .append(" - Polyglot Workspace$(RESET)\"\n");
        makefile.append("\t@echo \"\"\n");
        makefile.append("\t@echo \"$(CYAN)Aggregate Targets:$(RESET)\"\n");
        makefile.append("\t@echo \"  make build    - Build all services\"\n");
        makefile.append("\t@echo \"  make test     - Test all services\"\n");
        makefile.append("\t@echo \"  make lint     - Lint all services\"\n");
        makefile.append("\t@echo \"  make format   - Format all services\"\n");
        makefile.append("\t@echo \"  make clean    - Clean all services\"\n");
        makefile.append("\t@echo \"  make docker   - Build Docker images\"\n");
        makefile.append("\t@echo \"\"\n");
        makefile.append("\t@echo \"$(CYAN)Per-Service Targets:$(RESET)\"\n");

        for (MultiRepoServiceSpec service : spec.services()) {
            String name = service.serviceName();
            makefile.append("\t@echo \"  make ").append(name)
                    .append("-{build,test,lint,format,clean,docker}\"\n");
        }
        makefile.append("\n");
    }

    private void generateSimpleHelpTarget(StringBuilder makefile, List<String> serviceNames) {
        makefile.append("## Show this help\n");
        makefile.append("help:\n");
        makefile.append("\t@echo \"Polyglot Workspace Makefile\"\n");
        makefile.append("\t@echo \"\"\n");
        makefile.append("\t@echo \"Targets: build, test, lint, format, clean, docker\"\n");
        makefile.append("\t@echo \"Services: ").append(String.join(", ", serviceNames)).append("\"\n");
        makefile.append("\t@echo \"\"\n");
        makefile.append("\t@echo \"Per-service: <service>-<target>\"\n");
        makefile.append("\n");
    }

    private String toMakeVar(String name) {
        return name.toUpperCase().replace("-", "_");
    }

    private String detectBuildSystem(String language) {
        if (language == null) {
            return "make";
        }
        return switch (language.toLowerCase()) {
            case "java", "kotlin" -> "gradle";
            case "rust" -> "cargo";
            case "go", "golang" -> "go";
            case "typescript", "javascript" -> "pnpm";
            case "c", "cpp", "c++" -> "make";
            default -> "make";
        };
    }

    /**
     * Commands for a specific build system.
     */
    private record BuildSystemCommands(
            String build,
            String test,
            String lint,
            String format,
            String clean,
            String docker) {
    }
}
