import type { PhaseConfig, MountedPhase } from './types';

const PHASE_CONFIG: Record<MountedPhase, PhaseConfig> = {
  intent: {
    name: 'Intent',
    description: 'Clarify the goal, the problem to solve, and the evidence that supports why this work matters.',
    primaryTitle: 'Define Requirements',
    primaryDescription: 'Capture the user outcome and problem framing so later phases inherit a clear intent.',
    primaryLabel: 'Define Requirements',
    primaryTestId: 'define-requirements',
    secondaryLabel: 'Review Evidence',
    secondaryTestId: 'review-evidence',
    icon: '🎯',
    supportingTitle: 'Project overview',
    actionFeedback: 'Project details below are ready for goal and evidence review.',
  },
  shape: {
    name: 'Shape',
    description: 'Turn intent into structure by shaping the UI, information flow, and component composition.',
    primaryTitle: 'Add Components',
    primaryDescription: 'Open the builder surface below and shape the page structure with real components.',
    primaryLabel: 'Add Components',
    primaryTestId: 'add-components',
    secondaryLabel: 'Review Requirements',
    secondaryTestId: 'review-requirements',
    icon: '🎨',
    supportingTitle: 'Canvas and page builder',
    actionFeedback: 'Builder details below are ready for component and layout work.',
  },
  validate: {
    name: 'Validate',
    description: 'Review whether the shaped solution is consistent, ready, and safe to approve for generation.',
    primaryTitle: 'Approve Changes',
    primaryDescription: 'Use the gate and blocker evidence below to decide whether this packet is ready to move forward.',
    primaryLabel: 'Approve Changes',
    primaryTestId: 'approve-changes',
    secondaryLabel: 'Request Changes',
    secondaryTestId: 'request-changes',
    icon: '✓',
    supportingTitle: 'Validation and lifecycle review',
    actionFeedback: 'Validation details below reflect the latest gate summary for this phase.',
  },
  generate: {
    name: 'Generate',
    description: 'Prepare the implementation handoff from approved design into generated output and reviewable diffs.',
    primaryTitle: 'Generate Code',
    primaryDescription: 'Review the supporting builder context below before kicking off implementation work.',
    primaryLabel: 'Generate Code',
    primaryTestId: 'generate-code',
    secondaryLabel: 'Preview Codegen Plan',
    secondaryTestId: 'view-codegen-preview',
    icon: '⚙️',
    supportingTitle: 'Implementation context',
    actionFeedback: 'Implementation details below are ready for code generation review.',
  },
  run: {
    name: 'Run',
    description: 'Check readiness and execute the safest available run or deployment path for this project.',
    primaryTitle: 'Check Readiness',
    primaryDescription: 'Review the deployment posture and capability gates before attempting any release action.',
    primaryLabel: 'Check Readiness',
    primaryTestId: 'check-readiness',
    secondaryLabel: 'View Run Plan',
    secondaryTestId: 'view-run-plan',
    icon: '🚀',
    supportingTitle: 'Deployment and run plan',
    actionFeedback: 'Run readiness and deployment planning are available below.',
  },
  observe: {
    name: 'Observe',
    description: 'Watch preview health, activity, and operator signals to understand how the current build behaves.',
    primaryTitle: 'View Metrics',
    primaryDescription: 'Use the preview and observability evidence below to decide what needs attention first.',
    primaryLabel: 'View Metrics',
    primaryTestId: 'view-metrics',
    secondaryLabel: 'View Project Preview',
    secondaryTestId: 'view-project-preview',
    icon: '👁️',
    supportingTitle: 'Preview and observation',
    actionFeedback: 'Preview and operational signals are ready for review below.',
  },
  learn: {
    name: 'Learn',
    description: 'Capture what worked, what failed, and which reusable patterns should inform the next cycle.',
    primaryTitle: 'Capture Learnings',
    primaryDescription: 'Review the latest evidence below and record the most useful lessons from this iteration.',
    primaryLabel: 'Capture Learnings',
    primaryTestId: 'capture-learnings',
    secondaryLabel: 'View Retrospective',
    secondaryTestId: 'view-retrospective',
    icon: '💡',
    supportingTitle: 'Retrospective and insights',
    actionFeedback: 'Retrospective details below are ready for learnings capture.',
  },
  evolve: {
    name: 'Evolve',
    description: 'Convert validated learnings into the next cycle plan, roadmap changes, and backlog priorities.',
    primaryTitle: 'Plan Next Cycle',
    primaryDescription: 'Use the backed evidence below to decide what the next improvement cycle should prioritize.',
    primaryLabel: 'Plan Next Cycle',
    primaryTestId: 'plan-next-cycle',
    secondaryLabel: 'Review Backlog',
    secondaryTestId: 'view-roadmap',
    icon: '🔄',
    supportingTitle: 'Roadmap and backlog',
    actionFeedback: 'Roadmap and backlog details are ready for next-cycle planning.',
  },
};

export function getPhaseCockpitConfig(phase: MountedPhase): PhaseConfig {
  return PHASE_CONFIG[phase];
}

export function getAllPhaseCockpitConfig(): Record<MountedPhase, PhaseConfig> {
  return PHASE_CONFIG;
}
